### ISSUE TITLE
Saveloc gui overlap error

### ISSUE THREAD

**Issue by CoopJax** [momentum-mod/game#1002]
**Describe the bug**
Saveloc creation notice overlaps with the save location gui if you do it too many times.

**To Reproduce**
Just save current location and watch the notices pile up.

**Expected behavior**
Maybe move the notice down a bit or make the gui disappear after you save your current location?

**Screenshots**
<img src="https://i.imgur.com/9UdhcrO.png" alt="gui" data-canonical-src="https://i.imgur.com/9UdhcrO.png" style="max-width:100%;">

**Desktop/Branch**
 - OS: Windows
 - Branch: Latest Develop Branch

**Comment by CoopJax** [comment]
#1035 should fix this :)

**Comment by TheRealHona** [comment]
Don't close this issue manually, when the pull request is merged. the issue gets closed automatically.

**Comment by CoopJax** [comment]
ok
