### ISSUE TITLE
Browse maps menu button

### ISSUE THREAD

**Issue by CoopJax** [momentum-mod/game#1005]
**Is your feature request related to a problem? Please describe.**
You can browse and download maps just by clicking a button in the menu, which is easier than going into Firefox and finding maps.

**Describe the solution you'd like**
When you click the button, it opens up a web browser overlay that directs you to https://momentum-mod.org/dashboard/maps

**Describe alternatives you've considered**
Download maps from the map selector, although that might be trickier.

**Comment by bltech** [comment]
You can already download maps from the map selector (with a key).
