### ISSUE TITLE
$color doesn't work for PBR on models

### ISSUE THREAD

**Issue by bonjorno7** [momentum-mod/game#1012]
$color doesn't work for PBR on models.
Works fine for brushes though.

Go on the shadertest map, edit any model material VMT to use $color, see no effect.

 - OS: Windows
 - Branch: Steam version

**Comment by bonjorno7** [comment]
I nominate @andrewbaay to fix it 😄

**Comment by Gocnak** [comment]
Yeah this was also noticed by the recent work I did that factored in the `g_DiffuseModulation` alpha so that setting RenderColorA worked for things like stickybombs.

It seems like the PBR shader is unaffected by it except for the ambience lookup for diffuseIrradiance:
https://github.com/momentum-mod/game/blob/develop/mp/src/materialsystem/stdshaders/pbr_ps20b.fxc#L136

And my recent alpha factoring:
https://github.com/momentum-mod/game/blob/develop/mp/src/materialsystem/stdshaders/pbr_ps20b.fxc#L223

**Comment by andrewbaay** [comment]
so $color is g_DiffuseModulation? i thought it was 
albedo.xyz *= g_BaseColor;
that made me somewhat confused

**Comment by Gocnak** [comment]
@andrewbaay So yeah `$color` is tied to the `COLOR` material param:
https://github.com/momentum-mod/game/blob/develop/mp/src/public/shaderlib/BaseShader.h#L38

Which is then referenced inside BaseShader's `ComputeModulationColor`:
https://github.com/momentum-mod/game/blob/develop/mp/src/materialsystem/shaderlib/BaseShader.cpp#L472-L489

Which is called from PBR's cpp code directly:
https://github.com/momentum-mod/game/blob/7ec231bc73198109819dcf0e313a1783b116219c/mp/src/materialsystem/stdshaders/pbr_dx9.cpp#L666-L672

OR from this command which I couldn't really find the usage of:
https://github.com/momentum-mod/game/blob/ada49a1e6d81eb84ee10e8768853ee4fceecd35c/mp/src/materialsystem/stdshaders/BaseVSShader.cpp#L614-L648

**Comment by andrewbaay** [comment]
We thought that this sets the $color up
`		// Setting up vertex color
		Vector color;
		if (bHasColor)
		{
			params[info.baseColor]->GetVecValue(color.Base(), 3);
		}
		else
		{
			color = Vector{ 1.f, 1.f, 1.f };
		}
		pShaderAPI->SetPixelShaderConstant(PSREG_SELFILLUMTINT, color.Base());
`
since `info.baseColor` directly gets the color from the `COLOR` param.
its then directly multiplied to the albedo of the material.
if thats the case we should just replace the 

`albedo.xyz *= g_BaseColor;` with `    albedo.xyz *= g_DiffuseModulation.xyz;` to properly do it.. seems like getting the value directly is a hack

**Comment by Gocnak** [comment]
Huh yeah that should also work. Should it maybe change to be `g_BaseColor.xyz`? Not sure if that matters.

**Comment by Gocnak** [comment]
`g_BaseColor` is only given 3 floats but is defined as a `float4` in the shader. Is that also a problem?

**Comment by andrewbaay** [comment]
it should only give a warning implicitly truncating the value, but not actually change anything since we're multiplying it with 
`albedo.xyz` which implicitly truncates `g_BaseColor` to `g_BaseColor.xyz`

**Comment by andrewbaay** [comment]
i tried doing `albedo.xyz *= g_DiffuseModulation.xyz;` it just made all models white-ish and have weird colors, not the solution we're looking for.

**Comment by Gocnak** [comment]
Shouldn't it be `albedo.xyz = g_BaseColor.xyz`? After all, $color is setting the albedo color to use right?

**Comment by andrewbaay** [comment]
> Shouldn't it be `albedo.xyz = g_BaseColor.xyz`? After all, $color is setting the albedo color to use right?
well that would make everything a solid color whatever `g_BaseColor` is, in this part we are *modifying* the albedo texture to be customizable with `$color` hence we are multiplying that color to the albedo.

**Comment by bonjorno7** [comment]
Kinda off topic but could we make color HSV adjustment instead of RGB multiplication?
That'd make it way more useful I think.

**Comment by andrewbaay** [comment]
@bonjorno7 i guess that would be optimal, instead of using $color we should introduce a new $hsv to adjust stuff

**Comment by bonjorno7** [comment]
Why add more stuff instead of overwriting default stuff?
I'm fine with either solution, just curious.

**Comment by andrewbaay** [comment]
![image](https://user-images.githubusercontent.com/28888920/95798349-58849600-0d24-11eb-974d-7020bb5c0843.png)
turns out i was mistaken,
changing
```	albedo.xyz *= g_BaseColor;```
to
```albedo.xyz *= g_DiffuseModulation;```
will make
```
    "$color" "[1 0 0]"
```

**Comment by tsa96** [comment]
I have a HSV parameter working already, as hue shifting is extremely useful for doing colour modifications without affected unsaturated parts of a material, I make a branch in my fork today.

**Comment by bonjorno7** [comment]
Sears found out that the reason VertexLitGeneric uses $color2 is because Valve couldn't get $color to work either lol, so we'll just add $color2 to PBR to fix it.
