### ISSUE TITLE
Add $hsv to PBR Shader

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1014]
**What feature is your improvement idea related to? Please describe.**
As mentioned in the discord / in #1012, it would be good to have a material var that controls color but by using HSV values instead of RGB.

**Describe the solution you'd like**
Add an `$hsv` material param
Have the shader load it in if defined
Tint the albedo.xyz by the HSV value (using the correct translation to RGB)

**Comment by tsa96** [comment]
I will finish this tomorrow, just fighting with ps20 :)
