### ISSUE TITLE
Unreal Tournament Gamemode

### ISSUE THREAD

**Issue by CoopJax** [momentum-mod/game#1017]
Unreal Tournament will be sort of like rocketjump and Titanfall 2 wall movement. It will have autobhop and some custom movement like Double Jump and gun boosting.

Things needed for stubbing game mode:

Game code

    Add to game mode enum in mom_shareddefs
    Add localization token in g_szGameModes in mom_shareddefs
    mom_system_gamemode code is main place to define it

Website Code
    Update game mode type enum in client
    Update game mode type enum in server
    Update map uploading to have map prefix
    Update supported modes in run uploading

    Misc files
        Discord game mode rich presence icons
        Steam game mode localization in Dropbox/Momentum Mod Localization/
        Speedometer config default VDF file
        Momentum tips
        momentum/resource/momentum_english_ref.res
        momentum.fgd

Reference: https://youtu.be/TTf4LJf8E8A

Things needed for full game mode:
 Some custom movement including:
 Running side dodge jump
 Double Jump
 Wall jump sort of like Titanfall 2 wall jumping
 Gun boosting on walls (like rocketjump but with pistols)

**Comment by patrickmoc** [comment]
For anyone looking to stub this gamemode in the future, the webm, icon and general media is usually done by the momentum team and is not necessarily required until the official release of the gamemode.

**Comment by CoopJax** [comment]
Ah, gotcha.

**Comment by Gocnak** [comment]
Going to have to pass on this.

1. Momentum's gamemodes are pretty much locked at this point. Feature creep can be extremely easy to hit and adding all types of movement isn't the goal of the game, and could make us seem unfocused on what our game is trying to be.

2. The goal of each gamemode is to provide a unique enough style of play to make distinct gameplay experiences. I don't see how this really provides any unique style, this seems like mixing between a couple existing ones just for the sake of it. Around 2.0.0 we plan to have a "custom settings" thing that lets you do things like this though.

3. Things in Momentum should be Source related, I know defrag or conc is a bit of a stretch but they're related to Source directly. For this reason though we aren't focusing too much on Goldsrc or other entirely different engines.
