### ISSUE TITLE
CVAR mom_gamemode_override

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1018]
First order implementation to allow for the playing of a map outside of the intended gamemode without renaming the map prefix.

usage:
mom_gamemode_override [map prefix] (surf/bhop/rj/sj/conc/tsurf/parkour/defrag/climb/ahop/etc.)

Future implementation and integration within the game and UI TBD

**Comment by braem** [comment]
Would this be better as a command?

**Comment by Arkanoid0** [comment]
> Would this be better as a command?

Possibly, but what i meant by "First order implementation" was "simplest implementation". Without looking at the code, i figure that the gamemode must be set as a variable somewhere during map init, so the most basic way to provide this functionallity would be to simply override that var and re-initialize the gamemode settings.

I don't intend for this to be the final way this works, as was pointed out in discord this function will likely be exposed as part of the ui for variant styles (angle/scrollhop/etc), but i figured this should be simple enough to implement without significant rework. and further refinement can come later.
