### ISSUE TITLE
"Use Defaults" Button opens in background and can cause softlock

### ISSUE THREAD

**Issue by bltech** [momentum-mod/game#1019]
**Describe the bug**
Pressing the "Use Defaults" button on the Input Settings panel causes the dialog to open in the background - behind the settings. If not on a map, this will softlock the game, otherwise, the settings can be closed via ESC. This will also cause the settings panel to open when pressing ESC again instead of the main menu panel.

The "Use defaults" query dialog itself is also missing the cancel button although it can be closed by pressing ESC.

**To Reproduce**
- Open Settings
- Press "Use defaults"

**Expected behavior**
It should open in the foreground and have a cancel button.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/19615431/95929129-88cf4180-0dc3-11eb-945d-8e761755203f.png)

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: develop (f5a3ca94a3fae940a2c46fc60ccd3bcd504b81c5)

**Comment by bltech** [comment]
I'm also getting
`(gdb) print g_pSettingsDialog->GetParent()
$4 = (vgui::Panel *) 0x0
`
which looks concerning.

**Comment by Gocnak** [comment]
Simple fix, just have to use `g_pMessageBox` for creating this. It worked previously because the settings panel it came from wasn't full screen and modal.
