### ISSUE TITLE
Game crashes & unrendered models when cancelling the loading of certain maps

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1023]
**Describe the bug**
Cancelling the loading of maps can crash the game. It can also cause models to not load when opening a map. Code for it is in engine.

Only happens in certain situations. Eg: `sj_antiquity` crashes but `sj_asdf` does not; `sj_antiquity` doesn't crash in this way if `sj_asdf` has been fully loaded; `surf_milkyway` models don't show after cancelling loading of `sj_providence`. 

May have the same cause.

**To Reproduce**
1. Load a map
2. Cancel load (escape key on loading)
3. Game crashes or models aren't loaded upon loading another map

**Screenshots**
![image](https://user-images.githubusercontent.com/9014762/95944681-9a055780-0d9d-11eb-917b-ea8630b338b9.png)
![image](https://user-images.githubusercontent.com/9014762/95945609-b1454480-0d9f-11eb-9517-5962df339d32.png)
![image](https://user-images.githubusercontent.com/9014762/95945587-a5598280-0d9f-11eb-88ff-ce58c3de24f9.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version & Latest develop branch

**Additional context**
https://discordapp.com/channels/235111289435717633/235125108656701440/765781586603278417

**Comment by lvaness** [comment]
Is this still a thing on Chaos? I couldn't get it to crash when testing the examples here and some others.

**Comment by Gocnak** [comment]
Closing, can be re-opened if it's still an issue.
