### ISSUE TITLE
Zones break when resetting to a stage the player is currently in

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1028]
Found by Cabbage McGravel

**Describe the bug**
When the timer isn't running, restarting to a stage the player is current in will have zones cease to function until `reload` and asserts are hit in the client (speedometer and discord code).

**To Reproduce**
1. `mom_restart_stage` while in a stage and the timer isn't running
2. Asserts will be hit, stage & end zones will not render, and zones will stop working until the map is reloaded.

**Expected behavior**
This workflow should not break zones.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch only

**Additional context**
`zone_enter` is fired with a current track of -1, breaking client code.

**Comment by braem** [comment]
Changing it [this](https://github.com/momentum-mod/game/blob/5a552551eb3a165e7a0625547aafa3252ce27c56/mp/src/game/server/momentum/mom_player.cpp#L1918) to `Teleport` instead resolves this issue. Investigating why.

**Comment by braem** [comment]
> 
> 
> Changing [this](https://github.com/momentum-mod/game/blob/5a552551eb3a165e7a0625547aafa3252ce27c56/mp/src/game/server/momentum/mom_player.cpp#L1918) to `Teleport` instead resolves this issue. Investigating why.

Problem occurs when this is called in `ManualTeleport` : `g_pTrickSystem->PostPlayerManualTeleport(this);`

**Comment by Gocnak** [comment]
Oop, good catch. Forgot to put that behind a `g_pGameModeSystem->GameModeIs(GAMEMODE_TRICKSURF);`

**Comment by braem** [comment]
> 
> 
> Oop, good catch. Forgot to put that behind a `g_pGameModeSystem->GameModeIs(GAMEMODE_TRICKSURF);` . It'd be good to put that check inside those methods.

Yeah shoutouts to Cabbage. Would you want the checks inside the functions themselves or just in `ManualTeleport`?

**Comment by Gocnak** [comment]
Inside the functions themselves.
