### ISSUE TITLE
-nocustom launch option

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1030]
Requested by Juxtapo

**Is your feature request related to a problem? Please describe.**
Useful for mappers to test their map's packing. Annoying to have to move/delete/rename things to stop them from getting mounted/overridden properly

**Describe the solution you'd like**
Add a `-nocustom` launch option that avoids file mounting and adding search customs.

**Additional context**
Going to guess this requires engine access.

**Comment by bltech** [comment]
IMO this is probably better to put into the engine basket and do it when gameinfo.txt is being parsed. While you can remove search paths, it doesn't seem to remove vpk files (at least on Linux) and the filesystem interface is horrible (you get the search paths as one string with semicolons inbetween). 

You could also remove the custom mounting from the gameinfo.txt and add it in code but that would break the mounting in the tools.

**Comment by Arkanoid0** [comment]
As discussed, in theory this is possible by using sv_pure. There might be some issues with the way we do mounted content from other games, but unknown till attempted.

**Comment by lvaness** [comment]
In the next update, we're going to have `-nocustommount`, `-nogamemount` and the option not to mount the base folders of other games (e.g. the cstrike/ folder) and just take the vpks (and the download folder in this case):
```
	mount
	{
		440
		{
			"mountmoddir" "0"
			"tf"
			{
				"vpk"	"tf2_misc_dir"
				"vpk"	"tf2_sound_misc_dir"
				"vpk"	"tf2_sound_vo_english_dir"
				"vpk"	"tf2_textures_dir"
				"dir"	"download"
			}
		}
	}
```
