### ISSUE TITLE
Rename the showRuler command

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1032]
**What feature is your improvement idea related to? Please describe.**
The `showRuler `command has a name that does not follow the convention of any other commands and should be changed to make things more consistent. A name like `mom_ruler_enable `is more consistent with the 3 existing cvars related to this command (e.g. https://docs.momentum-mod.org/var/mom_ruler_duration/)

**Describe the solution you'd like**
Rename `showRuler `to `mom_ruler_enable `or something similar. 

**Describe alternatives you've considered, if any**
Any synonymous name would also work fine (show, display). Not renaming the command also will not break anything, it just looks rather strange and ugly as is IMO.

**Additional context**
The command also needs a documentation page made about it once the new name is decided upon. 

The command is also bound to `X` by default so the name may need to be updated there as well, idk I'm not a coder.

**Comment by braem** [comment]
`mom_ruler_show` to be consistent with the only other static menu (savelocs)
