### ISSUE TITLE
Prevent restart stage on first enter

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1043]
**What feature is your improvement idea related to? Please describe.**
In stages with big enough zones, players can restart stage right on entering one for a time save. This behavior should be stopped.

**Describe the solution you'd like**
Prevent restarting a stage when it's first entered in a run.

**Describe alternatives you've considered, if any**
Prevent restart stage from teleporting when player is already in the target stage.

**Comment by Gocnak** [comment]
This could be pretty simple by just only setting the current stage on Stage trigger exit? Though this would kinda mess up the HUD...

We could also just do the alternative and prevent doing `mom_restart_stage` when inside the stage trigger, yeah.

**Comment by braem** [comment]
> 
> 
> This could be pretty simple by just only setting the current stage on Stage trigger exit? Though this would kinda mess up the HUD...
> 
> We could also just do the alternative and prevent doing `mom_restart_stage` when inside the stage trigger, yeah.

Yeah I was planning on the latter as it's much simpler. I also wanted to get this into 0.8.6 which is why I assigned myself to this quite small issue. Mainly wanted it in ASAP because the change to put players on the ground always make it more abuse-able.
