### ISSUE TITLE
trigger_momentum_timer_stop can be escaped from

### ISSUE THREAD

**Issue by lodyb** [momentum-mod/game#105]
If you move into the edge, or corner of the end timer trigger, you can escape and continue playing if friction lands you outside of the trigger.

**Comment by lodyb** [comment]
Also worth noting that if you hit the very edge or corner of a trigger, you can trigger the end popup multiple times in the replay. I have made some runs where I do this repeatedly and I see the popup dialog appear and disappear a few times before finishing the run, ergo, the demo thinks that you have finished the run but in game it had not completed yet.

**Comment by tuxxi** [comment]
This was very recently fixed (today in fact!) https://github.com/momentum-mod/game/commit/c8b36f3850e5dad80218bf36bd6530a18a73b823

Thanks again for the feedback, it is much appreciated!
