### ISSUE TITLE
When you jump in the start zone (in ahop) it plays the mapstart sound over and over.

### ISSUE THREAD

**Issue by CoopJax** [momentum-mod/game#1050]
**Describe the bug**
A clear and concise description of what the bug is. If you have a video of it happening, you may post it here.

**To Reproduce**
Jump in place in the start zone.

If you have a video with the steps to recreate the bug, please post it here.
[The Bug](https://cdn.discordapp.com/attachments/765655141525225483/768211892505149460/2020-10-20_15-39-05.mp4) 

**Expected behavior**
Don't play the sound every time you jump in the start, only when you leave it.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version

**Comment by braem** [comment]
This is because you are starting the map; the timer is starting. Happens whenever it's set to start on jump.
