### ISSUE TITLE
Limit singlestep command

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1053]
**Describe the bug**
The `singlestep` command can be used with `next 1` to advance the game 1 tick at a time and should not be possible to use mid-run with timer on.

**To Reproduce**
1. Type `singlestep 1`
2. Bind a key to `next 1`
3. Hit said key to step forward 1 tick at a time

**Expected behavior**
The command should not be possible to use with a timer on. Perhaps should be locked behind -mapping?

**Desktop/Branch (please complete the following information):**
 - Branch: Latest Develop

**Additional context**
This feature would be nice to have available with frame input in a future TAS tool

**Comment by Gocnak** [comment]
https://github.com/momentum-mod/game/blob/ae019f46e0cd75a5ca0541b89521e78004ba1cbf/mp/src/game/server/momentum/server_events.cpp#L57

It's unloaded automatically when not in mapping mode. Is this not the case?

**Comment by hexaflexahexagon** [comment]
> https://github.com/momentum-mod/game/blob/ae019f46e0cd75a5ca0541b89521e78004ba1cbf/mp/src/game/server/momentum/server_events.cpp#L57
> 
> It's unloaded automatically when not in mapping mode. Is this not the case? Keep in mind develop branch automatically adds `-mapping` unless it's explicitly removed from the debugging launch params tab.

oh you're completely correct whoops, i swear I had disabled -mapping. that's what i get for playing with `mom_hud_versioninfo_enable 1` i suppose. `next` is not hidden without -mapping but that doesn't break anything, it's just an extra command that does nothing. i'm unsure if that alone is worth keeping this issue up or not, feel free to close if not.

**Comment by Gocnak** [comment]
Yeah next being visible is okay. If/when engine access they'll be removed in favor of our TAS stuff.
