### ISSUE TITLE
Add a visual indicator of zones loading

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1056]
**What feature is your improvement idea related to? Please describe.**
When starting a map through the map selector, the map's zones may take awhile to load.

**Describe the solution you'd like**
Would be nice to have some visual indicator that the zones are loading in.

**Describe alternatives you've considered, if any**
Make sure zones are loaded for the map the player starts. Not sure if this is possible without doing a sync (not async) API call on map load which will tank loading times.

**Additional context**
https://discordapp.com/channels/235111289435717633/235125108656701440/768481834887020575

**Comment by collinsample76fallo1111** [comment]
I can probably do the visuals for this but I will need some help with the code as I'm only familiar with python not c++

**Comment by Panzerhandschuh** [comment]
Oudated
