### ISSUE TITLE
Fix zones not loading sometimes when using the map command

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1057]
**Describe the bug**
When starting a map directly via the `map` command, sometimes zones are never loaded in. I believe this happens when loading an official map with `map` while it's not detected as in your library.

**To Reproduce**
1. Start the game
2. Type `map <mapname>` in console
3. Wait a while to be sure zones are not loading in
4. `reload` or `map <mapname>` again, zones still not loading in

**Workaround**
Map has to be start in map selector. For maps this bug occurs on they are not listed as in your library.

**Expected behavior**
Zones should load, albeit slowly if there is a bad connection, when using the `map` command.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version & Latest develop branch

**Additional context**
Related to https://github.com/momentum-mod/game/issues/1036

**Comment by Gocnak** [comment]
I *believe* that with the new map list system, we no longer use the concept of a library, so we will be loading the zones no matter what if it's a supported map. Closing for now, can reopen or make a new issue if it's still a problem after that.
