### ISSUE TITLE
Chat doesn't filter out large amounts of blank space causing an error

### ISSUE THREAD

**Issue by NinjaTheCookie** [momentum-mod/game#1067]
Spaces can be manipulated in chat to cause effects like these.

Doing the "say" command with many spaces and a valid character at the end will cause this to happen.
![image](https://user-images.githubusercontent.com/62808028/97095492-e3845b00-1657-11eb-960c-58d5ce92be5b.png)

Starting a message with a letter then posting spaces till the end and another valid character will cause this to happen, text turns white and they don't automatically show in chat while message is rendered.
![image](https://user-images.githubusercontent.com/62808028/97095527-6dccbf00-1658-11eb-95d0-3d9ba4b2a3d9.png)

Many spaces in a row should generally be filtered out of chat.

**Comment by Gocnak** [comment]
Might only need to do `str = str.Replace("  ", " ");` in ChatPanel.cpp:
https://github.com/momentum-mod/game/blob/develop/mp/src/game/client/momentum/ui/chat/ChatPanel.cpp#L590
