### ISSUE TITLE
Reset Concs in Start Zone

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1070]
**What feature is your improvement idea related to? Please describe.**
Concs should be reset in the start zone in the same way that SJ bombs are. Any concs out when hitting reset should fizzle, any concs when first entering the start zone would be fizzled. Exact same implementation but with concs instead of stickies to remove any goblin map start strats.

You should most likely also not be allowed to cook concs in a start zone (similar to charging stickies in SJ), as has also been suggested.

**Comment by braem** [comment]
This otherwise would but concs are not `CMomExplosive`'s, which are planning to move over.
