### ISSUE TITLE
Friends Tab not loading in Leaderboard

### ISSUE THREAD

**Issue by McGravel** [momentum-mod/game#1075]
**Describe the bug**
The Friends tab of the leaderboards doesn't appear to load, and stays on "Fetching Data..."

**To Reproduce**
Open the Leaderboard of a map on the Map Selector and check the Friends Tab

**Expected behavior**
The Friends tab should load!

**Screenshots**
![](https://i.imgur.com/vD81nyd.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows / Linux
 - Branch: Steam version (0.8.6)

**Comment by braem** [comment]
This only loads when you are in mapping mode. [This early return](https://github.com/momentum-mod/game/blob/761cd228132127068a93b4d44c44aa42a3ef5551/mp/src/game/client/momentum/ui/leaderboards/LeaderboardsTimes.cpp#L393) is being hit normally.

Looks like the codes for steam friends are different depending on whether you are in mapping mode? Strange. Maybe related to the [new steamworks API update](https://github.com/momentum-mod/game/pull/1000).
```
else if (type == TIMES_FRIENDS)
{
  if (code == 409) // The profile is private, we cannot read their friends
  {
    m_eTimesStatus[type] = STATUS_UNAUTHORIZED_FRIENDS_LIST;
    m_bUnauthorizedFriendlist = true;
  }
  else if (code == 418) // Short and stout~
  {
    m_eTimesStatus[type] = STATUS_NO_FRIENDS;
  }
}
```
