### ISSUE TITLE
Cursor sometimes cannot interact with spectator hud while chat box is open

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1076]
**What feature is your improvement idea related to? Please describe.**
When using chat while spectating, your cursor can sometimes interact with the hud (arrows to change target, X to stop spectating) and sometimes not, depending on if you had cursor input enabled before opening chat with the DUCK key.

video: https://streamable.com/1mzbod
In the video my cursor is invisible but you can see the boxes over the buttons when I hover over them and they are clickable.

**Describe the solution you'd like**
The cursor should always remain functional (or nonfunctional) when it is visible for consistency. 

**Describe alternatives you've considered, if any**
This is not necessary and could easily be ignored and left as is. Alternatively, the cursor could never interact with the spectator hud while chat is open but that is most likely less user friendly.

**Additional context**
When opening chat while the cursor is open, it teleports from wherever it is to the center of the chat box. This is a somewhat related issue but seemed too small to open another card, it can be split off if desired. Ideally the cursor doesn't teleport around and stays in place when it is already visible.

**Comment by braem** [comment]
Should be as simple asenabling spectator huds mouse input when opening chat (starting message mode)
