### ISSUE TITLE
"setpause" still used when opening Steam overlay

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1084]
**Describe the bug**
Toggling the Steam overlay still attempts to use the `setpause` and `unpause` commands, despite those being removed

Unknown command "setpause"
Unknown command "unpause"

**To Reproduce**
1. Enable steam overlay
2. Toggle steam overlay ingame
3. Check console output

**Additional context**
May or may not need engine to fully fix

**Comment by Gocnak** [comment]
The `setpause` is unfortunately done inside engine, but the `unpause` was something that was added:
https://github.com/momentum-mod/game/blob/develop/mp/src/game/server/momentum/server_events.cpp#L130-L133
And can be removed.

**Comment by Gocnak** [comment]
"unpause" was our code and handled by @McGravel , "setpause" is used by engine code and cannot be removed until we get engine. Keeping the card for tracking this, though.

**Comment by Gocnak** [comment]
This should be fixed (for momentum) as we compile out all pausing code.

**Comment by hexaflexahexagon** [comment]
setpause and unpause are both no longer output into console when toggling the steam overlay
