### ISSUE TITLE
mom_hud_menu_show commands are bound incorrectly in settings

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1087]
**Describe the bug**
Assigning a key to "Toggle showing Saved Locations Menu" or "Toggle showing Ruler Menu" in the settings panel does not work, as it binds them to the wrong commands. Instead of the old cvars they should use `mom_hud_menu_show rulermenu` and `mom_hud_menu_show savelocmenu` respectively.

**Desktop/Branch (please complete the following information):**
 - Branch: Steam version (0.8.6)

**Comment by Gocnak** [comment]
Should have been fixed in #1066 , can you verify?

**Comment by hexaflexahexagon** [comment]
> Should have been fixed in #1066 , can you verify?

misread the date on that commit and thought it was before 0.8.6, issue seems to have already been fixed.
