### ISSUE TITLE
Add freecam spectate mode

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1088]
**What feature is your improvement idea related to? Please describe.**
It is possible to toggle between 1st and 3rd person while spectating another player, but it is impossible to navigate into freecam mode without using the console.

**Describe the solution you'd like**
Using jump should swap between 1st person, 3rd person, and a freecam view. 
Alternatively, there could be a button added to the hud (similar to the X 'stop spectating' button) that goes between freecam and the current view.

**Additional context**
It is possible to enter freecam by typing `spectate` in console, but it has no autocomplete and outputs an error line saying `CBasePlayer::ChangeTeam( 1 ) - invalid team index.`, meaning it is most likely not intended. 

This issue is pretty close to another small spectator-related issue #1074

**Comment by braem** [comment]
When this is done, `spectate` cmd should prob be unloaded
