### ISSUE TITLE
Some user inputs bypass map finish panel and go to game

### ISSUE THREAD

**Issue by lmbellis** [momentum-mod/game#1091]
**Describe the bug**
Player able to jump, crouch, and fire rocket launcher/sticky launcher while the "Map Finish" Panel is up

**To Reproduce**
- Enter start zone then finish zone
- Fire rocket launcher/ sticky launcher
- To allow crouching to bypass the panel, jump once with the panel up.
https://youtu.be/t6ev7vu9slY

**Expected behavior**
All user input to be taken by the panel rather than in-game (eg. No jumping, crouching, or rockets fired).

**Desktop/Branch (please complete the following information):**
 Windows - Steam 0.8.6

**Comment by braem** [comment]
Can already have more movement with it open via https://docs.momentum-mod.org/var/mom_mapfinished_movement_enable/
But with it off, yeah that's a bug.

**Comment by Gocnak** [comment]
Yeah if we want to properly filter all input, you'd do it in [`clientmode_mom_normal.cpp`, specifically where it checks if the map finished panel is open](https://github.com/momentum-mod/game/blob/develop/mp/src/game/client/momentum/clientmode_mom_normal.cpp#L187-L196). We can check brae's linked convar and if it's off, basically swallow every input except right click of mouse.
