### ISSUE TITLE
Damage indicators should scale to sj/conc damage

### ISSUE THREAD

**Issue by benjl** [momentum-mod/game#1094]
**Describe the bug**
Right now the min and max size of the hit markers is clamped to the min and max damage you can receive from rockets in RJ (45 to 90).

**Expected behavior**
Min and max hit marker size should scale to min and max sticky or conc damage (and the defrag launcher in the future)

**Desktop/Branch (please complete the following information):**
 - OS: Any

**Comment by Gocnak** [comment]
One solution to this is to pass the explosive type down into the usermsg that the HUD uses and then use the proper scale there.

**Comment by Gocnak** [comment]
@bltech was this implemented in the new panorama damage indicators?

**Comment by hexaflexahexagon** [comment]
asked BLT and he said no since it wouldn't have been trivial to add properly, still needs to be done later

**Comment by lvaness** [comment]
Are concs supposed to deal damage? Because as far as I can tell they don't (so there is nothing to scale)

**Comment by hexaflexahexagon** [comment]
according to Mac they don't deal damage in tfc, so we can:
1. have all conc markers be statically sized
2. scale them based on knockback recieved instead of just damage, tho idk if people would want that because you'd have smaller markers the closer you are. plus handhelds would need to be dealt with

**Comment by hexaflexahexagon** [comment]
there were talks about adding more user customization of damage indicators (like width scaling to damage) but those can be opened as new cards, this is working as intended
