### ISSUE TITLE
No default bind for opening chat

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1096]
**Describe the bug**
There is no default bind for `chat_open`, causing players to not know how to open hud chat.

**Expected behavior**
Bind a key to it by default, preferably enter.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop

**Comment by Gocnak** [comment]
https://github.com/momentum-mod/game/blob/develop/mp/game/momentum/cfg/config_default.cfg#L30 ?

**Comment by braem** [comment]
Sorry i saw this reported in discord so figured it wasnt there.
