### ISSUE TITLE
Savelocs importing (copying) from map name with autocomplete support

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1104]
Mappers tend to make multiple named maps for each version for the map, meaning that during mapping it's a tedious process to manually copy savelocs over to a new map name that only has a change in the name (and not the layout).

Introducing a `mom_saveloc_copy (map name entry with auto complete)` command would be awesome for these mappers as they would only need to run it once to get all their previous locs on the new map.

**Comment by braem** [comment]
Does wildcard support in this context refer to auto complete?

**Comment by Gocnak** [comment]
Oop forgot to assign this to myself, wrapping up the branch for it. Yep I meant to have it be auto complete since they should know what revision map they last had to import from.
