### ISSUE TITLE
If you create a saveloc whilst under one timer, switch to another, then use the saveloc, it'll reset your timer to the first one.

### ISSUE THREAD

**Issue by tricksurf** [momentum-mod/game#1105]
**Describe the bug**
If you are on lets say "mom_restart 1" and you make a saveloc, then go to "mom_restart 2", if you hit the saveloc made whilst under "mom_restart 1" it'll reset your timer so that your restart bind restarts on "mom_restart 1" rather than 2.

**To Reproduce**
This works really well on surf_delight.
1. Do mom_restart 1 in console.
2. Create a saveloc.
3. Do mom_restart 2 in console.
4. Teleport to saveloc.
5. Press restart bind and notice it resets your timer state to the "mom_restart 1" instead of "mom_restart 2"

https://youtu.be/O69V8ZJH61o

**Expected behavior**
Your timer should stay on mom_restart 2 since you could just accidentally press a saveloc and restart on a different timer. This would force you to type mom_restart 2 everytime you accidentally teleport to a saveloc created whilst not under the influence of that timer.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam Version

**Comment by Gocnak** [comment]
I think if we coded everything around *accidental* button presses, people are going to eventually complain we don't do what they *intended*.

I raise this use case: I have a ton of savelocs on Bonus 1. I start to mess around with practicing Bonus 2, but decide I want to go back and practice Bonus 1 again off of my savelocs. What should `mom_restart` do for me in this instance? Why would I want to go back to Bonus 2 if I was practicing Bonus 1 off of savelocs made from Bonus 1? What if me going to Bonus 2 was the "accident" here?

The other solution is to not have savelocs store the current track and zone you're on, but then you get people complaining about the HUD not being correct when teleporting all around stages, plus some may even use the HUD to indicate where exactly the saveloc created was at (which track).

In my opinion, accidental saveloc loading is a mistake done by players and therefore shouldn't have any presumptuous code about it. We have safeguards to prevent loading them accidentally during the run, but if they go through and tele to it, our game shouldn't assume that they accidentally did it.

**Comment by tricksurf** [comment]
> I think if we coded everything around _accidental_ button presses, people are going to eventually complain we don't do what they _intended_.
> 
> I raise this use case: I have a ton of savelocs on Bonus 1. I start to mess around with practicing Bonus 2, but decide I want to go back and practice Bonus 1 again off of my savelocs. What should `mom_restart` do for me in this instance? Why would I want to go back to Bonus 2 if I was practicing Bonus 1 off of savelocs made from Bonus 1? What if me going to Bonus 2 was the "accident" here?
> 
> The other solution is to not have savelocs store the current track and zone you're on, but then you get people complaining about the HUD not being correct when teleporting all around stages, plus some may even use the HUD to indicate where exactly the saveloc created was at (which track).
> 
> In my opinion, accidental saveloc loading is a mistake done by players and therefore shouldn't have any presumptuous code about it. We have safeguards to prevent loading them accidentally during the run, but if they go through and tele to it, our game shouldn't assume that they accidentally did it.

I was just confused, because in 0.8.5 this didn't seem to be the case. You would be on one track, and if you teleported to a saveloc that was made under an older track it wouldn't just switch your track. At least I don't think it did, I could be wrong.

**Comment by Gocnak** [comment]
Correct. 0.8.6 added storing track and zone to the savelocs. So I'll close this, we want tracks and zones stored in the savelocs.
