### ISSUE TITLE
Custom Crosshair Settings

### ISSUE THREAD

**Issue by ghost** [momentum-mod/game#1107]
**Is your feature request related to a problem? Please describe.**
Easier way to get custom crosshairs than mounting them from a file locally. You can also customize them by making them bigger, smaller, possibly change the color.

**Describe the solution you'd like**
https://github.com/momentum-mod/game/pull/583 Sort of what this pr did, but updated to the latest settings UI.

**Comment by Arkanoid0** [comment]
See also #769, propose merge and rename to "crosshair system overhaul"

**Comment by tsa96** [comment]
Quick note, CS:GO handles crosshair previews with a CSGOCrosshair Panel instantiated in settings_game.xml, probably needs porting over

**Comment by hexaflexahexagon** [comment]
done
