### ISSUE TITLE
Tabs don't always reset visually when using arrow key navigation

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1120]
Reported by @bltech 

**Describe the bug**
Panels that have tabs (IE the menu drawer) have buggy arrow key navigation; the tabs that should be out of focus aren't reset visually when looping around from last to first tab.

**To Reproduce**
1. Select a panel with tabs
2. Wrap around from first to last or last to first tab using arrow keys

**Expected behavior**
Tabs that are not in focus should always visually show as unfocused.

**Screenshots**
https://cdn.discordapp.com/attachments/235125108656701440/771919831619600444/unknown.png
"Profile" and "Changelog" tabs are properly unfocused, but "Friends" isn't.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version & Latest develop branch

**Additional context**
https://discordapp.com/channels/235111289435717633/235125108656701440/771919714901426196

Related to https://github.com/momentum-mod/game/issues/1083

**Comment by Gocnak** [comment]
Is this a problem in Panorama? (Check when these panels are implemented in Pan)

**Comment by lvaness** [comment]
None of the tabbed VGUI panels are left as far as I can see and we don't really have keyboard movement anywhere, though it works fine if enabled
