### ISSUE TITLE
Prop shadows flicker 

### ISSUE THREAD

**Issue by bltech** [momentum-mod/game#1122]
**Describe the bug**
On ahop_coast, shadows will appear and disappear depending on angle (see video). This only happens on the shadows of the objects that used to be physics objects in HL2. It behaves much like the now fixed 3d skybox and sun issue where the world geometry phased in and out of existence. Maybe another opengl shader is null where it shouldn't be?

I'm assuming this is linux-only since I didn't see this on waezone's stream.

**To Reproduce**

- Boot up the game on Linux
- Open ahop_coast
- Observe the wooden box infront of the start zone

**Expected behavior**
The shadows should just persist

**Video**
https://streamable.com/7ckb8g

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: 0.8.6 Steam, 0.8.7 latest develop

**Additional context**
Shader detail doesn't matter, regarding shadow detail, on Low the shadows don't even appear and any higher shows the issue

This doesn't happen with barrels in de_aztec loaded in MM, however the objects seem to be something different as they push  you out and the shadows look much softer

It does happen on de_cbble at `setpos -2117.654297 -2049.454346 64.031250;setang 29.612093 -25.711700 0.000000`

Also on pl_upward with the resupply cabinet at `setpos 587.203308 1507.123169 640.031250;setang 15.884027 119.567574 0.000000`

This happens with prop_dynamic and prop_physics

**Comment by VortexParadox** [comment]
Can replicate on Windows, seems like render to texture is broken for some specific reason.  Also, this is with a hardware override launch parameter
https://imgur.com/m36YjQU

**Comment by Gocnak** [comment]
Given #1272 and the fact prop shadows are basically covered by CSM now, is this still applicable?

**Comment by lvaness** [comment]
Does CSM handle dynamic prop shadows as well? If so then, yeah this (and maybe the other one) can be closed as well.

**Comment by hexaflexahexagon** [comment]
CSM will show real-time shadows for stuff like thrown concs which makes me assume it does dynamic props as well, though I haven't tested that. (though not all maps will have CSM enabled, right? so i'm not sure how that's a proper solution since it's still an opt-in feature for mappers)

**Comment by VortexParadox** [comment]
CSM *has* replaced RTT. However there are commands in the game to modify RTT shadows or are related to RTT in some way. I was not able to get an RTT shadow on either `ahop_coast` or a test map. Even the VDC speculates that `shadow_control`, an entity to modify RTT parameters, may be obsolete in CS:GO.
Rather than an opt-in, Hex, CSM comes by default with any map built after L4D

**Comment by lvaness** [comment]
I'll just close this for now as these shadows don't currently exist.
