### ISSUE TITLE
Warn the player when joining an official map that mapping mode is active

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1130]
currently its quite possible to forget you are in mapping mode when playing an official map, resulting in valid runs not submitting to the leaderboards. This is much more of an issue currently, as most maps are unofficial and need a quick zoning to have a timer, but the game should be much more annoying about the fact that mapping mode is active when playing an official map.

**Comment by SCell555** [comment]
how should the player be warned? Say that mapping mode is active in loading dialog/show popup after trying to load map from map selector/show something in center of screen at first player spawn

**Comment by Gocnak** [comment]
This can use the same system as the sv_cheats and mom_gamemode_override HUD hint message things.

**Comment by SCell555** [comment]
It looks like only client knows about map's ID

**Comment by Gocnak** [comment]
Ooh maybe you can stuff it in the run submitter, where it checks mapping mode already. It would just do it on game event, leaving the start zone.
