### ISSUE TITLE
Game sometimes crashes when entering checkpoints

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1132]
**Describe the bug**
Hard crash to desktop when entering checkpoints

**To Reproduce**
Currently unknown, reports of ahop_coast cp1 and bhop_jago cp2

**Expected behavior**
Game doesn't crash.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam 0.8.6

**Additional context**
Crashlogs posted when repro'd

**Comment by Gocnak** [comment]
Does this still happen on 0.8.8+?

**Comment by Gocnak** [comment]
Closing as we haven't seen anything like this since 0.8.8+
