### ISSUE TITLE
Game crash when changing resolution on a map (Related to async replays)

### ISSUE THREAD

**Issue by bltech** [momentum-mod/game#1135]
**Describe the bug**
When changing the window resolution while on a map with ~50+ local replays, the game will crash with the following stack:
```
CMomReplayBase** CopyConstruct<CMomReplayBase*>(CMomReplayBase**, CMomReplayBase* const&) platform.h:1287
CUtlVector<CMomReplayBase*, CUtlMemory<CMomReplayBase*, int> >::InsertBefore(int, CMomReplayBase* const&) utlvector.h:954
CUtlVector<CMomReplayBase*, CUtlMemory<CMomReplayBase*, int> >::AddToTail(CMomReplayBase* const&) utlvector.h:932
CMomReplayFactory::FilesystemCallback(FileAsyncRequest_t const&, int, FSAsyncStatus_t) mom_replay_factory.cpp:237
CMomReplayFactory::FilesystemCallbackForward(FileAsyncRequest_t const&, int, FSAsyncStatus_t) mom_replay_factory.cpp:204
<unknown> 0x00000000f6ba8435
<unknown> 0x00000000f6ba65c0
<unknown> 0x00000000f6ba7498
<unknown> 0x00000000f6bab629
<unknown> 0x00000000f785effa
CThread::ThreadProc(void*) 0x00000000f7f48880
start_thread 0x00000000f7f051d4
__GI___clone 0x00000000f7e1b5e6
```

**To Reproduce**
- Join a map where you have 50+ local replays
- Change resolution / Switch fullscreen mode

**Expected behavior**
No crash

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: **develop**

**Additional context**
I'm adding this issue for record-keeping and because I have absolutely no clue what is going on but I'll also look into this myself, of course.

The callback seems to complete for 42-48 replays without a problem but for some reason, at that point, it fails when allocating the pointer. IMO reloading the replay files when changing resolution doesn't make much sense anyways but that's just a consequence of the panel being destroyed. And even then, I'm not really sure why it suddenly fails. Is there some random memory shortage while resizing or a race condition regarding the IO thread?

If I find no other solution, then I'll probably just open a PR to move leaderboard replay loading back to initial panel open instead of LevelInit before 0.8.7.

**Comment by Gocnak** [comment]
This is because the leaderboards UI is an `IViewPortPanel` that gets destroyed and recreated every time you change resolution.

A simple solution to this could be to remove that and do a static init call just like the main menu panel does.

**Comment by bltech** [comment]
I see, that could work. How would online times get updated though? Like a timer checked OnThink or a TickSignal set to some very high number?

**Comment by Gocnak** [comment]
Yeah on think would be best, just checking the timer there. I think that's what the Update stuff did anyways.
