### ISSUE TITLE
Add a key to mom_gamemode_override

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1140]
**What feature is your improvement idea related to? Please describe.**
Add a key for the `mom_gamemode_override` command. This can simply be a list of what numbers correlate to what mode in the command's description, pictured below. This is intended to be open to UI later anyways but the command is still useful for playing unofficial maps that are loaded through console and this should be a very small PR.
![image](https://user-images.githubusercontent.com/62961532/98891610-92a09f00-246c-11eb-96c8-a32a6611b2a6.png)
e.g. adding 0 = surf, 1 = bhop, 5 = sj, etc etc. 

**Describe alternatives you've considered, if any**
Alternatively you could add functionality to make something like `mom_gamemode_override ahop` work.

**Additional context**
Playing on latest develop in debugging mode. In my screenshot you can also see a strange line ` game notconnected replicated` which seems to be included by mistake and could also be removed pretty easily I assume.

**Comment by Gocnak** [comment]
As talked about [in the PR for the command](https://github.com/momentum-mod/game/pull/1081#discussion_r515560737), we want players to look up [the command on our documentation website](https://github.com/momentum-mod/docs/pull/135), which has all the gamemodes listed as potential inputs. As the majority of players will use the map selector UI / rename the map, I decided it wasn't worth potentially updating this documentation in two spots if gamemode numerics change in the future.

Strings would also complicate the logic in setting/using the command greatly, so it will stay numeric.
