### ISSUE TITLE
[Conc] Sticky conc trigger

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1143]
Within Conc maps, there is are sometimes chutes where you throw a conc down and it meets up with you later in the map which sometimes have the problem of being inconsistent because of conc bouncing. A useful trigger for both this and for other strats would be a trigger that freezes the conc in position when it touches it, similar to the behavior of sticky bombs.

**Comment by hexaflexahexagon** [comment]
don't existing maps use water for this? any reason that wont work?

**Comment by zike1017** [comment]
Pretty much any functionality that this would be capable of is already doable with water from my understanding of conc. As yes, concs essentially come to a dead stop when entering water, but not every map will put water at the bottom of these chutes. However, this also won't really matter that much as the current conc implementation the concs are for more bouncy than they should be. Lessening this will also make this less of a problem on maps that lack water.

**Comment by Arkanoid0** [comment]
Does water also work on walls and ceilings? I am trying to come up with triggers that add functionally and might make possible cool new strats on new maps, and ignoring that, the interaction with water is non-obvious and should be broken out to a dedicated trigger regardless.

**Comment by Arkanoid0** [comment]
Yeah i played a conc map that has water and it acted like i expected the interaction to work, the conc sank. What i want is a trigger that when a conc hits a solid brush within it, it acts like a sticky bomb, which is not quite how it works currently.

**Comment by hexaflexahexagon** [comment]
trigger was added and seems to work fine for conc. we wanted to expand this to be a more general explosive trigger (e.g. for rockets) but that can be a separate card we track.
