### ISSUE TITLE
XP Display on stats panel.

### ISSUE THREAD

**Issue by ghost** [momentum-mod/game#1155]
XP amount is not clearly visible, moving to the player stats panel on the menu drawer would be much more accessible to players who don't understand where it is located.

**Additional context**
<img src="https://cdn.discordapp.com/attachments/654321545044426762/777959478455697468/a.PNG" alt="where it can be placed" data-canonical-src="https://cdn.discordapp.com/attachments/654321545044426762/777959478455697468/a.PNG" style="max-width:100%;">

**Comment by Gocnak** [comment]
This is an old VGUI bug, and with the new profile player cards, XP is very prominently displayed. Closing.
