### ISSUE TITLE
Sound cache creates lower case folder variants

### ISSUE THREAD

**Issue by bltech** [momentum-mod/game#1177]
**Describe the bug**
If the "Team Fortress 2" folder is written in upper case on Linux (as it is created by Steam by default), the game will create a "team fortress 2" folder (or even sometimes  a "team" folder see discord link below) containing 16 byte sound cache files that would normally go to the real game folders. 

**To Reproduce**
- Have TF2 installed
- Launch Momentum
- (maybe load a map so that a cache gets generated?)
- Look into steamapps folder where there will be a second tf2 folder

**Expected behavior**
No new folder should be created

**Desktop/Branch (please complete the following information):**
 - OS: **Linux**
 - Branch: at least 0.8.5/0.8.6/0.8.7 and develop

**Additional context**
There is no difference between the new gameinfo "mount" key feature, old MomUtil::Mount code or hardcoded gameinfo paths.

There also seems to be some factors that will decide if the vpk even gets added as a search path, if i compile it myself from the same hard disk, it won't mount if there's uppercase letters, at all. All steam versions somehow do, even from different disks, even run directly through hl2.sh. This is probably a separate issue though.

This isn't too bad since you can rename the folder and Steam doesn't complain but having to tell every new Linux user to rename their folders might be even more annoying. Maybe it automagically gets fixed by Chaos Engine, who knows.

https://discord.com/channels/235111289435717633/356398721790902274/747915092942913629

**Comment by lvaness** [comment]
Doesn't seem to happen on Chaos anymore
