### ISSUE TITLE
Default to global times rather than local on official maps

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1179]
**What feature is your improvement idea related to? Please describe.**
Pressing tab always defaults to local times instead of global, what most people will care about.

**Describe the solution you'd like**
Times should be defaulted to "global" rather than "local" if on an official map. If the map is unofficial and thus there are no global times then it should default to the local tab instead.

**Describe alternatives you've considered, if any**
May want to make this a toggleable convar but I really don't see the point. People who don't like the change have to click an entire 1 more time to get to where they want, while for most people (playing official maps since that's what most people will be doing) this is a no brainer UX improvement.

**Additional context**
Suggested by nevier in discord.

**Comment by lvaness** [comment]
This seems to be the behavior right now, no?

**Comment by hexaflexahexagon** [comment]
it might've been changed at one point independent of this card, if that's the case it can be marked as resolved. it's a pretty clear UX thing so that's very likely as people were poking around at the pano leaderboards

**Comment by Gocnak** [comment]
This has been the behavior for quite some time. Online is not even showing up for unofficial maps.
