### ISSUE TITLE
Can't open certain maps

### ISSUE THREAD

**Issue by SirPingOffical** [momentum-mod/game#118]
I can open the most maps but some of them wont open and I don't know why.

**Comment by RabsRincon** [comment]
Can you provide more info? What are some examples of maps that do not open for you? What version of the mod are you using?

**Comment by danbrunost** [comment]
every map. When I press play map the game just shuts down.

**Comment by Nolan-O** [comment]
@danbrunost that is a new SDK bug. A fix is coming.

**Comment by RabsRincon** [comment]
A fix has arrived to the sdk. Update it and let us know if the problem remains
