### ISSUE TITLE
Overlapping warning boxes

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1186]
**Describe the bug**
The warnings for using practice mode and playing a map in a different gamemode overlap eachother 

**Expected behavior**
One/both should move so that they do not overlap 

**Screenshots**
![image](https://user-images.githubusercontent.com/5162166/105423316-495e8f80-5c13-11eb-8d57-502f0ad7c632.png)

**Desktop/Branch (please complete the following information):**
 - Branch: 0.8.7 steam release

**Additional context**
Reported by webby in discord

**Comment by Gocnak** [comment]
Will be resolved by #1718

**Comment by tsa96** [comment]
Fixed now they're using the new toast system.
