### ISSUE TITLE
host_timescale affects sounds with sv_cheats 0

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1194]
**Describe the bug**
`host_timescale` alters sound playerback when changed, even if the change is not in effect. For example, with `sv_cheats 0`

**To Reproduce**
1. Load map with `sv_cheats 0` and `host_timescale` anything but "1"
2. Do something to create a sound (e.g. shoot a stickybomb)

If you have a video with the steps to recreate the bug, please post it here.
https://streamable.com/vm1w5m

**Expected behavior**
When the timescale is not actually modified sounds should playback at the proper speed

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch

**Comment by braem** [comment]
On 0.8.8-rc, this bug doesn't occur as `host_timescale` changes regardless of `sv_cheats`, which is fine since it is locked behind mapping mode.

Bug might still happen on multiplayer games though. We will have to check P2CE for that.

**Comment by Gocnak** [comment]
So this bug should probably move to P2CE/Chaos source, closing for now.
