### ISSUE TITLE
Add RJ centerfire popup

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1203]
**What feature is your improvement idea related to? Please describe.**
RJ players coming from TF2 can often get confused by the rockets coming from the center since they don't realize that they're using centerfire (which is a different angle than the stock launcher in TF2).

**Describe the solution you'd like**
Add a popup that shows the first time a user plays RJ asking them if they want to use center fire or not. 

**Describe alternatives you've considered, if any**
Could also be integrated into the tutorial but many experienced users will skip these tutorials and possibly miss the message.

**Additional context**
Further review is probably needed for the exact wording / behavior but the general idea should be solid since this is a recurring issue.
https://discord.com/channels/235111289435717633/390338161982570517/793692634195558411

**Comment by Gocnak** [comment]
Duplicate of #1499 ? Or at least, this will be handled there. If that's the case, can this be closed?

**Comment by hexaflexahexagon** [comment]
probably. it should be _really_ emphasized so i'm hesitant but as long as we just throw it in everybody's face who's even smelled tf2 before it should be OK there.
