### ISSUE TITLE
Main menu logo spins too fast on Linux

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#1207]
**Describe the bug**
The Momentum Mod logo model on the main screen spins uncontrollably fast when dragged even a tiny bit on Linux

**To Reproduce**

1. Open MMod on Linux
2. Drag the large logo on the main menu

**Expected behavior**
It should spin slowly like on the windows version

**Desktop/Branch (please complete the following information):**
 - OS: Void Linux
 - Branch: Steam version

**Additional context**
I think this is a Source engine thing because it also happens in TF2 on Linux

**Comment by SlidyBat** [comment]
This is kind of tied to #1320, since once that's done this will likely fix itself.

**Comment by Gocnak** [comment]
Does this happen in CS:GO with the player model in the main menu? @chovelyoukai

**Comment by lvaness** [comment]
Looks like it's fixed now on Panorama.
