### ISSUE TITLE
Eyetele puts you into the wall at acute angles and protruding elements

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1208]
**Describe the bug**
When using `mom_eyetele` while almost parallel to the wall you're looking at, the command will get you stuck inside the wall.

**To Reproduce**

- Boot up any map, like triggertest
- Align yourself almost parallel to a wall, so that you can barely still target it (I can get some example angles if this is unclear)
- use `mom_eyetele` on the wall you're aligned to

**Expected behavior**
You should end up infront of the wall

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: 0.8.7

**Additional context**
Replacing the UTIL_TraceLine for a UTIL_TraceHull might be enough, this would also solve getting stuck when there are protruding walls in the way:
![20210201154405_1](https://user-images.githubusercontent.com/19615431/106473927-a9bbbf80-64a4-11eb-98b0-d40225d9ddd7.jpg)
![20210201154415_1](https://user-images.githubusercontent.com/19615431/106473957-b0e2cd80-64a4-11eb-81f5-69e54bedb689.jpg)

Also, it looks like the command tries to account for the bbox by removing 32 units from the end position, however the bounding box extends ~45 units in the diagonal direction and the amount needed to account for this at every angle tends to infinity with increasing angle. This fact will get you stuck inside diagonal walls, as well.

The only downside would be that if the corridor to where you aimed is too small at one single point and then gets bigger after, you still would get blocked halfway trough although there's enough space at the end (like you couldn't peek through a small hole to teleport, it would need to be player-sized) and solving both at once could turn out complicated, so I guess it depends what's considered more important. EDIT: A compromise could be to trace a line first, then trace a hull backwards and then rely on CGameTrace::fractionleftsolid (if it works like it should) to get nearest point on the line where the player actually fits.

Also, this (probably?) being mostly a mapping command, having to noclip might not be a problem anyway.

**Comment by Gocnak** [comment]
For now I just replaced it with UTIL_HullTrace, as it fixed the clearly bad logic of using a single point to represent the player hull. Since this can be used while noclipping, I figured the point of squeezing through a hole or something can just be negated by noclipping through it.
