### ISSUE TITLE
Screen juts when hit by stickybomb

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1209]
**Describe the bug**
When being hit by a sticky bomb the screen juts upwards slightly. This is especially noticeable when being hit in mid-air where there was previously very little screen movement.

**Expected behavior**
The screen should not jut noticeably and distract the player

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: Chaos

**Comment by Gocnak** [comment]
player.cpp does some weirdly random view punch when taking damage ~~not sure if we removed the line or something~~ which was by default in SDK 2013:
https://github.com/momentum-mod/game/blob/develop/mp/src/game/server/player.cpp#L1289
