### ISSUE TITLE
Miscellanious Chaos Build Rendering Issues

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1211]
**Describe the bug**
Some misc. visual errors on the new chaos engine build.

**Screenshots**
![20210204002750_1](https://user-images.githubusercontent.com/49064563/106846047-83537b00-6682-11eb-8980-3e6f89fe0fa7.jpg)
Certain tf2 assets are not being lit properly and appear black such as all of the rock models on cp_process_final

![20210204003750_1](https://user-images.githubusercontent.com/49064563/106846142-b0079280-6682-11eb-9946-cdf0d96a5baa.jpg)
Effects such as the point_spotlights and dust clouds appear more intense than they normally would

![20210204003852_1](https://user-images.githubusercontent.com/49064563/106846305-02e14a00-6683-11eb-8620-ca194a3f3554.jpg)
Shooting stickies underwater causes the arm particle to render incorrectly as a broken square.

**Desktop/Branch:**
 - OS: Windows
 - Branch: Chaos Build RC

**Comment by braem** [comment]
> Shooting stickies underwater causes the arm particle to render incorrectly as a broken square.

This was resolved: https://github.com/momentum-mod/game/issues/1225 (which was a duplicate sorry)

The other 2 are still outstanding

**Comment by braem** [comment]
> Certain tf2 assets are not being lit properly and appear black such as all of the rock models on cp_process_final

Caused by `$seamlessdetail 1`. Going to hardcode it off in the engine and it's not used in CSGO/Chaos.

**Comment by braem** [comment]
> Effects such as the point_spotlights and dust clouds appear more intense than they normally would

Lastly, this is because SDK hardcodes `point_spotlight` brightness to 64, whereas CSGO/Chaos doesnt. They also removed the ignore solids field for some reason. Going to add that back & add a brightness field & input.
