### ISSUE TITLE
Settings Menu Tabs Layering Issue

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1212]
**Describe the bug**
The settings menu becomes unusable until restarting the game if you click around the tabs too many times because they suddenly become layered incorrectly and are no longer accessible

**To Reproduce**

I caused this just by clicking around the different menu tabs rapidly.

**Screenshots**

![20210203234758_1](https://user-images.githubusercontent.com/49064563/106846576-8733cd00-6683-11eb-80a1-00c8ad21a461.jpg)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Chaos Build RC

**Comment by Gocnak** [comment]
Fixed and will be in latest push, verify that it is the case so this can be closed.
