### ISSUE TITLE
Rocket Sound Loops Forever in the Void

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1213]
**Describe the bug**
In the chaos build, if you noclip or practice mode into the void and continually fire rockets, the rocket travelling sound will continue to emit from the place you fired it. If you fire too many, they stack up so much that the audio gets distorted. These sounds dont seem to stop and you can hear them from nearby places inside the map.

**To Reproduce**

- Clip into the void outside of the map
- Fire rockets with a rocket launcher

**Expected behavior**
If a rocket is in the void it should not play any sound, or immediately detonate

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Chaos Build RC

**Comment by Gocnak** [comment]
We can check the point contents at the explosive's spawn location to immediately remove it if attempted to spawn out of bounds. Checking the point contents masked with `& CONTENTS_SOLID` can see if it spawns in something solid.

This check could be a static bool inside of CMomExplosive and checked inside each weapon that spawns it to prevent even creating the explosive in the first place. The weapon would then "dry fire".
