### ISSUE TITLE
Random noclip/Practice Mode crash on de_overpass

### ISSUE THREAD

**Issue by ghost** [momentum-mod/game#1216]
**Describe the bug**
The game seems to crash randomly if you noclip on maps, this example is on `de_overpass`.

**To Reproduce**
- Load the map: `map de_overpass`
- Noclip/practice mode immediately
- Fly backwards (S key only) until crash

**Expected behavior**
The game should continue to exist (that means not crashing)

**Screenshots**
N/A

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Additional context**
N/A

**Comment by hexaflexahexagon** [comment]
A crash also happens on loading `dz_blacksite` and looking around a bit while inbounds so it's probably not specific to noclip or this map.

**Comment by braem** [comment]
Looks like the crash is due to running out of memory. Should get a memdump and a popup though..

**Comment by hexaflexahexagon** [comment]
> Looks like the crash is due to running out of memory. Should get a memdump and a popup though..

Memdump does happen, they're put in the root Momentum Mod folder but popup does not. I can upload one of mine that i have if thatd be helpful but it seems very easy to recreate.

**Comment by Gocnak** [comment]
Seems to be fixed in recent build, needs testing & verification.
