### ISSUE TITLE
Sticky ring particle effect renders incorrectly under water

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1225]
**Describe the bug**
When shot into water, the stickybomb's ring particle effect renders oddly.

https://youtu.be/SbD5v_bLg_U

**To Reproduce**
Shoot a stickybomb into water while not underwater.

**Expected behavior**
Ring particle should render properly under water as it does on SDK build.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc only

**Comment by braem** [comment]
Unaffected by the solution to https://github.com/momentum-mod/game/issues/1215

**Comment by VortexParadox** [comment]
Transparency just gets ignored underwater... I could swap it to the friendlier `UnlitGeneric` but `SpriteCard`  has some special features like keeping a minimum rendering size for particles, which it uses. But without it the effect is completely lost with distance.
This material is also used in other particle systems, mainly debug sticky trails and conc

**Comment by braem** [comment]
Shouldn't have to switch to unlit; we will want to fix the `SpriteCard` shader in this regard.

**Comment by braem** [comment]
Temporary fix implemented. Long term solution being tracked internally. Closing.
