### ISSUE TITLE
Latest Chaos update makes CSM not work under -tools

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1227]
**Describe the bug**
Upon updating, I noticed that if I ran the engine on tools mode cascaded shadow maps would not render or be forcefully set as disabled. `csm_quality_level` is set to 3, however even changing it around makes no difference. The game freezes as if it were making a change, but the shadows in a map are the same.

**To Reproduce**
1.  Run the game with `-tools`
2.  Load any map compatible with CSM, like CSGO maps
3.  The map would show no sharp shadows (Make sure `cl_csm_auto_entity` is set to 1, some maps expect the game to create the entity)

**Expected behavior**
The game should behave like it did before the update, with `-tools` not having an impact on CSM

**Screenshots**
![image](https://user-images.githubusercontent.com/35622748/107858697-11ee9780-6dfb-11eb-84ee-fa1c39ef5ea0.png)
###### CSM with `-tools`
![image](https://user-images.githubusercontent.com/35622748/107858839-e6b87800-6dfb-11eb-8ca6-1621261b264d.png)
###### Same CSM settings without `-tools`

**Desktop/Branch (please complete the following information):**
 - OS: Windows 10
 - Branch: Steam, 0.8.8-rc Bring the Chaos

**Comment by Gocnak** [comment]
Does CSM work with `-tools` in the first place? Like CS:GO?

**Comment by VortexParadox** [comment]
this issue is now being tracked in the [Chaos Source Github](https://github.com/ChaosInitiative/Chaos-Source/issues/534), so I'll close it in favor of that
