### ISSUE TITLE
buildcubemaps fails on latest update

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1228]
**Describe the bug**
When running `buildcubemaps` the error `vtex failed to compile cubemap '<cubemap_texture>'!` will be printed, and the sampled cubemaps will be left in the path they would have if stored inside the BSP, but outside of the `game` folder

**To Reproduce**
1.  Run a map that has not been BSPZIPped
2.  Try to `buildcubemaps`
3.  The game will start sampling, but once it's done and the map has reloaded, the cubemaps should not be present
4.  Open the console and look for the error described here

**Expected behavior**
`buildcubemaps` should behave like it did before the update, with VTEX properly compiling and saving the textures to the BSP

**Desktop/Branch (please complete the following information):**
 - OS: Windows 10
 - Branch: Steam

**Additional context**
~~I can't confirm if this is an issue caused by me or if the tools are somehow borked, as I have noticed `content` `maps` and now `materials` hanging in the `|all_source_games|` path, which made me check my `gameinfo.txt` but it had no issues I could see~~
Confirmed now

**Comment by Gocnak** [comment]
Further investigation:

Writes the BSP version 21 if run on a BSP version 20 map. Hex-editing the version back to 20 makes the map load it seems. Fix could be to just use the BSP version of the map when rewriting it.

**Comment by VortexParadox** [comment]
I have compiled a map with the tools provided, but the error still occurs.
