### ISSUE TITLE
Revert cl_viewmodelfov to fov_viewmodel

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1230]
**What feature is your improvement idea related to? Please describe.**
With the change to the Chaos engine `fov_viewmodel` is no longer a command, instead being replaced by `cl_viewmodelfov` which is a much more awkward command name. This is also now inconsistent with `fov_desired`.

**Describe the solution you'd like**
Rename the command back to `fov_viewmodel` & change the default value from 50 to something more reasonable like 90.

**Describe alternatives you've considered, if any**
This is obviously low priority and can be left alone but it would be QoL for users first playing the Chaos build.

**Comment by Gocnak** [comment]
Changed name and defaulted to SDK's value of 70, but it's archived so players can change as they wish.
