### ISSUE TITLE
Cannot close frames parented to gameui panel with escape key

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1233]
**Describe the bug**
Frames parented to the gameui panel (eg. credits & settings) cannot be closed with the escape key.

**To Reproduce**
1. Open a frame parented to gameui panel (eg. credits)
2. Try to close with escape key, be sad

**Expected behavior**
Frames should have the option to be closed by escape key (map selector probably doesn't want to be closed with it, but credits definitely does).

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Additional context**
Might not be worth exploring/doing as we plan to switch to Panorama.

**Comment by Gocnak** [comment]
Rudimentary fix placed in the next push, will need testing both in the menu and in game to see if it'll close.

**Comment by braem** [comment]
In game it acts the same as SDK; closes but resumes game. Closes on main menu as well, though also closes console which doesn't occur on SDK. Very minor difference in workflow so marking this as resolved.
