### ISSUE TITLE
surf_facility void crash

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1236]
**Describe the bug**
When clipping out of bounds on the version of surf_facility on the map selector, the game seems to allocate a large amount of memory and then crash. The memory dump is therefore quite large (linked in team chat).

**To Reproduce**

- Load surf_facility through the map selector
- Go to the start zone
- Enter practice mode
- Clip outside the bounds of the level

**Expected behavior**
The game should be able to handle rendering the map from the void properly.

**Desktop/Branch:**
 - OS: Windows
 - Branch: Chaos Build

**Comment by hexaflexahexagon** [comment]
Probably the same issue as https://github.com/momentum-mod/game/issues/1216 ?

**Comment by Gocnak** [comment]
Seems to be fixed in latest Chaos build, needs testing.
