### ISSUE TITLE
Linux build doesn't mount VPKs

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1237]
**Describe the bug**
The game will basically mount nothing at all. You get a default arial-like font, not even hl2 textures in maps and no sounds at all. The only things that load are the loose files included with Momentum.

**To Reproduce**
- Manage to get it running on Linux in the first place
- Run the game

**Expected behavior**
Everything loads according to plan

**Screenshots**
![ahop_coast0003](https://user-images.githubusercontent.com/19615431/109044352-9c27dd00-76d2-11eb-9ed5-120aee180364.jpg)

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: 0.8.8-rc

**Additional context**
I investigated a bit with strace and so far I found that instead of looking inside the actual vpks, the game tries to access the actual file structure like `access("*steamlibrary/steamapps/common/momentum mod/hl2/hl2_sound_misc.vpk/materials/particle/screenspace_fog.vmt", F_OK) = -1 ENOENT (No such file or directory)`

**Comment by lvaness** [comment]
There are no problems mounting Portal 2 and CSGO though, I assume that's because they have the "canonical" pak??_???.vpk format that gets automounted when mounting the folder.

EDIT: There is however a caveat with CSGO; some models (and sounds?) don't want to load but that is probably a separate issue that should be investigated after this

**Comment by lvaness** [comment]
This seems to be largely fixed. It looks like sound(scape)s and CSGO textures/models are still broken, but only on some maps. Should I create a new issue for that?

**Comment by Gocnak** [comment]
Yes. I'll close this issue for now as the original problem was fixed, those seem like other issues with filesystem or render.
