### ISSUE TITLE
Banning yourself freezes the game

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1238]
**Describe the bug**
Using the command `addip|banip <random number> 0.0.0.0` will freeze the game and/or crash.

**To Reproduce**

- Join a map
- Type the aforementioned command

**Expected behavior**
Either nothing should happen, or you should actually get banned from your sp instance (idk why you would want to do that). Most likely though it shouldn't even exist in the first place. Interestingly, using `banid x 2 kick` actually works and will not let you join a map until you restart.

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: 0.8.8-rc

**Additional context**
This happens in every Source game I've tried (CSGO, TF2, 0.8.7)

**Comment by Gocnak** [comment]
Fix implemented, needs verifying in next game push before closing this issue.

**Comment by lvaness** [comment]
It no longer crashes. There is now the inconsistency that banip will not let you ban yourself while banid does but I don't think that's really a problem.
