### ISSUE TITLE
Cannot manually execute cfgs in custom folder

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1239]
**Describe the bug**
Trying to execute cfgs in the custom folder spews `exec: couldn't exec <cfgname>` and does nothing.

**To Reproduce**
1. Put a cfg file in `custom/<override folder>/cfg`.
2. Try to execute it in game by typing `exec <cfgname>` in console. 

**Expected behavior**
Should be able to manually execute cfgs in `momentum/custom/<override folder>/cfg/` folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/9014762/109104050-57a33e00-76e0-11eb-8f71-5d57343cee6b.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Comment by Gocnak** [comment]
Solution pushed that makes custom a `mod` search path again (SDK build had this). Verify in next push before closing.
