### ISSUE TITLE
Valve logo at end of credits shows as a "V"

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1241]
**Describe the bug**
At the end of the credits there should be a Valve logo, instead it is just the letter "V".

**To Reproduce**
1. Watch credits till the end

**Expected behavior**
Show Valve logo!

**Screenshots**
![image](https://user-images.githubusercontent.com/9014762/109105095-16139280-76e2-11eb-867e-0efa99bde38e.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Additional context**
Probably just missing the asset.

**Comment by Gocnak** [comment]
Looks like it's missing the font we use for credits somehow.

**Comment by Gocnak** [comment]
Yep it was searching for `HALFLIFE2.vfont` and we only have `HALFLIFE2.ttf`. Solution made for next push, verify before closing.

**Comment by braem** [comment]
Resolved

![image](https://user-images.githubusercontent.com/9014762/109303434-a5f33280-77ef-11eb-91b2-d1d92f8ed805.png)
