### ISSUE TITLE
Game pauses when alt-tabbing in fullscreen mode

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1243]
**Describe the bug**
When in fullscreen mode, the game pauses on alt-tab.

**To Reproduce**
1. Start game in fullscreen mode
2. Load a map with zones
3. Start a run
4. Alt-tab, wait
5. Tab back in, timer hasn't moved.

**Expected behavior**
Timer should continue to tick when alt-tabbed

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Comment by Gocnak** [comment]
Seems to have been resolved with either d3d9ex or similar.
