### ISSUE TITLE
Game can be slowed on windowed alt-tab

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1244]
**Describe the bug**
When `engine_no_focus_sleep` is set to a high number, the game slows down when alt-tabbing in windowed mode. Fullscreen alt-tabs currently pause the game (https://github.com/momentum-mod/game/issues/1243)

**To Reproduce**
1. Start game in window mode
2. Set `engine_no_focus_sleep` to a high number
3. Load a map with zones
4. Start a run
5. Alt-tab
6. Witness timer running slowly

**Expected behavior**
Timer should run at the same rate when alt-tabbed, regardless of the value of `engine_no_focus_sleep`.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Comment by Gocnak** [comment]
Made the command mapping-only as some mappers have expressed a desire to still have it.

**Comment by hexaflexahexagon** [comment]
This command is nice for streamers who alt tab and don't want their games running at 2fps while they look at discord or something,  would it be possible to keep that functionality somehow?
