### ISSUE TITLE
Update sv_cheats whitelist to match sdk mmod cvarlist

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1245]
**What feature is your improvement idea related to? Please describe.**
Since the transition to chaos, momentum is now (seemingly) using a similar sv_cheats whitelist as csgo, which is extremely restrictive on some of the commands that are protected by sv_cheats, some of which are unnecessary to be protected for momentum purposes (and more importantly, many commands that were allowed/disallowed in the sdk build had their flags changed in chaos). These include commands like showtriggers, drawclipbrushes, adjusting color correction, and disabling bloom, to name a few. Worth noting this is not an exhaustive list, if you compare csgo to css/tf2, many many commands were changed to be cheat protected. I also suspect that other commands that were made inaccessible in the sdk build might now be usable on the chaos branch, (eg commands that would allow the player to cheat with timer on).

**Describe the solution you'd like**
Change the flags for the commands that were changed in chaos back to their values in the sdk build.

**Comment by itVictor** [comment]
Forgot to mention, it'd also be worth looking into commands that may have been removed/added with the chaos branch and determine which commands should be re-added and/or determine what their flags should be.

**Comment by Gocnak** [comment]
I have updated it to allow cheat commands in singleplayer again. Verify in the next push before closing this issue.
