### ISSUE TITLE
Rendering issues when alt-tabbing in fullscreen

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1246]
**Describe the bug**
ALt-tabbing in momentum on chaos causes the game to flicker and/or freeze for roughly half a second, Happens anywhere in the game. Under some circumstances it can show the setting panel for half a second even if it was not open prior to alt-tabbing.

**To Reproduce**
1. set game to fullscreen
2. alt-tab out and in, notice flickering/freezes (freezes seem to happen more often when in map compared to main menu)

**Expected behavior**
No visual corruption.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Additional context**
Does not happened in windowed mode.
See if `-d3d9ex` changes anything since I know that affects alt-tabbing in other source games to some degree.

**Comment by Gocnak** [comment]
I implemented D3D9EX by default which is what CS:GO and TF2 engine does by default. In a push coming soon, please verify this still happens.

**Comment by itVictor** [comment]
fixed by checking "disable fullscreen optimizations" in exe properties, known issue that affects all source games when you don't check it
