### ISSUE TITLE
Light glow has issues rendering

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1247]
**Describe the bug**
It seems that partially or completely occluded additive sprites are having problems rendering

**To Reproduce**
1. Unzip [distortedperception.zip](https://github.com/momentum-mod/game/files/6042530/distortedperception.zip) and load the map contained.
2. Hang around on the light platform to the right and look into the passage directly in front.
3. Begin walking towards the middle of the platform and back to the edge. Some white rectangles should appear and disappear as the hall's visibility is toggled.
4. Looking up should show the sun sprite with the same issue.

**Expected behavior**
The white square should not render for occluded additive sprites

**Screenshots**
![image](https://user-images.githubusercontent.com/35622748/109135738-02395200-771d-11eb-90c3-98fd21db3240.png)
###### `setpos 20.11 109.06 96.03; setang  2.84 -63.90 0.00`

![iXwQmoaroq](https://user-images.githubusercontent.com/35622748/109207814-2a51a100-776f-11eb-92f8-9c9978576c41.gif)

**Desktop/Branch (please complete the following information):**
 - OS: Windows 10
 - Branch: Steam

**Additional context**
Seems like any type of sprite using some form of additive blend gets treated like this, regardless of shader.

**Comment by Gocnak** [comment]
This issue in particular has been fixed; any related issues can be opened in a new issue!
