### ISSUE TITLE
buildcubemaps breaks ingame mouse input on Linux

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1249]
**Describe the bug**
Attempting to build cubemaps on Linux will throw the error "Can't load vtex_dll.dll" which is reasonable but then it will also disable all mouse input ingame while menus work fine. This will last until you restart the game and it persists through map changes and reloads.

**To Reproduce**
- Go on any map
- type `buildcubemaps`
- Move your mouse

**Expected behavior**
Ideally, you should be able to build cubemaps but without mapping tools, I see no reason why you would need to generate cubemaps, it just shouldn't softlock the game.

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: 0.8.8-rc but I think this is yet another general Source thing (happened in TF2 aswell)

**Comment by Gocnak** [comment]
Does building cubemaps on Linux work in 2013/SDK build?

**Comment by lvaness** [comment]
It does to an extent, it flashes the textures on the screen but then crashes, but a vtex_dll.so file is actually present here, I'll have to test if it actually writes the cubemaps to files (apparently having it crash is a known issue on Windows i heard).

**Comment by lvaness** [comment]
I tried it on 3 different maps now and it only creates a folder in "momentum/materials/maps/map_name", then crashes and ~nothing more~ (on 0.8.7).

EDIT: I looked more closely and it actually creates appropriate cubemap files, for sj_amazon it created tga files, while for pl_upward and triggertests it's pfm files, so it fails somewhere before converting to vtf

![image](https://user-images.githubusercontent.com/19615431/112704559-60339380-8e9b-11eb-8af8-40887f61e26d.png)

**Comment by lvaness** [comment]
I'm really sorry for bumping this a third time but I feel this might be important to make buildcubemaps work on chaos:

I just figured out can actually get cubemaps to build on SDK, there is just a small oversight inside vtex: At some point, it sanity checks if the input path contains the string `materialsrc\\`, but since the input path gets converted to a linux path with forward slashes, it will always fail. Patching byte 0x0005BE1C in SDK 2013's vtex_dll.so from `\` to `\0` or `/` will make it match properly now and it will produce a working cubemap! Regarding chaos, if you decide to include vtex, changing the string accordingly would be required.

**Comment by Gocnak** [comment]
No worries about bumping! Very valuable info, I'll look into fixing this so that we're the first game to have working Linux cubemap building. 😁

**Comment by Gocnak** [comment]
We should have a vtex_dll with the aforementioned patch in the next push, adding the test+verify label.

**Comment by lvaness** [comment]
Well, this issue is fixed, however, now it just needs bsppack to actually build the cubemaps (`Can't load bsppack.dll`) but I suppose that's another issue and mouse input doesn't break anymore.

**Comment by Gocnak** [comment]
Yup let's create a new issue to port bsppack to linux. Closing as the original thing is fixed.
