### ISSUE TITLE
surf_stonework3 Loading the Engine Cubemap

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1251]
**Describe the bug**
surf_stonework3 uses a completely black envmap texture for all of its areas since there is not supposed to be anything reflective in the map, but in momentum mod the envmap used on most of the models is the default engine cubemap which shows a bright reflection of de_vertigo. The cubemap debug weapon seems to properly load the black cubemap though. This completely breaks the visuals of the map.

**To Reproduce**
- Load surf_stonework3
- Observe the broken reflections

**Expected behavior**
The cubemap from the bsp should take priority over the default engine cubemap. It is possible that the name of the cubemap (cubemapdefault vs defaultcubemap) is the issue.

**Screenshots**

![20210227160525_1](https://user-images.githubusercontent.com/49064563/109400159-77737580-791d-11eb-9e98-516bbd38209f.jpg)

![20210227160612_1](https://user-images.githubusercontent.com/49064563/109400164-7e01ed00-791d-11eb-80a4-54580c67720f.jpg)

![20210227160610_1](https://user-images.githubusercontent.com/49064563/109400170-835f3780-791d-11eb-8c65-6b65b12d1144.jpg)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Chaos Branch

**Comment by Gocnak** [comment]
Original issue fixed, the black pillars are intentional. Lighting improvements come from re-running CS:GO VRAD on the map, or using the CS:GO version of the map.
