### ISSUE TITLE
Allow mappers to store replays in their maps and use them

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1252]
This feature suggests adding a trigger for mappers to use that can interact with stored replays created by the mapper (or other), which the game can look for in some specific folder set for this type of thing, separate from actual replay files, and can be packed into a map and used.

The use of this is to allow mappers to set a triggered area which players can walk in, starting a visual countdown before activating a stored replay from the map (in some set folder a mappers able to pack and use), which, for example, would show how to do the current level they are on, and after the replay ends, sending them back to where they had been, similar to watching an actual replay. This can be cancelled at any time and won't be re-triggered while still in the trigger after the replay ends. This replay would have to be manually recorded with some created method for mappers, preferably some kind of menu.

### **Settings in this trigger would include:**

- Generic name.
- Generic disabled/enabled.
- Time of countdown (defaulting to 3 seconds)
- The replay to look for by name, from the dedicated folder, that it will play.
- The start and end time for the replay playback (if one is set to 0 or lower, it uses the start/end of the specified replay as its start/end time, whichever has 0 or lower. If the end time is larger than the replays length it will just use the end of the replay as its end time regardless)
- A toggle between showing the replay to the player or just playing back the ghost in the map without the player watching the replay directly.
- A value for how many times it should loop (if -1, it loops forever until the user chooses to end it. if 0, it does not loop. If set to -1 and the ghost is played in the map and not to the player, going into the trigger again will get rid of it) (this is good, for example, if the replay is small and the user will most likely want to see it multiple times before it stops).

With this should also include an entity of the same thing, without the countdown, which can instead be triggered by other stuff with fired outputs to it, such as instead a user input trigger. This would also have a toggle for if to start playing by default on map load.

This concept is comparable to something such as Jumpbot from jumping academy servers but with much more features and variability, allowing the mapper to have full control.

**Comment by hexaflexahexagon** [comment]
im fairly certain we already had plans to implement something like JunpBOT using ui and premade replays, possibly importing from JA's stash of recordings if possible. not sure if adding this instead really does the same function since about 95% of mappers wont bother with it, though this might just be a separate idea and im conflating the two?

**Comment by Ninja-Cookie** [comment]
> im fairly certain we already had plans to implement something like JunpBOT using ui and premade replays, possibly importing from JA's stash of recordings if possible. not sure if adding this instead really does the same function since about 95% of mappers wont bother with it, though this might just be a separate idea and im conflating the two?

This would be for way more than just jump, extending to any gamemode, and not just for showing how a level is done. it could also be used, for example, with detail, such as you enter an area and a ghost shows doing the level, similar to half-life's training, or just populating an area with fake players in some cyber setting. it can also be used to show more than just doing levels, for example tricks or the mappers personal "time to beat" ghost, so on, whatever a creative mapper can think to do.

I think the idea of using a separate function that can be applied to maps later, such as what jumpbot is able to do, adding a clickable thing into an already existing map to show a replay to show how a level is done, would also be necessary, as to be able to add them in the many already existing maps. This idea of mine would conjoin with that, not replace it, and just allow the mapper to create their own system that does this and is packed with the map its-self, the system to apply something later could use the same ideas here also, allowing for these flexible settings on them in what they actually do or how they operate, if to be clicked or stood at and such.

**Comment by hexaflexahexagon** [comment]
the showcase recordings similar to jumpbot would also extend to every gamemode but i see what you mean, that makes sense as just a standalone feature that mappers can use for their maps to add some more depth.

**Comment by Gocnak** [comment]
A really jank way to do this currently is just pack the replay and do a clientcommand for `mom_replay_play_ghost (name of packed ghost).mrf` . But we can look into using a proper entity to make it easier.

**Comment by Ninja-Cookie** [comment]
The output "OnPlaybackFinished" doesn't account for the replay being cancelled or stopped early, and can never trigger if infinitely looping because it doesn't officially end.

It would be nice to be able to point to the activator with an output "OnPlaybackStart".

Trying to make a trigger use this is more complicated than first thought. I got it working nicely using only 2 relays and the 1 activating trigger, however it took me a bit of thinking to come up with a solution on how to perform that, and isn't perfect, as if two triggers are next to each other and I leave one to enter the other replay trigger, when I leave the replay I now enter both triggers causing at least one to trigger... With some extra logic this could be fixed but going through all that is quite confusing. I'm not sure if there really is a better way of going about this using only the entity instead of having to work around the issue of it always triggering OnStartTouch when going back into a trigger from exiting a replay, but thought it was worth mentioning. It is perfectly possible to use this entity with a trigger but yeah.

Other than needing some work-arounds to get triggers to use the entity effectively, and other points made above, the entity its-self seems to work just fine and can play multiple replays at once doing different things.

**Comment by SlidyBat** [comment]
Discussed on discord, but pretty much all of the things Ninja-Cookie has brought up already exist, but it seems the game needed an update.
Closing this now, and we can open separate issues for any other enhancements needed for the entity.
