### ISSUE TITLE
sv_clamp_unsafe_velocities 0 by default

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#1255]
Right now the sv_clamp_unsafe_velocities command is set to 1 just like in csgo, this means that any map that uses some kind of booster will not work because it clamps the speed push. 

Make sure that (at least for surf/bhop, idk if the other gamemodes need it too) sv_clamp_unsafe_velocities is set to 0 by default. 

found on the new 0.8.8-rc steam beta version on windows

**Comment by hexaflexahexagon** [comment]
if my understanding of this command from reading online is correct then we can safely just remove it entirely and force the behavior to 0 in every gamemode

**Comment by granis48** [comment]
That is probably for the better. Unless someone can think of a situation where it would be good to stop in place when going too fast there's no reason for it to exist
