### ISSUE TITLE
sv_gravity is unrestricted

### ISSUE THREAD

**Issue by Hyper-Dan** [momentum-mod/game#1259]
**Describe the bug**
sv_gravity isn't disabled so players can fly super high

**To Reproduce**
Do sv_gravity [number] in console

**Expected behavior**
sv_gravity should be disabled to prevent cheating

**Desktop/Branch (please complete the following information):**
 
OS: Windows
Branch: 0.8.8-rc steam

**Additional context**
Found by Juice

**Comment by hexaflexahexagon** [comment]
fixed, command is now locked behind mapping mode
