### ISSUE TITLE
"reload" command doesn't work anymore

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#1260]
In old momentum typing "reload" in console would reload the map, this doesn't work in csgo and therefore doesn't work in this new momentum, idk why or what else reload would be for so should be fine changing it back. 

on the 0.8.8-rc build on windows

**Comment by Gocnak** [comment]
Solution is to use "restart" now, but we can make it tie to reload.

It fails for our game because we don't have saverestore, which it checks for some reason. Could maybe just make that check only happen if you pass the savepos param in...

**Comment by Gocnak** [comment]
Next build pushed will have this fixed, pending verify.

**Comment by hexaflexahexagon** [comment]
Appears to work correctly after update, command now reloads the map same as restart.
