### ISSUE TITLE
Clean up floating point error displaying in timer

### ISSUE THREAD

**Issue by harryjah** [momentum-mod/game#1263]
Currently, both in leaderboards and in the in game checkpoint times in the UI, accumulated floating point error shows itself in times that shouldn't be possible with the tickrates of the individual game modes. I'm not sure if it actually affects leaderboard placement, but either way it feels sloppy and it seems like a somewhat simple fix.

There's a number of solutions I'm sure, but my proposal would be to clean up the only clear source of floating point error I've noticed, which is the type and method of calculating the time parameter sent to the MomUtil::FormatTime function. Currently, it uses (endTick-startTick) * tickInterval to pass the function the time in seconds as a float to then format. My idea would be to use a fixed-point method by calculating the number of milliseconds (highest precision unit used in timer right now currently), like this:

int milliseconds = m_pRunData->m_iRunTime * static_cast<int>(m_pRunData->m_flTickRate * 1000.0f)

From this point, formatting the display of would change  very little and should display the proper times based on tick count (for any reasonable tick rate). In the likely event that the tick fractions are added to run data, it would just be a matter of adding something like:

int moremilliseconds = static_cast<int>(m_pRunData->m_fTickFractionSum * (m_pRunData->m_flTickRate * 1000.0f))

There are of course some annoyances with using fixed point, primarily overflow concerns and tedium in increasing the highest level of precision available to display. For overflow - at least at millisecond precision would not be an issue until displaying times over 8000 hours - at this point if for whatever reason a time this high actually needs to be displayed, the old way could be used. For the concern of ease of changing max precision, it might be a good idea to use the next level of precision, 1/10,000th of a second instead, because it is hard to imagine there ever being meaningful information from a fraction of a tick or something beyond that point, while formatting for lower precision is trivial and this would still display times over 800 hours.

**Comment by Gocnak** [comment]
Good suggestion! Had a couple of comments to add:

> I'm not sure if it actually affects leaderboard placement

It does not, leaderboard placement is purely integer ticks currently. It will start to affect placement when we have things like the offset tracer (#1262). 

> at least at millisecond precision would not be an issue until displaying times over 8000 hours

More than enough, the online leaderboards won't accept a run around 12 hours or so long -- pending actual limit implementation (right now it's just replay file size limit). Local runs I don't really see any point to any hard limit as it'll most likely hit hardware limits (tickcount wrapping past 32 bit int, RAM/HDD space limit, etc) before 8000 hours of recordings are even realized.

>  it might be a good idea to use the next level of precision, 1/10,000th of a second instead

Agreed. Especially if we go sub-tick with that tracer, we will definitely be getting into the sub-millisecond times. 1 tick = 0.015 seconds on 66 tick. Tracer will probably extend that another decimal place or two.

**Comment by harryjah** [comment]
Right, the only reason I mentioned the overflow issue was in case this was used for something like overall playtime in the game or something like that, which could be an easy oversight for anyone working on a random UI feature and looking for a timer, which could lead to some funny bugs 8000/800 hours of playtime down the line

e: I guess it's really unlikely anyone would try to use a fixed point timer from 1/10000th of a second count input for an any potentially long timer in the first place, so never mind
