### ISSUE TITLE
Add ability to switch RL viewmodel to uncentered version without script renaming/reloading

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1264]
**Is your feature request related to a problem? Please describe.**
To get a uncentered viewmodel for the rocket launcher, players have to rename a script to override it then reload the weapon script through console. Tedious for such a simple change.

**Describe the solution you'd like**
Players should be able to switch between centered/uncentered viewmodels just in-game, much like switching to left-handed viewmodels. Currently only applies to the rocket launcher.

**Comment by Gocnak** [comment]
Similar to #463 , implementation will come with the cosmetic system that allows users to change "loadout"
