### ISSUE TITLE
Certain assets fail to load on Linux

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1265]
**Describe the bug**
Some texture files in CSGO maps fail to load completely. It seems to affect mostly map-specific textures, but I'm not sure if those textures are actually packed inside the map or if they are part of the game. This happens on de_dust2 or de_aztec, for example.

Portal 2 maps maps (and CSS/TF2 maps as well) load fine.

**To Reproduce**
- Open de_dust2 on Linux

**Expected behavior**
All textures should load

**Screenshots**
It's just missing textures

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: Chaos latest build

**Additional context**
When it complains about missing textures, the names are in ALL UPPERCASE, that might be related.

Here's the console log from running clear; map de_aztec: https://gist.github.com/bltech/21a81619cf923bc8335735c465baf3d3

EDIT: I noticed a LOT got cut off so here's a more complete log: https://gist.github.com/bltech/9e16efa62fd550dab821351e48a0d115

**Comment by Gocnak** [comment]
Fixed by verifying CS:S install. Was trying to load CS:GO assets for CS:S maps and failing.
