### ISSUE TITLE
Conc grenades are not affected by trigger_push

### ISSUE THREAD

**Issue by checkcheckcheckcheck** [momentum-mod/game#1267]
Conc grenades are currently unaffected by trigger_push entities.

From my understanding, they should exhibit the same behaviour as rockets/stickies currently have when in a trigger_push entity, i.e. a conc thrown into an upwards push would rise, etc.

I can provide examples of this happening in TFC at a later point if needed.

Edit to include hex's comment below for visibility:

"after further testing it seems like concs are actually affected by push triggers- you just need the "everything" flag ticked. it would be nice if there were a conc (or projectile for rj/sj too) specific flag so that the player didn't also need to be affected. could edit this issue or make a new one for that"

**Comment by zike1017** [comment]
This can be tested on conc_yggreboot. When you spawn in inside the church, walk down into the pit. On this level if you noclip down to the bottom there's a trigger push above the small pool of water. This can be seen in the screenshot below.
https://i.imgur.com/X7pOtcT.jpg

Map download:
https://cdn.discordapp.com/attachments/733184759080943706/822161000919859205/conc_yggreboot_works1000percent_a1.bsp

**Comment by Gocnak** [comment]
Just to be clear, there's not any flags like the teleport trigger that filter which entities it applies to, correct? Just my hunch right now, I'll properly look at the entity later today.

**Comment by hexaflexahexagon** [comment]
after further testing it seems like concs are actually affected by push triggers- you just need the "everything" flag ticked. it would be nice if there were a conc (or projectile for rj/sj too) specific flag so that the player didn't also need to be affected. could edit this issue or make a new one for that

**Comment by Gocnak** [comment]
Let's make a new one for that, the original issue is no longer a problem.
