### ISSUE TITLE
surf_squirrelsonvacation - Engine Error

### ISSUE THREAD

**Issue by Kanisof** [momentum-mod/game#1268]
**Describe the bug**
When loading surf_squirrelsonvacation, it will get to around 10% or so, then crash to desktop with "Engine Error"

Fatal error loading pixel shader lightmappedgeneric_ps30 (2208...)

**To Reproduce**
Just load the map. Happens 100% of the time

**Expected behavior**
Load the map and play with squirrels

**Screenshots**
https://i.imgur.com/I7RG26N.jpg

**Desktop/Branch (please complete the following information):**
 - OS: [Windows]
 - Branch: [Latest Chaos version)

**Additional context**
Link to the map: https://gamebanana.com/maps/download/209216

**Comment by braem** [comment]
This map has at least one material (only found `glass/nonshitglass`) with a now invalid combo combination of `normalmapalphaenvmapmask` and `envmapmask`: https://developer.valvesoftware.com/wiki/$envmapmask. I'm not 100% on the reason why it's invalid now, but it makes little sense to have the combination in the first place.

I cannot decompile to get the textures used nor open it in VIDE so can't really change the map. The mapper has already remedied this in their CSGO version anyways, so we strongly encourage you to play that: https://gamebanana.com/maps/download/209241 (will require mounting CSGO i believe)
You can also boot the CSS version of the map with `mat_specular 0` if you really want.

I don't think we should look at this further, considering the error is from a mapper-made texture with a nonsensical combination.
