### ISSUE TITLE
Setting modelscale not possible in 0.8.8

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1269]
Setting modelscale using outputs such as "addoutput modelscale <num>" or "setmodelscale <num>" seem to have been misplaced or disabled in 0.8.8 and should be returned.

**Comment by Gocnak** [comment]
Upon further investigation there's a "ModelScale" keyvalue but no input to actually change it. Needs back porting from 2013.

**Comment by braem** [comment]
Planning on doing the fgd for this after the fgd changes to avoid rebasing the mega PRs

**Comment by braem** [comment]
Finished backporting this and have the FGD PR open. Will be in the next push. Closing.
