### ISSUE TITLE
VGUI uses wrong fonts on Linux

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1270]
**Describe the bug**
Instead of using Bebas Neue / Source Code Pro, the game defaults to Verdana (?), resulting in cutoff UI components

**To Reproduce**
- Launch the game on Linux

**Expected behavior**
The game should use the appropriate font

**Screenshots**
![image](https://user-images.githubusercontent.com/19615431/111887288-4514df80-89d4-11eb-8b5d-9ad55ff4c22e.png)

**Desktop/Branch:**
 - OS: Linux
 - Branch: Latest 0.8.8-rc (fresh install)

**Additional context**
You can also see it here https://discord.com/channels/235111289435717633/733230720079757332/819714644859944970 at around 4 seconds.

According to strace, the game finds the appropriate files and loads them without issue. `vgui_spew_fonts` also lists them (but I have no idea if that has any further meaning). The Momentum symbol font even displays correctly on the weapon switch menu and the Valve logo shows up in the credits.

I also tried: renaming the files to be lowercase and replacing the fonts with the .ttf variants from 0.8.7 to no avail.

**Comment by lvaness** [comment]
Btw it looks like this might be a duplicate of https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/326 ?

**Comment by Gocnak** [comment]
I have a feeling this has to do with the Linux font loader, and comparing against 2013 would be a good idea.

**Comment by kitlith** [comment]
it feels like it's not finding the vfont or something? It's querying libfontconfig, which doesn't know about it, and is returning \<system font that it thinks is closest\>. `[FcFontMatch] Bebas Neue => agave regular Nerd Font Complete Mono` is what i got on my system before i installed Bebas Neue.

Included fonts that it appears to search for:
 - Bebas Neue
 - Source Code Pro
 - Noto Sans
 
it does not appear to search for these:
 - HL2EP2.vfont
 - MomIcons.vfont
 - BigNoodleTitling.vfont (though it sounds like this is straight up unused these days?)
 - hl2crosshairs.vfont
 
you can workaround this locally by installing the fonts on your system
