### ISSUE TITLE
Goto button does not work on demoui

### ISSUE THREAD

**Issue by zike1017** [momentum-mod/game#1273]
**Describe the bug**
When playing back a demo on the chaos engine, the "Goto:" button is grayed out and does not function.

**To Reproduce**
1. Record a demo on any map
2. Stop the recording and playback the demo
3. Attempt to go to a certain time stamp in the demo
4. button no work :(

**Expected behavior**
The Goto: button should not be grayed out and should fast forward the demo to the specified tick.

**Screenshots**
https://i.imgur.com/BNbHkw8.png

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest Steam beta build for chaos

**Comment by Gocnak** [comment]
I'm thinking the demoplayer UI has the goto button disabled for some reason, but this is pending a further investigation into it. Should be a smaller card though.

**Comment by Gocnak** [comment]
Okay did some initial investigation, it's because the demoUI is now the CS:GO one: 
![image](https://user-images.githubusercontent.com/5162166/112775121-e8d04200-9009-11eb-8e94-8775540b51b3.png)

I assume we're probably not going to want this. I'll discuss with the Chaos team about it.

**Comment by Gocnak** [comment]
Closing as we're going to favor replays over demos.

**Comment by hexaflexahexagon** [comment]
> Closing as we're going to favor replays over demos.

I thought we planned on doing some sort of conversion from replay to demo in order for existing editing tools (SVR) to be usable, is that not the case anymore?

**Comment by Gocnak** [comment]
SVR doesn't require a demo to work; it replaces the startmovie command. You can startmovie and play back a replay to get a similar effect. Combined with the feature requests to make replays more video editor friendly, and being able to record arbitrary ones, demos will be more of a legacy system.
