### ISSUE TITLE
Rocket launcher takes too long to fire after switching from the shotgun

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/game#1276]
**Describe the bug**
The rocket launcher currently needs to wait for the full deploy animation to complete before firing, whereas it used to be able to override it with the correct timing in 0.8.7.

**To Reproduce**

1. Equip the shotgun
2. Switch to rocket launcher 
3. Shoot

**Expected behavior**
The rocket should fire at the same timings as in TF2/0.8.7.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch

**Comment by Hona** [comment]
Duplicate of #1242
