### ISSUE TITLE
Main menu 3d model can be moved

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1278]
**Describe the bug**
The main menu's 3d logo can be moved by holding shift and then clicking it, this is unintentional behavior. It does teleport back to its original position after releasing the mouse so you can't 'lose' it out of the edges of the panel but it shouldn't be possible to move it in the first place.

**To Reproduce**
1. Open the game
2. shift+click and drag the main menu logo
3. it moves and should not

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8-rc

**Additional context**
You can also change the lighting (ctrl+click) but I'm unsure if that's intended or a bug. It does not reset on releasing your mouse like moving the logo does.

**Comment by Gocnak** [comment]
This is no longer the case in Panorama, which we're heading towards.
