### ISSUE TITLE
savelocs dont save after reloading map with -hijack

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#1281]
I'm making a map and made a whole bunch of savelocs, when recompiling and running the $game_exe thing with -hijack it reloaded map like it's supposed to but all savelocs disappeared. plz fix.

on chaos steam version

edit: did the same thing again and now the savelocs saved, gonna test some more

**Comment by granis48** [comment]
ok i cant seem to reproduce it, dunno what happened so im just gonna close this

**Comment by Gocnak** [comment]
If it happens again definitely try to get the steps for it! Savelocs are saved on map shutdown, so if -hijack is not properly shutting down the map then it could not save them.

**Comment by granis48** [comment]
I found out how to replicate it!

It will never save new locs that are started with the timer running. however if i disable the timer and create a saveloc, it will save after reload. 

To replicate yourself: 
- make a map and zone it
- create some savelocs with the timer running
- recompile map and launch game with the -hijack parameter
- watch the savelocs disappear

Any savelocs made without timer will stay like normal after reload. 
Only happens if timer is running when you make the savelocs. 
Normal reloads (reload, retry or reopening the map) do not have this issue.

**Comment by braem** [comment]
Something similar is happening to @Road2SilverEagleMaster in Discord. Savelocs aren't saving for them when reloading a map manually after it compiles (not using `-hijack`). Also happens for them with timer off. They are using hammer++.

See https://discord.com/channels/235111289435717633/356398721790902274/837629785914998794

I'm wondering if hammer is doing something when compiling a map that you are currently on which prevents shutdown from being called. Or maybe just changing the map file at all?

**Comment by Gocnak** [comment]
Found out why it happened, was a missing check in the engine. Should be fixed in the next push.

**Comment by Gocnak** [comment]
Savelocs should properly save on level shutdown, either through hijack or even the map command.
