### ISSUE TITLE
Game is automatically noborder when in windowed mode.

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1284]
**Describe the bug**
Running momentum in windowed mode (either through launch options or by changing in-game video settings to windowed) will never have a border. This is the opposite of how traditional source games work where you need to opt-in to noborder with a launch option. This is inconvenient for most users as they would rather be able to drag the window around.

**To Reproduce**
1. Launch the game in windowed mode.

**Expected behavior**
The game should be bordered by default, requiring a launch option to opt-in. 

Alternatively, we could just add an option to turn borders on (e.g. `-border` to compliment `-noborder`) but that seems unintuitive given people are used to how other source games work. 

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8-rc

**Additional context**
Might be a general chaos issue rather than momentum but i'm putting the issue here to be safe since I can't play p2ce.

It could also be nice to have an in-game option to enable/disable window borders but that's probably better in a separate issue.

**Comment by braem** [comment]
Issue is with the videocfg being stored in local storage. You can change this by going to `[your steam install] > userdata > [your userID] > 669270 > local > cfg > video.txt` and changing `"setting.nowindowborder"` to `"0"`.

It is a Chaos issue yeah. I believe the best resolution to be storing this in `[game]/cfg/` instead, as Portal2 does.

**Comment by braem** [comment]
Changed to read/write from `momentum/cfg` / `p2ce/cfg`. In the next push, to get a border you will have to go into `momentum/cfg/video.txt` and change the setting there (it will be created when you launch the game for the first time).
