### ISSUE TITLE
skybox_swap causes crash

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1285]
**Describe the bug**
Using `skybox_swap` appears to consistently crash the game while on any map.

**To Reproduce**
1. load a map (e.g. rj_beef)
2. enter the `skybox_swap` command

**Expected behavior**
The game should not crash and the command should work as intended if we care about that. I believe it's a portal 2 command from what I can see online but there isn't very much about it that I can see. The description given by `help` reads "Swap through the skyboxes in our queue." We already have our own way of changing skyboxes so this could possibly just be removed entirely.

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8-rc

**Comment by Gocnak** [comment]
Fixed for next push, was a simple null check.

**Comment by Gocnak** [comment]
Does this still happen?

**Comment by hexaflexahexagon** [comment]
fixed with the newest push
