### ISSUE TITLE
stripper:source support?

### ISSUE THREAD

**Issue by Nyano1337** [momentum-mod/game#1286]
There's no tools and plugins to fix maps as i know.
Can we support **stripper:source** in the future in order to fix some surf maps, such as surf_map_h, surf_compulsive_h, surf_exocube_h and so on.

**Comment by hexaflexahexagon** [comment]
maps should be fixed through hammer when they're being made or ported to momentum, adding something like stripper just adds needless complexity where we don't really need it like a traditional server would.

**Comment by itVictor** [comment]
I think he means for playing maps for personal use, especially maps that aren't added to momentum as an official map (yet). Many of those maps can be buggy and were fixable with stripper in css/go.

That said I can't imagine it'd be worth it for momentum to support metamod/other plugin stuff for a relatively niche use-case.

**Comment by Gocnak** [comment]
Hi, maps will be fixed upon being officially added to the game's map selector. Basically, using [entspy](https://developer.valvesoftware.com/wiki/Entspy) on the bsp, or decompiling and recompiling (worst case scenario) to fix the map.

Run-time fixes like Stripper that run every time is messy in my opinion, versus fixing things permanently (and only once).

I'd love to have our map porting tool be open source, so definitely keep an eye out for a new repo popping up in this org sometime soon. The goal would be to have the same tools that porters+admins will use to review maps before adding them, allowing quick and easy modifications.
