### ISSUE TITLE
Parallax-corrected cubemaps show up as wireframe on Linux

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1289]
**Describe the bug**
The floor below spawn on `triggertest` and half of `cubemaptest` are transparent with a wireframe surrounding it.

**To Reproduce**
- Open `triggertest`

**Expected behavior**
The floor should show a proper cubemap

**Screenshots**
![cubemaptest0002](https://user-images.githubusercontent.com/19615431/114246836-f2579380-9993-11eb-8a9a-4e6ae5bc4855.jpg)

**Desktop/Branch (please complete the following information):**
 - OS: Linux
 - Branch: 0.8.8-rc

**Additional context**

```Error: Material "maps/cubemaptest/cubemaptest/plasterwall030a_parallax_0_0_64" uses unknown shader "SDK_LightmappedGeneric"
Error: Material "maps/cubemaptest/cubemaptest/plasterwall030c_parallax_0_0_64" uses unknown shader "SDK_LightmappedGeneric"
Error: Material "maps/cubemaptest/cubemaptest/plasterwall030c_parallax_3_-468_62" uses unknown shader "SDK_LightmappedGeneric"
Error: Material "maps/cubemaptest/cubemaptest/tilefloor_cmf_3_-468_62" uses unknown shader "SDK_LightmappedGeneric"
Error: Material "maps/cubemaptest/cubemaptest/tilefloor_cmf_3_480_62" uses unknown shader "SDK_LightmappedGeneric"
Error: Material "maps/cubemaptest/cubemaptest/plasterwall030a_parallax_3_480_62" uses unknown shader "SDK_LightmappedGeneric"
Error: Material "maps/cubemaptest/cubemaptest/plasterwall030c_parallax_3_480_62" uses unknown shader "SDK_LightmappedGeneric"
Error: Material "maps/cubemaptest/cubemaptest/tilefloor_cmf_0_0_64" uses unknown shader "SDK_LightmappedGeneric"
Error: Material "maps/cubemaptest/cubemaptest/plasterwall030a_parallax_3_-468_62" uses unknown shader "SDK_LightmappedGeneric"
```

**Comment by Gocnak** [comment]
While this bug is because the map uses the old SDK_ shader, the current lightmappedgeneric also doesn't have fully working PCC due to needing recompiling, and that recompiling taking 50+ days on a single computer.

**Comment by hexaflexahexagon** [comment]
in chaos this is now an issue on windows as well it looks like. dx9/11 both.

**Comment by Gocnak** [comment]
Correct, the problem is the shader name, not the shader itself. PCC should be in the base LightmappedGeneric shader, not SDK_Lightmapped.

**Comment by lvaness** [comment]
While they aren't parallax-corrected (on DX9/togl), they aren't wireframe anymore.
