### ISSUE TITLE
Documentation on building

### ISSUE THREAD

**Issue by thomassross** [momentum-mod/game#129]
Even just a link to https://developer.valvesoftware.com/w/index.php?title=Source_SDK_2013 and https://developer.valvesoftware.com/wiki/Setup_mod_on_steam would probably be enough.

**Comment by tuxxi** [comment]
https://github.com/momentum-mod/game/wiki/Building-the-mod

Is this documentation sufficient? I can add more if needed.

**Comment by Gocnak** [comment]
After going through about 4 migrations of builder VMs, I'll take a shot at adding the instructions for all 3 platforms to our wiki that Tuxxi linked there. I'll close this issue when I've done so.

**Comment by Gocnak** [comment]
Sorry it took so long, but the wiki page is now [Building The Game](https://github.com/momentum-mod/game/wiki/Building-The-Game) and includes all three platforms. If this needs fleshed out more just open another issue about it.
