### ISSUE TITLE
Smoke rendering issue on rj_it

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1292]
Reported by Durbo

**Describe the bug**
The smoke in this rj_it connector renders strangely. It renders fine when farther away but getting close renders these weird squares.

**Screenshots**
![image](https://user-images.githubusercontent.com/9014762/114286856-58392f00-9a17-11eb-9e47-c901aebf3466.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8

**Additional context**
This is using a TF2 particle (exists in `particles/TF2_fx.pcf`). I believe one of these:
![image](https://user-images.githubusercontent.com/9014762/114286850-50798a80-9a17-11eb-8bf5-93a9830d2d1f.png)
Maybe a shader issue the materials these use (`materials/particle/flamethrowerfire/flamethrowerfire102` or `materials/smoke/smokelit_nofade_add`)

**Comment by braem** [comment]
Also happens with fog here on arcane:
![image](https://user-images.githubusercontent.com/9014762/114826194-09272d00-9d7c-11eb-978c-8b5bcea28b27.png)

**Comment by Gocnak** [comment]
Ended up being a shader problem, fixed in the next push.

**Comment by Arkanoid0** [comment]
No more squares
