### ISSUE TITLE
Wrong reflections from previous map

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1293]
**Describe the bug**
Loading [this](https://cdn.discordapp.com/attachments/634116622159708193/830687368679915560/conc_speed_remastered_a8.bsp) map and going to `setpos 8499.869141 -5424.492188 3667.485840;setang 82.663818 97.830345 0.000000
` (the start of level 4) will normally not have any noticeable reflections at all on the water. However, after loading some previous maps and then loading `conc_speed_remstaster_a8` the reflections were horribly wrong and using an image from somewhere it shouldn't have been, see below.

![image](https://user-images.githubusercontent.com/62961532/114297964-daf6d400-9a81-11eb-8c15-207fa3c735e8.png)

**To Reproduce**
I can't find a way to consistently reproduce this issue. I suspect it had something to do with loading a texture (maybe a cubemap?) from a previous map that is used on the next map when it shouldn't be. The maps I can remember loading are the linked map, de_dust2 (from CS:S, not GO), dz_blacksite, and then the linked map again, where the issue was found. There may have been more but I don't remember exactly.

**Expected behavior**
The reflections should look as they're meant to.

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8-rc

**Additional context**
The map linked above was made by fingerprince if there are questions about it.

**Comment by Gocnak** [comment]
I wonder if a cubemap texture isn't being correctly shutdown. Might be when the map packs its own cubemap and you go to one without one. Maybe that isn't cleared? Not sure, would have to reproduce this first.

**Comment by SCell555** [comment]
This looks like water rendertargets aren't getting updated and are stuck at last rendered view.

**Comment by SlidyBat** [comment]
There were some changes/fixes I did to cubemap loading that may have fixed this. It's difficult to tell though without reliable reproduction steps.

**Comment by hexaflexahexagon** [comment]
if in a couple months of casual playing nobody has seen this issue again I'll probably call that good enough and close the card. i couldn't recreate it reliably no matter what i tried

**Comment by hexaflexahexagon** [comment]
i'll go ahead and close this until somebody else experiences this issue, i couldn't replicate it even before it was possibly fixed
