### ISSUE TITLE
DX11 some transparent textures are broken

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1295]
**Describe the bug**
When using dx11 some transparent textures are broken and are instead filled in with a gray color.
Some examples can be found at https://imgur.com/a/qJvry68 (you can see some transparent materials working on rj_cube, they just look a bit different than dx9 which is probably fine. the ones on rj_apex don't work at all)

edit: after the most recent 0.8.8 fix these textures are no longer filled with gray but are instead completely binary, see this comment: [https://github.com/momentum-mod/game/issues/1295#issuecomment-831683433](https://github.com/momentum-mod/game/issues/1295#issuecomment-831683433) 

**To Reproduce**
1. Load a map with a transparent texture (rj_apex)
2. Look at it and notice the lack of (proper) transparency

**Expected behavior**
The texture should look normal

**Screenshots**
https://imgur.com/a/qJvry68

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8 Dx11

**Comment by hexaflexahexagon** [comment]
doesn't appear to be completely fixed. on rj_apex at least there is either full transparency or full opacity on the glass texture, similar to $alphatest. compare this to the screenshot in the initial post where there are some textured lines between the grids themselves.
![image](https://user-images.githubusercontent.com/62961532/116962460-02e9e980-ac74-11eb-9bb7-0d63543f7f90.png)

**Comment by SlidyBat** [comment]
> doesn't appear to be completely fixed. on rj_apex at least there is either full transparency or full opacity on the glass texture, similar to $alphatest. compare this to the screenshot in the initial post where there are some textured lines between the grids themselves.
> ![image](https://user-images.githubusercontent.com/62961532/116962460-02e9e980-ac74-11eb-9bb7-0d63543f7f90.png)

This is the same issue as https://github.com/momentum-mod/game/issues/1316 (which is that $alphatest is on when it shouldn't be), so I'm closing this in favor of that.
