### ISSUE TITLE
DX11 overlays with transparency are broken.

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1296]
**Describe the bug**
Overlays with transparency show up fine, but all of the transparent area is set as white when it shouldn't be. This is very visible here on sj_internal. Using `r_renderoverlayfragments 0` makes the entire thing disappear.
![image](https://user-images.githubusercontent.com/62961532/114689591-d893b480-9ce3-11eb-947c-185bbd6060dc.png)

**To Reproduce**
1. Load a map with overlays (sj_internal)
2. Look at one and notice the lack of transparency

**Expected behavior**
The overlays should work as intended

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8 dx11

**Additional context**
Might be related to https://github.com/momentum-mod/game/issues/1295

**Comment by Gocnak** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/5162166/116767760-37ee0600-aa00-11eb-8701-da6d2b9951c4.png)
