### ISSUE TITLE
DX11 Sticky activation ring too large

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1297]
**Describe the bug**
The sticky activation ring is too large and the size changes depending on which map you load, most likely due to being further from 0 0 0. The first picture below is a couple hundred units from the origin of the world, the second is almost on one corner of the grid.
![image](https://user-images.githubusercontent.com/62961532/114690218-7e472380-9ce4-11eb-9693-1063203c9c28.png)
![image](https://user-images.githubusercontent.com/62961532/114690237-81421400-9ce4-11eb-90ba-198dd0d408bb.png)

It's worth noting that the size doesn't change with player distance from the ring, just where the sticky was shot.
![image](https://user-images.githubusercontent.com/62961532/114690350-98810180-9ce4-11eb-801a-fab09b37ca4a.png)

**To Reproduce**
1. Load any map with stickyjump movement
2. Shoot a stickybomb and observe the particle being too large.

**Expected behavior**
The particle should be the right size

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8 dx11

**Comment by Arkanoid0** [comment]
Appears fixed in conc to, which uses the same particle and had the same issue.
