### ISSUE TITLE
(DX11?) +paint decals and shallow water don't interact properly

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1299]
**Describe the bug**
Decals that are partially or completely underwater look strange, have bad coloring, aren't properly transparent, and so on. This happens both on dx9 and dx11 but the issues appear to be visually different on either.

DX11:
![image](https://user-images.githubusercontent.com/62961532/114747595-01856b00-9d1f-11eb-9aa3-74b5f145cf76.png)

DX9:
![image](https://user-images.githubusercontent.com/62961532/114747819-3f828f00-9d1f-11eb-8aa7-df826ad238fc.png)

**To Reproduce**
1. Load a map with water (sj_internal)
2. Paint

**Expected behavior**
The paint should work.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8

**Comment by Arkanoid0** [comment]
Paint and explosion decals are still broken for me on DX11 
![image](https://user-images.githubusercontent.com/1642129/116765868-b63caf00-a9e4-11eb-838b-f2b9233a2aaf.png)

**Comment by SlidyBat** [comment]
I've implemented a solution that fixes this for both DX9/DX11, should be available to test next update.

**Comment by hexaflexahexagon** [comment]
looks good now
