### ISSUE TITLE
DX11: Weird lines on textures with flashlight on when shadows are set to high

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1300]
**Describe the bug**
Shining the flashlight while looking at the floor or at a wall (if you're close to it, don't appear from far away) will cause weird lines to appear, warping when you move your viewing angle with your mouse. From my testing, this only happens when shadow detail is set to "high" in settings, setting it to low or medium causes the lines to not show. Other settings appear to have no effect.

**To Reproduce**

1. set shadow detail to high in video settings
2. load a(ny) map (tested on rj_beef)
3. shine flashlight and look at floor or walk up to a wall 
4. see lines that warp when you move your mouse

**Expected behavior**
No lines appear.

**Screenshots**
![20210414211903_1](https://user-images.githubusercontent.com/20176719/114805020-de32de00-9d67-11eb-9496-86be32496946.jpg)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8 with DX11 enabled

**Comment by Gocnak** [comment]
Does this still happen on latest DX11?

**Comment by hexaflexahexagon** [comment]
Nope
