### ISSUE TITLE
Crash on surf_pantheon

### ISSUE THREAD

**Issue by Ekibunnel** [momentum-mod/game#1301]
**Describe the bug**
Game crash on map loading.

**To Reproduce**
Load the map surf_pantheon

**Expected behavior**
Don't crash

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version 0.8.8

**Additional context**
using dx9 idk if that matter

**Comment by Gocnak** [comment]
Does this still happen on latest?

**Comment by Ekibunnel** [comment]
Fixed, It doesn't crash anymore.
