### ISSUE TITLE
Investigate optimizing map dropdown loading in console

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1303]
**What feature is your improvement idea related to? Please describe.**
Typing `map ` in console with a large amount of maps mounted will result in a significant stutter or even the game freezing temporarily. 

**Describe the solution you'd like**
Some way of loading maps that doesn't freeze the game or cause huge stutters, perhaps only loading what is strictly necessary to display? A game dev would know better than I do how to fix this sort of issue.
![image](https://user-images.githubusercontent.com/62961532/114961433-fde50780-9e36-11eb-9566-61b50d09357d.png)

**Comment by Gocnak** [comment]
Could cache the map list and asynchronously build it. Would be a fun exercise.

**Comment by Gocnak** [comment]
This has an async version in the next push -- keep in mind with lots of maps it might take a bit to fully populate the list now, but it should no longer stutter.

**Comment by Arkanoid0** [comment]
Works, but spams the console every time you type a new letter. 
![image](https://user-images.githubusercontent.com/1642129/116765654-68737700-a9e3-11eb-8085-a04954f2a32c.png)

**Comment by Gocnak** [comment]
So the original problem is gone, but a separate card can be made for having this not spam (as much) and send a message to console when it's done. I'll close this issue, definitely open a new one for that though!
