### ISSUE TITLE
Toggle Duck in "Ahop" no longer unducks automatically after jumping

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1304]
Using toggle_duck in ahop is meant to uncrouch you after jumping, this is no longer the case as of 0.8.8

**Comment by braem** [comment]
This is because the new engine has `toggle_duck` as well, so it's duplicated (should spit out a console warning on boot). It's most likely using that over ours somehow.

**Comment by hexaflexahexagon** [comment]
fixed
