### ISSUE TITLE
Make hammer not register as a steam app

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1305]
Ported from https://github.com/ChaosInitiative/Chaos-Source/issues/82

### Describe the bug
Opening hammer for a certain game counts on steam as playing that game. This can be nice for tracking hours mapping (and may even be an intended feature?) but it is inconvenient because you can't launch a game from steam while using hammer, a regression from existing valve games. According to the above discussion this could be accomplished by either changing hammer's appID (if we were to have a separate SDK or something) or by making hammer not run as a steam game.

### To Reproduce
1. Open hammer
2. Look at steam

### Expected behavior
Opening hammer should not make steam think that you are playing the game.

### Operating System (Optional: Only if OS Specific)
 - OS: Windows
 - Branch: 0.8.8

**Comment by SCell555** [comment]
This applies to any tool (vbsp, vvis, vrad, ...) that uses filesystem. They will also show up as Momentum or whatever game they belong to.

**Comment by hexaflexahexagon** [comment]
confirmed fixed in latest update
