### ISSUE TITLE
Velocity not correctly resetting in saveloc [0.8.8]

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1307]
When teleporting to a saved location, your previous speed, before teleporting, effects the speed set by the saveloc which you teleport to, only if the held key pushed is moving into the same direction your previously velocity was going, relative to the savelocs location.
![savevel](https://user-images.githubusercontent.com/62808028/115118738-9ea10780-9f9c-11eb-86b1-a4aae4416fae.gif)

Expected behaviour is the velocity when teleporting should always be the same into the saved direction, regardless of what keys are being held or what velocity you previously had before teleporting, refer to 0.8.7 for example.

This was hard to explain but I hope it's understood, ask for more details if needed.

**Comment by Arkanoid0** [comment]
Fix appears to work, cannot replicate.
