### ISSUE TITLE
SJ decals don't show up

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1308]
**Describe the bug**
SJ decals don't show up after detonating a stickybomb even when the setting is enabled. They still work for ghosts in your lobby.

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8

**Comment by Gocnak** [comment]
Should be fixed for next push.

**Comment by Gocnak** [comment]
Confirmed show up.
