### ISSUE TITLE
Speedometer text can get covered by damage indicator

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1313]
Due to the Z position of the speedometer vs the damage indicator, the damage indicator can draw over the other HUD elements and should be shifted to be further back. This *should* be simple by just changing the "zpos" key in the damage indicator's res file (for the main control) to be a negative value.

![image](https://user-images.githubusercontent.com/5162166/116506487-63031900-a88b-11eb-8c7e-81ee54044a7a.png)

Reported by Toss in our Discord

**Comment by braem** [comment]
Yup, simple fix
![image](https://user-images.githubusercontent.com/9014762/116526486-81b6df00-a88e-11eb-81ce-769ae9883d31.png)
