### ISSUE TITLE
Using map command results in console spam when maplist is not fully loaded

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1315]
Works, but spams the console every time you type a new letter. 
![image](https://user-images.githubusercontent.com/1642129/116765654-68737700-a9e3-11eb-8085-a04954f2a32c.png)

_Originally posted by @Arkanoid0 in https://github.com/momentum-mod/game/issues/1303#issuecomment-830475083_

**Comment by Gocnak** [comment]
Clarifying note: This should:
1. only print once every X seconds (I say 5 or even 10)
2. and then print that it is done searching.

**Comment by Gocnak** [comment]
This was implemented. @Arkanoid0 can you confirm if the spamming has stopped?

**Comment by Gocnak** [comment]
Closing for now, cannot get the spam on my machine, re-open if it's still the case.
