### ISSUE TITLE
Dx11 some textures don't render at all

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1316]
**Describe the bug**
Some textures show as nodraw in dx11. Examples:
![image](https://user-images.githubusercontent.com/62961532/116961392-3aa36200-ac71-11eb-9cd2-475f0cb5fdac.png)
![image](https://user-images.githubusercontent.com/62961532/116961411-468f2400-ac71-11eb-8fdc-f87e85c40d0a.png)
![image](https://user-images.githubusercontent.com/62961532/116961425-4db63200-ac71-11eb-9e9a-10e8519ed70d.png)
(the second example flickers if you move your mouse, hence the two images. may be a different issue than the first screenshot)

dx9:
![image](https://user-images.githubusercontent.com/62961532/116961536-97068180-ac71-11eb-860a-898f877f4e06.png)
![image](https://user-images.githubusercontent.com/62961532/116961552-9f5ebc80-ac71-11eb-9312-a960fe955f24.png)

**To Reproduce**
1. Load the map below
2. `setpos -433.119812 206.739929 -869.967896;setang 18.876011 161.111069 0.000000`
3. `setpos -3712.000000 0.000000 -955.968750;setang 0.000000 0.000000 0.000000`

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8 dx11

**Additional context**
[map download](http://jumpacademy.tf/maps/academy_classic/b)

**Comment by vindow** [comment]
Also happens with vent textures on rj_apex:
![20210503225439_1](https://user-images.githubusercontent.com/5974776/116965637-20fb1e00-ac63-11eb-8d81-b3bcf92e70a2.jpg)
rj_apex pos:
`setpos 13051.434570 3943.968750 1476.031250;setang 36.260406 -136.533905 0.000000`


As well as these cliff textures on jump_adventure
![20210430174810_1](https://user-images.githubusercontent.com/5974776/116965680-36704800-ac63-11eb-86eb-43b3c4b58a52.jpg)
jump_adventure pos:
`setpos 6710.374023 -9762.881836 3291.031250;setang 4.245146 -2.240451 0.000000`

[map download for jump_adventure](https://jumpacademy.tf/maps/adventure)

**Comment by SlidyBat** [comment]
Seems like $alphatest was being enabled when it shouldn't have been. This should be fixed in the next build, please retest.

**Comment by hexaflexahexagon** [comment]
fixed on newest update
