### ISSUE TITLE
Dx11: mat_texture_list 1 is not working properly

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1317]
**Describe the bug**
May be a chaos issue but I can't test p2ce. While in dx11 mat_texture_list 1 shows no textures and is blank.
![image](https://user-images.githubusercontent.com/62961532/116962105-21031a00-ac73-11eb-85ec-14cccf3ee68b.png)

**To Reproduce**
1. Load any map
2. `mat_texture_list 1`
3. nothing happens

**Expected behavior**
The menu shows up properly
![image](https://user-images.githubusercontent.com/62961532/116962234-72130e00-ac73-11eb-9d50-ed556893508c.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: 0.8.8 dx11

**Comment by SlidyBat** [comment]
I've implemented most of the needed things for `mat_texture_list` to work, minus the texture size/memory used info. So this should work in the next build, but sizes will be reported as 0 kb. I'm waiting until I finish some other work before I implement that.

I'm happy to keep this issue open until then to track that.

**Comment by hexaflexahexagon** [comment]
everything but size appears to be working after the newest update like mentioned in slidy's last comment. will leave this open to track that
![image](https://user-images.githubusercontent.com/62961532/117627897-94f76380-b146-11eb-9f59-c16afafd65fa.png)

**Comment by hexaflexahexagon** [comment]
appears to be fixed
