### ISSUE TITLE
Startup screen is off in panorama

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#1319]
**Describe the bug**
The startup screen when first launching the game doesn't display correctly.

**To Reproduce**
Launch the game in panorama (ie. without `-legacyui` param).

**Expected behavior**
Startup screen displays correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/25954912/117242227-3301da00-ae78-11eb-938d-53256fd6346d.png)

**Additional context**
It seems that the image used in the splash screen (`console/background01_widescreen.vtf`?) is expected to be a square texture. The rendering code then stretches it to the required resolution. Either change that requirement, or replace the texture with one that works properly.

**Comment by Gocnak** [comment]
Yeah the 2013 menu assumes it's just widescreen already but bases it on aspect ratio, hence the `_widescreen` addition there.
