### ISSUE TITLE
Add setting to not restart timer on re-entering a start zone

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1321]
**What feature is your improvement idea related to? Please describe.**
Currently entering the start zone will always reset your timer and restart your run. This is problematic for defrag maps especially where going back through the start area with extra speed is required. This can be worked around by changing geometry but that would be tedious for the large number of ported maps that would need to have that done.

**Describe the solution you'd like**
Add an option to the timer start zone entity to allow players to go back through the start area, keeping speed but not restarting their timer. This option should be togglable in the same way that something like timer starting on jump/on leaving the zone is.

**Describe alternatives you've considered, if any**
Mentioned above this can be worked around with teleports and changing map geometry but that would get tiring for map porters & having maps be as close to 1:1 as possible is typically desired regardless.

**Additional context**
Suggested by sOkam! in the discord.

**Comment by Gocnak** [comment]
Hold on, if a map *requires* that the start zone not restart the timer, this is a different priority entirely, and would have to be mapper controlled (in the zone file).

Otherwise this might actually benefit from being the default behavior... most people reset with a bind anyways and we can add a HUD hint for doing so... needs discussing with the community.

**Comment by hexaflexahexagon** [comment]
i dont think this needs to be default behavior, just a kv that mappers can optionally set that's somehow communicated to the player

**Comment by jason-e** [comment]
Some options we may add which would both allow for this are:
1. Only activating a zone when the player is on the ground (the setting to deactivate the zone could still be separately set to on-leave or on-jump)
2. Attaching a filter entity to the zone that the player must pass to activate it (deactivating could also be done with a filter, though leaving the zone volume would still always deactivate it).
