### ISSUE TITLE
func_lod does not show up in game

### ISSUE THREAD

**Issue by RoadyBhop** [momentum-mod/game#1324]
**Describe the bug**
func_lod is invisible

**To Reproduce**
load a map with func_lod in it and noclip to it

bhop_4muddz has one in at the end of stage 2 right before the teleport door https://gamebanana.com/mods/124341

**Expected behavior**
func_lod is invisible at range then becomes visible when closer

**Desktop/Branch (please complete the following information):**
 - OS: Windows 10
 - Branch: steam version

**Comment by Gocnak** [comment]
Extra details:

It seems like func_lod [had its keyvals changed in the L4D branches](https://developer.valvesoftware.com/wiki/Func_lod) (which we're now based on in Chaos) to allow a range:
![image](https://user-images.githubusercontent.com/5162166/118078562-77174200-b384-11eb-9cc5-a8904a79c57d.png)

We may just need to tweak the default behavior to take the value in (is the keyval named different? the value not properly applying to the range?).

**Comment by braem** [comment]
The old kv is coming across fine, just that there is an issue with computing distance fades it seems. Most likely effects more than just `func_lod`s

**Comment by hexaflexahexagon** [comment]
seems to be fixed on `bhop_4muddz` with latest update

**Comment by braem** [comment]
Good to note for the map porting guide that the distance fade calculation differs from older games to newer ones (portal 2, csgo, etc). So if these old maps are recompiled with our hammer, they will have to account for the new distance fade calculation.
