### ISSUE TITLE
func_button sometimes doesn't work correctly the first time it is used

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1325]
**Describe the bug**
This bug exists in tf2 as well as momentum mod. 

`func_button` entities, specifically set to something like `On Damaged -> !activator`, do not work properly the first time they are used in the current session. Using them a second, third, etc time will work properly. Also in SJ using 2 stickies instead of 1 for the first activation will work for some reason, even if they are both detonated at the same time.

**To Reproduce**
1. Load a map set up like above (`jump_yes_b4` linked below)
2. Go to the button (`setpos -8933.917969 -8209.738281 -8091.968750;setang 25.177860 -147.275574 0.000000` on `jump_yes_b4`, the button is the purple platform below you)
3. Shoot the button once, you do not teleport. 
4. Shoot the button again, you do teleport. 
5. Use the setpos command to shoot the button again, now every time you hit the button you will teleport like desired.
6. Reload the map and notice that the first time you shoot the button it again does not work properly.

**Expected behavior**
Buttons should work the first time you shoot them

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: 0.8.8

**Additional context**
`jump_yes_b4` download can be found at https://mega.nz/file/8OpFAIzS#kKS6BiSJa3suc3tCGvVHUbdxy4YbySx_-ZD5258_ZEs

**Comment by braem** [comment]
> Also in SJ using 2 stickies instead of 1 for the first activation will work for some reason, even if they are both detonated at the same time.

A little note on this: explosions happen one after another even when they're on the same tick. So the OnDamage func or w/e is being called twice in that situation.

**Comment by hexaflexahexagon** [comment]
> A little note on this: explosions happen one after another even when they're on the same tick. So the OnDamage func or w/e is being called twice in that situation.

ah that makes more sense then.

**Comment by braem** [comment]
Does this still occur?

**Comment by hexaflexahexagon** [comment]
Fixed on newest version.
