### ISSUE TITLE
Certain console errors do not print on a new line

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1327]
**Describe the bug**
Some (possibly) new errors  are not formatted to end in a new line, causing the console to mash errors together creating a single hard to read block

**To Reproduce**
1. Start the game
2. Open the console

**Expected behavior**
The errors should print to new lines and in the case of multiple consecutive errors, bundle them together  and append a multiplier at the end indicating how many times said error was printed within a short time frame. E.g.: `Big Red Error! (x8)`

**Screenshots**
![image](https://user-images.githubusercontent.com/35622748/118385586-c4d6b900-b5d5-11eb-843b-cb4d290b2011.png)
![image](https://user-images.githubusercontent.com/35622748/118385593-db7d1000-b5d5-11eb-8023-f0b29fdd214c.png)
![image](https://cdn.frankerfacez.com/emoticon/109777/1)

**Desktop/Branch (please complete the following information):**
 - OS: Windows 10
 - Branch: Steam 0.8.8

**Comment by lvaness** [comment]
So the particle sheet one was actually already fixed for the next push, do you have any map where the second one happens?

**Comment by VortexParadox** [comment]
No map, this is all from the console log as soon as the game lets me open it

**Comment by lvaness** [comment]
My plan is to just remove the r_rootlod_enable launch parameter and restore the functionality and see if any problems arise, there's no easy way to find out if the issue referenced in the error even applies anymore

**Comment by Gocnak** [comment]
Does this still happen on the latest build?

**Comment by patrickmoc** [comment]
![20210530091039_1](https://user-images.githubusercontent.com/49064563/120103667-1f6c2b00-c127-11eb-91d0-7c59ca7432e3.jpg)
On the latest build these errors have the correct newlines, the other errors do not appear on startup.

**Comment by patrickmoc** [comment]
> The errors should print to new lines and in the case of multiple consecutive errors, bundle them together and append a multiplier at the end indicating how many times said error was printed within a short time frame. E.g.: `Big Red Error! (x8)`

If the multiplier mentioned was intended to be in this fix, it does not appear.

**Comment by Gocnak** [comment]
The multiplier for multiple errors of a similar type is a different feature request card, original issue was fixed.
