### ISSUE TITLE
Investigate optimizing time to mount other games on boot

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1328]
**Is your feature request related to a problem? Please describe.**
Loading momentum while not mounting any other source games is significantly faster than when mounting them. On my system, editing `gameinfo.txt` to remove all other source games results in a loading time of a couple of seconds. Using the default configuration and mounting TF2 (with 1000s of custom maps), CSS, CSGO, and Portal 2 takes over 3 minutes to load. For me momentum is on an SSD and every other game is on my HDD which, admittedly, is old and dying, but other people have reported the similar loading times likely due to assets or custom maps in base games. 

While we will support easier user selection of what to mount (think Garry's mod's UI for it) having load times this long is always good to avoid if possible. 

**Describe the solution you'd like**
Investigate how game assets are mounted and try to improve boot time. I'm not a programmer so I have no idea how best to do this.

**Comment by lvaness** [comment]
For now, we will have the options mentioned in https://github.com/momentum-mod/game/issues/1030#issuecomment-867479426 to at least triage the issue if you have thousands of maps for some games, which will probably become more granular in the future. Of course, there's still optimizations to be done

**Comment by lvaness** [comment]
The next update will also contain further optimization to initial load times.

**Comment by hexaflexahexagon** [comment]
considering my repeat load times are about 3s each with every possible game mounted i will consider this issue resolved, other people seem to be reporting similar results
