### ISSUE TITLE
Pistol code changed, no longer uses burst mode draw animation

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1329]
**Describe the bug**
The pistol code must've changed, as I remember implementing a burst mode draw animation. Which the weapon no longer uses, transitioning linearly into the burst mode idle sequence

**To Reproduce**
1. Enter a map of your choice, preferably a gamemode that allows to draw the pistol
2. Draw the pistol and change to burst mode
3. Draw another weapon
4. Switch back to the pistol

**Expected behavior**
The pistol should use the burst mode draw activity, `ACT_VM_DRAW_SPECIAL`

**Desktop/Branch (please complete the following information):**
 - OS: Windows 10
 - Branch: Steam

**Additional context**
I remember a comment in the code regarding the text displayed when changing fire modes. I guess it can be removed now that there's a visual indicator of the selected fire mode

**Comment by Gocnak** [comment]
Should be in the next push.

**Comment by patrickmoc** [comment]
The animation seems to be fixed in the latest steam build as well as the panorama branch.

> I remember a comment in the code regarding the text displayed when changing fire modes. I guess it can be removed now that there's a visual indicator of the selected fire mode

This display text still shows in the latest steam version but not in the panorama branch.
