### ISSUE TITLE
Default to horizontal speedometer

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1330]
**What feature is your improvement idea related to? Please describe.**
People asking how to change the speedometer from absolute to horizontal is an extremely frequent occurrence in the discord. In 99% of situations players will either prefer horizontal over absolute or not care between the two. This is made worse by the unintuitive programmer ui but is still a concern after the new settings ui is implemented. 

**Describe the solution you'd like**
Default horizontal speedometer only rather than absolute speedometer only.

**Describe alternatives you've considered, if any**
We could enable both by default but that would be too cluttered imo

**Comment by braem** [comment]
Worth noting that changing the default won't changes peoples current configs - they'd have to delete `cfg/speedometer.vdf`.

Also, because this fix wouldn't involve code, this can be fixed by anyone on the team by modifying `cfg/speedometer_default.vdf` on our game repo.

**Comment by hexaflexahexagon** [comment]
yeah that's fine, the vast majority of our total players aren't playing the game (on steam) right now anyways. there'll also still be people asking who are using the 0.8.7 build.

also are you sure that that's true? i figured that the game repo wasn't actually being used at all anymore and that this would still have to happen in the chaos repo. it could be done here then pulled into the chaos repo but that seems a bit silly for such a simple change.

**Comment by braem** [comment]
> also are you sure that that's true? i figured that the game repo wasn't actually being used at all anymore and that this would still have to happen in the chaos repo. it could be done here then pulled into the chaos repo but that seems a bit silly for such a simple change.

Sorry for the confusion - The internal (non-NDA) game repo, not this public one.

**Comment by hexaflexahexagon** [comment]
resolved
