### ISSUE TITLE
Port zonmaker over to Chaos

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1331]
The zonmaker project was introduced in 0.8.7 and allows mappers to get a .zon file out of their VMF.

- [x] Import tool into Chaos codebase
- [x] Only enable for Momentum (use `[ $MOMENTUM ]`)
- [x] Update the [CmdSeqDefault.wc](https://github.com/ChaosInitiative/Chaos-FGD/blob/master/hammer/cfg/CmdSeqDefault.wc) file to have the step for final build.

**Comment by braem** [comment]
`CmdSeqDefault.wc` has now been made game-specific so it's ready to add the step here: https://github.com/ChaosInitiative/Chaos-FGD/blob/master/hammer/cfg_momentum/CmdSeqDefault.wc
