### ISSUE TITLE
Slide trigger unintuitively clamps speed in TF2 modes

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1333]
**Describe the bug**
In TF2 modes (rj + sj) the slide trigger clamps to your base walking speed on landing and your maximum bhop speed on jumping. Intuitively, you would not expect either to happen and would want to smoothly preserve speed. There is no slide functionality in TF2 so there isn't a precedent to follow but this seems to be what the community preferred after a quick discussion. 

**To Reproduce**
1. Load the linked map (or any map with a slide trigger) with RJ or SJ movement
2. Quickly move into the trigger and notice how your speed is clamped
3. Jump (+jump) after building speed and notice how your speed is again clamped

**Expected behavior**
Speed should not be limited by the slide trigger

**Additional context**
Example map bsp/vmf download:
https://cdn.discordapp.com/attachments/671175695648423959/843811656596324352/rj_slidebug.vmf
https://cdn.discordapp.com/attachments/671175695648423959/843811654868140052/rj_slidebug.bsp

**Comment by Gocnak** [comment]
I'm just gonna go with the "preserve speed" since it's just for the first jump *out of the slide*, so any jumps after immediately clamps speed.

**Comment by hexaflexahexagon** [comment]
seems to work fine. the test map linked was only 1 unit tall i believe which is why it doesn't work there, but on triggertests they must be taller since everything works as intended
