### ISSUE TITLE
Investigate changing default HDR parameters to more reasonable values 

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1334]
**Is your feature request related to a problem? Please describe.**
Playing old maps without hdr support in momentum results in horrible bloom and overexposed lighting due to lack of HDR entities in the map. Many mappers ignore hdr completely because ldr looks good enough for them. We still want to provide the option for mappers to fully utilize hdr though.

**Describe the solution you'd like**
Change default values to something closer to LDR.

**Additional context**
Discord discussion 
https://discord.com/channels/235111289435717633/235121530609205249/844673163224023060

**Comment by granis48** [comment]
The values I've been defaulting to for a while are these: 
![image](https://user-images.githubusercontent.com/52294733/177632630-86fd9bd9-589b-4d4f-8230-886eaa58f2f3.png)
 
Having the min and max exposure close to eachother really minimizes the hdr effect and having values above 1 keeps the map fairly bright.
