### ISSUE TITLE
Add "freeze player on saveloc teleport" toggle

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1337]
Most players teleport multiple times to savelocs to get their bearings and properly handle the new location+velocity.

Adding a `mom_saveloc_freeze_on_teleport [0/1]` toggle that teleports the player to a saveloc but then freezes them until they press a key (IN_JUMP maybe?) would be pretty cool, pun totally intended.

Other options for this feature would be freeze after teleport with ~~either a separate key to unfreeze~~, or +key to teleport and -key to unfreeze

_Originally posted by @Arkanoid0 in https://github.com/momentum-mod/game/issues/291#issuecomment-728266497_

**Comment by hexaflexahexagon** [comment]
+tele_to_saveloc freezing the player and -tele_to_savelic unfreezing the player seems the most intuitive + cross-gamemode compatible to me. using +jump or something would be weird I'd think. a set (cvar) delay could be a good alternative but preferably the above by default.

**Comment by Gocnak** [comment]
The problem I have with that +- system is that it means adding another input that's tied to just teleporting to the current saveloc? Any saveloc? How does it distinguish between current/specific?

With the toggle and then requiring IN_JUMP to be repressed (debouncing if held already), I think that's the cleanest solution that can apply to all types of saveloc teleporting. Not to mention the HUD menu could add a simple toggle for it there.

**Comment by hexaflexahexagon** [comment]
IN_JUMP meaning +jump? or is that something with like player airborne state

**Comment by Gocnak** [comment]
Yep the key bound to +jump

**Comment by hexaflexahexagon** [comment]
i have reservations but I'd have to test it ingame to be sure it's awkward so I can hold those until this gets added (and would be an easy change)

one big concern i have though is about people with jumpcrouch binds where they hold one key that holds jump and crouch both, but maybe we just tell those people to use normal control schemes or disable the feature entirely.

**Comment by Arkanoid0** [comment]
My original implementation of this mode was utilizing `pause`, and was just a simple +/- alias that did both pause and saveloc tele. I think +/- is a perfectly reasonable way to implement this system, and the best way to do this i think is just to turn the current saveloc teleport command `mom_saveloc_current` into `+saveloc` or similar and add `mom_saveloc_freeze 0/1`.

Another reasonable implementation would be to force the player to match the input state stored in the saveloc. This is both more and less elegant than having a dedicated button, as its easier to accidentally have the same button state, but you also don't have to use bind an extra button or anything. Most of the point of freezing is having a moment to remember where you saveloc was and reset your mind and buttons to that position in the map, and with held movement key protection this system works very well.

There might be a few more reasonable implementation options we might want to look at, but these two at least are the most obvious to try out first.

**Comment by hexaflexahexagon** [comment]
Added with `+mom_saveloc_current`, works great! nice stuff
