### ISSUE TITLE
Savelocs should store player explosives

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1338]
**What feature is your improvement idea related to? Please describe.**
Savelocs being used on explosive-based modes like SJ, RJ, Conc, and Defrag.

**Describe the solution you'd like**
Savelocs should store explosive entities created by the player. If I throw a conc, or shoot a rocket, or shoot a sticky, I expect to see those explosives in the world after teleporting back to the saveloc.

Notes:
- Store a `m_iSavelocCreator` int variable on the explosive to be able to remove them easily when teleporting to another saveloc
- Teleporting to the same saveloc over and over should only keep showing the same explosives at that time; delete all explosives and only create the ones from that saveloc
- Use `m_vecExplosives` to cycle through the player's explosives
- Weapon attack delay is already saved inside savelocs, but *weapon charge time is not* (see #1339)

I have a feeling saveloc KV format will need to be figured out beforehand but this can be a separate block from the player weapon data (in #1339).

**Comment by braem** [comment]
I have this working for all explosives (apart from stick trigger outputs currently). Here is an example of what the keyvalues look like:
[savedlocs.txt](https://github.com/momentum-mod/game/files/6648127/savedlocs.txt)

Those beginning with `explosive_` are the fields from the base explosive, `CMomExplosive`, whereas the `sticky_` ones are class specific, in this case stickybombs. There is an inheritance on the savestate that makes it possible, which will fail to create the explosive if the types don't match. It uses the current gamemode to figure out which explosive needs to be created.

Teleporting to other savelocs calls `DestroyExplosives()` so there doesn't need to be any deletion of explosives apart from that. They are always destroyed on start zone enter as well.

Still missing weapon stuff like charge times and conc timer sounds (oh boy). I don't believe there is a way currently to offset a sound. I hope I'm mistaken. Anyways those are weapon specific stuffs not explosives.

**Comment by hexaflexahexagon** [comment]
explosive state is properly stored now so this can be closed. weapon state is coming later #1339
