### ISSUE TITLE
Instant teleportation into and then out of a clip brush does not reset velocity.

### ISSUE THREAD

**Issue by lewisfff** [momentum-mod/game#134]
# Problem:

Teleporting into a clip brush, then immediately out into the world does not reset player velocity to 0. Player can effectively telehop abuse in Momentum whereas in Counter-strike: source the velocity is not applied.

I have created an example map where the teleporters are supposed to launch you out with a fixed velocity. In Momentum, you can launch (e.g. with noclip) into the teleporter and the velocity is carried across to the next stage instead of being reset.

# Reproduction:

https://github.com/lewisfff/surf_basics

**Comment by lewisfff** [comment]
Easier map for testing: all you have to do it fail and you can telehop in Momentum

http://gamebanana.com/maps/195988

**Comment by Nolan-O** [comment]
I have renamed this issue to prevent players that are lightly browsing the repository from developing the belief that there are movement differences between CS:S and Momentum, because that is not the case.

**Comment by Gocnak** [comment]
Fixed in e4cae17
