### ISSUE TITLE
mom_release_forward_on_jump broken on Chaos

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1340]
**Describe the bug**
`mom_release_forward_on_jump 1` on Chaos will fail to work and print the error 
```
FCVAR_CLIENTCMD_CAN_EXECUTE prevented running command: -forward
Tried to look up command -forward as if it were a variable.
```
when jumping and either +forward or +back keys are being held. Note that everything behaves fine on 0.8.7

**To Reproduce**
Just set `mom_release_forward_on_jump 1` and try jumping whilst holding a movement key on any map.

**Expected behavior**
Jumping should fire -forward or -back if either of those keys are being held.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam

**Additional context**
Credit to esox in Discord for the find :)

**Comment by lvaness** [comment]
Reported as working on Discord
