### ISSUE TITLE
Conc timer text is cut off on high resolutions

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1343]
**Describe the bug**
It appears that the timer for the concussion grenades works fine on smaller resolutions, but does not scale properly at 1440p. This causes the text to be unreadable.

**To Reproduce**
- Run the game in 1440p
- Throw a conc grenade

**Expected behavior**
It should be properly scaled at all resolutions.

**Screenshots**
![20210526041750_1](https://user-images.githubusercontent.com/49064563/119619274-31be3000-bdda-11eb-8d34-f22f28b0325b.jpg)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version

**Comment by lvaness** [comment]
Is this Windows-only? Looks like this for me on 1440p 
![Screenshot_20210526_164213](https://user-images.githubusercontent.com/19615431/119680496-8648c600-be41-11eb-9de7-b01b67e36c44.png)

**Comment by braem** [comment]
It's cut off for me as well on 3440x1440
The size of it is hardcoded.
