### ISSUE TITLE
DX11: Alt-tab causes rendered fps to lock to monitor refresh rate

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1344]
**Describe the bug**
Alt-tabbing out and back in to the game causes the max fps to drop from the value set in fps_max to the current refresh rate of the active monitor.

**To Reproduce**
Start a map, tab out then back in.

**Expected behavior**
Rendered fps should stay at set value

**Screenshots**

**Desktop/Branch (please complete the following information):**
 - OS: Win10
 - Branch: Steam

**Comment by hexaflexahexagon** [comment]
resolved by the latest update
