### ISSUE TITLE
Prevent concs from spamming collision sound

### ISSUE THREAD

**Issue by zike1017** [momentum-mod/game#1347]
**Describe the bug**
When concs hit a surface many times in rapid succession the sound effect is played excessively.

**To Reproduce**
Easiest way to produce this is to throw a conc into a push trigger that pushes concs down towards the ground like on conc_ninja.
https://streamable.com/d2mngg

**Expected behavior**
The conc should only play the collision sound once.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version

**Comment by Gocnak** [comment]
Implemented. Controllable via https://github.com/momentum-mod/docs/issues/190 convars. Conc bounce sounds only occur if the grenade is moving/moved from its last bounce location. Needs testing, should be in latest push.

**Comment by Gocnak** [comment]
Was the implementation good enough? Can close if so.
