### ISSUE TITLE
Stickybombs bounce a little before sticking to world geometry

### ISSUE THREAD

**Issue by harryjah** [momentum-mod/game#1350]
Stickybombs bounce a little before sticking to world geometry, sometimes floating in air.
![Screenshot (25)](https://user-images.githubusercontent.com/63326505/120117830-0c1b8880-c144-11eb-81b0-5d11c97dbae7.png)

Shoot stickybombs at any stick-able ground or wall surface. Charging a bomb will cause more of a bounce before the bomb sticks.

Expected behavior:
Bombs should ideally stick right at the point of collision, or at least be closer to the 0.8.7 behavior of barely human perceptible bounce distance before sticking.

 OS: Windows
 Branch: Steam version

**Comment by braem** [comment]
Fix will be in in the next push. Keep in mind that they still do bounce a tad, just like in TF2: https://cdn.discordapp.com/attachments/549657950201970688/850204880366338108/2021-06-03_18-51-20.mp4

**Comment by Gocnak** [comment]
Does this still happen?

**Comment by harryjah** [comment]
Nice, it seems to be fixed!
