### ISSUE TITLE
Add mom_restart_checkpoint

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1351]
**Is your feature request related to a problem? Please describe.**
Add `mom_restart_checkpoint` to match `mom_restart_stage`. Some modes (rj/sj/conc) use checkpoints for individual jumps and rarely use stages, so having this command to quickly teleport between levels would be useful.

**Describe the solution you'd like**
Add a command similar to `mom_restart_stage` except for checkpoint zones instead. This would need:
- [ ] a docs page, e.g. https://docs.momentum-mod.org/command/mom_restart_stage/
- [ ] a matching safeguard command, e.g. https://docs.momentum-mod.org/var/mom_run_safeguard_restart_stage/
- [ ] a chat command "cp" "checkpoint" and "L" (as that's what tf2 servers use) should be good for triggers, https://docs.momentum-mod.org/guide/chat-commands/ 

**Additional context**
It's TBD by community review if we want to keep the functionality of being able to reset to your last touched checkpoint while your timer is running (similar to `mom_restart_stage` with no parameters) as that's typically useless in surf/bhop maps and potentially unwanted in RJ/SJ-type maps.

**Comment by Arkanoid0** [comment]
Discussion on this and interrelated concepts is currently taking place on the forums, [Here](https://forum.momentum-mod.org/d/64-implementation-notes-on-zones-and-jump-maps) and [here](https://forum.momentum-mod.org/d/66-remove-mom-restart-stage)

**Comment by Panzerhandschuh** [comment]
RJ players don't want this because it changes what strategies they use to recover runs.
