### ISSUE TITLE
Add "view on website" button to uploaded runs

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1353]
**Is your feature request related to a problem? Please describe.**
Any run that is uploaded on the website should have a button in-game that links the two.

**Describe the solution you'd like**
Add a "View on Website" button to the menu pictured below if the run itself exists on the website, opening a link like `https://momentum-mod.org/dashboard/runs/12345` to expand on the connection between the website and game.
![image](https://user-images.githubusercontent.com/62961532/120121126-c379c480-c16f-11eb-9098-56d5056bbaf8.png)

**Additional context**
Might need website work too iunno

Suggested by Ark in Discord

**Comment by Gocnak** [comment]
Won't need website work, can open in the steam overlay, but you'll have to sign in to be able to see it.

**Comment by hexaflexahexagon** [comment]
on an unrelated note, is it (realistically) possible to not require the steam sign-in so heavily on the website? i know we have the dashboard thing but typically most of what people are now using the website for (look through maps, look at recent records, look at top times) does not require a sign-in on other community websites and we've had a couple minor grievances with that, especially on mobile where people aren't really able to 1 click and sign in that easily and may just wanna look at a time.

**Comment by Gocnak** [comment]
The API is absolutely going to require authentication. While the idea of maybe making a "sign in via game token" is enticing, it could be a very catastrophic security issue if your game token somehow gets compromised. Signing in via steam is for your security.

**Comment by hexaflexahexagon** [comment]
Don't know if this got merged in the update this morning at 2am but I don't see the option so I'm guessing not.

**Comment by Gocnak** [comment]
This was pushed the day hex's comment was made, and I just confirmed it's in game and working fine 👍
