### ISSUE TITLE
Console still eats inputs while "fading out" on chaos engine

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1355]
**Describe the bug**
Attempting to close the console and then immediately start moving will result in a short delay while the console fade out animation plays. This is new with chaos and is an undesired change.

**To Reproduce**
1. Open console ingame
2. Close console using escape
3. wadwasdasd

**Expected behavior**
When closing the pause menu completely the console should instantly stop taking inputs, even if it is still technically fading out.

**Desktop/Branch (please complete the following information):**
OS: Windows
Branch: Most recent steam

**Additional context**
If we decide to change the console to use panorama instead then this will likely be automatically fixed, though having a card open to track it just in case is always nice.

**Comment by Gocnak** [comment]
Should be a matter of editing ConsoleScheme to have the frame fadeout to be 0.

**Comment by lvaness** [comment]
The panorama console will just not fade out at all

**Comment by Gocnak** [comment]
Does this still happen on the latest push?

**Comment by hexaflexahexagon** [comment]
The console no longer has any fade-out animation so this is a non-issue
