### ISSUE TITLE
Expose panorama_reload command

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1357]
`panorama_reload` is a command that lets you hot reload panorama files and is very useful for creating and debugging panorama ui. right now the command is not available for players playing the game using steam, which should be changed. 

"I was wrong with the _DEBUG thing, but currently it is only enabled when game is built local from "trunk" and windows only"

**Comment by SCell555** [comment]
This should be already available in latest build.

**Comment by hexaflexahexagon** [comment]
@tsa96 can you check this when you get a chance?

**Comment by hexaflexahexagon** [comment]
fixed
