### ISSUE TITLE
State isn't correctly saved in slide triggers on saveloc

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1361]
if saving inside of a Slide Trigger ([trigger_momentum_slide](https://docs.momentum-mod.org/entity/trigger_momentum_slide/)), it does not save the properties of you being inside of a Slide Trigger or any effect of the trigger, meaning on teleporting to that save, there is a short time where it does not think you are in one, so friction takes over causing you to lose speed, or allowing to jump regardless of the triggers properties.

In general, what triggers you are in should be saved, or check what triggers that location has in it, applying it to the player, before teleporting the player to the saved location.

**Comment by jason-e** [comment]
This issue is obsolete with the implementation of `func_slide` (to replace `trigger_momentum_slide`).
