### ISSUE TITLE
surf_happyhands crash 

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1362]
**Describe the bug**
Going to this spot on surf_happyhands crashes the game.

https://cdn.discordapp.com/attachments/235125108656701440/852298229130461244/unknown.png

Reported on Dx9 but also happens with dx11. There are css and csgo versions of this map and they both crash in the same spot in the same way (game instantly closes, no prompt or freeze)

DL: https://gamebanana.com/mods/122244

**Desktop/Branch (please complete the following information):**
 - OS: Windows

**Additional context**
https://discord.com/channels/235111289435717633/235125108656701440/852298232498618418

**Comment by lvaness** [comment]
Here's the map to reproduce this crash immediately ( credits to @hexaflexahexagon )
[npc_crash.zip](https://github.com/momentum-mod/game/files/6873180/npc_crash.zip)

**Comment by hexaflexahexagon** [comment]
fixed
