### ISSUE TITLE
Add input to explode/fizzle rockets within trigger_stick_explosive

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1365]
**What feature is your improvement idea related to? Please describe.**
Trigger above freezes projectiles in place when they either touch it or a surface while within it. For rockets, this would be useless as they would never explode on their own. Adding an input to the trigger that either explodes or fizzles all frozen rockets (or projectiles?) within it would be ideal.

**Describe the solution you'd like**
Add an input like above. 

**Describe alternatives you've considered, if any**
This is already possible by parenting a phase brush (no collision for players but does have collision for rockets) to the rocket to make it explode, but this is complicated to set up.

**Additional context**
https://discord.com/channels/235111289435717633/733184759080943706/852971912866168842

**Comment by braem** [comment]
Rockets currently arent effected by the trigger, but will make them be with the imput.
