### ISSUE TITLE
Quadrant check was inadvertently removed from CategorizePosition()

### ISSUE THREAD

**Issue by jason-e** [momentum-mod/game#1368]
**Describe the bug**
In [CategorizePosition()](https://github.com/momentum-mod/game/blob/153e4e800d108e8f2293bd1c315b997c40eeafd7/mp/src/game/shared/momentum/mom_gamemovement.cpp#L1737), used for determining if you should be on the ground or not, a piece of logic was inadvertently removed over 3 years ago by #150.

When the game checks for suitable ground below you, it first checks under your entire bounding box for a shallow-enough surface. If that check fails, it then uses [TryTouchGroundInQuadrants()](https://github.com/momentum-mod/game/blob/153e4e800d108e8f2293bd1c315b997c40eeafd7/mp/src/game/shared/gamemovement.cpp#L3723) to check for suitable ground under each quadrant of the player's bounding box individually, and will use any shallow-enough ground found this way. In Momentum, that quadrant backup check is still performed, but any successful result is ignored! I am not sure if this is still the case in 0.8.8.

Fixing this is a trivial matter of changing the way the if-else branches are done in `CategorizePosition()`. However, I have to wonder if this "quadrant check" is desired or even necessary for Momentum, especially since this seemingly went unnoticed for over 3 years. The quadrant check first showed up in the game code in HL2 (it was not in HL1 or Quake), and my best guess is it exists to aid in walking over bumpy terrain. I can think of some contrived scenarios where it could come into play in Momentum, but I believe it is not important, at least as far as surf and bhop are considered. Whether other game modes depend on this behavior, I have no idea. Without really knowing its importance (or lack thereof), it may be best to restore the original functionality.

**Example scenario**

![image](https://user-images.githubusercontent.com/2745352/121773717-4a9d4400-cb43-11eb-9e5c-08a64ece4422.png)

This is the only way I can even think of reliably benefitting from this behavior in surf/bhop, and even this example probably doesn't matter in any practical way. In a world without a trigger jumping fix, this behavior can be abused to easily jump at the bottom of a surf ramp without activating thin triggers there, however that does not apply to Momentum since trigger jumping is not possible anyway. On a related note, my improvements to the trigger jumping fix (#1367) prevent this sort of trigger jumping, while the older version of the fix would not.

**More info**

[Here](https://github.com/momentum-mod/game/blob/153e4e800d108e8f2293bd1c315b997c40eeafd7/mp/src/game/shared/gamemovement.cpp#L3856-L3879) is what the relevant block in `CategorizePosition()` looks like in the working base version. 

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: latest public develop branch

**Comment by Gocnak** [comment]
Just to clarify, this branch is not the code in question? https://github.com/momentum-mod/game/blob/develop/mp/src/game/shared/momentum/mom_gamemovement.cpp#L1734

**Comment by Gocnak** [comment]
I think I see, you mean the missing `else` statements? I have added back the missing `else`, it seems like that was incorrectly removed yeah.

**Comment by jason-e** [comment]
Yeah the way the branches were originally structured, there were two places where a ground entity was successfully set (the standard case and the inner quadrant check case). At some point in Momentum development, those branches were switched to a boolean value that gets set and then checked after the branches to facilitate adding more logic when setting the ground entity. Then in that pull request they removed the boolean thing and put all of the ground setting stuff as an `else` on the main check, ignoring the inner quadrant check branch.

**Comment by Gocnak** [comment]
Alright cool, I'll add the missing else no problem, I noticed it when adding Portal relevant code. It'll be in the next update!
