### ISSUE TITLE
Conc fuse timer is wrong

### ISSUE THREAD

**Issue by zike1017** [momentum-mod/game#1370]
**Describe the bug**
The conc fuse timer is supposed to be 4.0 seconds long. It would appear that concs currently have a ~3.8 second fuse timer.

**To Reproduce**
Hold a conc until it explodes with "mom_hud_conc_timer_countdown 1" enabled. The grenade explodes when the timer is clearly not at 4.0 seconds. The side by side video demonstrates the difference. 

Comparison between MM and TFC:
https://streamable.com/5ofmo6

**Expected behavior**
Concs should have the same fuse time as they did in TFC.

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version

**Comment by braem** [comment]
It is currently 3.81 seconds yeah

**Comment by Gocnak** [comment]
Adding as a `mom_conc_timer_length` convar so it can be tweaked. 3.8 was also found in TFC code reversing, but video evidence suggests it's 4 seconds which is definitely weird, but still good to test.

**Comment by Gocnak** [comment]
Closing as it's configurable until a default is determined. See https://forum.momentum-mod.org/d/70-conc-changes-megathread/14 for more info.
