### ISSUE TITLE
Some Panorama buttons don't render on DX11

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1374]
**Describe the bug**
Some Panorama panels are missing the images for their buttons

**To Reproduce**
- Open game on DX11 and Panorama

**Expected behavior**
Buttosn should show up

**Screenshots**
![image](https://user-images.githubusercontent.com/19615431/122303138-57cf7f80-cf03-11eb-89d7-40bd4684e579.png)

**Desktop/Branch (please complete the following information):**
 - OS: Win
 - Branch: Steam

**Additional context**
Reported by BlockBuilder57 on Discord

**Comment by SlidyBat** [comment]
This may have been fixed in latest update, please retest.

**Comment by SlidyBat** [comment]
Confirmed fixed by BlockBuilder57.
