### ISSUE TITLE
Expand trigger_stick_explosive to work more natively with rockets

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1377]
**What feature is your improvement idea related to? Please describe.**
`trigger_stick_explosive` is an entity that freezes concs / stickybombs either as they enter it or as they collide with something while within it. This would be very nice to have for rockets as well, but we would need a way to make the rockets explode manually.

**Describe the solution you'd like**
Add 2 inputs to trigger_stick_explosive to:
- Explode all projectiles within the trigger's volume (rockets, concs, or stickies)
- Fizzle all projectiles within the trigger's volume (rockets, concs, or stickies)

**Describe alternatives you've considered, if any**
It would also be nice for gimmick purposes if you were able to simply send an input to a projectile and make it explode/fizzle/etc but that's unrelated to this card.

**Additional context**
This will also need changes to the entity's doc page to add the new inputs and specify that the entity now works with rockets as well.

**Comment by braem** [comment]
This is already in. If not, then the next push. See https://www.github.com/ChaosInitiative/Chaos-FGD/tree/master/fgd%2Fbrush%2Ftrigger%2Ftrigger_stick_explosive.fgd

**Comment by hexaflexahexagon** [comment]
oops, i didn't check i just remembered this from the discussion whenever that was. closing this then since it looks like this is in.
