### ISSUE TITLE
Main Menu Webm/Static Image Convar

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1380]
**Is your feature request related to a problem? Please describe.**
Webms look great on Panorama but can be a resource hog due to decoding on the CPU.

**Describe the solution you'd like**
Add a convar (perhaps `mom_hud_mainmenu_video`, 1 by default, 0 to disable the webm). We can easily grab that value from Panorama and I'll add JS code to determine whether to display a webm or a static image as soon as this is in.

**Describe alternatives you've considered**
Port to Scaleform

**Comment by tsa96** [comment]
Since the light and dark versions of the backgrounds both have their fans, getting an option for light vs dark like `mom_hud_mainmenu_video_version` would be great as well - we'd then have two options for enabling/disabled video and light/dark

**Comment by Gocnak** [comment]
These have been implemented as `mom_ui_menu_background_video [0/1]` and `mom_ui_menu_background_type [0, 1, ...]`.

**Comment by tsa96** [comment]
Can confirm this all works
