### ISSUE TITLE
Remove texturebugs 

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1382]
**Is your feature request related to a problem? Please describe.**
Texturebugs are done by swapping your keys from W+A to W+D (or vice versa) as the top of your hitbox passes the bottom of a brush. This video showcases a map made to utilize texturebugs: https://youtu.be/cn-aZZvicBI

While texturebug jumps can be cool, most of the time they're either used as unintentional skips that save lots of time or as cheese for a hard jump. Because of this it would be generally better for the entire game if they were removed to avoid aids speed strats that become required for a competitive time on a map.

They exist primarily in the TF2 modes (RJ and SJ) but they also happen in conc as well I believe. 

**Describe the solution you'd like**
Remove texturebugs. 

**Describe alternatives you've considered**
We could also add some trigger that lets you manually re-enable them but that sounds way more complicated than necessary to me, especially considering we don't have triggers for re-enabling angled wallbugs which have already been removed.

**Additional context**
The actual difficulty of removing these is unknown, though it should definitely be doable with engine access. ILDPRUT has identified the root cause of them being some collision optimization on strictly cuboid shapes. More context can be found in some discord discussion that I can't seem to dig up. I would recommend asking ILDPRUT before tackling this issue.

**Comment by zike1017** [comment]
Here's the discussion where ILDPRUT and friends talk about texturebugs https://discord.com/channels/235111289435717633/602643431453360148/852469412257857576

**Comment by chrb22** [comment]
Should be pretty simple to fix in-engine, but an indirect fix can also be implemented in TryPlayerMove. If an in-engine fix is wanted, I can point out where you need to look and explain what needs to be done.

**Comment by chrb22** [comment]
Angled wallbugs+derivatives and maybe coordinate bugs should also be quite easy fixes in-engine I think?

**Comment by Ninja-Cookie** [comment]
Incase it's relevant to finding and fixing the issue or not, you don't need to transition from A to D, you can just press one or the other at the correct time while pushing against the wall. You don't necessarily need to be looking at the wall either, just pushed against it in some way as far as I know. I have not fully tested this.

On topic of mapping, to do them in a map manually you can already just use a trigger_userinput that outputs "OnKeyPressed" to enable a trigger_setspeed, then if you pressed the key when in the trigger, setspeed activates and the player is stopped from falling while keeping horizontal speed. This emulates the same effect but with a lot more input time making it consistently achievable and specific to where you personally want it as a mapper, if at all.

**Comment by hexaflexahexagon** [comment]
> Angled wallbugs+derivatives and maybe coordinate bugs should also be quite easy fixes in-engine I think?

angled wallbugs are already fixed since the rampbug fix that was in the game before rj/sj solves the same core issue. coordinate i imagine would also be easy to fix so that would be good too.

**Comment by chrb22** [comment]
An in-engine fix would probably be cleaner than the messy sv_ramp_fix in TryPlayerMove. Same story would go for the other bugs.
