### ISSUE TITLE
UI for concs is hidden in unrendered visleaf

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1383]
**Describe the bug**
Concs that are in unrendered visleaves (e.g. around a corner) get their matching UI hidden. See this video https://www.youtube.com/watch?v=0ar4pjDn6AQ

**To Reproduce**
1. Throw conc 
2. Walk around a wall
3. poof

**Expected behavior**
A conc's UI should always be visible when it is thrown.

**Desktop (*please complete the following information*):**
 - OS: Windows
 - Renderer: DX9
 - UI: VGUI

**Additional context**
This issue seems to be new (as of about 6/19) since it hasn't been reported yet, meaning a recent change likely broke something.

**Comment by Gocnak** [comment]
I think the conc projectiles just need `SetTransmissionState` to be `FL_EDICT_ALWAYS`, like ghosts do. Should be trivial.

**Comment by hexaflexahexagon** [comment]
this seems to happen for stickies and rockets too with their trails (and the stickybomb glow)

**Comment by hexaflexahexagon** [comment]
appears to be resolved
