### ISSUE TITLE
"sv_interval_per_tick" not correctly setting custom tickrates

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1385]
"**sv_interval_per_tick**" appears to not be able to set custom tickrates above the gamemodes default tickrate in current version 0.8.8. For example, if I play bhop, the default tickrate is **100**, I can then do stuff like "**sv_interval_per_tick 0.1**" to set it to 10, this will continue to work for anything that is **below a tickrate of 100**, and if I do "**sv_interval_per_tick 0.0078125**" to set it to **128**, this seems to work also, being it is a known tickrate by "**sv_tickrate**", however any other value that would make the tickrate above **100** (or above whatever gamemodes default tickrate) will not set it, and just defaults back to a tickrate of 100, or whatever the gamemodes tickrate is.

**Comment by hexaflexahexagon** [comment]
fixed
