### ISSUE TITLE
Spectator / replay UI shows wrong key to toggle mouse capture

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1387]
**Describe the bug**
The top right of the replay / spectator UI is supposed to tell the player what key they need to press to toggle mouse input. It should be whatever +jump is bound to, however right now it will always say "d" as shown below. This is not +moveright (tested by unbinding D and binding another key to +moveright), rather it literally always says D.

![image](https://user-images.githubusercontent.com/62961532/123341326-c6bc6200-d51b-11eb-92c5-5187d6f7dbe4.png)

**Expected behavior**
The player's jump key should be shown in the UI.

**Desktop (*please complete the following information*):**
 - OS: Windows
 - Renderer: Both
 - UI: Both
 
**Additional context**
Reported by Shegetz in discord

**Comment by Arkanoid0** [comment]
![image](https://user-images.githubusercontent.com/1642129/123369213-93d59680-d53a-11eb-99fa-69bdb6718d97.png)
It says to press s for me, which is even weirder as i don't even have anything bound to s directly, its bound to an alias that eventually binds to +moveright. Additionally, the correct button is still ctrl (+duck)

**Comment by Gocnak** [comment]
This will be implicitly fixed by switching over to panorama ( #1511 )
