### ISSUE TITLE
VGUI lobby panel icons no longer scale properly

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1392]
**Describe the bug**
The icons shown below no longer scale properly on the VGUI version of the build. This may or may not be an issue for panorama but it should most likely be investigated at the least.

![image](https://user-images.githubusercontent.com/62961532/123523656-f5107d80-d692-11eb-9d07-1fc19635b04d.png)

**Desktop (*please complete the following information*):**
OS: Windows
Renderer: Dx9 (both iirc)
UI: VGUI

**Additional context**
I think BLT did the changes that broke this so they'll probably know best what to investigate. This card is mostly just so that this doesn't get forgotten about & become an issue later when we swap to panorama.

**Comment by lvaness** [comment]
This should be fixed in the next update already, but I'll check it later

Okay maybe not, I'll see if it's an easy fix but otherwise I don'T think it's worth worrying too much about it.

**Comment by hexaflexahexagon** [comment]
Fixed
