### ISSUE TITLE
Pressing ` with chat open types the character and opens console

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1393]
**Describe the bug**
Pressing your console toggle key (`) while you have chat open results in both the character being typed and the console being opened, which is unintuitive. 

**Expected behavior**
The console should not open whenever the ` character is typed into a text field (such as chat).

**Desktop (*please complete the following information*):**
OS: Windows
Renderer: Dx9
UI: both

**Comment by Gocnak** [comment]
Was this fixed in the latest push?

**Comment by hexaflexahexagon** [comment]
seems to be fixed
