### ISSUE TITLE
jpeg command breaks rendering on DX9

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#1397]
**Describe the bug**
The jpeg command to take screenshots causes rendering to break in DX9 Momentum Mod. The only thing that seems to render correctly is the viewmodel, but the map, HUD, and menu are completely broken. Textures randomly switch between brushes, polygons are all over the screen, and HUD and GUI elements either don't draw or draw strangely. It happens in both Panorama and VGUI.

**To Reproduce**
1. Load any map in DX9.
2. Issue the jpeg command from console.
3. Enjoy.

**Expected behavior**
The rendering should not completely break.

**Screenshots**
![noneuclidean](https://cdn.discordapp.com/attachments/663603008466190349/860158549786624010/noneuclidean0002.jpg)

![smallcity](https://cdn.discordapp.com/attachments/663603008466190349/860158628069769226/rj_smallcity0002.jpg)

![musparium](https://cdn.discordapp.com/attachments/663603008466190349/860158734919401492/rj_musparium_p0003.jpg)

Pressing esc in Panorama:
![panorama esc](https://cdn.discordapp.com/attachments/356398721790902274/860154286210285568/unknown.png)

Typing "jpeg" in console in VGUI:
![jpeg vgui](https://cdn.discordapp.com/attachments/663603008466190349/860159469166133278/unknown.png)

Typing jpeg in console in Panorama:
![jpeg panorama](https://cdn.discordapp.com/attachments/663603008466190349/860159752418754631/unknown.png)

**Desktop (*please complete the following information*):**
 - OS: Windows
 - Renderer: DX9
 - UI: Both

**Comment by braem** [comment]
Cant seem to replicate this on any shaderapi/UI configuration on the steam or debug build.
Perhaps some other fix happened to resolve this issue.

**Comment by hexaflexahexagon** [comment]
fixed, no more glitchart 🔨
