### ISSUE TITLE
DX11: Water 'surface' isn't rendering

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1398]
**Describe the bug**
The edge of a wall has a thin line of void drawn near the top of the water, visible in the video below.

https://user-images.githubusercontent.com/5162166/138022148-c4899be7-e236-488b-8967-c15c6b0151a3.mp4

See the relevant discussion in discord here.
https://discord.com/channels/235111289435717633/356398721790902274/860064193713405952

**Desktop (*please complete the following information*):**
OS: Windows
Renderer: DX11
UI: Panorama

**Additional context**
https://github.com/momentum-mod/game/issues/1298

**Comment by SlidyBat** [comment]
This is likely an issue with clip planes, which were fixed for #1568, so it's possible this is fixed too. Should retest next update.

**Comment by hexaflexahexagon** [comment]
seems good now
