### ISSUE TITLE
prop_static entities do not render with the correct lighting

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1401]
**Describe the bug**
As of the latest update prop_static entities do not render correctly. Screenshots down below showcase the exact effects (prop_static on the left and prop_dynamic on the right).

**Screenshots**
dx9 without csm:
![image](https://user-images.githubusercontent.com/62961532/124184684-ed344d00-da87-11eb-86cf-aa7528bcce75.png)

dx9 with csm:
![image](https://user-images.githubusercontent.com/62961532/124184737-0210e080-da88-11eb-84d9-08ba3d77e6d4.png)

dx11 without csm:
![image](https://user-images.githubusercontent.com/62961532/124184669-e73e6c00-da87-11eb-9ebf-64eb9b0f3315.png)

dx11 with csm:
![image](https://user-images.githubusercontent.com/62961532/124184794-148b1a00-da88-11eb-861b-e64f8f5a57e4.png)

**Desktop (*please complete the following information*):**
OS: Windows
Renderer: Both
UI: VGUI

**Additional context**
I included csm because the effect on the prop_static did seem to change somehow but it's most likely unrelated

**Comment by SlidyBat** [comment]
This should have been fixed a while back.
