### ISSUE TITLE
Portals show as a missing texture without mounting Portal 2

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1403]
**Describe the bug**
If a player doesn't have Portal 2 downloaded any world portals they see will show as missing textures. Because this specific model is going to be so integral to gameplay we should include it with momentum by default.

Photo from GameChaos:
![image](https://user-images.githubusercontent.com/62961532/124192952-1529ad80-da94-11eb-9387-4c567899195d.png)

**Comment by hexaflexahexagon** [comment]
resolved

**Comment by hexaflexahexagon** [comment]
was not actually resolved we're still getting reports of this, the model exists so we may just be missing a texture we need to include? no idea what's wrong.

**Comment by Gocnak** [comment]
Yep it was 2 more materials we were missing, should be fixed in latest build.
