### ISSUE TITLE
Standing in the seam between two portals shows a thin nodraw strip

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1404]
**Describe the bug**
Happens when standing in the very center of two portals all around the player. See the image below on noneuclidean.

![image](https://user-images.githubusercontent.com/62961532/124193136-4efab400-da94-11eb-8b9a-f11944db4871.png)

Something that may or may not be related is that other rendering seems to hiccup while in a portal seam as well.
Normal:
![image](https://user-images.githubusercontent.com/62961532/124194823-3d66db80-da97-11eb-8934-9dc5ad6f3434.png)

Broken: (walls on the pillar are not straight, cube edges are somewhat jagged. it's easier to see while moving between portals ingame)
![image](https://user-images.githubusercontent.com/62961532/124194802-36d86400-da97-11eb-9244-22d0cda62aef.png)

**Comment by SlidyBat** [comment]
DX11 rendering of portals was improved to match DX9, so there will no longer be a white strip in the seam. Unsure if the other issues have been fixed though.

**Comment by hexaflexahexagon** [comment]
i'm seeing some other random shadow issues in noneucliddean on those boxes but that's not really related to this I don't think so closing
