### ISSUE TITLE
Delete and recreate particle effects for projectiles being teleported

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1406]
**What feature is your improvement idea related to? Please describe.**
Particles for projectiles shot through portals shoot through the world to the real location of the new area. To fix this we should be deleting the old projectiles particles as soon as it is teleported and creating new particles for the fake copied projectile. This also needs to work for things like the player trail if they have that enabled.

![image](https://user-images.githubusercontent.com/62961532/124193761-67b79980-da95-11eb-8301-550e47e5d630.png)

**Comment by Shegetz** [comment]
Trails are properly being recreated but conc timers are being separated from the conc
![image](https://user-images.githubusercontent.com/73811375/160557705-677ba0d3-c902-4dad-b745-b1a56beea30d.png)

**Comment by Gocnak** [comment]
Regarding conc timers: https://github.com/momentum-mod/game/issues/1407
