### ISSUE TITLE
Investigate using portals in VRAD calculations

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1412]
**Is your feature request related to a problem? Please describe.**
One common use of portals is to create seamless transitions between different areas. The main difficulty with this use is that you need to completely replicate things like texture allignment, props, and other small details to made the effect truly invisible. Lighting is one of the harder things to get right, as currently portals do not transmit light and thus you have to manually replicate the lighting environment. 

**Describe the solution you'd like**
Somehow make light seamlessly traverse through portals. I'm not sure how this would work for portals that open / close or ones that move, so perhaps you would need to add a flag or keyvalue for this that forces those things to remain constant. 

**Additional context**
This may also be better suited for the chaos repo but I don't think they use world portals too often in p2ce in the ways that momentum mappers are going to in the near future so I put the card here to be safe. It can always be transferred later.

**Comment by Gocnak** [comment]
This is problematic because portals can be closed, and then the lighting doesn't make any sense.

**Comment by hexaflexahexagon** [comment]
one possible solution is what i mentioned in the issue which is to add a KV that forces portals to remain open & then use those in VRAD. most people will want to have their portals always open anyways so this is a good compromise

i dont even think it would be impossible to do lighting with toggleable portals because that would just be 2 states for a given area, one with an open portal and one with a closed one. It would work the same as dynamic lights do currently. These can still get excessively expensive quick if you have lots of entities in the same spot so we would need the same limits dynamic lights have if we were to go this route. 

However, I think the first solution is fine and would give mappers 95% of what they want from this card for 20% of the effort.

**Comment by Gocnak** [comment]
Smaed from the P2CE team has implemented this. You need to set the portal to static with the `isstatic` keyvalue. Then compile using Momentum's VRAD with:

![image](https://user-images.githubusercontent.com/5162166/151936758-366f4c06-10f8-4550-b1d7-5bf5b568b72e.png)

**Comment by hexaflexahexagon** [comment]
this has been in for a hot minute now and does work. there are some kinks but those exist in separate issues so i think it's safe to close this issue now.
