### ISSUE TITLE
Add a panel to spectate somebody on a different map

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1416]
This was suggested on a twitch stream and Gocnak seemed rather interested so I'll copy it here to track

**Is your feature request related to a problem? Please describe.**
Currently to spectate somebody you need to leave your map, load their map, and then spectate them. This could be simplified by allowing players to open up a UI panel that loads a "video" of the other player's camera position without having to leave their current map. 

This also seems rather useful for allowing players to watch replays while on a different map. Ideally being able to do both would be great.

**Describe the solution you'd like**
Something that does the above.

**Additional context**
Suggested by maxam

**Comment by Gocnak** [comment]
A lot would have to be done in the engine, basically stripping out map loading and rendering to be completely containerized systems. I don't think this is realistically possible, or worth the gargantuan effort for such a simple solution: just go to the map it's on.
