### ISSUE TITLE
Panorama settings menu search bar does not allow ctrl+backspace

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1419]
**What feature is your improvement idea related to? Please describe.**
The panorama settings menu search bar does not allow ctrl+backspace. Other hotkeys like ctrl+a seem to work fine.

**Comment by tsa96** [comment]
Might be possible to add, but requires C++ changes to the TextEntry panel

**Comment by lvaness** [comment]
While we're at it, I'll add ctrl+delete for the one person in existence who will use that

**Comment by hexaflexahexagon** [comment]
resolved
