### ISSUE TITLE
Crash on surf_pantheon

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1422]
**Describe the bug**
Loading `surf_progress` and then `surf_pantheon` will cause a crash and give the error below:

![image](https://user-images.githubusercontent.com/62961532/124758507-a5387e80-defc-11eb-90c6-5dd40555dda0.png)

**Desktop (*please complete the following information*):**
Windows, VGUI, Dx9

**Additional context**
Reported by pear
https://discord.com/channels/235111289435717633/356398721790902274/862037567948062741

**Comment by bakapear** [comment]
It's also worth mentioning that it only happens when cstrike is not mounted and `surf_pantheon` gets missing textures.

**Comment by Gocnak** [comment]
Again? Not related to #1301 ?

**Comment by hexaflexahexagon** [comment]
The old crash would happen while loading the map IIRC while this one happens if you 
1. load a different map first
2. don't have css mounted 
3. load the map and then walk around for a few seconds
even if it is related to the old card it happens on the latest version anyways

**Comment by Gocnak** [comment]
Seems like all it was upset about was the lack of the `cs_italy/black` texture. I added our black.vmt to a folder `momentum/materials/cs_italy/` and it works fine. Should be fixed in the next push!
