### ISSUE TITLE
Basic Panorama drawer panel implementation

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1424]
- [x] Lobby tab
  - [x] Lobby list
  - [x] Lobby details
    - [x] Member list
    - [x] Join/Spectate functionality
    - [x] #1485
- [x] Stats tab
- [x] Changelog
  - [x] #1425

**Comment by tsa96** [comment]
A further addition that'd be great

// - Expand lobby member state data

This data could include 

- current run data: current stage/checkpoint, time into run, run type? (HSW etc)
- current gamemode (in case they're overriding)
- practice mode
- watching a replay

Edit: moving this to its own issue
