### ISSUE TITLE
Panorama main menu background commands do not work from console

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1427]
**Describe the bug**
Updating `mom_ui_menu_background_video` or `mom_ui_menu_background_type` from the console will change their values but not update the main menu accordingly. Going into settings the values will have been adjusted properly, but the menu won't update until you click on the option in the settings menu.

**Desktop (*please complete the following information*):**
Windows, Dx9, Panorama

**Comment by Gocnak** [comment]
Not planning on doing this, would require hooking into when the convar changes and that ties cvar and UI code too much. To change it is 2-3 clicks on the settings panel, people should just use that.
