### ISSUE TITLE
Dx11: Animated Panorama BG video does not work

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1428]
**What feature is your improvement idea related to? Please describe.**
Dx11 is missing functionality needed to play videos such as the main menu background in panorama. This is especially obvious when booting panorama+dx11 with the animated video background on because the game will hang and never fully boot.

**Comment by Gocnak** [comment]
Despite #1439 , we'll say this is resolved as on dev machines and when DX11 successfully launches, the video playback does work. Problems booting DX11 are another issue, already tracked.
