### ISSUE TITLE
Add a borderless windowed option to the "Video" settings panel

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1430]
**Is your feature request related to a problem? Please describe.**
See the image below. It's possible to launch in borderless windowed via launch options but that's unintuitive and requires a full restart to change to. 

![image](https://user-images.githubusercontent.com/62961532/125201817-b1934300-e23e-11eb-9eb2-521013cc4ee4.png)

**Describe alternatives you've considered**
There were ideas of removing fullscreen support completely given Dx11 improvements, if we do that then the name of the option could simply be "Fullscreen" rather than something like "Fullscreen windowed"

**Comment by lvaness** [comment]
It exists in Panorama

**Comment by SlidyBat** [comment]
This option is available in Panorama settings, and likely won't be backported back to VGUI.

**Comment by hexaflexahexagon** [comment]
oops, i could've sworn earlier that it wasn't there.
