### ISSUE TITLE
Panorama Search Does Not Change Active Tab

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1431]
**Describe the bug**
In panorama, the search function does not change the active tab the player may be on.

**To Reproduce**

1. Open settings
2. From the "input" tab, search for something, like "video"
3. Click on the found setting
4. Notice the top of the tabs do not change

**Expected behavior**
The top tab should change to the desired category + subcategory where the setting is found.

**Screenshots**
![image](https://user-images.githubusercontent.com/5162166/125206751-d4c9ec80-e256-11eb-880a-0b4ce22d093d.png)

**Desktop (*please complete the following information*):**
 - OS: Windows
 - Renderer: DX9 (Default
 - UI: Panorama

**Comment by hexaflexahexagon** [comment]
fixed in the latest update
