### ISSUE TITLE
Update settings submenu selection on scroll

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1433]
**What feature is your improvement idea related to? Please describe.**
Currently, the subsection navbar within settings pages does not update its selected RadioButton when the user scrolls between different subsections.

**Describe the solution you'd like**
The correct RadioButton should be activated when the user scrolls into its corresponding subsection. This likely requires handling a scrolling event in some way, though as far as I know Panorama doesn't have anything like an onscroll event attribute.

**Describe alternatives you've considered, if any**
If it's technically too difficult to handle scrolling, it may be worth discussing the subsection navbar's current style and placement. We definitely want to avoid the navbar displaying as if the wrong subsection is currently in focus, so perhaps we remove styling on the activated RadioButton entirely.

**Additional context**
Demonstration video below. Notice how the subsection nav stays on "Paint" the entire time.

https://user-images.githubusercontent.com/35813309/125227844-873b9700-e2cb-11eb-8e19-df330c7d6460.mp4

**Comment by hexaflexahexagon** [comment]
done
