### ISSUE TITLE
[Website] Top 10 Run History

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1434]
For the upcoming feature update on the website, a nice idea for ways to explore the data is to implement a History of the Top 10 runs, allowing you to scroll through time, watching the wr and the top10 slots change and improve, in a similar manner to the [youtube channel ABACABA (example video: minecraft any%)](https://www.youtube.com/watch?v=6eF4vD7D_Qc)

This is data we already have and are storing in the database, but currently have no mechanism to display. It's a neat idea IMO, and something nobody else is currently doing.

**Comment by hexaflexahexagon** [comment]
if this is meant to be on the website it should go on the website repo at https://github.com/momentum-mod/website
if its meant to be an in-game UI thing then thats not super obvious

**Comment by Arkanoid0** [comment]
> if this is meant to be on the website it should go on the website repo at https://github.com/momentum-mod/website
> if its meant to be an in-game UI thing then thats not super obvious

sorry, forgot that we had seprate trackers for game and website. i'll close and move it over
