### ISSUE TITLE
Panorama: Trick list UI shows up during loading screens briefly

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1436]
**Describe the bug**
See below. It does not happen immediately but seemingly only during a specific phase of the map loading process. It also appears to only happen the first time you load a map in your game session, you will have to reload to get it to appear again.

![image](https://user-images.githubusercontent.com/62961532/125321833-187e2e00-e30b-11eb-907a-d28ec845dab8.png)

**Desktop (*please complete the following information*):**
Windows, Both, Panorama

**Comment by lvaness** [comment]
From what I've seen so far, there's 1 billion ways to fix this badly, but doing it properly could take much more effort than we should afford to VGUI.

**Comment by hexaflexahexagon** [comment]
If the easiest fix is anything more than a 1 liner then it's probably not worth bothering about considering VGUI is going to be removed completely in the next few months.

**Comment by yasiralamriki** [comment]
I'm not able to reproduce this
