### ISSUE TITLE
VGUI elements always draw under Panorama elements

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1437]
**Describe the bug**
Not sure if we actually want to fix this as we will eventually be removing VGUI support but for the time being it is a very obvious issue that players see. UX is a little worse because some elements are tricky to click but everything works just fine that I can tell. 

![image](https://user-images.githubusercontent.com/62961532/125322483-d4d7f400-e30b-11eb-8a4a-3fd9c12385e0.png)

**Comment by Gocnak** [comment]
Yep rendering issue. I believe it's the rendering done in `view.cpp` or `viewrender.cpp`, I had to do some ifdef momentum around how the panels drew for Chaos...

**Comment by hexaflexahexagon** [comment]
it's still not possible to click panorama elements while any VGUI one is open it looks like but that's fairly minor and not really related to this card.
