### ISSUE TITLE
Dx11+Panorama: Using `-profile` causes inconsistent crashing

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1439]
**Describe the bug**
Not sure if this is going to be replicable so some more investigation may be needed.
Launching with pano+dx11 with the `-profile` launch option seems to occasionally crash on boot at the bad aspect ratio loading screen. Sometimes there are errors and it cycles between a few different ones but they're all related to the allocator like below:
![image](https://user-images.githubusercontent.com/62961532/125323392-b9b9b400-e30c-11eb-9448-89ffaf8cf878.png)

Other configurations seem to work fine (dx9, vgui)

**Desktop (*please complete the following information*):**
Windows, Dx11, Panorama

**Comment by Gocnak** [comment]
What happens if you edit config.cfg and change the menu background `mom_ui_menu_background_video` to 0?

**Comment by hexaflexahexagon** [comment]
slidy and i talked a bit and this crash is fairly inconsistent. I can sometimes load properly with the animated bg on and sometimes I crash so I'm not sure how to recreate reliably. xb was having similar-seeming crashes too

**Comment by Gocnak** [comment]
What about game mounts? Does not mounting any games help?

**Comment by hexaflexahexagon** [comment]
After some experimentation there is either a massive coincidence or `-profile` is causing this crash. i was unable to replicate it before putting it back in my launch options (it was there for an unrelated issue when I was experiencing these crashes) and now it has happened 2/2 times

**Comment by Gocnak** [comment]
Hm. What's `-profile` do?

**Comment by hexaflexahexagon** [comment]
it's something to do with profiling game performance, I added it because I thought I was having exceedingly long load times (>5 minutes) and BLT told me I could try using it to give some relevant info. turns out that issue was just dx11 not being able to play back videos but the launch option was still there while i was getting these

e: i can just remove it and it seems like this works fine (assuming other people can replicate) but this may be something worth fixing? or we could just remove `-profile` because players probably wont miss it

**Comment by Gocnak** [comment]
This might be related to a threading issue. Can you please confirm it still happens without `-profile`? Try restarting your machine as well, some users find that helps hit it.

**Comment by hexaflexahexagon** [comment]
I have never gotten the same crash without `-profile`, even after restarting my computer and booting straight into dx11+panorama.

**Comment by lvaness** [comment]
My guess is that the load time overhead of -profile just causes the FS threading issues to become worse. We should check on this when we fix that.

**Comment by hexaflexahexagon** [comment]
Yeah that seems to match my experience, I've actually gotten a similar looking crash a few times now even though I haven't been using `-profile` anymore

**Comment by hexaflexahexagon** [comment]
at least one of the crashes related to this seems to be fixed so marking as resolved for now
