### ISSUE TITLE
linked_portal_door icon requires portal 2 to be mounted

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1440]
**Describe the bug**
Not having portal 2 mounted results in a huge error instead of the proper icon for `linked_portal_door`. If we don't ship this icon we definitely should. 

![image](https://user-images.githubusercontent.com/62961532/125328780-b6c1c200-e312-11eb-9969-bd3f59fe83a1.png)

**To Reproduce**
1. Unmount portal 2
2. Open hammer and make a `linked_portal_door` entity
3. eror

**Comment by hexaflexahexagon** [comment]
this might just be due to people using hammer++ instead of our hammer editor so this may be a nonissue once they switch

**Comment by braem** [comment]
Yes we already have the materials/model in platform (`Momentum Mod/Platform/`). They are `models/editor/angle_helper.mdl` and `editor/portal_dual.vmt` for the iconsprite.
We are missing materials/model for `prop_linked_portal_door` though. We'll either add those or remove the prop, as it seems very specific to portal 2.
