### ISSUE TITLE
Panorama JS exception on loading a map from the map selector

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1444]
**Describe the bug**
Loading a map from the map selector gives the error below. Something about trying to find the player before they're created.

![image](https://user-images.githubusercontent.com/62961532/125431221-1c67bc30-95c9-4713-ae9d-7292f6f230e5.png)

**To Reproduce**
1. Load a map from the map selector
2. err

**Expected behavior**
no error

**Desktop (*please complete the following information*):**
Windows, Dx11, Pano

**Comment by Gocnak** [comment]
Closing as this was part of the initial port to Panorama. If this happens again we can re-open.
