### ISSUE TITLE
Allow linked_portal_door to be toggled by a filter

### ISSUE THREAD

**Issue by tricksurf** [momentum-mod/game#1445]
**Is your feature request related to a problem? Please describe.**
Would solve problems of a lot of complex puzzles, but not a problem with the game.

**Describe the solution you'd like**
Add an attribute to the linked_portal_door entity so they can disappear and appear based on filters.

**Describe alternatives you've considered**
Don't see any other alternatives to this idea. It's more of just a quality of life feature that would allow more complex portal setups.

**Comment by Gocnak** [comment]
Are there any inputs for this? Couldn't you control it with a general trigger with filters sending the inputs to the portals?

**Comment by hexaflexahexagon** [comment]
there are inputs to open and close portals yeah. i don't understand what exactly the original issue here is asking for with a filter
