### ISSUE TITLE
Trigger for rolling stickies if inside of trigger

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1448]
Instead of making specific walls stickies can't collide with for example, it would be nice to be able to trigger an area that disallows stickies from sticking to anything if the sticky is inside of that trigger, this would greatly lower brush's used in a map as well as simplify making them.

**Comment by braem** [comment]
For those testing, i haven't yet added this to the FGD: https://github.com/ChaosInitiative/Chaos-FGD/issues/76

**Comment by braem** [comment]
Will be in next push now; https://github.com/ChaosInitiative/Chaos-FGD/pull/77

**Comment by hexaflexahexagon** [comment]
added and seems to work nicely
