### ISSUE TITLE
Panorama Tooltip Hover Follow Cursor

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1452]
Make a tooltip mode where the tooltip is positioned by the mouse cursor (with offsets I suppose?) that follows the mouse around, instead of opening to a static spot like CS:GO has it.

**Comment by tsa96** [comment]
Not super important with settings info panels replacing tooltips in the settings page (the place that originally motivated this issue).

**Comment by tsa96** [comment]
Yeah this can be closed imo
