### ISSUE TITLE
Various rendering bugs while stood perfectly between 2 portals

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1453]
I wasn't sure what to name this because I wasnt sure if these were related to eachother or not. Feel free to edit this / drag some of these into separate cards if that makes more sense.

**Describe the bug**
Standing perfectly between 2 portals will cause the following rendering issues:
1. Shadows on some props render over top of the props (they're some pushable physics prop, don't know which specifically)
2. Other portalable areas are shown through the world at specific view angles

Note: we do have this card https://github.com/momentum-mod/game/issues/1404 that may or may not be related. This issue can also still be observed here. 

**To Reproduce**
Stand in the specified spot on noneuclidean 
`setpos 399.233215 359.971802 -443.969147;setang 8.646287 -137.874237 0.000000`

**Screenshots**
![image](https://user-images.githubusercontent.com/62961532/125939802-6115f54d-a462-45a7-b854-6ee702eecfe7.png)
![image](https://user-images.githubusercontent.com/62961532/125939837-44516261-7fc2-4310-b69e-f861fdc59baa.png)

**Desktop (*please complete the following information*):**
Windows, Dx11, Panorama

**Comment by SlidyBat** [comment]
The second image is due to `r_portalfastpath`, which we default to 0 now. There are also various other rendering improvements/fixes that have been made to DX11.

**Comment by hexaflexahexagon** [comment]
Seems mostly fixed, there are some tiny white lines in the second screenshot's position but they're so small I don't really care (plus screenshots are busted for me right now anyways)
