### ISSUE TITLE
Music Volume does not actually work

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1459]
It seems the Music Volume does not work (regardless of UI, even by command). 
Usually you are able to specify what uses the music channel by placing sounds within "sound/music" (I assume it doesn't need to be this specific folder tbh but for testing it was just to make sure), and when calling to the sound path by entity or otherwise, you specify the beginning of the path with a # in front of it, this makes it use the Music channel base, controlled by the Music Slider or snd_musicvolume. ( https://developer.valvesoftware.com/wiki/Ambient_generic ), however, in 0.9.0, doing this has no effect on these specified sound paths, changing what volume the music is at by either of those methods doesn't change anything and the music plays at full volume.

**Comment by braem** [comment]
This is no longer the case with the new volume sliders. Maps will have to put the music in sounds/music path to be classified as music, which we will enforce in map submission. Has been verified before but this issue was forgotten to be closed.
