### ISSUE TITLE
$color does not work on func_brush

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1463]
**Describe the bug**
Textures using $color on func_brush dont receive the proper color value. $color2 however does work. This is obviously an easy workaround but it breaks backwards compatibility on existing maps so should be changed if the fix isnt too difficult.

**Additional context**
Reported by Smaed in discord, though this has happened in momentum for a while now. $color works fine on func_brush entities in css.

**Comment by lvaness** [comment]
DX11? DX9?

**Comment by hexaflexahexagon** [comment]
Happens in dx11 and dx9 both. the easiest way to check is on `sj_sketchy` bonus 2. 
TF2: 
![image](https://user-images.githubusercontent.com/62961532/137233886-b2a52659-a609-4fde-a0ac-2f19c94b7796.png)

Momentum:
![image](https://user-images.githubusercontent.com/62961532/137234444-7521cce0-5da1-496f-80f5-941304bd09c9.png)

**Comment by VortexParadox** [comment]
On a similar vein, `$color2` does not work on models. `$color` does however, oddly enough.
If this is still occurring, it looks like the parameters were swapped around?
Happens on both shader APIs
Disabling `cl_brushfastpath` allows `$color` to work again, but `cl_modelfastpath` makes no change to bring back `$color2`

**Comment by hexaflexahexagon** [comment]
resolved, `sj_sketchy2` b2 now has color again.
