### ISSUE TITLE
Improve readability of keybinds section in settings (panorama)

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1465]
**What feature is your improvement idea related to? Please describe.**
The keybinds section in settings in panorama is very difficult to read, there's no alternating color lines (like other settings do) and the distance between bind description and bind is a lot of wasted space, very difficult to line up with what you're trying to bind. Vgui was nice in that it was much narrower.

**Describe the solution you'd like**
Improve readability of the keybinds section by adding alternating color lines and narrowing the space between bind and bind description.

**Additional context**
panorama dx9/11, windows 1440p borderless windowed

**Comment by itVictor** [comment]
Just a side note, I think the settings panel as a whole could benefit from being more narrow due to the wasted space, it's just more problematic in the keybinds section.

**Comment by VortexParadox** [comment]
Alternating rows are barely visible on dark mode, and, separate to this issue, there's lower hierarchy read problems with the settings tabs and the text contained in them
<img src=https://user-images.githubusercontent.com/35622748/135745681-2dfe088c-4b2e-4f2f-9b5e-3d93b9c7929c.png width=410>

**Comment by hexaflexahexagon** [comment]
on light mode i think this looks pretty nice:
![image](https://user-images.githubusercontent.com/62961532/135763656-7eb04c93-8b53-415e-9fa0-4b56b4c7e70a.png)

on dark mode it is pretty hard to see like vortex said:
![image](https://user-images.githubusercontent.com/62961532/135763670-5d0f5eb4-680d-4066-b60f-52014e71847d.png)
