### ISSUE TITLE
Untranslated string in settings page

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1466]
**Describe the bug**
under video -> rendering -> global shadow quality
assuming that setting should be "Low" instead
![image](https://user-images.githubusercontent.com/20176719/126592933-9a0e51a7-b5a2-4758-b864-40c33e0e2bd7.png)

**Desktop (*please complete the following information*):**
 - OS: [Windows]
 - Renderer: [DX9]
 - UI: [Panorama]

**Comment by hexaflexahexagon** [comment]
fixed
