### ISSUE TITLE
Disallow changing setting sliders if the setting is turned off

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1467]
**What feature is your improvement idea related to? Please describe.**
Currently, settings that have an on/off toggle and have a slider associated with it allow users to change the values of the slider even if the setting is set to off, this makes adjusting the slider do nothing and should be more obvious to the user. 

Currently "mouse acceleration" and "override ghost color alpha" are set up like this.

**Describe the solution you'd like**
Grey out the slider for those settings if it's set to off, and allow changing the value if it's on.

**Additional context**
panorama

**Comment by hexaflexahexagon** [comment]
feature seems to work now

**Comment by itVictor** [comment]
fixed for mouse accel, but you can still move the slider for override ghost color alpha

**Comment by lvaness** [comment]
Just a matter of adding the relevant control to that slider as well

**Comment by hexaflexahexagon** [comment]
seems to be fixed
