### ISSUE TITLE
Shading issues on props

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1470]
**Describe the bug**
In the past, this bug was only visible on PBR assets, where the shaded areas of a mesh would have these black spots on them. But now I've been noticing this problem on VLG models. Static or dynamic, they all have this issue to varying degrees. It's always visible on the shaded areas, pointing away from the environment lighting.
It looks like RTT is having issues with props as well, in a similar fashion, shaded areas would get self-shadowed by the texture shadow. 

**To Reproduce**

1. Join `shadertest`
2. On the right you will see PBR assets, they *might* display the bug I'm talking about
3. Create a dynamic prop, it should also display this bug now

**Expected behavior**
These shading artifacts should not be present

**Screenshots (click to view full resolution)**
<img src="https://user-images.githubusercontent.com/35622748/126826986-c790441b-1605-458a-8e53-9cdc25bdfa43.png" height="240"> <img src="https://user-images.githubusercontent.com/35622748/126827013-75e9cd80-33be-474a-99c9-747925aac689.png" width="240"> <img src="https://user-images.githubusercontent.com/35622748/126827058-d9e05bf9-2e96-42d5-83fc-fa3fdc5d561b.png" height="240"><img src="https://user-images.githubusercontent.com/35622748/126827849-d16b89a0-b8e7-43b1-bdf9-fa9feb442aad.png" height="240">

##### Here, the headcrab is PBR and Alyx VLG
**Desktop (*please complete the following information*):**
 - OS: Windows 10 Pro 21H1
 - Renderer: DX9
 - UI: VGUI

**Additional context**
Given that nobody has mentioned having this issue, I'm wondering if it's just GPU related

**Comment by hexaflexahexagon** [comment]
Does this happen in dx11 as well? if not it may not be worth too much effort since we want to get rid of dx9 completely sometime before 1.0.0

**Comment by VortexParadox** [comment]
Doesn't sem to be present on DX11

**Comment by Gocnak** [comment]
Closing as DX11 is going to be our default renderer.
