### ISSUE TITLE
Add way of specifying model skin in weapon script

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1471]
**What feature is your improvement idea related to? Please describe.**
For example, using the TF2 override scripts it is impossible to have blue stickybombs right now.
![image](https://user-images.githubusercontent.com/62961532/127754515-f64eae49-5b3b-4077-8794-0f5c9fd575d5.png)

```
    "ModelData"
    {
        "view"      "models/weapons/v_models/v_stickybomb_launcher_demo.mdl"
        "world"     "models/weapons/w_models/w_stickybomb_launcher.mdl"

        "sticky"    "models/weapons/w_models/w_stickybomb.mdl"
    }
```

**Describe the solution you'd like**
Some way of doing the above. Once added the override scripts should ideally be updated to make it clear how to use the blue variants, though this will only apply for new installs.

**Comment by SlidyBat** [comment]
I added syntax for optionally specifying skin, your example would look like this:
```
"ModelData"
{
	"view"      "models/weapons/mom_stickylauncher_classic/mom_sl_classic.mdl"
	"world"     "models/weapons/mom_stickylauncher_classic/mom_sl_classic.mdl"

	"sticky"
	{
		"path"  "models/weapons/w_models/w_stickybomb.mdl"
		"skin"  "1"
	}
}
```

However, the skin parameter won't work for ViewModel models. Only entity/world models will actually use it.

**Comment by hexaflexahexagon** [comment]
Doesn't seem to work for me. For example this:
```
    "ModelData"
    {
        "view"      "models/weapons/v_models/v_stickybomb_launcher_demo.mdl"
        "world"     "models/weapons/w_models/w_stickybomb_launcher.mdl"

        //"sticky"    "models/weapons/w_models/w_stickybomb.mdl"
        "sticky"
        {
            "path" "models/weapons/w_models/w_stickybomb.mdl"
            "skin" "1"
        }
    }
```
looks like:
![image](https://user-images.githubusercontent.com/62961532/164561400-a33282d8-2592-4cf5-86a4-c657cfcae38e.png)

Could just be user error and a typo somewhere but I've tried a few permutations and had no luck getting the inner 'sticky' block to actually work. can't seem to find and relevant errors in console either.

**Comment by SlidyBat** [comment]
Unfortunately still in review and didn't make it in this last update.

**Comment by hexaflexahexagon** [comment]
works, thanks!
![image](https://user-images.githubusercontent.com/62961532/165204371-caa853fe-f050-4cb1-900a-151d58cd8a0e.png)
