### ISSUE TITLE
Change (or allow changing) airdecelerate cutoff value

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1472]
**Is your feature request related to a problem? Please describe.**
Playing with dramatically different airaccel and airdecel values (10:1 or even 100:1) in modes like RJ/SJ can occasionally unintuitively nuke your speed when doing S-taps due to slight overstrafing. Currently the cutoff angle is ~160 and would probably be better around 100. 

**Describe the solution you'd like**
This could probably work being a cvar for people to play around with some more, e.g. `sv_airdecelerate_cutoff`. 

**Describe alternatives you've considered**
If we don't want to add another cvar for this, a doc page, etc. then we can just change the value to something around 100 like lumia mentioned.

**Additional context**
https://discord.com/channels/235111289435717633/733230720079757332/871171848304488490

**Comment by jason-e** [comment]
This was added with the movement refactor as `sv_airdecelerate_angle` (default 120 degrees).
