### ISSUE TITLE
Allow players to restart while the run end screen is up

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1474]
**What feature is your improvement idea related to? Please describe.**
To save clicks, players may want to simply hit their restart bind as soon as they finish a run rather than manually clicking the big red X. We should make this possible 

**Describe the solution you'd like**
Allow players to use their restart bind while the run stat screen is still up, closing it when they restart

**Describe alternatives you've considered, if any**
We probably dont want to bother doing this in vgui but rather making sure that it happens when we recreate this panel in panorama later down the line.

**Additional context**
Suggested by ArchRhythm

**Comment by braem** [comment]
you should already be able to do this, or perhaps it requires https://docs.momentum-mod.org/var/mom_mapfinished_movement_enable/ ??

do note there is a delay on restarting immediately; the run has to be saved first before youre allowed to restart

**Comment by hexaflexahexagon** [comment]
correct, the original suggester must have just had that set to 0 instead.
