### ISSUE TITLE
Hammer Map Launcher stays active in the backround when using `-hijack`

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1476]
**Describe the bug**
Hammer Map Launcher, the utility that undertakes the map compiling process so Hammer itself remains active, stays alive in the background after map compile *and* after Hammer shuts down if the user passes `-hijack`. 
It looks like `crashpad_handler.exe` and a separate instance of `chaos.exe` remain active under Hammer Map Launcher, with `chaos.exe` taking all the CPU resources (~30% in my case).
Each time a `-hijack` is passed it will launch a new instance of the engine, which can add up to the point it slows down my computer.
Despite this, the original engine instance does accept the commands passed by `-hijack`

**To Reproduce**
1. Start Hammer
2. Start the game
3. Open or create a compilable map
4. Add a new `$game_exe` launch command with `-hijack` and `+map $file`
5. Start the compiling process
6. Once loaded-in in the game, run the `-hijack` command through the map launcher tool again
7. A new instance of the engine should start up at the very least

**Expected behavior**
I don't know how `-hijack` gets treated internally, but it should not start and keep new instances of the game running and consuming resources in the background. Perhaps this issue ties in to the other bug where one can't start the engine with console commands passed through the Hammer Map Launcher (e.g.: `-game $gamedir +map $file` doesn't start with the engine attempting to load a map.

**Screenshots**
![image](https://user-images.githubusercontent.com/35622748/128279323-d714c5d1-fedd-469f-b17d-3f78be627e38.png)

**Desktop (*please complete the following information*):**
 - OS: Windows 10
 - Renderer: DX9
 - UI: VGUI

**Additional context**
* I cannot confirm if this happens in other Chaos games so I decided to post this here
* The original engine instance was started with `-mapping` and `-legacyui`. The rest are just attempts to hijack

**Comment by Gocnak** [comment]
Does this still happen on the latest push?

**Comment by VortexParadox** [comment]
Seems to be fixed!
