### ISSUE TITLE
Timer elements for thrown concs are stuttery while moving

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1480]
**Describe the bug**
Throwing a conc and then moving will cause the countdown and timer bar attached to it to be very noticeably stuttery. This may not be an issue after removing VGUI and using panorama but that hasn't been done yet.

**To Reproduce**
1. Throw a conc in the air
2. Move while it's in the air

**Desktop (*please complete the following information*):**
Windows, Dx11, VGUI

**Comment by braem** [comment]
I changed this to `OnTick` instead of `OnThink` at some point for some reason. Will be resolved with the panorama HUD :)

**Comment by braem** [comment]
Conc entpanels implemented in panorama with no stutters. Bye VGUI :^)
