### ISSUE TITLE
Engine crash on loading jump_pipebomb_v1

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1483]
**Describe the bug**
Loading `jump_pipebomb_v1` produces the following crash consistently 
![image](https://user-images.githubusercontent.com/62961532/128994393-2534517e-ac72-414e-9615-715c89907b6d.png)

**To Reproduce**
1. https://cdn.discordapp.com/attachments/671175695648423959/874928619028373514/jump_pipebomb_v1.bsp
2. Crash

**Expected behavior**
no crashy

**Desktop (*please complete the following information*):**
Windows, Dx11, Panorama

**Additional context**
I have no idea what this map is, I was just loading random maps I had downloaded. It's probably a tf2 map and probably very old

**Comment by bakapear** [comment]
From testing, it seems that it only crashes on Dx11. Dx9 workin fine for me

**Comment by bakapear** [comment]
I found out that it crashes because the map has a prop_dynamic with the model `models/player/hwm/spy.mdl`.

[testmap.zip](https://github.com/momentum-mod/game/files/6967773/testmap.zip)

Changing it to a different model that is not a HWM one fixes the issue.

**Comment by lvaness** [comment]
Might be the same issue as surf_happyhands #1362 ?

**Comment by hexaflexahexagon** [comment]
The happyhands crash manifested slightly differently (happens in dx9, isn't an instant crash when loading, game closes rather than showing an error message) so I would doubt it, though it could be a similar root cause somewhere down the pipeline.

**Comment by hexaflexahexagon** [comment]
fixed
