### ISSUE TITLE
Panorama TextEntry tends to eat inputs

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1486]
**Describe the bug**
TextEntry inputs often continue to accept keyboard inputs even after the panel is no longer on screen.

**To Reproduce**
Most obvious case the settings search: after closing the settings panel with the search entry selected, the entry will continue to accept input. Also occurs with the search in the drawer panel.

**Expected behavior**
The panel should lose focus and stop accepting input when it or its parent/parent contextpanel is closed. There's some 'ReadyForDisplay' logic in settings_search.js brought over from CS:GO that may be supposed to be handling this.

**Desktop**
 - OS: Windows
 - Renderer: DX9]
 - UI: Panorama

**Comment by Gocnak** [comment]
@bltech is this related to #1542 ?

**Comment by hexaflexahexagon** [comment]
i don't think so, that issue is a mouse nav thing iirc

**Comment by lvaness** [comment]
Well kind of, the default focus for the chat panel is its textentry, so even if only the toast part is visible, the hidden textentry takes focus on click anywhere. So something that denies input for invisible panels would also kind of solve that problem incidentally

**Comment by hexaflexahexagon** [comment]
seems to be fixed, i can't reproduce anymore
