### ISSUE TITLE
logic_relay_queue crashes the game when doing queues

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1488]
**logic_relay_queue** performs normally like a **logic_relay**, however when the **logic_relay_queue** has not performed all outputs and queues to output again once finished, on performing the first set of outputs and firing the next que, the game instantly crashes. Unrelated to fast retrigger flag.

**Comment by braem** [comment]
Would it be possible to get a BSP for testing/verification?

**Comment by Ninja-Cookie** [comment]
> Would it be possible to get a BSP for testing/verification?

Sorry for late reply, did not check till now, it seems to all be fixed but here's a test BSP and VMF. I assume something was done to fix it.
[logic_relay_queue_test.zip](https://github.com/momentum-mod/game/files/7070728/logic_relay_queue_test.zip)

**Comment by Ninja-Cookie** [comment]
> Would it be possible to get a BSP for testing/verification?

Correction: It seems to still crash in this map calling to the logic_relay_queue like how it's written in the issue above. Shoot eye while it's flashing it will crash when it ends trying to trigger the queue.
[crashtest.zip](https://github.com/momentum-mod/game/files/7071038/crashtest.zip)

**Comment by braem** [comment]
What's happening is the rocket is triggering it (it is the activator) then exploding *before* the queue gets to the item. Null activators are fine but the event is triggering as the rocket is deleting (while it is marked for deletion) which causes problems. Just gunna add a check for it to use a null activator if it is marked for deletion.

**Comment by Gocnak** [comment]
Was this fixed in the recent push?

**Comment by hexaflexahexagon** [comment]
> Correction: It seems to still crash in this map calling to the logic_relay_queue like how it's written in the issue above. Shoot eye while it's flashing it will crash when it ends trying to trigger the queue. [crashtest.zip](https://github.com/momentum-mod/game/files/7071038/crashtest.zip)

this map doesn't seem to crash for me on latest steam dx11 so i'm guessing its been fixed and will close this
