### ISSUE TITLE
Add Map Based Replay Controls

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1491]
**Is your feature request related to a problem? Please describe.**
For tutorial levels we need to be able to show the user a replay of the technique or level they are learning. Many movement techniques require visual aid rather than just descriptions.

**Describe the solution you'd like**
Add the ability to include replay files into your bsps or in the momentum files in a specific location and provide an entity that can load and activate these replays through entity I/O. Properties would include a targetname, and the name / path of the replay to use. Other outputs / parameters like setting a timestamp or playback speed could also be included but would not be essential. This would allow for the mapper to trigger a replay of the tutorial component when the player initially visits it. This would be nice to have accessible for community maps outside of the learn section. This may also require making replays less reliant on the map's zones since we may want replays of single stages rather than full maps.

**Describe alternatives you've considered**
Alternatively we could have a ghost that loops the level for the player to spectate or we could approach them as cutscenes separate from replays. I think using replays for this would be better to familiarize users with the replay hud though.

**Comment by hexaflexahexagon** [comment]
similar to https://github.com/momentum-mod/game/issues/1252

**Comment by patrickmoc** [comment]
Looks like a duplicate, yeah. I think it's important to extract this behavior into its own point entity rather than a trigger since there may be other means of triggering the replay rather than just player collision. I will close this one for now
