### ISSUE TITLE
Regressed `+duck` behavor

### ISSUE THREAD

**Issue by Nolan-O** [momentum-mod/game#1492]
`+duck` typically enables on key down and disables on key up just like movement keys (e.g. `+moveleft`), but at some point it began toggling only on a full press and release of a key, so 2 key presses are needed for duck toggling.

This was probably introduced in the update to chaos and may be related to #1304

**Comment by hexaflexahexagon** [comment]
i can't seem to recreate this, could you add some more details? e.g. what gamemode you're experiencing this in. also i'm unsure if you mean `+duck` or `toggle_duck` since the issue you linked was related to `toggle_duck`

**Comment by Nolan-O** [comment]
Sorry for late response, It is happening in the bhop gamemode

Oops I did not mean to close this

**Comment by jason-e** [comment]
@Nolan-O Are you still having this issue? Make sure your key is actually bound to `+duck` and not `toggle_duck`.

**Comment by SlidyBat** [comment]
This is likely due to `option_duck_method` being set to 1, which causes `+duck` to toggle.
Not sure why this happened, but the issue writer hasn't responded and we haven't had any other reports of this, so I'm closing.
