### ISSUE TITLE
Panorama console panel

### ISSUE THREAD

**Issue by lvaness** [momentum-mod/game#1493]
Implement an ingame console based on Panorama to solve the input issues arising from having VGUI and Panorama active simultaneously

Relevant issues:
- #1355 
- #1393 
- #1178
- #1479
- #1420

Planned features:
- [x] Main panel
  - [x] Receive console messages
  - [x] Send console commands
  - [x] Autocomplete (maybe a bit cooler?)
  - [x] Draggable for move and resize (resize maybe not at every panel edge for simplicity's sake, c.f. Dota 2)
  - [x] Proper input handling
  - [x] Keep functionality separate from design principle (i.e. allow quake-style console if desired)
- [x] HUD panel (developer 1 and con_drawnotify 1)
  - [x] work like VGUI
- [x] General considerations
  - [x] Bunch up identical messages (maybe something more elaborate down the line, just `Missing material xyz (x7)` for now)
  - [x] Try to prevent large perf impact on high message load
  - [x] Filtering

**Comment by VortexParadox** [comment]
`cvarlist` upsets the Panorama console a lot

**Comment by lvaness** [comment]
Cvarlist should be fixed now; as it's fully implemented, I'll close this one and UX changes can be separate issues
