### ISSUE TITLE
Remove tiny blood splatter on shooting/knifing another player

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1494]
Helps us stay closer to our goal T rating for the game. Also the blood looks pretty ugly

**Comment by Gocnak** [comment]
I believe this already happened, but, we should instead hook into when players hit ghosts for some fun effects like, custom models being able to have a "hurt" sound.

**Comment by braem** [comment]
> I believe this already happened, but, we should instead hook into when players hit ghosts for some fun effects like, custom models being able to have a "hurt" sound.

It hasnt happened yet. 

Blood splatters on shooting players was 'removed' by ghosts changing in such a way that the bullet trace no longer hits them. The knife uses a different trace that does still hit. Both will need to be fully removed.
