### ISSUE TITLE
postprocess_controller keeping postprocess's across maps sometimes

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1498]
### Describe the bug

Effects, such as blurs from vignette, seem to keep or not clear during map loads. Changing or reloading maps keeps them around. Not clear on the entire details of why and how, just that it does.

### How To Reproduce

do an effect with postprocess_controller, change map.

### Expected Behavior

Don't keep the postprocess around / clear it on loading stuff.

### Operating System

Windows

### Renderer

DX9 (default)

### UI Framework

VGUI (default)

**Comment by xen-000** [comment]
I was never able to reproduce this. Post process settings are updated every frame and it just sets the defaults if there's no controller present.

**Comment by hexaflexahexagon** [comment]
Maybe something to do with changing to a map where the entity is present but unused? A test map to reproduce would be good, I'll try working on that soon if nobody else does.

**Comment by xen-000** [comment]
Well if the entity is present then the game just uses its settings.

**Comment by hexaflexahexagon** [comment]
after a bit of testing I cannot reproduce this anymore, though I never did back when it was reported either
