### ISSUE TITLE
Console commands / Keybinds

### ISSUE THREAD

**Issue by TheAsuro** [momentum-mod/game#15]
### Actions that will be bound to keys by default
* [X] Reset to start of map (if the map has a lobby or something similar, maybe make this a esc-menu option?)
* [x] Reset to start of first stage
* [x] Reset to start of current stage
* [x] Jump to savepoint (#22) 
* ~~Toggle other player models on/off~~

### Cheats
* [x] Change tickrate

These lists will probably grow a lot during development, this Issue just serves as a place to collect them all and to post ideas to.

**Comment by RabsRincon** [comment]
Weren't we going for the multiplayer implementation? Then `Change tickrate [cheat, implemented]` wouldn't make much sense(at least for the clients), right?

**Comment by TheAsuro** [comment]
You're right, now that we are going for the multiplayer implementation this doesn't make much sense. However we might still want to leave it in for now for debugging.

**Comment by RabsRincon** [comment]
Closing this for tracking reasons. Open it if new keybinding needs pop up
