### ISSUE TITLE
Investigate/Fix Panorama TextEntry focus behaviour

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1502]
### Describe the bug

Currently it's very difficult to remove cursor input from TextEntrys. This is affecting search bars, chat, and other misc entries and becoming extremely annoying. I've had a look at CS:GO's files and failed to understand what's different for us.

### How To Reproduce

Select any TextEntry, then try click various other parts of the screen. In practically all cases, the TextEntry will continue trying to take input. Clicking some panels will stop it but it feels inconsistent, may be to do with panels have acceptsfocus or acceptsinput but I can't figure it out. DropDowns are the only thing that removes input consistently, probably because they spawn an entire new panel spanning the screen.

### Expected Behavior

Clicking anywhere outside of the TextEntry should remove input, as is standard in user interfaces, both web and desktop.

### Operating System

Windows

### Renderer

DX9 (default)

### UI Framework

Panorama

**Comment by Gocnak** [comment]
The clicking has been resolved but ideally we should also add `ReadyForView` event listeners to the text entries that make it lose focus when unreadied for view.

**Comment by Gocnak** [comment]
Happy anniversary! Is this still an issue in game ever since we made the default focus behavior lazy?

**Comment by tsa96** [comment]
Oh yeah, this was fixed ages ago. But let's keep it open for another y-
