### ISSUE TITLE
Bullets don't activate buttons in practice mode

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1503]
### Describe the bug

While in practice mode bullets do not activate buttons to open doors.

### How To Reproduce

1. open map with button ex. rj_bomb
2. enter practice mode
3. shoot button with shotgun
4. observe it hasn't opened the associated door

### Expected Behavior

Shooting buttons should open doors in practice mode.

### Operating System

Windows 10

### Renderer

DX9 (default)

### UI Framework

VGUI (default)

**Comment by Mac-tf2** [comment]
Isn't this an intended feature to stop button cheating?

**Comment by Gocnak** [comment]
It is, but when the timer is not running it should still do damage.

**Comment by hexaflexahexagon** [comment]
fixed
