### ISSUE TITLE
Panorama avatar image does not fit the panel

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1507]
### Describe the bug

The avatar image on all avatar panels are not sized correctly
![image](https://user-images.githubusercontent.com/35622748/135746190-6eda2348-7e55-4a8f-bfed-55c426d1390c.png)

### How To Reproduce

1. Start Momentum in Panorama mode
2. Avatar image should show up as incorrectly sized

### Expected Behavior

The image should occupy the whole dedicated frame

### Operating System

Windows 10

### Renderer

DX9 (default)

### UI Framework

Panorama

**Comment by Gocnak** [comment]
Can we get more info? What resolution are you playing at? Do repeat boots make it show up right?

**Comment by VortexParadox** [comment]
Sure, I'm running the game at 1366*768. And it's always sized like this

**Comment by hexaflexahexagon** [comment]
Can reproduce, on loading in 1366*768 borderless windowed (dx11) my profile picture looks like the above.

1920x1080 works fine, as does 1600x900. anything lower seems to bug out.

**Comment by braem** [comment]
Not going to assign a size as this *could* be quite a deep issue. The avatar panels all have full width so maybe a problem with the resolution scaling? (oh boy)

**Comment by SlidyBat** [comment]
The ChaosAvatarImage has an internal Image panel (can see it in the panorama debugger). CS:GO sets the width/height of this internal panel to 100% through CSS, which we are missing:
```css
CSGOAvatarImage .AvatarImage
{
	width: 100%;
	height: 100%;
}
```

I've applied the same thing, but through C++, so that games don't have to rely on that CSS code being present.

**Comment by granis48** [comment]
I am not able to change the resolution on fullscreen windowed mode but i tried many different resolutions on both dx9 and dx11 both in windowed and fullscreen and was not able to replicate the wrong scale avatar. Seems to be fixed

**Comment by VortexParadox** [comment]
Yep it's fixed
