### ISSUE TITLE
Panorama HUD Speedometer

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1508]
### What feature is your improvement idea related to?

Panorama port

### Describe the solution you'd like

See mockup on Zeplin.

Some notes on functionality:
- Avoid loading speedometer CFG in JS
- Create new CFG without VGUI layout options
- Have options from the CFG as JS accessors
- New cvar for limiting updates on the axis speedometers (the every frame ones)

**Comment by hexaflexahexagon** [comment]
Was the `New cvar for limiting updates on the axis speedometers (the every frame ones)` step implemented? I can't find the convar anywhere, just the new `mom_hud_speedometer_enable` one. If so (or if we decided to skip adding that) then this issue can be closed

**Comment by braem** [comment]
> 
> 
> Was the `New cvar for limiting updates on the axis speedometers (the every frame ones)` step implemented? I can't find the convar anywhere, just the new `mom_hud_speedometer_enable` one. If so (or if we decided to skip adding that) then this issue can be closed

No haven't implemented that yet. Added the enable one with the dual sliders because it was ez

Related issue was closed: https://github.com/momentum-mod/game/issues/1553

**Comment by hexaflexahexagon** [comment]
ohhhh, gotcha. i'll un-block this and we can close it whenever that convar gets added in. everything else looks good to me tho. (we can make a docs issue too just so it doesn't get forgotten about)

**Comment by braem** [comment]
Included in next push:
Added the convar - `mom_hud_speedometer_fps`. Increase/decrease coloring should be remedied as well, and scale with FPS. If not good still we can tweak the `COLORIZE_DEADZONE` value in `panorama/scripts/hud/speedometer.js`.

**Comment by hexaflexahexagon** [comment]
convar now exists
