### ISSUE TITLE
Panorama strafesync HUD

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1515]
### What feature is your improvement idea related to?

Panorama port

### Describe the solution you'd like

See Zeplin for mockup

**Comment by hexaflexahexagon** [comment]
Settings could use a little more refinement lol but that can be a separate card, the actual panel works perfectly.

![image](https://user-images.githubusercontent.com/62961532/143691864-200a1153-92ce-4499-8fc4-a80763b34289.png)
