### ISSUE TITLE
Panorama colorpicker

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1520]
### What feature is your improvement idea related to?

Panorama port

### Describe the solution you'd like

Perhaps more of a Chaos thing than Momentum specific. Will need this for changing colors in the settings.
Doesn't have a mockup from what I see.

**Comment by hexaflexahexagon** [comment]
One was made by tra and posted in discord, just not uploaded anywhere

**Comment by braem** [comment]
We've talked about trimming back the amount of parameters that exist in the VGUI one so I'm not sure if this is final.

**Comment by hexaflexahexagon** [comment]
added
