### ISSUE TITLE
Panorama Map Selector

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1523]
### What feature is your improvement idea related to?

Panorama port

### Describe the solution you'd like

See Zeplin for mockup.

### Additional context

Things left:

- [x] Styling (Tom's getting this one)
- [x] #1544
- [x] #1545
- [x] #1546
- [x] Pass map data into MapEntrys using attributes rather that dialog vars so we can customise in JS more, control what icons are shown next to PB time, what's shown in the tooltip over the PB
- [x] ~~Add DelayLoadList event on load with no. of items in list, show if no items are loaded~~ Went with adding `MapSelector_MapsFiltered( count )` instead
- [x] Fire event for each MapEntry each time data updates
- [x] Remove MapCompletedFlag being required to exist by C++
- [x] Rename SettingsSearchTextEntry in map selector C++ XML and JS to MapSelectorSearchTextEntry
- [x] #1547

**Comment by tsa96** [comment]
Currently most data is being updated from C++ using dialog variables. I'd like to be able to show more PB data in tooltips, could be done in C++ but IMO that's something JS should handle. For the map entry panels at least, it'd be nice to have PB data passed in as panel attributes so they can be accessed from JS using `$.GetContextPanel().GetAttributeString()`, as far as I know JS is unable to get the value of dialog vars, only set them.

**Comment by tsa96** [comment]
Also, we need to have a discussion about staged and linears. On modes like bhop and surf distinguishing staged and linears is often very desirable, to the extent where having togglebuttons to enable each would be really nice. I understand with RJ and SJ linear and staged can be a bit more ambiguous so maybe the filters would be less useful, but I'd argue it's better to include filters that are extremely useful to some modes and not particularly useful for others than to not have the filters entirely. Worth talking about on Saturday.
