### ISSUE TITLE
Map Selector mode tooltip doesn't go away

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1532]
### Describe the bug

The tooltip suggesting that users use right click to select one mode and deselect the rest does not disappear.

### How To Reproduce

1. select every mode in the map selector
2. manually left click all of them to deselect
3. observe that the tooltip suggesting you use right click for this does not disappear

### Expected Behavior

The tooltip should disappear when switching panels / after some time

### Operating System

Windows 10

### Renderer

DX11

### UI Framework

Panorama

**Comment by tsa96** [comment]
fug

**Comment by tsa96** [comment]
Fixed on map selector branch, should be on Steam shortly
