### ISSUE TITLE
Using clear button does not clear search on map selector

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1533]
### Describe the bug

Using the clear button after searching does not properly clear conditions and maps no longer show up even if deleting text from search

### How To Reproduce

1. search for a map on the map selector
2. try to clear the search / delete text from search
3. observe an empty map selector that hasn't had its conditions cleared

### Expected Behavior

when clicking the clear button all applied conditions to the map selector should be cleared
when deleting your search, maps that fit your other criteria should show again

### Operating System

Windows 10

### Renderer

DX11

### UI Framework

Panorama

**Comment by tsa96** [comment]
Yeah I've not finished hooking up search, that'll be fixed in near future

**Comment by Gocnak** [comment]
Is this properly implemented now?

**Comment by hexaflexahexagon** [comment]
looks good to me, closing.
