### ISSUE TITLE
[Panorama Console] Caught-repeat messages do not show back up in developer console notify panel

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1534]
### Describe the bug

In-game, there's the console notify panel in the top left that shows console messages in game. A feature of the panorama console is that exact-same console messages are now bundled with an `(x<num>!)` added to it.

Going in game, and triggering something to cause a message to spawn will show, then eventually fade away. Triggering the message *yet again* will not cause the repeat label to show up.

### How To Reproduce

1. Go in game
2. Bind some key to "echo blah"
3. Spam the key in game to see "blah (x7!)"
4. Wait a bit until it fades away
5. Continue spamming the blah key
6. Note that the message updates in the actual console, it just does not show the message in the notify panel until another unique message is passed

### Expected Behavior

Causing the repeat message to increment the counter should also show the message again on the notify panel.

### Operating System

Windows

### Renderer

DX9 (default)

### UI Framework

Panorama

**Comment by lvaness** [comment]
It's not really a bug, I just found the information value of having the repeat message also flash the notify tends to go to zero very quickly

**Comment by Gocnak** [comment]
Old notify was still showing it, to let you know it was spamming. I think it's still valuable to show the `(x<num>)` string incrementing.
