### ISSUE TITLE
Loading screen truncates load % string at specific number

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1538]
### Describe the bug

When loading maps the loading % label sometimes truncates, it's really noticeable despite it only happening for around a half second.

### How To Reproduce

1. Open a map that's larger
2. Watch very intently the loading % label
3. Notice at around 11? % it turns into `1...`
4. It quickly changes back to 17% and onwards

### Expected Behavior

Do not truncate it. Tom may know what to do to fix it, we may just need to set a min width on it?

### Operating System

Windows

### Renderer

DX9 (default)

**Comment by tsa96** [comment]
Fixed merged in yesterday
