### ISSUE TITLE
Using tab autocomplete in panorama console does not add a space after the command

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1540]
### What feature is your improvement idea related to?

Trying to quickly use tab completion looks something like this in the panorama console:
`mom_gamem` -> tab -> `mom_gamemode_override` -> `mom_gamemode_override5`

Due to a space no longer being automatically inserted after hitting tab. I'm unsure if this only happens to convars that require a value (like `mom_gamemode_override`) or if other console commands (like `hud_reloadscheme`) are also supposed to have a space inserted but the end result doesn't matter much if differentiating between the two is too complicated. 

### Describe the solution you'd like

Pressing tab to complete a command should automatically add a space after it for ease of use.

### Additional context

cc blt

**Comment by lvaness** [comment]
Yeah, no problem to add that, I'll just have to observe the VGUI console a bit more closely on what it does
