### ISSUE TITLE
Movement keys "freeze" for seemingly no reason

### ISSUE THREAD

**Issue by JosSamLoh** [momentum-mod/game#1542]
### Describe the bug

While trying out the new map _(bhop_tripportals)_ I seem to have had my movement keys freeze randomly while playing. Tried on another gamemode & map and got the same results.

### How To Reproduce

1. Join a map
2. Play
3. Have all of your movement keys freeze and be unable to register any more key presses
4. Fix by pressing escape

### Expected Behavior

Not have my movement keys freeze in the middle of a run.

### Operating System

Linux (Arch)

### Renderer

DX11

**Comment by tsa96** [comment]
Any specific circumstances under which this is recurring? Can you replicate it consistently? Could be something to do worth portals

**Comment by JosSamLoh** [comment]
> Any specific circumstances under which this is recurring? Can you replicate it consistently? Could be something to do worth portals

So far I've experienced it on multiple maps, with and without portals, multiple gamemodes, seemingly completely randomly.

**Comment by Hat-Kid** [comment]
Can confirm I've had the same thing happen on Arch Linux within a minute of joining random maps no matter the gamemode.

**Comment by hexaflexahexagon** [comment]
Sounds like this issue is local to Linux users. blt said they were messing with some input code so they have a good idea of where to look

**Comment by lvaness** [comment]
I haven't heard of this happening for a while and it should be theoretically impossible now
