### ISSUE TITLE
[Map Selector] Tri-state button component

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1546]
Map selector's filters, specifically these three:
![image](https://user-images.githubusercontent.com/5162166/138025856-574739e8-b52f-4766-b1bc-edbe7bbeae5d.png)

need to have a way to have a "include (ON), exclude (OFF), prevent (RED)" 

Example:
I want to search by favorite maps that are NOT completed. Currently you can only search for all favorite maps, or favorite completed maps:
![image](https://user-images.githubusercontent.com/5162166/138026029-b70ccb05-11bb-4e20-8d97-4062f690f211.png)

Another example:
I want to show all maps I have NOT downloaded. You can only show both downloaded and not downloaded, or just downloaded:
![image](https://user-images.githubusercontent.com/5162166/138026126-4d24f4ec-73cd-4d40-bd22-19a40775f68e.png)

**Comment by hexaflexahexagon** [comment]
done & in the map selector
