### ISSUE TITLE
`mom_hud_keypress_enable 0` doesn't always work

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1552]
### Describe the bug

I have `mom_hud_keypress_enable` in all of my gamemode.cfg files, some set to 0 and others set to 1. Loading a map with SJ movement, where `sj.cfg` has `mom_hud_keypress_enable 0`, always loads in with the hud element enabled. Typing `mom_hud_keypress_enable` in console to display the value shows it to be 0. Setting the cvar to 0 manually removes the hud element like you would expect. The command is not in my autoexec file.

### How To Reproduce

1. Create `sj.cfg` and add `mom_hud_keypress_enable 0`
2. Load an sj map
3. Notice the showkey display is being drawn
4. `mom_hud_keypress_enable 0` in console
5. The display goes away

### Expected Behavior

When the cvar is set to 0 the keypress display should be hidden

### Operating System

Windows 10

### Renderer

DX11

**Comment by hexaflexahexagon** [comment]
I just had the element stuck enabled, setting `mom_hud_keypress_enable 0` did nothing. Doing `mom_hud_keypress_enable 1` and then back to `mom_hud_keypress_enable 0` did make it go away, which feels related to this issue.

**Comment by Gocnak** [comment]
I have a feeling this is related to the ugly SetActive pattern found in our Panorama code that we will be looking to improve soon. This should be fixed in a future push.

**Comment by hexaflexahexagon** [comment]
resolved
