### ISSUE TITLE
Discord rich presence constantly tries to establish Discord connection when Discord is closed

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1557]
### Describe the bug

The game constantly fails to connect to Discord when Discord is closed and RPC for Discord is enabled.

### How To Reproduce

1. Open Discord
2. Open the game
2. Make sure game has `mom_discord_enable 1`
3. Close Discord
4. See spam

![https://cdn.discordapp.com/attachments/390338161982570517/902273480559558706/VQjMTiyFwf.gif](https://cdn.discordapp.com/attachments/390338161982570517/902273480559558706/VQjMTiyFwf.gif)

### Expected Behavior

It should handle Discord closing properly and not spam.

### Operating System

Any

### Renderer

DX9 (default)

**Comment by Gocnak** [comment]
Update to the steps to reproduce, this was when Discord was open with the game open, then closing Discord *with the game still open*

**Comment by hexaflexahexagon** [comment]
seems to be fixed, the repro steps only give me 1 single error message now about discordRPC being shut down which i'd guess is intended
