### ISSUE TITLE
Tabbing out of & into the game sometimes locks all keyboard input

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1560]
### Describe the bug

I can't consistently replicate this but if I find steps to later I'll edit this card. Sometimes, when tabbing back into momentum all keyboard input is locked. Mouse input works fine. Pressing escape once fixes this, probably something to do with panorama focus code as that's been giving us lots of issues lately. 

### How To Reproduce

1. xyz
2. Tab out of momentum mod
2. xyz 
3. Tab into momentum mod
4. Input from keyboard doesn't work
5. Escape key
6. Input works again

### Expected Behavior

no bug

### Operating System

Windows

### Renderer

DX9 (default)

**Comment by lvaness** [comment]
Does this still happen? I was never able to reproduce

**Comment by hexaflexahexagon** [comment]
i'll go ahead and close this unless someone else experiences it after this newest push
