### ISSUE TITLE
Lock `+strafe` and related commands behind `sv_cheats 1`

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1563]
### What feature is your improvement idea related to?

This is something we've been talking about on and off for a while so I decided to make a card to track it. Will probably need a more concrete team discussion before following through with to make sure we're sure, as this may upset a minority of players.

+strafe and related commands (`m_*`) can be used to move the character around using the mouse rather than wasd. This is really useful in modes like ahop or sj where you sometimes want to precisely slowdown, as +strafe is much easier than learning how to briefly tap s and control your speed. Because of this, we may want to consider removing the command. Some players like it, others don't, so it's a fairly subjective game design decision. Some other things to consider include keybind UI, how we fit all the actions for a mode like ahop comfortably near WASD, approachability for new players to a mode, and generally if we want this to become a meta that everyone has to learn to use in the future. 

### Describe the solution you'd like

Remove `+strafe` and all associated commands that are only needed when using mouselook navigation (to my knowledge, that's a good chunk of the m_* commands) should be locked behind `sv_cheats 1`. 

### Describe alternatives you've considered, if any.

Could use `-mapping` or `-dev` instead, doesn't matter.

**Comment by chovelyoukai** [comment]
I think this can be closed, we've introduced the `mom_mv_allow_mouse_strafing` cvar which disables +strafe entirely in bhop, surf, climb, tricksurf, and parkour. We're also working on movement changes in ahop to better balance +strafe. +strafe is remaining unchanged in all other modes.

**Comment by Gocnak** [comment]
As per the comment above.
