### ISSUE TITLE
'Return' and 'Quit' buttons are backwards

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1564]
### What feature is your improvement idea related to?

On the current Pano Quit confomation popup, the ordering is currently return on the left, and quit on the right

Looking at several other source games, including CS:GO, CS:S, Portal 1 and 2, TF2, and DOTA2, They all have Quit/yes/confirm on the left, and return/no on the right.

Windows itself follows the convention of yes/no, rather than no/yes. 

### Describe the solution you'd like

Swap the ordering of quit and confirm to match the standard of other source games

**Comment by hexaflexahexagon** [comment]
this has been done
