### ISSUE TITLE
Make concs avoid sinking into the ground

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1566]
### What feature is your improvement idea related to?

Since conc grenades' hitbox is 0.0001 units at their origin, when resting on the ground they're ~halfway in the floor. Having some way of avoiding this would be nice, though it's TBD if we want this considering it'd misalign the conc projectile and explosion center. A good proposal should probably be thought up before anyone tackles this.

### Describe the solution you'd like

Make concs not visually sink into the floor

### Describe alternatives you've considered, if any.

Leave it as-is

**Comment by Gocnak** [comment]
Not really going to be possible without also messing how concs would visually appear in the air, as the solution requires offsetting the model origin. Anything more than that would be complicated for very minimal benefit. Closing as won't do.
