### ISSUE TITLE
Missing texture on portals from far away on DX11

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#1568]
### Describe the bug

When looking at a portal from far away it shows the error texture.
![unknown](https://user-images.githubusercontent.com/52294733/139691650-8dd1c45d-9fa5-4b69-8417-146cbdfb62e0.png)
 

### How To Reproduce

I'm not sure what the cause is, i started the game with dx11 and launched bhop_tripportals and noticed the portals were wack. 

SCell was able to reproduce it by lowering graphics settings (except for shader detail) as well as something with the fov? https://discord.com/channels/235111289435717633/356398721790902274/904741533880823909

### Expected Behavior

no error

### Operating System

windows 10

### Renderer

DX11

**Comment by hexaflexahexagon** [comment]
seems to be fixed for me
