### ISSUE TITLE
"Unknown Command" response only shows when at the main menu, not in-game

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1569]
### Describe the bug

Typing a non-valid command on the main menu shows the below correct output:

![image](https://user-images.githubusercontent.com/62961532/140629089-1ec0853f-a397-4ec8-9ff3-d195003aaa04.png)

But doing the same while in a map shows nothing (the error pictured is visible with `developer 1` only):

![image](https://user-images.githubusercontent.com/62961532/140629103-ac6bc75c-2a0b-44ce-91bb-55caa31582ef.png)

### How To Reproduce

1. Type `asdf` in console at the main menu, see response
2. Load any map
3. Type `asdf` and see no response

### Expected Behavior

The "Unknown command" message should always show

### Operating System

Windows 10

### Renderer

DX11

**Comment by lvaness** [comment]
This should be fixed with the next release. Additionally, some "dearly missed" game messages printed to chat (e.g. savelocs) should reappear as well

**Comment by granis48** [comment]
Seems to be fixed now. And the chat messages are showing up when creating savelocs/start marks too :)
