### ISSUE TITLE
Leaderboard panel flashes on screen when opened with 'cl_drawhud 0'

### ISSUE THREAD

**Issue by EthanV-3D** [momentum-mod/game#1570]
### Describe the bug

Leaderboard panel seems to try to render for a single frame, before disappearing, when pressing tab with cl_drawhud 0.

### How To Reproduce

1. Launch game, enter a map
2. Enable cl_drawhud 0
3. Open leaderboard panel with tab, or whatever button it's bound to

### Expected Behavior

No panel should appear at all

### Operating System

Windows 10

### Renderer

DX9 (default)

**Comment by lvaness** [comment]
Is this still happening? I can't reproduce it

**Comment by hexaflexahexagon** [comment]
nope, not for me at least
