### ISSUE TITLE
Panorama: add a way to disable animations

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1574]
### Is your feature request related to a problem?

For whatever reason they may have (performance, photo-sensitivity, spite) players may want to disable all hud animations. Consider this seems like something that's relatively easy to add, I think it's worthwhile to do at some point. 

### Describe the solution you'd like

A cvar that disables all panorama animations.

### Describe alternatives you've considered, if any.

Alternatively we could have something like a "no / minimal / full" amount of animation toggle so people can have some middle ground, but this seems like something that would require a lot more work to implement.

**Comment by tsa96** [comment]
Duplicate of https://github.com/momentum-mod/game/issues/1575
