### ISSUE TITLE
[Panorama] Expose convar name for all settings controls

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1576]
### What feature is your improvement idea related to?

Currently only ChaosSettingsEnum ChaosSettingsEnumDropdown expose their `convar` attributes, which I'm trying to access in JS to show in the new info panels, ChaosSettingsSlider, ConVarColorDisplay and ChaosSettingsKeybinder don't expose anything.

### Describe the solution you'd like

Make a cleaner way of getting convar values e.g. set the convar as an accessor than I can just get with `panel.convar`

**Comment by Gocnak** [comment]
Dev note: Seems like Enum and Dropdown fall through in their `SetProperty` methods to the base Panel2D's method which inserts it into the map that `GetAttributeString` gets at.

We should instead clean up all of these controls to properly:
1. Return true when the attribute "convar" is handled (convar is properly initialized)
2. Expose the convar name directly inside the object template

**Comment by braem** [comment]
did this and also exposed 'bind' for the keybindings panel
