### ISSUE TITLE
Panorama Persistent Storage Dump and Clear Commands

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1580]
### Is your feature request related to a problem?

We're starting to use persistent storage a bunch and could do with better ways of debugging it, especially when working with playtesters.

### Describe the solution you'd like

Add two commands, something like `dump_panorama_persistent_storage` and `wipe_panorama_persistent_storage`. Former outputting all the KVs stored to console, latter clearing everything. We should never be storing sensitivity or vital data here anyway so these should be safe to do.

**Comment by Gocnak** [comment]
Added under the `panorama_persistent_storage_*` convar suite
