### ISSUE TITLE
DX11: crash on loading `jump_academy2_rc8`

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1583]
### Describe the bug

Loading `jump_academy2_rc8` in dx11 will crash the game consistently for me. Dx9 does not crash. `_rc7` also does not crash in either, though I think it did at one point for what that's worth. I don't see any crash dumps in my `_sentry` folder or `appdata/local/crashdumps` but it happens reliably for me and hopefully for devs as well. Map isn't public so no download link but I can share it with whoever is investigating this.

### How To Reproduce

1. Open map
2. crash

### Expected Behavior

no crash

### Operating System

Win10 19042.1348

### Renderer

DX11

**Comment by Gocnak** [comment]
Potentially related to #1483 , has a model inside of it that uses hwmorph, which was fixed recently, awaiting confirmation next push that this and that issue are fixed.

**Comment by hexaflexahexagon** [comment]
fixed
