### ISSUE TITLE
Taking a screenshot while around portals has visual artifacts

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1589]
### Describe the bug

Standing between two portals and using window's snipping tool: 
![image](https://user-images.githubusercontent.com/62961532/143712507-0c864474-2eb6-421f-b296-c89b2b8057ef.png)

Backing up and using snipping tool again:
![image](https://user-images.githubusercontent.com/62961532/143712929-777bad44-fbfd-4df3-9cc2-507a72a24c13.png)

### How To Reproduce

See above

### Expected Behavior

No weird white spots

### Operating System

Win10 19042.1348

### Renderer

DX11

**Comment by Gocnak** [comment]
Does this still happen?

**Comment by yasiralamriki** [comment]
![image](https://user-images.githubusercontent.com/70416702/157686269-8ed8387c-6669-48c9-8d4f-d6a713db32ce.png)
Doesnt happen for me

**Comment by hexaflexahexagon** [comment]
me neither
