### ISSUE TITLE
Fixing Ramp Glitch

### ISSUE THREAD

**Issue by fatalis** [momentum-mod/game#16]
Let me start by saying I don't know what the fuck I'm doing. I'm terrible at math and don't know much about Source.

But I -somewhat- fixed ramp glitch, or at least narrowed down the cause a bit. I found a couple lines that when commented out, fix some types of ramp glitches that occur. It doesn't fix the glitches that occur due to bad vertexes, just the "random" ones.

I tested this using a high tick rate so glitches occur more often. Using all 3 patches I was able to (somewhat) surf at 1000tick (not 100) and not get immediately stuck on ramp when touching it.

This isn't a proper fix, but hopefully someone that knows math can use this info to fix it for real. The root cause is probably a precision error in TracePlayerBBox? I don't know, I'm giving up for now cause I'm stupid.

Commenting out this fixes most glitches. Didn't notice any side effects. Also allows falling down a vertical ramp (surf_olympics) etc.
https://github.com/momentum-mod/game/blob/67308c6427d45244afa1efd6c8e7108682e5c4e0/sp/src/game/shared/gamemovement.cpp#L2802

Comment out this to fixes a less common case. No idea what the comment is talking about and couldn't reproduce or notice side effects.
https://github.com/momentum-mod/game/blob/67308c6427d45244afa1efd6c8e7108682e5c4e0/sp/src/game/shared/gamemovement.cpp#L2794

Mostly occurs at 1000tick, commenting out somewhat fixes but has game breaking side effects.
https://github.com/momentum-mod/game/blob/67308c6427d45244afa1efd6c8e7108682e5c4e0/sp/src/game/shared/gamemovement.cpp#L2775-2783

**Comment by Gocnak** [comment]
This is awesome, I will definitely look into applying some of these.

Most of the surfing and bhopping will occur at 100 tick or below (veterans will probably still want 66 tick) so knowing precisely where this happens is incredible, good work Fatalis!
