### ISSUE TITLE
[Panorama] Option to open links in browser rather than Steam Overlay

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1602]
### Is your feature request related to a problem?

We're going to be having a lot of website integration in-game linking to things like player profiles on the website. It seems like mostly a matter of preference whether you prefer to view that page in Steam Overlay or in browser, likely depending on things like whether you have a second monitor and whether you play in borderless or fullscreen.

### Describe the solution you'd like

Create a JS function to open a URL in browser, and ideally another function to open *either* in browser or in Steam Overlay. Then add an option to the user interface section of the settings where players can choose one or the other.

We should probably have some kind of "don't show me again" external site warning that warns about URLs other than momentum-mod.org, perhaps hardcoded in C++ so custom HUDs can't disable it.

**Comment by lvaness** [comment]
Yeah we should be very careful with this, as far as I know, the only way to do this is using `start` on windows (or maybe some windows api function) and `xdg-open` on Linux so we need to make **really** sure people aren't launching random applications

**Comment by Gocnak** [comment]
I really don't think it's worth the security risk here.
