### ISSUE TITLE
Distance ctaps seem slightly harder than in tf2

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1609]
### Describe the bug

Many people have noted that ctaps seem off compared to TF2. probably something in the duck code that's different from tf2

### How To Reproduce

1. Try ctap
2. death

### Expected Behavior

Ctaps are bettererer

### Operating System

Windows 10

### Renderer

DX11

**Comment by Gocnak** [comment]
This should be implicitly fixed by the movement refactor that @jason-e is working on. Should be in around 0.9.2 (maybe before then).

**Comment by Gocnak** [comment]
Was confirmed fixed by Ninja Cookie in discord.
