### ISSUE TITLE
Add `mom_hud_speedometer_enable` to panorama speedometer settings

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1612]
### What feature is your improvement idea related to?

We recently added speedometer settings, would be good to also add the setting to bulk enable/disable everything.

### Describe the solution you'd like

Add a "Enable speedometers" setting for `mom_hud_speedometer_enable`, probably using a fancy dropdown thingy like the other 'enable' cvars with sub-settings use.

**Comment by braem** [comment]
Will also come with `mom_hud_speedometer_fps` and some tweaks to speedometer settings

**Comment by hexaflexahexagon** [comment]
added
