### ISSUE TITLE
When searching in settings, index the current language's results as well as english

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1613]
### What feature is your improvement idea related to?

Many players are used to looking through settings in english rather than their native language, so we should allow people to search for both english and localized settings at the same time. When clicking a result it will still be displayed in their language, but the issue is typically just indexing things. Not all languages have good translations for things and all of that (`m_gierungsgeschwindigkeit 0`)

### Describe the solution you'd like

When my game is in french and I search for `jump` I should still see the jump keybind thingy in the results, despite `jump` potentially not existing in the localized copy of all the strings.

### Describe alternatives you've considered, if any.

pootis

**Comment by tsa96** [comment]
This is best to work on round 0.10.0 as we start actually getting some localisation in, quick thought now - easiest way is to set some extra attribute for keywords (comma separated) that can be the English string plus any other stuff like "fov" for "field of view". Then have the JS search check that attr as well as the text

**Comment by tsa96** [comment]
Somewhat similar thing brought up here  https://discord.com/channels/235111289435717633/390338161982570517/919886516153638962 have it parse section subheadings as well

**Comment by Gocnak** [comment]
Bumping to medium priority as we start to translate stuff now.

**Comment by tsa96** [comment]
Eh, I kinda wanna get this done now and the JS for this contains some Valve stuff, gonna do this issue this evening
