### ISSUE TITLE
Add cvar the enable ramp bounce thing.

### ISSUE THREAD

**Issue by RoadyBhop** [momentum-mod/game#1616]
### What feature is your improvement idea related to?

In css if you let go of space when hitting a ramp you gain height without a cost to your speed, this is removed in momentum mod. This should be added back as a cvar for mappers who want to use momentum mod to test maps for css release. 

### Describe the solution you'd like

some cvar to enable this, could be behind mapping mode.

### Additional context

consult rio for more information if needed :)

**Comment by jason-e** [comment]
This was added with the movement code refactor as `mom_mv_fix_nojump_slope_boosts`.
