### ISSUE TITLE
Reorganise weapon volume sliders

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1619]
### What feature is your improvement idea related to?

Currently we have two sliders for weapon volume, "Player Weapon Volume" and "Overall Weapon Volume". "Overall" does seem to affect all weapons, which is very unintuitive as now both "Player" and "Overall" affect your own weapons.

Also, neither of these sliders actually affect impact sounds (I don't think any of the sliders do) meaning it's possible to have impact noises completely drown out the weapon noises themselves.

### Describe the solution you'd like

A better option would be "Player Weapon Volume" and "Ghost Weapon Volume" (I don't think there can be weapon sounds from other sources).

This might be annoying to do from a technical point of view but it seems needed, as being able to control ghost weapon volume matters a great deal.

For impact sounds I'm not so sure, adding another slider for them seems like a bit much as we don't want to overwhelm people, maybe best to just include them with the base weapon volume?

**Comment by braem** [comment]
Can easily add an explosives sounds one, but do we want one for player and ghost for that too? or should we just bundle that into weapon volumes? dont wanna have a billion sliders.

Effecting ghosts only is on the radar though there is some extra consideration needed in adding a game-specific change into the sound system.

**Comment by hexaflexahexagon** [comment]
i would say just having 2 sliders for 'weapons,' one for you and one for ghosts works. assuming we have good levels then that should cover everything people realistically want (who cares about making the gun louder but the impact sound lower but then explosive louder?)

**Comment by tsa96** [comment]
From a UX point of view I think ghost only sounds is extremely important, in fact pretty essential IMO. If that's impossible we'd have to come up with a way to explain to people that one slider is going to affect EVERYTHING and one just the player, since this is very unintuitive. IMO even if that's a lot of work it's worth the time - I know that might sound totally exasperating to hear from a non-dev but ghost sounds can easily become super overwhelming (and I expect will be the case more and more as the number of playtesters thereby number of players in lobbies increases) so this feels like a very important QoL change.

Another sound I wanted to bring up is paint noises, in lobbies you here it spammed a TON (especially by people who've just got into playtest), I guess those could be bundled in with "Ghost sounds"?

**Comment by tsa96** [comment]
Also, timer and paint sounds are currently in their own folders, we should either move them into an existing one, or create a slider for them.

**Comment by braem** [comment]
timer ones should be in ui/
not sure what to do about paint sounds, maybe best with weapon

**Comment by hexaflexahexagon** [comment]
we don't have a paint gun anymore which would make it an easy decision but i would say weapon is the best category for them still

**Comment by tsa96** [comment]
Adding on to this rather than doing a new issue - ahop sprint sound doesn't seem to be affected by any sliders currently, should be handled somewhere.

**Comment by tsa96** [comment]
Closed by https://github.com/momentum-mod/panorama/pull/98
