### ISSUE TITLE
+duck to show/hide mouse cursor in replays doesn't work when bound via an alias

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#1620]
### Describe the bug

When watching a replay +duck normally toggles mouse capture, but if you don't have a key directly bound to +duck and instead have an alias in between it instead causes the camera view of the replay to duck.

### How To Reproduce

Execute the following aliases:

```
bind ctrl +duck2

alias "+duck2" "+duck"
alias "-duck2" "-duck"
```

### Expected Behavior

The capture of +duck should work regardless of if its bound directly or bound via an ailas.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
We've fixed this by hardcoding it to toggle mouse with left CTRL, regardless of binds. We want to remain consistent like this for key input commands -- similar to the leaderboards always toggling mouse with right click (and not +attack2).
