### ISSUE TITLE
Standing-Crouch Bug

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1621]
### Describe the bug

By making a save in the air while crouching, standing up on ground, then crouching and loading the save at the same time, you can be put into a Standing-Crouch state, where you're physically taller than your collision box.

https://user-images.githubusercontent.com/62808028/146708809-8f14bbea-67c5-4a6e-9bc2-51f7c31246b3.mp4

You are able to shoot through ceilings in this state and possibly more, however it doesn't seem to activate triggers through them.

https://user-images.githubusercontent.com/62808028/146708823-6ad5e8bc-1c2a-4ece-988d-d2671596cffc.mp4

 

### How To Reproduce

1. Jump in the air in some way, crouch, and make a save before you land.
2. Stand up on any ground surface.
3. Crouch and load the save at the same time.

### Expected Behavior

Crouch as normal.

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by jason-e** [comment]
Fixed in the latest playtest version! Seems this was actually an older bug that was unrelated to a recent ducking/saveloc tweak.
