### ISSUE TITLE
on stage 5 of surf_rookie a wall pops up but only for the first run of the stage

### ISSUE THREAD

**Issue by HellosHere** [momentum-mod/game#1625]
### Describe the bug

when surfing on stage 5 a wall is covering the hole you have to go through but only for the first time you enter the stage, after you die it goes away.

### How To Reproduce

just go to stage 5 and it should be there if not try starting from the beginning of the map then playing all the way to stage 5.

### Expected Behavior

when I enter stage 5 there is a wall coving the hole 

### Operating System

windows

### Renderer

DX11 (default)

**Comment by xen-000** [comment]
That's really how stages 5 and 6 were made, it's not a bug.

[video](https://youtu.be/sf5VA_uxN0w?t=21)
