### ISSUE TITLE
Spam Players with Projectiles / Other

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1626]
### Describe the bug

Momentum Mod only sends whether a player fired a weapon, it does not check if they should be able to fire that weapon, meaning you're able to jump in a lobby at `host_framerate 1` and fire off a bunch of rockets for example. To your perspective the rockets fire as normal, reaching the wall very fast, for anyone else however, it's simply creating the ghost rocket event with them spawning as normal at the regular speed and spamming the lobby with a bunch of projectiles, lagging and possibly crashing them if done fast enough.

### How To Reproduce

1. Join a lobby and be with someone in the same map.
2. Set `sv_cheats 1` and `host_framerate` to `1` or lower, while the other is normal.
3. Fire any kind of weapon, most effectively projectiles.

### Expected Behavior

There should be a check in place preventing you from receiving/using certain packets information if the normal time for that weapons fire-rate has not gone by.

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
Seems to be fixed, players don't see me shooting any rockets at all when using `host_framerate 1`
