### ISSUE TITLE
Momentum Pistol Single Shot Should Behave Like the USP from CS:S

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1627]
As per aimer from their stream, the USP is typically the go-to single shot pistol for most bhop maps. The glock is typically *only* used for its burst. Because we have the ability to, we should make the pistol behave like the USP when in single shot mode, and behave like the glock in burst fire mode, all using the same model.

**Comment by hexaflexahexagon** [comment]
seems to be implemented according to the #general-bhop folks (this is the right tab this time)
