### ISSUE TITLE
Add detailed information about jump (gain percentage, efficiency percentage) and strafe trainer bar 

### ISSUE THREAD

**Issue by Xosebelge** [momentum-mod/game#1629]
### Is your feature request related to a problem?

While bhopping your jump strafe can be defined by three values: sync (how accurate you are pressing a-d and moving mouse left/right), gain (how many speed you earn via strafe), efficiency (how far do you jump).
Presently, we have tracker only for sync. And you can not implement bars for gain/efficiency via panorama scripts, because you lack information about player view angle.

### Describe the solution you'd like

UI part:
- Add new subsection in settings (Detailed strafe info) with next switches: 
  - Show sync percent 
  - Show gain percent
  - Show efficiency percent
  - Enable strafe trainer bar 
- Add new hud or change the speedometr to track sync/gain/efficiency for last jump (MomentumPlayerAPI.GetLastJumpStats)
- Add another hud for strafe trainer (bar, which is updating every tick and calculating moving average of (player view angle delta)/(perfect angle). It should track values from 0 to 200 (or maybe more, where values >200 should be clipped as well as negative ones). 100% is the perfect angle and it should be at the center of bar.  (moving average across 10 ticks should be enough)

Technical details:
- Every tick we should calculate strafe gain and perfect strafe gain.
How to calculate:

![Strafe calculation](https://i.ibb.co/Z6R9g2m/strafe.png)
On picture:
- v - current velocity vector
- u - Current_gain * WishDir
- f - final velocity vector
- _a_ - angle between Velocity and WishDir

You can skip next paragraph with math and read further, but it not that hard :-)
Current_gain = max(0, sv_air_max_wishspeed - dot_product (CurrentSpeed, WishDir))
Using Law of cosines: 
f = sqrt(v\*v + u\*u - 2\*v\*u\*cos(pi-_a_)) = 
sqrt(v\*v + max(sv_air_max_wishspeed - v\*cos(_a_), 0)^2 + 2\*v\*max(sv_air_max_wishspeed - v\* cos(_a_), 0)\*cos(_a_)) = 
{sv_air_max_wishspeed - v\*cos(_a_) > 0, otherwise gain is 0} =
sqrt(v\*v +v\*v\*cos(_a_)^2 + sv_air_max_wishspeed^2 - 2\*sv_air_max_wishspeed\*v\*cos(_a_) + 2\*v\*sv_air_max_wishspeed\*cos(_a_) - 2\*v\*v\*cos(_a_)^2) =
sqrt(sv_air_max_wishspeed^2 +v\*v\*(1 - cos(_a_)^2)) =
sqrt(sv_air_max_wishspeed^2 +v\*v\*sin(_a_)^2)

As we can see to get maximum final velocity we need 90 degrees between v and u. Note, that in original movement code u is min(Current_gain, accelerate_speed), where accelerate_speed = (1/tickrate)\*|v|\*sv_airaccelerate, but with default parameters( sv_air_max_wishspeed = 30, sv_airaccelerate = 1000, tickrate=128)  accelerate_speed is always > Current_gain, when speed>3.84, so we can ignore this. But on some kz maps with sv_airaccelerate will not be 90.
For kz: u = min(Current_gain \* WishDir, accelerate_speed)

So to get optimal angle to move your mouse we need simply to solve next equation:
tan (Optimal rotation angle) = sv_air_max_wishspeed/v  =>
Optimal rotation angle = atan(sv_air_max_wishspeed/v)

Now to get gain percentage we can calculate ratio of ViewAngle delta / Optimal rotation angle,

Efficiency can be defined as (Euclidian distance between 2 landing points) / Distance travelled (aka f\*(1/tickrate)).  ( Do not forget to clip it to 1 as maximum to avoid problems with portals)

Also strafe sync can be redefined as percentage of ticks, where Current_gain > 0.

To get final numbers for Gain and Efficiency it should be multiplied by strafe sync,

### Describe alternatives you've considered, if any.

It is possible to implement those statistics in panorama ui via js, but player view angle is still needed and it is better to have all this calculation in C++ code.

**Comment by Gocnak** [comment]
@tsa96 this might be relevant to the card you've been wanting to make -- just FYI.

**Comment by tsa96** [comment]
Huh, was looking for an issue like this and couldn't find one.

A lot of this could be done in Panorama (and the slow stuff ported to C++ if necessary). We'd definitely need an `OnJump` event, and some additions to the API. appa, spicy and tekno have all expressed some interest in working on stuff so let's see how they get along.
