### ISSUE TITLE
trigger_momentum_limitmovement breaks with filternames

### ISSUE THREAD

**Issue by RoadyBhop** [momentum-mod/game#1630]
### Describe the bug

trigger_momentum_limitmovement breaks when using a filtername for activating it. it works for starting the limitmovement but when the players targetname is changed the movement limitation stays when inside or outside the trigger.

### How To Reproduce

create a trigger_momentum_limitmovement and have 2 filter_activator_name entites, one of them default and one that is used for the limitmovement trigger, the filter can be activated on the player with sv_cheats 1 and using ent_fire player addoutput "targetname x", when in the limitmovement trigger change back to the default filtername and the limitmovement stays. 

### Expected Behavior

when the players filtername changes to be different then the one required by the limitmovement trigger they should go back to normal (aka no limitations on movement)

### Operating System

windows

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
still broken according to roady

**Comment by hexaflexahexagon** [comment]
to add some more info I made a test map, best experienced with `mom_hud_keypress_enable 1`: https://cdn.discordapp.com/attachments/671175695648423959/974929068233486396/limitmovement_filter.bsp

the filter on the limitmovement trigger is set to allow entities with targetname "joe". to replicate the bug:
1. stand in the trigger. notice you are unaffected
2. `ent_fire player addoutput "targetname notjoe"` - notice nothing happens
3. walk outside of the trigger and then `ent_fire player addoutput "targetname joe"` - you now cannot jump/crouch when inside of the trigger which is desired behavior. walk out of the trigger and you can jump, walk back in and you cannot jump. etc
4. reset your targetname
5. stand inside of the trigger and set your targetname to joe. now walk out of the trigger and you are constantly unable to jump! even though you're outside of the trigger. you must walk into and out of the trigger again (WHILE your targetname is still joe) to go back to having normal movement outside of the trigger

**Comment by granis48** [comment]
gonna add that to test this you need to launch the game in mapping mode and enable sv_cheats 1. 
I tested the provided limitmovement_filter.bsp and changed my targetname back and forth both inside and outside the trigger and was not able to reproduce the issue. Every case worked as expected
