### ISSUE TITLE
Make the `Quit game` keybind always pop a confirmation menu; Remove the `quitting the game` safeguard

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1637]
### What feature is your improvement idea related to?

This is generally nicer UX since for the most part people are always going to want a confirmation when quitting using a hotkey on the keyboard (not only when in a run like the safeguard enables). In total:

1. Make a new command called `quit_confirm` or something that opens the same menu that hitting the top-right power button does, regardless of when it was called (like from a keybind)
2. Make the "Quit game" keybind setting bind to that command instead of plain `quit`
2a. Optionally, consider adding both `quit` and `quit_confirm` to the keybind menu with a string that properly differentiates them. Would be nice for power users who don't want the menu but this is always an option through console anyways so w/e
3. Remove the "Quitting the game" safeguard completely.

Making a new command instead of modifying `quit` allows powerusers to do what they want but still keeps more friendly default behavior for the 99% of people who want it.

### Describe the solution you'd like

do above

### Additional context

Unrelated, I thought the `quit_prompt` command did \#1 above but if it's meant to then it's completely busted, see https://github.com/momentum-mod/game/issues/1636

**Comment by Gocnak** [comment]
From discord, my reply:
![image](https://user-images.githubusercontent.com/5162166/148514032-e78cdee6-bc3b-414f-bb04-e50070167623.png)

**Comment by Shegetz** [comment]
Trying to quit with quit bind doesn't bring up the prompt in game, the prompt goes to the main menu and doesn't bring you there. You have to manually hit escape and go to it, which feels like it kind of defeats the purpose of trying to get out quickly

**Comment by braem** [comment]
> Trying to quit with quit bind doesn't bring up the prompt in game, it goes to the main menu which you have to hit escape to get to, which feels like it kind of defeats the purpose of trying to get out quickly

it should be pausing the game when you hit the bind - popups cannot occur in-game, only in a pause menu or main menu

**Comment by braem** [comment]
Needs testing. This has been working for me on dev and steam since I implemented it a few months back.

**Comment by hexaflexahexagon** [comment]
confirmed
