### ISSUE TITLE
Spamming `mom_spectate` and `mom_spectate_stop` gives extra height

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1644]
### Describe the bug

See video by Tunific who reported this: https://www.youtube.com/watch?v=sfa-UPDd55c

### How To Reproduce

1. `bind mwheelup "mom_spectate; mom_spectate_stop`
2. `bind mwheeldown "mom_spectate; mom_spectate_stop`
3. Jump or be knocked upwards by an explosion
4. Hold duck (important)
5. Spam the bind

### Expected Behavior

Nothing abnormal

### Operating System

win10

### Renderer

DX11 (default)

**Comment by braem** [comment]
Might be to do with the new duck fixes put in place? (@jason-e )

**Comment by jason-e** [comment]
It's unrelated to ducking. I haven't looked into it enough yet to know exactly why it's happening, but I do know that using savelocs for entering/leaving practice mode fixes the problem, which is something I was looking at switching over anyway (#1623). Currently practice mode uses it's own rudimentary state/saving and loading, so it will be good to switch to the more robust saveloc stuff.

**Comment by xen-000** [comment]
This seems to have been fixed somehow during the movement refactor.
