### ISSUE TITLE
Update weapons on mom_player_weapon_spawn_desirability change immediately

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1646]
### What feature is your improvement idea related to?

Currently changing whether you have a glock/knife etc on spawn is a pain. Adding the cvar to settings (https://github.com/momentum-mod/game/issues/1645) will help, but you shouldn't have to reload/respawn for the change to take effect.

### Describe the solution you'd like

Add a listener (or whatever you call it in C++ land for when the setting changes, and add or remove the weapons corresponding to each option accordingly.

**Comment by hexaflexahexagon** [comment]
Seems to work
