### ISSUE TITLE
Toggling drawing entities crashes the game

### ISSUE THREAD

**Issue by jokimty** [momentum-mod/game#1647]
### Describe the bug

Title. When toggling drawing entities through the map commands menu the game instantly crashes, 100% of the time.

### How To Reproduce

1. Open a map (I only tried 5)
2. Turn on the "Map Commands Menu" (unbound by default)
3. Use "Toggle Drawing Entities" (bound to "7" by default)

### Expected Behavior

Well, I want to turn on drawing entities.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
doesn't seem to crash, though I never replicated this before the patch

**Comment by jokimty** [comment]
It also got fixed for me after yesterdays (17th) patch.
