### ISSUE TITLE
surf_bullet / jump_finite_v2 crash/performance hit

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#1648]
### Describe the bug

`surf_bullet` and `jump_finite_v2` either crash or see a massive performance hit on load.
This has to do with vphysics, specifically relating to ragdolls.

### How To Reproduce

1. Load `surf_bullet` or `jump_finite_v2`
2. See first assert for details
3. Good luck

### Expected Behavior

Maps should be able to load and play fine with ragdolls.

### Operating System

Windows 11

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
`jump_finite_v2` seems to play fine for me
