### ISSUE TITLE
Add local map tab for unofficial, locally downloaded BSPs

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1649]
### Is your feature request related to a problem?

This is something that's been heavily requested and debated, this card just exists to track the idea. We may or may not want to actually do it.

### Describe the solution you'd like

Add a tab to the map selector for 'local' maps, ones that are not downloaded from the website but rather read directly from the `momentum/maps` folder (as well as mounted games). While we cannot show certain metadata like authors, screenshots, etc, we can still show some. This being:
- Last played
- Is / Is not an official map (or we can just remove all official maps from the listing by default, nobody should be playing official maps through this tab anyways)
- Last modified(? to show when something was copied? idk could be useful. at least a sort option)
- Does / does not have zones
- Local PR
- What game it is from, if possible. e.g. `momentum/maps, tf/maps, css/maps` etc

### Describe alternatives you've considered, if any.

we could not add this as an alternative

### Additional context

requested by everybody and their mother

**Comment by Gocnak** [comment]
As we add more and more official maps this becomes a glorified `map` command, used by less and less people. Too much effort for very little gain over the short term. Adding this would also make it look like we "officially" support "unofficial" maps (🤔), which would be empty UX for the majority of players.

Going to close this, I'd rather focus on the zoning tools and getting as many maps officially on the selector as possible instead.
