### ISSUE TITLE
Add some sort of confirmation when making speedometer changes

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1651]
Many people miss the save button when making changes, we should do something about that. Potential solutions:
1. Add a pop-up when you make changes and don't save them before exiting the menu
2. Make the save button more obvious somehow 
3. Do away with the save button altogether and automatically save after making changes or closing the menu or something

**Comment by hexaflexahexagon** [comment]
Just had to fight with github mobile and try 3 times to add that feature label because apparently there's a save button you need to hit, else it does nothing and throws away your changes... deja vu

**Comment by braem** [comment]
Made this save on close now but forgot to link issue
