### ISSUE TITLE
DX11: Flashlight causes weird view angle

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1654]
### Describe the bug

Using the flashlight on dx11 does a funny, video by Dwemer who reported this is below. Does not happen on dx9

https://user-images.githubusercontent.com/5162166/148503404-e051a116-b332-41a2-9573-2574b44a2888.mp4

### How To Reproduce

1. Load rj_vex
2. Go to jump 16
3. Use flashlight

### Expected Behavior

Flashlight works normally

### Operating System

Win10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Does this still happen on the latest build?

**Comment by hexaflexahexagon** [comment]
nope
