### ISSUE TITLE
DX11: Water on surf_pantheon is off

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1658]
### Describe the bug

Reported from XBmann:

"water and reflections on dx11 are still looking pretty fucky"

![image](https://user-images.githubusercontent.com/5162166/149086621-24f6b548-37d5-45e9-a68d-c5be3c7d268c.png)
![image](https://user-images.githubusercontent.com/5162166/149086638-864e8706-c0d9-4666-b4ba-b10bd67dd442.png)

https://user-images.githubusercontent.com/5162166/149086663-84940dfc-7c5f-4072-9858-c86a1aeb1c3c.mp4

### How To Reproduce

1. Open surf_pantheon in DX11
2. Look at water in start area ramps

### Expected Behavior

Water should not be glitching out

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by Shegetz** [comment]
Black squares in Image2 and the video still persisting

**Comment by SlidyBat** [comment]
I added the needs testing label a little early, since this didn't actually make it into the update at the time. The fix should actually be in now though.
