### ISSUE TITLE
API authenticating fails

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1660]
### Describe the bug

![image](https://user-images.githubusercontent.com/62961532/149671372-80d2bf00-ba12-45ee-b470-30431e2b87a0.png)
Probably related to recent S3 shenanigans, I believe I heard gocnak talking about this at one point so it's likely already known but documenting it just for posterity.

Reported by nick_n

### How To Reproduce

1. Open game
2. Fail to authenticate

### Expected Behavior

win

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
S3 and overall game auth aren't related. This sorta looks like steam was down or something for this user? Could be worth seeing if they can log in via the site.

**Comment by hexaflexahexagon** [comment]
from the user:
"update on this:
 - i can log in through the momentum mod website and edit my profile and do normal things
 - mom_api_url_auth and mom_api_url_base are set to their normal values
 - privacy settings are set to public on my steam account, account is not limited, i have been able to auth in mmod in the past
 - reinstalling mmod/deleting my cfg does nothing :-("

**Comment by hexaflexahexagon** [comment]
nvm they found a cvar set wrong, everything works as intended now.
