### ISSUE TITLE
`sj_zero` crash

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1661]
### Describe the bug

Loading sj_zero will crash after walking forwards slightly. I wasn't able to reproduce this so it may be a specific setting that causes it, tbd.

https://user-images.githubusercontent.com/5162166/151934829-a7df700d-193b-475f-9a47-ea68da3cc72b.mp4

Reported by Rhythmations for Polexit

### How To Reproduce

1. Load sj_zero
2. walk forward in the start zone a little bit
3. Crash

### Expected Behavior

no crash

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Verified fix by submitter
