### ISSUE TITLE
Running zonmaker with a BSP completely locks up my system

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1664]
### Describe the bug

Trying to pass a BSP to zonmaker has it start reading it, but after a while my machine will go entirely unresponsive

### How To Reproduce

1. Open a command prompt window at `Momentum Mod\bin\win64\`
2. Pass `zonmaker.exe <BSP of your choice>`
3. Zonmaker should start reading and will crash your computer soon afterwards

### Expected Behavior

A check for a valid file type should be placed to avoid these issues. Zonmaker shouldn't cause a lock-up like this in any case

### Operating System

Windows 10 21H2

### Renderer

DX9 (Legacy)

**Comment by VortexParadox** [comment]
I know this is user-error, but a little check for a valid type would be nice, as well as a more concise error message when passing a file, e.g.: `Usage: zonmaker.exe <VMF file>` instead of the current `zonmaker.exe <input file>`

**Comment by hexaflexahexagon** [comment]
seems to be resolved:
```
PS C:\SteamLibrary\steamapps\common\Momentum Mod\bin\win64> .\zonmaker.exe ..\..\momentum\maps\sj_amazon.bsp
Reading..
Couldn't parse any zone information from VMF!
PS C:\SteamLibrary\steamapps\common\Momentum Mod\bin\win64>
```
