### ISSUE TITLE
Panorama: Color picker colors that have 0 alpha are "hidden" from the player

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#1666]
### Describe the bug

Setting any color to 0 alpha makes the settings color box completely invisible, leading to bad UX for those that may have accidentally gotten there.

![image](https://user-images.githubusercontent.com/5162166/149900445-6b9cc8cf-f1ac-4eec-8f2a-01c0741ea0a2.png)

### How To Reproduce

1. Open settings
2. Go to any setting with color
3. Change it to have 0 alpha
4. Notice the color box is now invisible and completely unfriendly to any new player that may have accidentally set this

### Expected Behavior

Two things I can think of:
1. Quick and easy: Add a border to the color box to make it clear it's supposed to be a button
2. Harder: Make the color box have the checkerboard background that "translucent" content has typically

### Operating System

Any

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
![image](https://user-images.githubusercontent.com/62961532/151666432-0325764e-a802-45bb-abd6-2b451615b4cc.png)
fixed
