### ISSUE TITLE
All maps have invalid textures when playing

### ISSUE THREAD

**Issue by rojuu** [momentum-mod/game#1668]
### Describe the bug

All maps seem to have invalid textures. All the textures are just displayed as pink/black grids. This is on a fresh install of Momentum Mod, tried with both the default backend and the legacy DX9 backend.

Screenshot of what it looks like:
![Screenshot](https://user-images.githubusercontent.com/15312785/150749553-828137b4-1a57-453d-9bc6-84574b95c3db.png)

### How To Reproduce

1. Open a fresh install of Momentum Mod
2. Download a map
3. Press play

### Expected Behavior

When I load into a map, I should see the maps textures.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by rojuu** [comment]
I'm happy to help in any way to fix this issue

**Comment by Gocnak** [comment]
The game will be updated in the future to say which games the maps mount content from. (see #682) 

In this case, `surf_utopia` relies on Team Fortress 2 textures. We recommend installing TF2, CS:S, and CS:GO to support every possible map Momentum will have.

If that is not an option, you may look into using the `mat_error_texture_replace_advanced 2` command to replace the textures with the colors used on the brush data.

I will be closing this issue as this is not particularly a game problem, but please do not hesitate to report more bugs via here, GitHub is the best way to track stuff for us!
