### ISSUE TITLE
Sidebar covers menu items when 4:3 resolutions are used

### ISSUE THREAD

**Issue by henrym11106** [momentum-mod/game#1669]
### Describe the bug

tested at various resolutions; sidebar covers things in the main menu, options and map selection screens when any 4:3 ratio res is in use. windowed and fullscreen.
![Screenshot 2022-01-28 22-40-38](https://user-images.githubusercontent.com/20314143/151650760-df73f90f-a30f-4d92-a40e-a9d466e9c15a.png)
![Screenshot 2022-01-27 19-00-45](https://user-images.githubusercontent.com/20314143/151650764-ea787d8a-b044-4b9d-bfef-3af20c6b8329.png)
![Screenshot 2022-01-27 19-01-55](https://user-images.githubusercontent.com/20314143/151650767-c123d5e6-501f-4168-81fa-b6032725c98e.png)
![Screenshot 2022-01-28 22-45-27](https://user-images.githubusercontent.com/20314143/151650809-5280b452-2929-4826-b1f9-c6e9e933e60d.png)

### How To Reproduce

Launch with any 4:3 res

### Expected Behavior

Menu items should not be obstructed

### Operating System

Linux

### Renderer

DX11 (default)

**Comment by henrym11106** [comment]
This appears to be mostly fixed with the latest release, everything works on 4:3 except for one minor issue: while watching replays the exit button is pushed offscreen, especially at lower resolutions. this is also effected by the length of the label shown on the view mode button.
![Screenshot 2022-11-28 22-45-51](https://user-images.githubusercontent.com/20314143/204459810-6c9aa520-52d4-48b2-855e-512bb386ecbc.png)
![Screenshot 2022-11-28 22-44-23](https://user-images.githubusercontent.com/20314143/204459812-491c4282-ae20-47c6-a27a-c49ea05b6671.png)
![Screenshot 2022-11-28 22-34-37](https://user-images.githubusercontent.com/20314143/204459862-9d47ec0d-ddbb-441f-8e35-fc955342aa67.png)

**Comment by tsa96** [comment]
Could do a simple fix for this now, but the spec panel really needs more general styling work, I'll probably do after 0.10.0

**Comment by Gocnak** [comment]
Closing this card as completed then, will tackle the new spec overlap near 0.10.0.
