### ISSUE TITLE
Momentum Hammer not rendering some maps

### ISSUE THREAD

**Issue by Jake-Coding** [momentum-mod/game#1672]
### Describe the bug

momentum hammer will open and compile, but not render some vmfs. I suspect this is due to something with momentum's hammer parsing using indents? cause that should be the only thing changed. The files open just fine in tf2's hammer. I don't have access to csgo's hammer to check if it works there.

Unfortunately gh won't let me attach a vmf, so it is saved as a .txt. just rename it to a vmf :
[rj_catapult_test_momentum.txt](https://github.com/momentum-mod/game/files/7967054/rj_catapult_test_momentum.txt)
)

### How To Reproduce

1. Open hammer.exe from Momentum Mod Playtest/bin/win64
2. File -> Open
3. Select the rj_catapult_test_momentum.vmf
4. The skybox should load, as should the origin. All grids are blank, as is the 3d view. 
5. Compile with f9
6. It works in game
7. Attempt to open using the hammer from Team Fortress 2/bin
8. It works

### Expected Behavior

Momentum's hammer should render any valid .vmf file

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Jake-Coding** [comment]
Compiling in momentum hammer doesn't work sorry. thought it did.

**Comment by Jake-Coding** [comment]
oh no it worked again. good luck figuring this out

**Comment by hexaflexahexagon** [comment]
i remember an issue about this but it looks like it's probably unrelated. https://github.com/ChaosInitiative/Chaos-Source/issues/262

**Comment by Jake-Coding** [comment]
its unrelated. I've had that issue before, but this time the grids all show up, it just doesn't recognize any entities as existing in them

**Comment by Jake-Coding** [comment]
this is what happens if you don't have a cordons in your vmf. i am a moron.
