### ISSUE TITLE
When Alt-tabbed viewmodel and projectile textures glitch out

### ISSUE THREAD

**Issue by Gnawmon** [momentum-mod/game#1674]
### Describe the bug

https://user-images.githubusercontent.com/99086327/152649379-d2937620-1bea-4414-8b00-d8d24ba6f0d8.mp4

If needed I can provide more information.

### How To Reproduce

1. Open a map
2. Alt-tab
3. Alt-tab again

### Expected Behavior

When alt-tabbed textures should glitch out.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gnawmon** [comment]
It's known

**Comment by lvaness** [comment]
It's fine, this issue wasn't tracked yet on Github so it can be kept
