### ISSUE TITLE
+strafe ignores limit movement trigger

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1675]
### Describe the bug

title. see video by Mr Burguers who reported this:
https://cdn.discordapp.com/attachments/235125108656701440/939530844123590696/2022-02-05_14-38-44.mp4

### How To Reproduce

1. load triggertests
2. +strafe
3. bwah

### Expected Behavior

Either:
1. we make limitmovement limit "angles" somehow, i.e. if it blocks +forward then you can use +strafe but just can't go forwards, or something? 
2. remove +strafe globally because it's jank and shitty and dumb
3. some other smart solution

### Operating System

win10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Solution: Remove +strafe

**Comment by chovelyoukai** [comment]
We shouldn't really remove +strafe but I can look into making limitmovement only accept inputs aligned to the directions that it allows.

**Comment by jason-e** [comment]
Is +strafe a thing in defrag? It will probably not be allowed on most modes.

**Comment by hexaflexahexagon** [comment]
it is used commonly to line up overbounces to my knowledge because you need exactly 0 hvel to get the height. imo if it's going to be allowed anywhere it might as well be allowed everywhere unless there's a specific reason for it not to be. in jump for example there's really no way to abuse it

**Comment by chovelyoukai** [comment]
Agree with hex. unless there is a good reason to remove it, it should stay. And yes it must be in defrag.

**Comment by jason-e** [comment]
Well there's all the stuff mentioned in #1563 for starters. There's also been a lot of talk about it for ahop in Discord and I thought it's already been long decided that it won't be allowed there. Beyond that, it muddies the waters when it comes to detecting strafe optimizer cheats, so it will probably need to be blocked on bhop as well at the very least.

**Comment by chovelyoukai** [comment]
The only new thing that issue brings up is that it's useful  in SJ, and that we'd need a UI element for it. Removing it from ahop is already well established but what's good in ahop doesn't have anything to do with what's good in any other mode. If you add bhop, and even sj, that still leaves 7 modes where it's either benign or objectively useful (defrag).

**Comment by jason-e** [comment]
Well the main point of that other issue is it makes it easier to precisely slow down, which applies to most if not all modes I would think, and for any modes where it's not already "the meta" we should consider removing it entirely (especially since it makes anticheat easier to do in some cases). For defrag and any other mode where it happens to already be a big thing, keeping it is fine.

**Comment by Gocnak** [comment]
This should now be accounted for in the latest update, pending more +strafe work in the future.
