### ISSUE TITLE
console spam with "missing skybox texture" on a map without it

### ISSUE THREAD

**Issue by plarr** [momentum-mod/game#1677]
### Describe the bug

going on a specific map that has no skybox after playing any map that has skybox causes console spam with "error loading vmt file for skybox/..." and low fps
https://www.youtube.com/watch?v=nqCnRva5sNE

### How To Reproduce

1. open any map that has skybox
2. open specific map taht has no skybox
3. see low fps and console spam

### Expected Behavior

game shouldn't try to look for skybox from previous map

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
Caused by the `sv_skyname` cvar not being reset across maps. I've changed that, so `sv_skyname` will revert back to the default value when a map is loaded.
