### ISSUE TITLE
Expose Movement Data Required for Cgaz and SnapHUD to Panorama

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1678]
### Is your feature request related to a problem?

Cgaz and snaps are core parts of defrag and the sooner we get the UI in the better, especially as snap zones should help test defrag a lot.

### Describe the solution you'd like

Getting the Panorama API to expose the following will allow others to work on it. Got someone keen on helping requesting the following vars:

  **critical**:
  - max speed
  - max acceleration
  - velocity
  - view direction
  - input
  - FOV
  - viewport dims
  - delta time/physics tick

**wishlist**:
- max air speed
- max air accel
- physics mode (qw/vq3/cpm/etc)

I'll then get them up to speed with Panorama JS and help them out where possible

**Comment by braem** [comment]
Already have velocity in MomentumPlayerAPI.

For input, we should touch the keypress hud - make it pure JS even.

A lot of these are cvars which can get from gameinterface, but is better to get them from an API to not be doing lookups

**Comment by tsa96** [comment]
We'll need to be running some stuff every frame bit obvs don't want to be querying FOV that often, not sure how best to account for people changing it mid run, can't think of a good event to use to recheck that value.

Handling input like that sounds great yeah, also custom hud makers will love us for that. View dir can just be momplayerAPI I guess.

Thanks brae!!

**Comment by TEKN1SHUN** [comment]
Instead of asking for max speed and max accel, could the movement API expose a player walking/falling state and haste state?

**Comment by braem** [comment]
> Instead of asking for max speed and max accel, could the movement API expose a player walking/falling state and haste state?

Definitely yup! Can get this in after the big movement refactor gets merged.
