### ISSUE TITLE
env_cascade_light breaks lighting of map compiles

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1679]
### Describe the bug

If an **env_cascade_light** is placed into a map, regardless of it being enabled or not, and then compiled with the map, areas seem to become hyper-dark in spots across the map.

Example VMF you can compile (Includes compiled BSP): 
[cascade_light_test.zip](https://github.com/momentum-mod/game/files/8036229/cascade_light_test.zip)

![image](https://user-images.githubusercontent.com/62808028/153289497-018a58f5-1ea3-404f-ab8d-5728a15933f5.png)

Extreme example of what can happen:

![image](https://user-images.githubusercontent.com/62808028/153287397-d627bf0b-9ffc-48ba-b5b0-d3008ce106e1.png)

### How To Reproduce

1. Open Hammer with a basic map that can compile.
2. Have a light of some kind exist in the map.
3. Add the **env_cascade_light** entity to the map anywhere.
4. Compile in any way with lighting.

### Expected Behavior

Lighting shouldn't do this.

### Operating System

Windows

### Renderer

DX11 and DX9

**Comment by SlidyBat** [comment]
This was a regression from when portal traversal was added to VRAD. Should be fixed in next update.

**Comment by hexaflexahexagon** [comment]
compiling the included map seems to work, closing
