### ISSUE TITLE
env_tonemap_controller keeps settings switching to new maps without one

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1680]
### Describe the bug

Settings changed with **env_tonemap_controller** such as **SetBloomScale** do not get reset if switching to maps that do not contain an **env_tonemap_controller**

Normal map default settings, no **env_tonemap_controller**:
![image](https://user-images.githubusercontent.com/62808028/153449662-0cb9d873-f788-49f0-83a2-588ba1f10004.png)

Switching to map that does have **env_tonemap_controller** and coming back:
![image](https://user-images.githubusercontent.com/62808028/153449820-0a2a178c-816f-4315-9ca2-cc92448010d1.png)

### How To Reproduce

1. Have two maps with lighting, one with **env_tonemap_controller** and modified settings, and one without **env_tonemap_controller**.
2. Load the map with an **env_tonemap_controller** that has modified settings.
3. Switch to the map that does not have an **env_tonemap_controller** entity, it now has the same tonemap settings.

### Expected Behavior

Default tonemap settings should exist and not keep between maps.

### Operating System

Windows

### Renderer

DX11 and DX9

**Comment by hexaflexahexagon** [comment]
confirmed working, testable via these two maps: https://cdn.discordapp.com/attachments/671175695648423959/974925091412541470/env_tonemap_maps.zip

1 = no tonemap present
2 = tonemap w/ extreme bloom scale present
