### ISSUE TITLE
Default "author" line to off when no author is specified

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1681]
### What feature is your improvement idea related to?

See image below:
![image](https://user-images.githubusercontent.com/62961532/153733109-79158b9b-ed3f-4ae8-9d58-856930b2e045.png)

This author line probably shouldn't be showing up on any unofficial maps where it doesn't get fed real data.

### Describe the solution you'd like

When on an unofficial map, there's no reason to display an "author" line here.

**Comment by Gocnak** [comment]
Was this done already on green? @braem

**Comment by braem** [comment]
> Was this done already on green? @braem

Yup!
