### ISSUE TITLE
add command to hide all models/brushes with no collision

### ISSUE THREAD

**Issue by RoadyBhop** [momentum-mod/game#1683]
### What feature is your improvement idea related to?

it can be annoying to tell when something is solid or non solid in a map and it would be nice to have a simple command that works for all types of objects (models/brush/displacements/anything else) in the game to tell the difference.

### Describe the solution you'd like

a command that will hide anything that is not solid or does not cause some interaction with the player (triggers) from view.

### Describe alternatives you've considered, if any.

if not one command it could be split between the different types. models already have a nice command vcollide_wireframe which can show the difference between solid and non solid with the color of the wireframe but is a cheat protected command :(. If this is so they could be added as chat commands so they are written in a way that is easier to find.

**Comment by hexaflexahexagon** [comment]
:^) sniped by 30 minutes https://github.com/ChaosInitiative/Chaos-Source/issues/349

**Comment by hexaflexahexagon** [comment]
(github mobile sucks so i'm only able to close this now)
