### ISSUE TITLE
surf_utopia missing textures

### ISSUE THREAD

**Issue by thephoenix107** [momentum-mod/game#1685]
### Describe the bug

The map surf_utopia is missing all textures.

![20220216113341_1](https://user-images.githubusercontent.com/43836455/154247083-c5583657-4c9e-4be5-beaf-b5c9ec7908db.jpg)

Changing the renderer makes no difference.

### How To Reproduce

Just download and open the map.

### Expected Behavior

Textures should not be missing.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
this is happening because tf2 isn't installed so it is intended behavior. we're going to try and make this better (like by warning you before loading the map that you're missing x game that the map needs) but for now the solution is to either install tf2 or use `mat_error_texture_advanced 2`
