### ISSUE TITLE
Game Crash on Flashlight Use 

### ISSUE THREAD

**Issue by decl0s** [momentum-mod/game#1688]
### Describe the bug

This crash seems to be independant from the renderer - it happens both in DX9 & DX11.

Trying to enable the player's flashlight closes (crashes) the game immediately. Sometimes the game does not crash while enabling the flashlight while in practice mode for some reason, exiting practice mode after a successful flashlight enabling will still crash the game.

### How To Reproduce

1. Open Momentum Mod (either DX11 or DX9)
2. Load up **bhop_parallel**
3. Press the bind to open the flashlight.

### Expected Behavior

The game should open the player's flashlight, lighting up world geometry in it's cone of vision and should not crash the game.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
map download: https://cdn.discordapp.com/attachments/569893896545632317/944435727846998026/bhop_parallel_V1.zip 

we also had a similar thing on sj_koi but apparently that was closed. https://github.com/momentum-mod/game/issues/1593

**Comment by Gocnak** [comment]
Does this still happen on latest?

**Comment by Gocnak** [comment]
Confirmed fixed by Traz
