### ISSUE TITLE
Playtest settings not saving / are being affected by base game settings

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1689]
### Describe the bug

Some settings within the playtest version of the game don't save, seemingly caused by also having the base game installed. Affected settings are ones like volume or binds created through console. If you change settings on the base game they will be affected on the playtest version, but not necessarily 1:1
ex: setting my base game volume to 43% made it 11% on playtest, where it was previously 0%.
uninstalling the base game does not fix the issue, the settings will still revert on playtest.

### How To Reproduce

1. Have playtest installed
2. install the base game
3. change settings on the base game
4. observe they've affected the playtest version

Alternatively

1. Have playtest installed
2. install the base game
3. change settings on playtest
4. restart and observe they haven't been saved

### Expected Behavior

Settings on playtest should save / be independent of the base game

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Does this still happen anymore? We've had countless fixes done to it.

**Comment by Gocnak** [comment]
According to Tom this is all sorted now
