### ISSUE TITLE
filter_player_state improvements

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/game#1690]
### What feature is your improvement idea related to?

The filter is pretty limited currently, with only bhopping, surfing or grounded.

### Describe the solution you'd like

Add an explosive jumping state, and maybe some other niche use cases that I can't think of.

**Comment by Panzerhandschuh** [comment]
@Mac-tf2 `filter_momentum_player_state` has been replaced with `filter_momentum_surface_collision`. Do we still need a player state filter for things like bhopping, rocket jumping, etc.? If so, can you come up with a specific use case for this filter?

**Comment by Mac-tf2** [comment]
This was originally for learn section to make it easier to tell when a player was doing certain mechanics. AFAIK we're going in a different direction with learn now so this isn't needed for that anymore.
