### ISSUE TITLE
Console autocomplete and enter don't play nicely

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1692]
### Describe the bug

`If you tab to autocomplete something, pressing enter will make it use that new string and execute the next autocomplete item` from Osplo

### How To Reproduce

ex. typing `q` in console and pressing tab will put `quit` in the text box, then pressing enter executes `demo_quitafterplayback`

### Expected Behavior

Enter should submit the typed command

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by braem** [comment]
Fixing by removing the recently added enter submission behaviour
