### ISSUE TITLE
func_precipitation renders precipitation at world center

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1695]
### Describe the bug

func_precipitation appears to render a precipitation at world center, however it also still works where it's placed in the map.

https://user-images.githubusercontent.com/62808028/155062584-b234d6a5-9ad1-4384-82cb-41b7eef7aa5b.mp4

### How To Reproduce

1. Have a func_precipitation in a map.
2. Go to 0 0 0 (world center point)

### Expected Behavior

don't render anything here if there is no trigger here for it to render

### Operating System

Windows

### Renderer

DX11 (default) and DX9

**Comment by braem** [comment]
Worth noting that the rain there is insanely dense - on debug build i get like 0.1 fps in the general area

Turning off rain `r_RainSimulate 0` lets you see the particles and oh my lord 
![image](https://user-images.githubusercontent.com/9014762/155075959-ad26020b-a1fd-402f-a975-0543148648ae.png)

Where in god's name is it coming from LOL
![image](https://user-images.githubusercontent.com/9014762/155076141-5f82ea6c-2543-4caf-9e4e-429c27167bd1.png)

**Comment by Ninja-Cookie** [comment]
![image](https://user-images.githubusercontent.com/62808028/155212678-9a0a6d1a-9382-406e-971c-f62ca3525ee4.png)

It's an issue in CS:GO also, lol

**Comment by braem** [comment]
Found this was occurring for `func_smokevolume` as well, for the same reasons. It has to do with now having an `origin` kv for these entities in the FGD.

New internal change should fix this.
