### ISSUE TITLE
Add Panorama API for version info, update versioninfo component

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1696]
### What feature is your improvement idea related to?

<MomHudVersionInfo> currently gets it value set directly from C++. This is very rigid, and we need to access this info from other places as well,

### Describe the solution you'd like

Create a Panorama API that exposes the various parts of the current version text, e.g. version, DX version, Git stuff

**Comment by braem** [comment]
Exposed via `MomentumAPI.GetVersionInfo()`, which returns a JSO with fields:
- `version` (string)
- `isDX11` (bool)
- `isInMappingMode` (bool)
- `gitversion` (string)

**Comment by tsa96** [comment]
Perfect, thanks Brae.
