### ISSUE TITLE
Can no longer arrow key through multiple previous commands in console

### ISSUE THREAD

**Issue by ryskates** [momentum-mod/game#1697]
### Describe the bug

When arrow keying up or down in console the console locks on the most recent command and doesn't allow you to continue past it.

### How To Reproduce

1. Open console
2. Enter two commands separately
3. Attempt to use the arrow key to get back to the first command you used

### Expected Behavior

Before this latest update you could arrow key through prior commands as far as you wanted.

### Operating System

Win 10

### Renderer

DX11 (default)

**Comment by braem** [comment]
Fixing by removing recently added behaviour of updating autocomplete list on iterating previous commands
