### ISSUE TITLE
trigger_push/trigger_teleport clientside prediction

### ISSUE THREAD

**Issue by fatalis** [momentum-mod/game#17]
Boosts/teleports suck when your ping is high.

I tried to implement this but got nowhere. I think the prediction engine just isn't capable as it is and would need a lot of things rewritten. Not to mention all triggers live on server and arent shared. Maybe someone else can figure this out.

**Comment by TheAsuro** [comment]
Momentum mod runs the game movement entirely clientside, all server functionality will be our own code. This means we won't need any prediction for movement or physics.

**Comment by fatalis** [comment]
Oh right, you guys are doing a custom multiplayer implementation or something, right?

**Comment by TheAsuro** [comment]
Yeah, players won't need to interact with each other, so using the multiplayer components of source would just make things more complicated.

**Comment by fatalis** [comment]
That means the server-authoritative nature of Source is gone. Hopefully anti-cheat is good.
