### ISSUE TITLE
trigger_push not affecting players in defrag

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/game#1707]
### Describe the bug

trigger_push doesn't affect players within the trigger volume.

### How To Reproduce

walk into a trigger_push, nothing happens.

### Expected Behavior

the player should be pushed

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Mac-tf2** [comment]
trigger_gravity also does not work.

**Comment by chovelyoukai** [comment]
Fixed a few updates ago.
