### ISSUE TITLE
Consider adding cow mangler shoot angles in RJ

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1708]
### Is your feature request related to a problem?

In TF2, the stock rocket launcher has a 12 unit offset, the original has a 0 unit offset, and the cow mangler has an 8 unit offset. If there's enough desire, we should implement this as an option for people. Some things to consider:

- This would be reflected in that startup prompt thing
- More settings / convar / etc bloat most likely
- How do we show that the player is using this angle to spectators (you can't just offset because we have the viewmodel xyz offset commands, might require a 3rd render of the thing?)

### Describe the solution you'd like

Add 8 unit rocket offset as an option

**Comment by Gocnak** [comment]
Gonna go with no on this one, and instead will point to the unique gameplay of beggar's instead as compromise.

**Comment by hexaflexahexagon** [comment]
im not gonna fight this being closed but i want to point out those two are in no way comparable lol

**Comment by Gocnak** [comment]
Okay maybe I was too quick to judge. We can add the angles as a run flag.

**Comment by braem** [comment]
> Okay maybe I was too quick to judge. We can add the angles as a run flag.

would be fine to just have it in main runs; it's just another usable shoot angle like center or side fire

**Comment by Shirge** [comment]
Btw the rocket launcher actually have a bit of aim assist:

**tf2 projectiles have aim assist, & how you can miss without missing:**
https://www.youtube.com/watch?v=AUPBC5W1KHo

**correction & common questions about the rocket aim assist:**
https://www.youtube.com/watch?v=CoQYWDsDH94

This is probably completely useless information because there's _probably_ nothing that would cause aim assist to be triggered in if you were to play the maps on TF2. So it's fine to leave this out of Momentum Mod.

**Comment by hexaflexahexagon** [comment]
We do have the 2k unit crosshair thing mentioned in that video (and have debated possibly removing it even), though I'm not sure if we have the weird entity aim correction stuff. Even if not there is no PVP or players so the only things that'd possibly trigger that would be like moving props or something, but that wouldn't be desirable anyways.

**Comment by Shirge** [comment]
> We do have the 2k unit crosshair thing mentioned in that video (and have debated possibly removing it even), though I'm not sure if we have the weird entity aim correction stuff. Even if not there is no PVP or players so the only things that'd possibly trigger that would be like moving props or something, but that wouldn't be desirable anyways.

It would be very infuriating if moving props triggered it and made you fail a rocket jump.
