### ISSUE TITLE
`host_timescale` with `sv_cheats 0` still affects sounds

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1710]
### Describe the bug

Changing the value of `host_timescale` while having `sv_cheats` off still affects sounds as if it was enabled, while the gameplay remains unaffected

### How To Reproduce

1. Start any map while in `-mapping`
2. Change `host_timescale` to any value, make sure `sv_cheats` is `0`
3. Fire a weapon or do anything that causes a sound event

### Expected Behavior

Sounds should keep playing as normal, as `host_timescale` is not affecting the player or the world

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by braem** [comment]
this is a chaos issue

**Comment by VortexParadox** [comment]
ah, my bad. I can't transfer the issue to Chaos however

**Comment by hexaflexahexagon** [comment]
apparently nobody can, github doesn't let you transfer issues between repos. though as per today's meeting in 0.9.3 we're gonna be tackling all the random `sv_cheats 0` convars that need allowed through so we can just keep this here
