### ISSUE TITLE
[DX11] Particle sprites do not render correctly

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1711]
### Describe the bug

Particle sprites with translucency don't blend correctly
<table><tr>
<th><img src="https://user-images.githubusercontent.com/35622748/156945924-07cdc0e5-119a-4188-a0c4-2772563c44cd.png"></th>
<th><img src="https://user-images.githubusercontent.com/35622748/156945949-edfcecf0-ea4d-4d18-a517-c3de05af6cef.png"></th>
<th><img src="https://user-images.githubusercontent.com/35622748/156946031-f108909e-b647-4f4c-8477-648bdee2ea05.png"></th>
</tr></table>

### How To Reproduce

1. Enter any map
2. Fire any weapon, preferably the RL as its trail has the most particles drawn at once

### Expected Behavior

It should render as it did under DX9

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
Don't think I am able to replicate this? Looks like this when I try: 
![image](https://user-images.githubusercontent.com/25954912/156947108-41c2d5a9-1920-41bc-a2b7-877ecfe25f50.png)

**Comment by VortexParadox** [comment]
I'll try to take a look at the graphic configs that are auto assigned to my vendor id, because yeah this is odd

**Comment by VortexParadox** [comment]
The game was not on DX11 I, again, forgot DX11 is not launched by default; odd to see this graphical bug back on DX9 but it's a relief to see that the problem isn't my iGPU.
The particles render with no issues in DX11
