### ISSUE TITLE
Spectate UI buttons / replays keep focus and swallow Enter key

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1714]
### Describe the bug

Spectate UI and replay UI stay focused after closing. If spectate buttons are interacted with they swallow the enter key.
### How To Reproduce

1. enter a map and spectate
2. click the first person, next/last person, or exit button
3. press enter and see the last button you clicked is now bound to it

### Expected Behavior

UI shouldn't remain focused after closing, and the spectate buttons shouldn't swallow the enter key.
### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by lvaness** [comment]
It's not really rebinding the key, it's just that the fix for textentry focus also means that buttons will stay in focus after you click them.

We might just have to disable that behavior for HUD elements specifically
