### ISSUE TITLE
setting "effect detail" to other than high greatly decreases radius of rendering func_lod

### ISSUE THREAD

**Issue by plarr** [momentum-mod/game#1716]
### Describe the bug

https://user-images.githubusercontent.com/72131600/157216099-4f891f3a-7dad-4218-9ffd-edc229c6814e.mp4

### How To Reproduce

1. open map that has func_lod (blue blocks above grey blocks near the start on bhop_tripportals for example)
2. make sure you are on high effect detail
3. check the radius where func_lod is become visible 
4. change effect detail to low or medium
5. the radius where func_lod is become visible is decreased

### Expected Behavior

func_lod radius should stay the same on any "effect detail" setting

### Operating System

Windows 11

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
Fade values were changed to be consistent across all settings, and also made to match CS:GO.
