### ISSUE TITLE
Speed gain worsens when FPS is not at a multiple of the tickrate

### ISSUE THREAD

**Issue by f0e** [momentum-mod/game#1717]
### Describe the bug

Inconsistent fps / fps that isn't at a stable multiple of the tickrate will result in worse speed gain due to ticks receiving inconsistent numbers of mouse inputs.

e.g. 150 fps on 100 tick:
```
frame & mouse input collection
tick (1 input)
frame & mouse input collection
frame & mouse input collection
tick (2 inputs)
frame & mouse input collection
tick (1 input)

etc.
```

Every second tick will have an extra mouse input, meaning the amount the mouse moves will be higher than the previous tick. This results in worse speed gain since your viewangle delta will not be consistent.

Video demonstration:
https://www.youtube.com/watch?v=GIemC1eKPw0

### How To Reproduce

1. Join any bhop map
2. Set fps_max to 300 (100 tickrate * 3)
3. Try strafing, see what speed you get on 6th jump
4. Set fps_max to 150 (100 tickrate * 1.5)
5. Try strafing, see what speed you get on 6th jump

You should consistently see worse speed with fps_max 150.

### Expected Behavior

Speed gain should be the same no matter the framerate.

### Operating System

Windows 11

### Renderer

DX11 (default)

**Comment by jason-e** [comment]
Fixed with `m_rawinput 2`, which interpolates frame-aligned mouse samples to get the correct mouse position for game ticks.
