### ISSUE TITLE
Can't create savestates from replays

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1720]
### Describe the bug

Trying to create a savestate from a replay always results in the message "Must be on ground to create a start mark" regardless of whether or not the player is actually within a start zone

### How To Reproduce

1. Open a map
2. start a replay
3. use mom_saveloc_create (savestate menu not currently working in spec/replay)
4. see console output "Must be on ground to create a start mark!"

### Expected Behavior

You should be able to create savestates from replays

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
i wonder if this is because you're standing in the start zone while watching the replay

**Comment by Shegetz** [comment]
I tested both inside and outside the start zone multiple times on multiple maps

**Comment by Shegetz** [comment]
The savestate is being created but is trying and failing to create a start a start mark at the same time
