### ISSUE TITLE
HDR commands now cheat protected

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1725]
### Describe the bug

All the normal commands related to HDR are now cheat-protected since at least the March 7 update. This includes `mat_colorcorrection`, `mat_disable_bloom`, and `mat_dynamic_tonemapping`. They should not be cheat protected.

### How To Reproduce

type commands into console and notice they are cheat protected

### Expected Behavior

commands should be available normally

### Operating System

w10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
```
v — Today at 6:36 PM
regarding the hdr commands
they're all added to settings
but only bloom works
color correction and tonemapping are still cheat protected so changing the value doesn't do anything (in the settings panel you can set it to disabled but it's still enabled if you look at the cvar/ingame) 
```

**Comment by tsa96** [comment]
Confirmed by v
