### ISSUE TITLE
Re-add HDR commands to settings panel

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1726]
### Is your feature request related to a problem?

In the VGUI version of the settings (and most other source games), the HDR commands `mat_colorcorrection` and `mat_disable_bloom` were available with a simple enable/disable switch. Since the the move to panorama, these settings have not been added. Additionally add `mat_dynamic_tonemapping` to the settings panel for the same reasons.

### Describe the solution you'd like

HDR commands in settings panel with enable/disable toggles

**Comment by itVictor** [comment]
these settings are partially broken now, the "disabled" option has the same effect of picking "enabled" (ie it sets the cvar values to on/1)

**Comment by xen-000** [comment]
Which setting exactly? And I also can't reproduce this on the steam build.

**Comment by itVictor** [comment]
> Which setting exactly? And I also can't reproduce this on the steam build.

 the 3 I mentioned in the top post, but it seems like the commands don't seem to change correctly in the settings before/after changing the cvars manually through the console, as well as possibly whether you are in main menu vs ingame (tested on bhop_eazy)

testing on the key version, not the playtest

**Comment by Gocnak** [comment]
Please test stuff on the playtest version where possible, there's been known issues with settings not properly saving for key version due to AppID shenanigans we have to do.

**Comment by itVictor** [comment]
This also happens on the playtest version, same things I mentioned above.

One thing I did notice is that if I change the settings on all 3 and then change another (unrelated) setting, it gets set back to enabled if I close and open the settings (with no change the cvar values). This only happens while in a map, on the main menu the settings keep the change but the cvar isn't being changed there either.

**Comment by xen-000** [comment]
I still can't reproduce this. Are you sure you're actually applying the settings?
