### ISSUE TITLE
Remove automute from typing too many messages in a lobby

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1729]
### What feature is your improvement idea related to?

Absolutely nobody that I've seen likes it when people get automuted from typing a few messages quickly. It doesn't even inform you, suddenly the person just isn't speaking.

### Describe the solution you'd like

Completely remove it. If people want to mute somebody they will not be shy about it.

**Comment by lvaness** [comment]
I don't see why it should be removed. Sure it could be disabled by default or the limits higher. There is also already an event being sent when somebody gets (un)muted that would probably get turned into a notification

You can also just turn it off once and forget about it forever

**Comment by tsa96** [comment]
I think putting the limit significantly higher should work. Currently, it's an issue for regular players so clearly needs to be changed. This is something that's only going to useful filtering aggressive spam via scripts, trying to find some kind of sweet spot is inevitably going to result in false positives so I think something like 10 messages per second could work.

**Comment by braem** [comment]
Increased spam msg limit as suggested
