### ISSUE TITLE
Weapon switch sound not changed by ui volume

### ISSUE THREAD

**Issue by rellort1** [momentum-mod/game#1730]
### Describe the bug

The volume of the weapon switch sound can only be changed by lowering the full game audio, the ui volume doesn't change it.

### How To Reproduce

1. Open Settings
2. Change ui volume
3. notice the weapon switch sound is the same volume

### Expected Behavior

The weapon switch sound should change with the ui volume slider since its part of the ui

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by braem** [comment]
We'll have a cvar to toggle it next update. Will have to wait until we have our own sound to be changeable by the volume slider, since it points to Valve's which we cannot redistribute.

**Comment by Gocnak** [comment]
The Valve sound *might* be in the HL2 VPKs we ship, but if it isn't yeah we'd have to get Monolith/Burrito/Happy to make us a new one.

**Comment by braem** [comment]
Will distribute as it is a HL2 sound. This allows the sound to be effected by ui volume.
Also togglable via `mom_hud_weaponselection_sound_enable`.
