### ISSUE TITLE
Forward slider settings in ChaosSettingsSlider

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1737]
### What feature is your improvement idea related to?

Sliders can be a pain right now, never snapping to discrete values. This makes setting specific values very hard, especially annoying in the case of setting timescale to exactly 100%. ESPECIALLY combined with the fact setting percentage values in corresponding textentries in the `ChaosSettingsSlider` doesn't work properly (if there's an issue for that already we should make one as well). 

### Describe the solution you'd like

Add two new attributes to the `Slider` panel, `snapmult` and `snapprecision`. Whether the notch is being dragged and it comes within a `snapprecision`th of a multiple of `snapmult`, from either direction, set the notch to that multiple.

**Comment by braem** [comment]
slider already has snapping (see usage of notched sliders in mapselector/controlslibrary)

unfortunately it is hard to forward slider options to the actual slider in the settingsslider though..

**Comment by tsa96** [comment]
I was thinking we don't want snapping everywhere, just on specific multiples, my bad!. But yeah I guess `snaptoincrement` with a really small increment should be okay. Is not possible to pass those same attribute names set in the `ChaosSettingSlider` to the underlying `Slider`? I feel like we've done something like that before. If not, this issue can be closed, apologies from the unnecessary issue!

**Comment by hexaflexahexagon** [comment]
seems to be implemented according to the #general-bhop folks

**Comment by hexaflexahexagon** [comment]
WRONG CARD
