### ISSUE TITLE
new entity - trigger_userinput with more features

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#1738]
### Is your feature request related to a problem?

In learn maps if we want to limit/guide the player and their inputs it requires a ton of I/O involving trigger_userinput, player_speedmod and env_hudhint (and maybe env_zoom too).  
And if you wanna do multiple keypresses at once it gets even more confusing. 

### Describe the solution you'd like

While this is doable, it's not very preferable. Combining these entities and improving upon the trigger_userinput entity will make this work a lot less tedious.  

### Describe alternatives you've considered, if any.

This new entity would essentially be a normal trigger_userinput but with the added functionality of:  
- player_speedmod  
    - for the slowmotion effect only  
- env_hudhint  
     - To tell the player stuff  
- env_zoom  
     - For a cooler effect complementing the slowmotion  
- multiple keys that can trigger it at the same time  
     - Right now you can only do one key at a time  
     - This could have some synergy with the hudhint to show all the buttons that trigger it rather than just one  
  
Then being able to fire outputs OnKeyHeld, OnKeyReleased, etc like the original entity should still be there for extra functionality.  
  
Also being able to negate the button pressed can be useful. I.e. have it triggered if the player isn't holding the assigned key.  
  
While we're at it we can also add more keys that trigger it, right now it's missing things like +speed and +walk (maybe even more)

**Comment by hexaflexahexagon** [comment]
there have been some issues brought up in #learn by granis but we can go ahead and make new cards for those, the initial entity is done
