### ISSUE TITLE
Impossible to resume game after going to menu while result window is open

### ISSUE THREAD

**Issue by Martussoun** [momentum-mod/game#1747]
### Describe the bug

After finishing a map or watching a replay finish the result window opens, and if you manage to get to the pause menu(it opens when you open the steam overlay) it will become impossible to resume the game again by pressing Escape

### How To Reproduce

1. Finish map/ watch replay finish
2. Results window opens
3. Open steam overlay(shift+tab)
4. Pause menu opens
5. Escape key doesnt resume game

### Issue Map

Any map

### Expected Behavior

When I press escape in the pause menu the game should resume regardless of what windows are open in-game

### Operating System

Win10

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
Fixed as part of #1509
