### ISSUE TITLE
Other modes not changing some Vars from defrag

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1748]
### Describe the bug

When switching from a defrag map to another mode some vars are seemingly not being properly set to the intended mode. The extent of which is unknown but can be seen in sticky bounce behavior. Normally shooting down as in the video will put the stickies close enough to use to perform downairs,

Altered behavior: 

https://user-images.githubusercontent.com/73811375/161415887-f5060f64-e32e-47db-9407-691cb0aebea7.mp4

 

### How To Reproduce

1. open defrag map
2. join sticky jump map
3. shoot stickies attempting to downair
4. see they bounce further than normal

### Issue Map

sj_antiquity

### Expected Behavior

Stickies shouldn't be bouncing so far away from you that you can't perform downairs after switching from a defrag map

https://user-images.githubusercontent.com/5162166/161419874-b64c25d8-d7d3-4f88-be72-f815b4c856db.mp4

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
seems to be resolved using the given SJ example
