### ISSUE TITLE
trigger_softbarrier or similar

### ISSUE THREAD

**Issue by Belastigen** [momentum-mod/game#175]
a trigger_softbarrier in CS:GO is a trigger brush that prevents the player from maintaining speed through it but only in one direction. This allows for one-way mapping, as well as preventing the player from accidentally falling back a stage without the need for the slightly more complicated checkpoint filter teleports system.

**Comment by Gocnak** [comment]
We now have this inside the Chaos engine build, under the exact same entity name `trigger_softbarrier`. Closing.
