### ISSUE TITLE
Hide the `building_cubemaps` cvar

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1754]
### What feature is your improvement idea related to?

Title. This doesn't need to be exposed for any reason, and can cause issues when people accidentally put it in console

### Describe the solution you'd like

Hide the `building_cubemaps` command

### Additional context

https://discord.com/channels/235111289435717633/235125108656701440/961409452181962782

**Comment by tsa96** [comment]
Confirmed by v
