### ISSUE TITLE
Lobby Settings/Create Lobby panels having text in buttons being able to be highlighted with click and drag

### ISSUE THREAD

**Issue by ashley-cervidae** [momentum-mod/game#1755]
### Describe the bug

On the lobby settings/create lobby panel you can click and drag to highlight the text within the "cancel" and "update/create" (when it's active) buttons.

![image](https://user-images.githubusercontent.com/61669291/162261737-8fde0adf-d810-4ca1-97f4-232eed6787f7.png)
![image](https://user-images.githubusercontent.com/61669291/162261786-e99d0a8f-b042-4681-abff-8dbebeaa0779.png)

### How To Reproduce

1. Open lobby side panel, create new lobby
2. Click and drag over the text in the Cancel button (and the Create button, once active)
3. Repeat step 2 after opening a lobby and going into the lobby settings panel (with Create replaced by Update)

### Issue Map

Lobby panel

### Expected Behavior

I should not be able to highlight the text in those buttons.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by tsa96** [comment]
This is known but not tracked I guess, so thanks for the issue! Should be in 0.9.2 project board probs Goc.

I haven't looked at this in several months, IIRC when I last looked any Label in a popup was behaving like this. I think probably a C++ issue but worth testing more before digging deep into Pano C++ code.

**Comment by lvaness** [comment]
This is an XML issue as far as I can tell, these labels have an onactivate event set (instead of the buttons), so they accept input, which by default also means selection for labels

**Comment by tsa96** [comment]
Oh haha, that'd definitely be it. Easy fix then

**Comment by tsa96** [comment]
Fixing this in the cleanup branch I'm working on

**Comment by granis48** [comment]
I cannot replicate this, seems to be fixed
