### ISSUE TITLE
Panorama non-16x9 Aspect Ratios

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1761]
Panorama adds an AspectRatioAxB class for different aspect ratios, e.g. `.AspectRatio16x9`, `.AspectRatio4x3` and so on. We can then use CSS to style child panels by selecting for any panels that are children of a panel with the AspectRatio class (so, all panels). We'll generally use this sort of pattern in Sass:

```
.panel {
  ... general styling ...
  .AspectRatio4x3 & {
    ... styling specifically for .panel on 4x3 ...
  }
}
```

Firstly we should decide all the different ratios we want to support. 4x3 I'm quite adamant about - even though it might take some tweaks in various places, it's not at all uncommon for people to use it, especially CS players. 5x4 and 16x10 I don't know, they're less common and even more square than 4x3, I still think worth supporting if possible. Higher ratios that 16x9 are more and more common with the rise of ultrawides, and generally easier for us to support due to lack of the squishing effect on lower ratios. So definitely 21x9, and PeenScreeker has some 32x9 monstrosity so we could even try support that if he wants to contribute using whilst using that. FWIW CS:GO has styling for 16x9, 4x3, 5x4, 16x10 and 21x9.

On that: generally on ratios lower than 16x9 like 4x3 a lot of stuff gets sort of squished together, for example the main menu topnav. In that case, we might need to decrease the size of the topnav buttons or topnav itself so they fit better. This will be the task that takes the most thought and creative eye.

On higher ratios we may want to avoid stuff getting stretch too far and increase the side padding of a lot of pages - we should be able to do a lot just by increasing the padding of `mainmenu__page`.

We'll be forced to scale up various background images and videos, won't look great but should be good enough, especially if we add 4k versions in the future. https://github.com/momentum-mod/game/issues/1528 will be part of this.

This is gonna be a pretty boring job but shouldn't be too much work given how well organised our stylesheets are. It's possible to set your monitor to non-standard resolutions in Nvidia's control panel by going to "Create Custom Resolution" on the Change Resolution page.

**Comment by Evylon** [comment]
When using 16:10 some UI elements in panorama are rendered outside of the window, off to the right. See screenshot below. Other menus are also affected, i.e. the settings.

OS is Windows 10, driver is DX11, build is the latest from steam playtest.

![panorama-16-to-10-rendering](https://user-images.githubusercontent.com/46427024/194636693-d8facf69-c206-4281-9409-4b1c1bc8a72f.PNG)

**Comment by Gocnak** [comment]
@Evylon hey nice find! If this is still happening on 0.9.2+ can you open a separate issue for it? If it's all good please let us know as well :)
