### ISSUE TITLE
Add label telling you to right-click in leaderboards/end of run panel

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1764]
Some people have been taking a while a realise that right-clicking in the leaderboards tab menu gives you cursor control. We should just add a smallish label somewhere informing people (CS:GO does the same if you want a reference).

**Comment by rdg11** [comment]
@tsa96 would I need to localize this string? because I wanted to try this but I don't know how to do that part. 
Or If I create a PR for this and it gets merged, can I create an issue on that?
