### ISSUE TITLE
Panorama Image Refactor

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1765]
Panorama's icons are currently stored in `materials/panorama/`, which is weird as they're not materials. We should move to `panorama/images/`. Also, the folder organisation is pretty bad. We tend to use the same icons in various different places, so putting them in folders based on where they are used in the UI (e.g. "mapselector") is silly. We should either put them in more abstract categories where they fit e.g. "online", "gameplay" etc. or just keep them in the base folder.

Also, we're currently using a lot of icons from https://materialdesignicons.com/. These are great and most are under a very relaxed licensed (https://github.com/Templarian/MaterialDesign/blob/master/LICENSE) apart from some that are under Apache 2.0. We should go through all our current icons and check which are from there, ideally replacing the ones under Apache 2.0. We should then add the Pictogrammer's part of the license to THIRD-PARTY-LEGAL-NOTICES.txt

Finally, our icons are currently all scaled to a 24px viewbox. This is often too low, and is an issue in places where those icons are set via JS, for example SimpleContextMenus. We either need to find a way to increase the resolution in those places (and ideally Panorama would scale textureheight/texturewidth based on resolution anyway) or we could batch modify all our existing icons, increasing the viewBox and using something like  `<g transform="scale(2)">`.

**Comment by Gocnak** [comment]
Done in green's PR # 142
