### ISSUE TITLE
Incorrect swim speed in RJ/SJ

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/game#1768]
### Describe the bug

Swim speed is too high in the RJ and SJ gamemodes.

### How To Reproduce

swim in a straight line, notice that the speed is more than 80% of walking speed.

### Issue Map

all

### Expected Behavior

swim speed should be 80% of walking speed.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
dup of https://github.com/momentum-mod/game/issues/1750
