### ISSUE TITLE
[Console] Investigate improving tab autocomplete behavior

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1776]
### What feature is your improvement idea related to?

The effort vs reward of this should be considered but the current behavior of autocomplete can definitely be improved at least a little without rewriting it all. See this issue that was made yonks ago for the best case scenario: https://github.com/ChaosInitiative/Chaos-Source/issues/156

But that may require extensive work for a fairly minor improvement, so if we can cheaply get some bonus UX that may be preferable in the short term. 

### Describe the solution you'd like

Best case scenario, have both windows (SDK 2013/tf2/css) flavored autocomplete where tab types the full first result, hitting tab again types the full second result and the list doesn't update until you type a key or hit backspace AND bash (CSGO / previously mmod) flavored autocomplete that simply completes up to the most unique sequential characters in all the results.

More info: https://github.com/ChaosInitiative/Chaos-Source/issues/156

### Describe alternatives you've considered, if any.

From BLT 4/21/2022 in the team channel:
```
i think it would be nice to have it in the way that the part that gets cycled 
is already pre-selected so if you start typing again it will just get removed (or backspace)
```

### Additional context

Also see granis' comment here: https://github.com/momentum-mod/game/issues/1527#issuecomment-937912331

**Comment by jason-e** [comment]
Upon further investigation, CSGO actually has the same behavior as other Source games, so our Console should be updated to mimic that behavior (see ChaosInitiative/Chaos-Source#570)

**Comment by Gocnak** [comment]
I think this issue was tackled recently by @bltech, are we back to normal?

**Comment by lvaness** [comment]
I didn't touch the behavior much, I only fixed some bugs with it
