### ISSUE TITLE
Game crash when alt-tabbing back into game on jump_finite_v2

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#1778]
### Describe the bug

Setting the map to jump_finite_v2 causes the game to crash if you alt+tab out then try to alt+tab back in.

Only happens in Dx11 in exclusive fullscreen (dx9 any display mode and dx11 fullscreen-windowed doesn't crash).

### How To Reproduce

1. open game in exclusive fullscreen, dx11
2. set map to jump_finite_v2
3. alt+tab out
4. attempt to alt+tab back in
5. game crash

### Issue Map

jump_finite_v2 
download: http://tempus.site.nfoservers.com/server/maps/jump_finite_v2.bsp.bz2

### Expected Behavior

no crash when alt+tabbing back into the game

### Operating System

w10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Confirmed fixed by OP
