### ISSUE TITLE
Settings slider text entry changes don't apply without pressing enter

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1779]
### Describe the bug

If you change the numerical value in the textentry in a ChaosSettings Slider, the change won't apply unless you press enter. So clicking another settings option or pressing ESC will have no effect.

### How To Reproduce

Change a value, click elsewhere, cvar won't update.

### Issue Map

Irrelevant

### Expected Behavior

Best to just update the value as soon as the text entry changes so it changes for each char. Essentially changing behaviour from `ontextentrysubmit` to `ontextentrychange`

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
resolved
