### ISSUE TITLE
Zoning cursor no longer shows when creating zones

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1780]
Something in the 21/04/22 update (FC2733464) broke zoning. Pressing "Create Zone" in the zone menu will give you mouse control but no longer shows the cursor, and left clicking has no effect.

**Comment by Gocnak** [comment]
Good ol VGUI. You have to use the commands directly `mom_zone_mark` until we redesign the new zone tools for 0.10.0. Going to close this for now, this is just the unfortunate byproduct of removing VGUI + being 2 versions away from redoing the UI entirely to make a small port to pano not worth the effort.
