### ISSUE TITLE
Hammer Entity Report: SHIFT+Click two items in list ignores the visual filter

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1781]
### Describe the bug

When using SHIFT+Click to select all and between, it selects everything clicked on and between the two selections, in the order of the entities, instead of how it is shown in the list.

Selecting them normally works, and you can select multiple with CTRL, however when selecting all and between, like how you can shift+click in a windows computer folder to select two files and everything in-between it, this selects every entity that would be between it not shown in the list, 

https://user-images.githubusercontent.com/62808028/165193258-da7864ab-1472-44fa-80ec-80cbdaa001a1.mp4

### How To Reproduce

1. Have a map with multiple different types of brushes and/or entities that display in the Entity Report.
2. Open the Entity Report, and Filter something specific, such as Brush Entities by class of trigger_momentum_slide if that exists in the map.
3. Select something in the list, then, holding Shift, select something lower in the list.
4. Click "Go to" or "Properties" to display what is selected on Grid.

### Issue Map

N/A

### Expected Behavior

Only what is displayed in the list should get selected.

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
fixed
