### ISSUE TITLE
OnDamage output on a func_button was broken by a mmod change

### ISSUE THREAD

**Issue by Gorge004** [momentum-mod/game#1782]
### Describe the bug

A while ago the OnDamage output was changed in mmod to check the flags of the func_button before firing. This means it's not possible to ahve a OnDamage output fire without the "OnDamage Activate" flag ticked. 

It was thought to be a bug and that's why it was changed this way, but it isn't a bug and fixing this removes niche applications of a func_button while also making 90%+ of all button in tf2 jump maps needing to be "fixed" when getting ported to mmod.

There is an OnPress output in a func_button wich already check for the button's flags. The way buttons are currently in mmod, the OnDamage output is exactly the same as the OnPress. You can not currently fire an OnDamage output without pressing the button. 

There are some niche application to be able to use Ondamage output without pressing buttons but the main reason this should be reverted to how it is in tf2 is its not a bug and it avoids needing to change every buttons in maps when we start porting them over. 

### How To Reproduce

1. Set any OnDamage output in a func_button
2. Don't tick the OnDamage Flag
3. Shooting button will not fire the output

### Issue Map

https://www.dropbox.com/s/fd9sznwarun9pr1/jump_it_final.bsp?dl=0

jump_it, the jump at this timestamp:
https://youtu.be/POMuTErmDok?t=74

That's just 1 example in many, most buttons in jump map are made the same way as that one.

### Expected Behavior

OnDamage output should fire when the button entity takes damage regardless of the flags set on func_button

The output to fire whenever a button is pressed is OnPress wich already works this way.

### Operating System

all of them

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Fixed in the next release, will be in both next 0.9.x and 0.10.0.
