### ISSUE TITLE
`func_slide` entities cannot be stuck with stickybombs

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1783]
### What feature is your improvement idea related to?

`func_slide` brushes, like any other 'func' entity like a `func_brush`, turn stickybombs into rollers. this is concerning because making a surface slideable but also stickable was trivial with the trigger entity, however is now very tedious (making invisible 1 unit phase across the entire surface).

### Describe the solution you'd like

somehow make it easily possible to stick `func_slides`. my idea was to allow for some sort of entity flag or keyvalue that marks an entity as unmoveable (similar to VRAD world portals) and thus has no need to roll stickies. not sure how practical this is, but if it works out it would also have the benefit of letting mappers mark any other `func_` entity as stickable

### Describe alternatives you've considered, if any.

if the above does not work easily then any other solution would be fine.

### Additional context

it is also impossible to slide on displacements right now as they cannot be entities, not a huge deal but would be nice if that could also be resolved somehow. that will most likely be a separate card and project though unless someone comes up with a very elegant solution to the issue

**Comment by braem** [comment]
Should be able to use `trigger_stick_explosive` volumes to ensure a stick.

**Comment by Gocnak** [comment]
Closing, do what Brae said
