### ISSUE TITLE
Make drawer panel open on clicking the tiny buttons

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1784]
### What feature is your improvement idea related to?

right now clicking the tiny buttons (pic) does nothing, but they should also open the drawer if it is closed.
![image](https://user-images.githubusercontent.com/62961532/165422892-4b4b1499-0573-49bd-be7a-1f7b1ad49ea4.png)

### Describe the solution you'd like

make clicking each button open the respective tab of the side drawer

### Additional context

this might just be a side effect of the drawer not being done yet but I figured it was worth putting into an issue just in case. the lobby tab is implemented and clicking that button also does not open the drawer

see: https://github.com/momentum-mod/game/issues/1424

**Comment by tsa96** [comment]
This was merged in a month or so ago
