### ISSUE TITLE
Momentum doesn't run on Fedora 35

### ISSUE THREAD

**Issue by JosSamLoh** [momentum-mod/game#1785]
### Describe the bug

Momentum does not open at all on Fedora 35.

Errors from `10th Apr, 2022`
```bash
[juice@cupdessy Momentum Mod]$ ./momentum.sh 
[S_API] SteamAPI_Init(): Loaded '/home/juice/.local/share/Steam/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 669270
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198111733936 [API loaded no]
SDL video target is 'x11'
AppFramework : Unable to load module engine.so!
Unable to load interface VCvarQuery001 from engine.so, requested from EXE.
```
```bash
SDL video target is 'x11'
Invalid cast.
warning: Probes-based dynamic linker interface failed.
Reverting to original interface.
AppFramework : Unable to load module engine.so!
Unable to load interface VCvarQuery001 from engine.so, requested from EXE.
[Thread 0x7ffff67c5640 (LWP 12582) exited]
[Thread 0x7fffe82ce640 (LWP 12585) exited]
[Thread 0x7ffff65c3640 (LWP 12584) exited]
[Thread 0x7ffff66c4640 (LWP 12583) exited]
[Thread 0x7fffe81cd640 (LWP 12586) exited]
[Thread 0x7fffe80cc640 (LWP 12587) exited]
[Thread 0x7fffe8acf640 (LWP 12581) exited]
[Inferior 1 (process 12577) exited normally]
```
Errors from `28th Apr, 2022`
```bash
[juice@cupdessy Momentum Mod]$ ./momentum.sh 
[S_API] SteamAPI_Init(): Loaded '/home/juice/.local/share/Steam/linux64/steamclient.so' OK.
[S_API FAIL] SteamAPI_Init() failed; no appID found.
Either launch the game from Steam, or put the file steam_appid.txt containing the correct appID in your game folder.
Failed to initialize filesystem Steam API context. Please make sure Steam is running!
```

### How To Reproduce

1. Be running Fedora 35
2. Start Momentum
3. Doesn't run :(

### Issue Map

N/A

### Expected Behavior

Momentum runs perfectly fine with no issues

### Operating System

Linux, Fedora 35

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
The 28th April error is you not running it from Steam, or at least you're running it without Steam running?

**Comment by JosSamLoh** [comment]
> The 28th April error is you not running it from Steam, or at least you're running it without Steam running?

That's where I'm confused, because I have steam running, using the rpmfusion package as well. The two separate errors happened on practically the same set-up, with the first one was when I was running the steam flatpak I believe, either way, Momentum doesn't run with either.

**Comment by JJL772** [comment]
Can you run the game using the following command: `GAME_DEBUGGER=strace ./momentum.sh` and post the `strace.log` here?

Make sure you have strace installed. This error is probably due to missing libraries

**Comment by JosSamLoh** [comment]
> Can you run the game using the following command: `GAME_DEBUGGER=strace ./momentum.sh` and post the `strace.log` here?
> 
> Make sure you have strace installed. This error is probably due to missing libraries

[strace.log hastebin](https://haste.zneix.eu/raw/digyjopete)

**Comment by JosSamLoh** [comment]
This issue seems to be solved as far as I know, in the latest version of Fedora, and is now pretty much identical to #1591, and has the same fix.
