### ISSUE TITLE
JS exception when trying to add "Energy" speedometer

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1787]
### Describe the bug

![image](https://user-images.githubusercontent.com/62961532/166068534-e64ea77a-8445-4356-aa84-c0d29d82ce78.png)

It seems like it still gets added and runs fine if you hit 'continue' however, so probably just something tiny.

### How To Reproduce

1. Open settings -> Interface -> Speedometer
2. If you already have energy (for some reason), remove it
3. Try to add energy speedometer

### Issue Map

UI

### Expected Behavior

No exception

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
We should honestly remove the Energy speedometer.

**Comment by hexaflexahexagon** [comment]
I'm all in favor of that because anybody who uses the energy meter is probably some sort of serial killer who we don't want to associate with, so best to get them all out now
