### ISSUE TITLE
Hitting enter in console after downloading a map loads the map

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1788]
### Describe the bug

Downloading a map via the map selector, opening console, then typing a command and hitting enter will load the map that was just downloaded when it shouldn't.

### How To Reproduce

1. Open map selector, click any map that doesn't have a green arrow "downloaded" icon. Note that it don't have to _actually_ download it, e.g. if the cache file broke and it doesn't think you have the map but you do, therefore there's no download bar when clicking the icon.
2. After done, open console and type anything `echo hi` then hit enter.
3. Load map

### Issue Map

All of them

### Expected Behavior

Hitting enter in console should only input the command, not hit enter in the map selector.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by lvaness** [comment]
I can't believe there isn't an issue for this yet; I do however have a pretty good idea how to fix it by now

**Comment by lvaness** [comment]
Confirmed fixed in discord
