### ISSUE TITLE
env_bubbles renders center origin of map

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1789]
### Describe the bug

Like how **func_precipitation** was rendering its rain in center origin of map, env_bubbles does the exact same thing.

### How To Reproduce

1. Place env_bubbles in a map away from origin, with origin inside of map to see.
2. Compile map and go to center origin of map and you will see bubbles.

### Issue Map

N/A

### Expected Behavior

Render within the trigger bounds

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
fixed, though `env_bubbles` will show it's trigger texture ingame for some reason. putting that in a separate chaos issue
