### ISSUE TITLE
env_surface_teleport failing to teleport

### ISSUE THREAD

**Issue by Syrreal** [momentum-mod/game#1792]
### Describe the bug

env_surface_teleport does not teleport the player while holding a movement key directly into another brush

The teleport surface in the video is dirt
https://user-images.githubusercontent.com/76134393/166209359-a7e4bfe1-e622-4ac2-b931-22b0bdfed2a0.mp4

I tested with a rock and concrete as well. Having rock selected does not teleport at all (however, it's also not listed on the docks but is an option in the entity). Concrete also has the bug.

Landing inside of a portal also does not reset you.

### How To Reproduce

1. Load a map that uses env_surface_teleport
2. Jump onto the teleport surface into the side of a non-teleport surface block at any 45 degree angle (0, 45, 90, etc.)
3. Hold the corresponding movement key(s)

Teleport after either releasing the movement keys, changing your angle to the block, or moving away from the block.

### Issue Map

[bhop_indirection.zip](https://github.com/momentum-mod/game/files/8601949/bhop_indirection.zip)

### Expected Behavior

Always teleport when landing on a surface that is selected by an env_surface_teleport entity.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Confirmed resolved by OP in discord
