### ISSUE TITLE
Toast menus get cut off during shaking animation

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1803]
### Describe the bug

![image](https://user-images.githubusercontent.com/62961532/168331994-9ed77584-d288-41f8-854d-d66addbb8245.png)

### How To Reproduce

1. Load trigger tests
2. Enable `sv_cheats` / `mom_gamemode_override` / `-mapping`
3. Walk out of start zone

### Issue Map

triggertests

### Expected Behavior

Animation does not get cut off on the left side of the screen

### Operating System

win10

### Renderer

DX11 (default)

**Comment by tsa96** [comment]
Just an overflow thing, easy fix, will do soon
