### ISSUE TITLE
Engine viewport in `-tools` mode is non-functional

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1807]
### Describe the bug

See https://github.com/momentum-mod/game/issues/1218#issuecomment-1126653140 and above for context. Viewport starts blue, then upon loading a map via console will briefly display the map before turning into a display of whatever is in the top-left of the screen.

### How To Reproduce

1. Launch in `-tools` mode, hit F10 to enter tools mode
2. Use console to load a map (`map sj_amazon`)
3. Watch the engine viewport

### Issue Map

all

### Expected Behavior

engine viewport works like intended

### Operating System

win10

### Renderer

DX11 (default)

**Comment by VortexParadox** [comment]
This seems to be fixed now. I have fiddled around with tool `.res` files however. So if a person with a vanilla install can confirm the viewport only works once inside a map then this can be closed
