### ISSUE TITLE
Expose the constant that determines how bright `mat_fullbright 1` is

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1808]
### Is your feature request related to a problem?

Somewhere in the engine there is a magic value that determines what lightlevel to use for `mat_fullbright 1`. it would be very cool if this were accessible via a convar that people could change

### Describe the solution you'd like

add a new convar that does the above. probably does not need to be added to settings

### Additional context

dont forget to make an issue on the doc repo when this gets added so we can document it

**Comment by SlidyBat** [comment]
There isn't really an internal constant being used that we can expose. Each shader / system handles mat_fullbright itself in different ways (e.g. changing ambient light value, changing color modulation value, using white textures) and it is very hardcoded.

Might be feasible to make such a constant that all of these systems use, but it would be a big refactor and honestly I don't think it is worth the effort.

Can you explain why this is needed? If it is just for map visibility, could `mat_brightness` or #1371 achieve that?

**Comment by Gocnak** [comment]
Closing, not worth the effort. I agree with Slidy's comment.
