### ISSUE TITLE
Defrag: Add dedicated slick functionality

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#1813]
### What feature is your improvement idea related to?

Currently defrag slick is handled by the slide trigger entity. This entity is obsolete and will eventually be removed. Slick needs to have the following properties:

- Does not have the RNG of a trigger-based solution
- Takes priority over other, non-slick surfaces that are flush with it
- Works on displacements
- Can be highlighted or otherwise rendered in a way that reveals hard to see slick surfaces

Slick ideally has the following properties:

- Easy to apply to all instances of a material in a map
- Also easy to apply to complex brushwork with many different materials
- Easy to convert non-slick maps into slick maps
- Can be applied to arbitrary brush entities
- Can be applied to models

### Describe the solution you'd like

A slick surface property could be added that is retrieved on every ground trace. The mapper would have multiple different ways to add this surface property to suit different use cases.

- A `func_slick` entity that the compiler converts back to world geometry, but with the extra surface property added. This would be the fastest way to make a brush slick. ("I want this really complex brush thing to be slick without editing every single material" or "I want this material to be both slick and non-slick but I don't want to make two identical versions")
- A parameter that can be added to VMTs and props. This would allow brush entities and displacements to be slick. ("I want this ice texture to always be slick" or "I want this iceberg prop to always be slick")
  - We can provide an invisible slick tool texture that can be overlaid on existing geometry.
- A VBSP compile parameter that just adds the slick surface property to everything in the map. This allows making slick variations of existing maps without editing every single material or trying to make the whole map a giant entity.

From the point of view of the movement code, all of this would look exactly the same, just a surface property that is either there or it isn't.

**Comment by hexaflexahexagon** [comment]
Should func_slick and func_slide be separate entities? Are there any functions besides name alone where they differ that can't be applied as a kv for func_slide or something? etc

**Comment by chovelyoukai** [comment]
#### Reasons to not have them the same:
- Having them be the same entity would either mean that the existing slide options would have to be implemented in defrag (and wouldn't be available with all the other options,) or that they would be ignored in defrag.
- It conflates the two technically different mechanics of slick and sliding. Personally I don't think that's a problem at all but @jason-e and I have had a lot of discussions about it and I don't think we've agreed on anything yet.
- `func_slide` operates by having unique content bits. That's required for `func_slide` because it has to be an entity to have customizable settings. Slick doesn't need customizable settings so it can just be a surface property. We could get around this by making `func_slide` have both the slide contents and the slick surface. Now that I think about it though, I don't know why a surface property alone wouldn't also be possible.
- `func_slide` is always overridden by non-slide flush surfaces. Slick needs the opposite behavior, and that might be difficult to implement.

#### Reasons to have them the same:
- Having one entity for both behaviors would improve compatibility of maps between modes (though it would still make gamemovement more complex, because now it needs to look for both surface properties and content bits, and this would be doable anyway even with two separate entities.)
- One less entity to make, I guess.

I'd also like to note that sliding, as in hit-the-ground-but-don't-get-grounded, does not belong in defrag. It would break a lot of internal consistency, since so many different effects occur when you become grounded, and currently there is no distinction between "hitting the ground" and "getting grounded." There's also really no demand for another zero friction mechanic.

**Comment by hexaflexahexagon** [comment]
Different entities seems the best to me then. `func_slide` will do nothing in defrag while `func_slick` will do nothing in every other mode, presumably.

**Comment by chovelyoukai** [comment]
For now they can do nothing in opposite modes, but I think that people playing dfwc2017-6 in bhop, or people playing bhop_everfast in defrag, will be surprised and disappointed when normally zero-friction ground isn't zero-friction anymore because you crossed the Quake III Barrier.

In my opinion, the two mechanics are conceptually close enough to be interchangeable, despite being technically different. My solution for the future is to have all slick surfaces in not-df act like slide with default settings, and have all `func_slide`s in df act like plain old slick, regardless of their settings. I think it may be more complicated for us, but a few extra lines of code is worth it to make our players' and mappers' lives simpler.

**Comment by Gocnak** [comment]
Hey @chovelyoukai is this implemented with the recent changes?

**Comment by chovelyoukai** [comment]
Yes, though we can do follow on issues for additional funcionality like slick on displacements.
