### ISSUE TITLE
Consider adding `jump` as an alias for the map selector 

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1821]
Really tiny thing but the rj/sj thing throws so many people off that it may be worth adding jump as a hidden alias for the map selector search bar ONLY. We still want people to learn the new gamemode names, this just seems like a potential QoL thing.

To be explicit if somebody types "jump" "jump_" or mayyybe even "jum" it should show results for "rj_" and "sj_" in addition to the normal results (like a map called "bhop_jump_around").

**Comment by Gocnak** [comment]
This is actually a website issue, as all the UI does is forward to the API search query. We could on the server filter jump_ into the two modes, but I also think this might not be necessary as in the future the gamemode filters will properly search for those modes too.

**Comment by hexaflexahexagon** [comment]
well I assume it would be easier to do it via panorama and to just modify the search parameter, or do some hackery and do 2/3 API requests and just merge all the de-duplicated results in at once. though not sure on the tech behind any of these elements so could be wrong.

By gamemode filters do you mean like the ( Surf ) ( Bhop ) ( Rocket Jump ) ( etc ) buttons on the map selector? because if so those already work perfectly fine, they're just slightly out of the way for people newly transitioned (happy pride month) from tf2 to mmod so I'd like some text search bar hackery in addition.

**Comment by Gocnak** [comment]
The gamemode buttons do not currently search on the site. It's only map name and tier. We will be hooking up all the map selector filters to the site as the rewrite continues. I say site side because otherwise the work would also have to be duplicated for the frontend site's search functionality.

**Comment by Gocnak** [comment]
Too specific of a case, we want people to learn the new prefixes for jump modes.
