### ISSUE TITLE
`$bumpframe` is ignored by the `PBR` shader

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#1825]
### Describe the bug

The `AnimatedTexture` proxy allows materials to cycle through the frames of their animated VTFs ([VDC page](https://developer.valvesoftware.com/wiki/List_Of_Material_Proxies#Texture_manipulation)).
The PBR shader however ignores `$bumpFrame` or it was not implemented to begin with. In the same vein, `$mraoFrame` should be implemented to allow cycling through `$MRAOTexture`, keeping compatibility with the proxy. 
### How To Reproduce

1. Run `map dev_PBRTextureFrame`
2. Once in, you should immediately see a spinning cube, but with some details not moving. This is `$bumpFrame` in question not working

### Issue Map

| **Test Map:  `dev_pbrtextureframe`** |
| :---: |
| <img src="https://user-images.githubusercontent.com/35622748/172673204-06d504dd-d3c6-4f37-b6b4-edfc1574eba0.png" width=450> |
| [Download](https://github.com/momentum-mod/game/files/8863613/PBRFrame.zip) |

### Expected Behavior

The proxy should be able to modify the textures as intended

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by hexaflexahexagon** [comment]
im not sure if something got broken or if I'm missing a material or something but loading the test map I don't see any spinning cube: 
![image](https://user-images.githubusercontent.com/62961532/175849931-925685de-9c0a-488d-89cd-1b10d9ffb5a7.png)

**Comment by VortexParadox** [comment]
![chaos_k8YlMDBjBU](https://user-images.githubusercontent.com/35622748/175851721-3660a16f-4d2f-4dd3-b3c1-256faf71ef69.gif)

Fixed!
