### ISSUE TITLE
Player spawns improperly on portal 2 maps

### ISSUE THREAD

**Issue by noruVitbar** [momentum-mod/game#1828]
### Describe the bug

When loading up portal 2 maps made with the builtin level editor of portal 2, the player spawns inside a box, wich is meant to run some scripts and then telepeort the player to antoher box and then to the starting elevator.

### How To Reproduce

1: Download (mostly) any map made for portal 2 that spawns you in an elevator
2: Load the map using the `map` console command
3: Spawn in a box

### Issue Map

https://www.mediafire.com/folder/2l6cm1ybdetfr/portal2maps

### Expected Behavior

The player should spawn in the box, and be teleported.

### Operating System

windows 10 (probably non system specific issue)

### Renderer

DX11 (default)

**Comment by lvaness** [comment]
We are not planning to ship VScript with the game at this current time. Therefore, I don't see any way we would be able to fix this in a reasonable way. I also don't really see why you would want to play any PeTI maps in Momentum as half of the entities don't even exist
