### ISSUE TITLE
Gravity too high to play on some maps made for other games (low priority)

### ISSUE THREAD

**Issue by noruVitbar** [momentum-mod/game#1829]
### Is your feature request related to a problem?

When i loaded up bhop_rgb_v5 (a map made for portal 2) some jumps where impossible because portal 2's gravity is 600 and momentum mod's is 800.

### Describe the solution you'd like

The game should recognize the game the map was made for and adjust the gravity acording to the game its meant for. (ex: portal 2's gravity is 600, csgo's gravity is 800, that makes for some imposible jumps in portal 2 maps)
I know it's hard to code, but it's doable

### Describe alternatives you've considered, if any.

Adjust the trigger_catapults to make the jumps doable

**Comment by lvaness** [comment]
This seems like a tall order to support unofficial maps when you can just change the gravity value yourself when playing it. Figuring out what game the map was made for just from the BSP is not trivial at all

**Comment by tsa96** [comment]
Official maps will fix this up in porting, doing the technical legwork here for unofficial maps is just not worth it, the user should just set the cvars themselves.
