### ISSUE TITLE
Right Click Cursor visibility in watching replay

### ISSUE THREAD

**Issue by Zylviij** [momentum-mod/game#1830]
### What feature is your improvement idea related to?

I intuitively use right click to make the cursor visible in the replay viewer, but the "correct key" is ctrl.

### Describe the solution you'd like

To make the cursor visible on the end of run screen, you right click. I'd like the replay screen overlay to have matching behavior.

### Additional context

![image](https://user-images.githubusercontent.com/7347274/173423931-6a77c09e-054a-429d-8790-bba45cebf5f3.png)

**Comment by lvaness** [comment]
duplicate

**Comment by Zylviij** [comment]
Hey, @bltech did you know that you can [link to the issue](https://github.com/momentum-mod/game/issues/1771) that is duplicated? It makes it much easier to follow!
