### ISSUE TITLE
Rotating brushes in-game with Solid Type "BSP" breaks them

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1831]
### Describe the bug

If you rotate a brush in-game that has the Solid Type of "BSP", the collision gets wonky and doesn't act correct.
The rotation can be with any input to it such as `addoutput "angle 0 90 0"` or `SetAbsAngles "0 90 0"`

https://user-images.githubusercontent.com/62808028/174500908-51fea11d-9b6f-4d24-b6f7-a47c65facca9.mp4

### How To Reproduce

1. Create a map that has a brush that can modify its Solid Type to BSP
2. Have some form of input that causes that brush to rotate in the map
3. Touch it

### Issue Map

N/A

### Expected Behavior

The collision should dynamically update properly with the brush.

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by Ninja-Cookie** [comment]
The examples used in the issue are all seemingly fixed, however some jank still exists with things not rotated by 90 degrees, or compiled starting non-90 degrees.

https://user-images.githubusercontent.com/62808028/189974523-b6083b8c-1899-46ce-8a4d-60dfa017c9f5.mp4

https://user-images.githubusercontent.com/62808028/189974791-5394cb8c-1ca2-4141-855b-6ee9d3613bfe.mp4

**Comment by jason-e** [comment]
This looks like normal behavior. The game does collisions with entities rotated from their normal position in the coordinate space of the entity, and even in that space, the player's bounding box must be axis aligned (this is a limitation of BSP collision and also what makes it efficient). The effect is that the player's bounding box is essentially rotated along with the entity but only for collisions with that entity, which is an unintuitive feeling. You can also get slightly stuck on rotated entities as well for some reason but I think that's also normal.
