### ISSUE TITLE
Trigger with Explosive Only flag still gets activated by clients

### ISSUE THREAD

**Issue by ashley-cervidae** [momentum-mod/game#1838]
### Describe the bug

A trigger with the Only Explosives flag still gets activated when a client enters the trigger volume.

### How To Reproduce

1. Make a trigger_multiple brush entity with the flag set to Explosives Only (preferably with an test output to an entity)
2. Compile the map, enter the trigger volume in game

### Issue Map

I created the following test map demonstrating the issue.

[explosive_only_trigger_test.zip](https://github.com/momentum-mod/game/files/9108613/explosive_only_trigger_test.zip)

### Expected Behavior

A client should not be able to activate a trigger volume that has the Explosive Only flag

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Hey, does this still happen on the latest version?

**Comment by ashley-cervidae** [comment]
It's been fine for at least a few weeks as far as I'm aware, just tested it again just then and can confirm it's not happening.
