### ISSUE TITLE
Some prop_dynamic renderfx are not supported

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1842]
### Describe the bug

The support for prop_dynamic in Momentum Mod do not match the behavior of CS:S. Firstly, in momentum props meant to be static do not appear in game when left in a map as a prop_dynamic. This means that prop_dynamic_override has to be used more often while in CS:S it appears normally.

Secondly, the renderfx settings distort (15) and hologram (16) are not labeled consistently in the momentum fgd and do not render at all in game. Renderfx Fade Near (26), Spotlight FX (24) and Cull By Distance (TEST) (23) are omitted from the fgd although they may not be fully functional in CS:S either. The rest seem to work 1:1 with CS:S.

This behavior occurs regardless of directx settings.

![momentumfx1](https://user-images.githubusercontent.com/49064563/181661254-3116f062-7ded-47fd-9ed4-7524ac34bb50.gif)

![cssfx1](https://user-images.githubusercontent.com/49064563/181661258-87fe34ca-6b31-4439-9bb0-9357e881fd49.gif)

### How To Reproduce

- Create a map for CS:S featuring a prop_dynamic with renderfx set to distort.
- Load the map in momentum, it will not appear.

### Issue Map

I ran into this issue when experimenting with an unreleased map but I have made a map specifically to test these issues
[prop_dyn_fxtest.zip](https://github.com/momentum-mod/game/files/9215151/prop_dyn_fxtest.zip)

### Expected Behavior

Legacy renderfx should be supported in order to provide support for any CS:S maps that may want to use it.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by xen-000** [comment]
The first issue is caused by a difference in assets used by each game. Both HL2 (which we use) and CS:S have that same dumpster model but in CS:S it doesn't have `prop_data` keyvalues, while in HL2 it does. If a model has `prop_data` then it can only be used in prop_physics or any of the _override props.

**Comment by Gocnak** [comment]
Is this still happening on the latest push?

**Comment by patrickmoc** [comment]
Seems fixed, the prop_data thing mentioned by xen still causes the test map to be missing models but that is outside the scope of this issue.
