### ISSUE TITLE
Color the `"" isn't a valid key` output

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1850]
### What feature is your improvement idea related to?

The impact of a key not having a bind vs not existing are pretty vastly different for how similar the following two message are at a glance:

![image](https://user-images.githubusercontent.com/62961532/182494227-485b2e41-b5a1-4778-b1b1-d4c70558f41f.png)

This is mostly just noticeable when fiddling with keypad bindings because someone had the bright idea to not label buttons by the obvious number key but to instead use the base name like some sort of num-unlocked wizard, but I feel like it's still a nice touch in general when binding the other keys. 

### Describe the solution you'd like

Make the `[engine] "kp_pgdown" isn't a valid key` text orange like the map-doesn't-exist error in the above screenshot is

### Describe alternatives you've considered, if any.

You could also make it red I guess but that's a bit aggressive

**Comment by tsa96** [comment]
This should be in next update
