### ISSUE TITLE
texture loading fails with lightmapped_4wayblend shader on dx11

### ISSUE THREAD

**Issue by RoadyBhop** [momentum-mod/game#1858]
### Describe the bug

textures are failing to load when ising lightmapped_4wayblend shader on a displacement. further discussion in #mapping channel here https://discordapp.com/channels/235111289435717633/235121530609205249/1013948331686383686

### How To Reproduce

download .vmt and .bsp provided by vortex

https://discordapp.com/channels/235111289435717633/235121530609205249/1013945487801454632

https://discordapp.com/channels/235111289435717633/235121530609205249/1013944610432749710

load the map, type mat_reloadallmaterials and see changes on parts of the blend being loaded

### Issue Map

https://discordapp.com/channels/235111289435717633/235121530609205249/1013944610432749710

### Expected Behavior

the textures should load in normally as they do on dx9 or csgo

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
I had a fix for this, but there was another issue with 4wayblend on DX11: https://discord.com/channels/235111289435717633/235121530609205249/1017393584800026643

Tracking that in this issue too.

**Comment by Gocnak** [comment]
Does this still happen on latest release?
