### ISSUE TITLE
Defrag: Ammo system

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#1861]
### Is your feature request related to a problem?

Defrag should have an ammo system.

### Describe the solution you'd like

Weapons have magazines (ammo limits) that can hold a particular amount of ammo (200) by default. Mappers should be able to set, give, and remove ammo from the player, and also set the ammo limit. This can be implemented with player inputs like SetAmmo and AddAmmo.

Setting the player's ammo anything less than 0 should be equivalent to infinite ammo.

This system could definitely be extended to other modes as well.

**Comment by chovelyoukai** [comment]
Upcoming ammo system implements this partially. Splitting this issue to handle the other elements.

**Comment by Gocnak** [comment]
The ammo system was implemented, is this safe to close?

**Comment by chovelyoukai** [comment]
Yep
