### ISSUE TITLE
Defrag: Change vintage physics

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#1862]
### Describe the bug

Vintage physics are in need of tweaking.

### How To Reproduce

play vintage

### Issue Map

N/A

### Expected Behavior

- Autohop
- `sv_friction 4`
- Air accel should be made more like Quake 1

### Operating System

N/A

### Renderer

DX11 (default)

**Comment by Snowiez** [comment]
+ sv_accelerate 10
