### ISSUE TITLE
Paint not displaying for the player using it

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1865]
### Describe the bug

Paint won't display or even make a noise for the player trying to use it, but for other players it makes the noise but displays large white dots

### How To Reproduce

1. try to paint
2. observe it doesn't work
3. confirm another player see's white dots

### Issue Map

Any map

### Expected Behavior

Paint should both work and use the settings the player has set

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
Believe this was fixed recently
