### ISSUE TITLE
Change the loading screen tip that says brightness only works in fullscreen

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1868]
### What feature is your improvement idea related to?

We now have `mat_brightness` which works in borderless windowed so we can edit this loading tip to reflect that:

https://github.com/momentum-mod/game/blob/09f0c8a65181daa454e559ef0cef9324e9b30420/mp/game/momentum/resource/momentum_english_ref.res#L729

:^)

### Describe the solution you'd like

Remove the message in the parenthesis

**Comment by tsa96** [comment]
Goc fixed this on POEditor 3 weeks ago
