### ISSUE TITLE
Crash after `kill`-ing rocket/stickybomb/conc

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1869]
### Describe the bug

Sending a `kill` input to a rocket, stickybomb, or conc will result in the game immediately crashing upon leaving the map.

### How To Reproduce

1. Load the given BSP with either RJ, SJ (default), or Conc movement
2. +attack, notice the projectile is immediately `kill`-d
3. `reload` or `disconnect` and observe crash

### Issue Map

VMF: https://cdn.discordapp.com/attachments/671175695648423959/1016904910714970163/sj_use_after_free.vmf
BSP: https://cdn.discordapp.com/attachments/671175695648423959/1016904910958231602/sj_use_after_free.bsp

### Expected Behavior

no crash

### Operating System

win 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Does this still happen on latest version?

**Comment by hexaflexahexagon** [comment]
appears to be fixed on the given test map
