### ISSUE TITLE
postprocess_controller Vignette acts incorrectly if you've changed resolution on maps with no light

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1880]
### Describe the bug

Very weirdly specific bug, If you have changed your resolution at any time during Momentum Mod, even before going into the map, postprocess_controller's Vignette doesn't work correctly.

- Only happens on maps with no light.
- You do not have to be in the map when you changed resolutions.
- The effect is permanent and can't seem to be fixed unless from rebooting Momentum Mod.
- Happens on both DX11 and DX9.

https://user-images.githubusercontent.com/62808028/190513448-87d96b83-4738-4d07-b85b-537de1879996.mp4

https://user-images.githubusercontent.com/62808028/190518663-9abd5fe5-69da-40ea-b691-e15f5d809dce.mp4

![image](https://user-images.githubusercontent.com/62808028/190513183-a5fdcfe5-c75c-4ebb-8c1d-9d289ed60dcf.png)
(These settings may look odd but are not the direct cause of the issue)

### How To Reproduce

1. Create a postprocess_controller on a map with no compiled light that uses some kind of visable Vignette settings.
2. Enter game, change resolution to anything else, load the map.

### Issue Map

N/A

### Expected Behavior

I guess not to do this? It's such a specific bug, but still a bug.

### Operating System

Windows

### Renderer

DX11 (default) & DX9

**Comment by Gocnak** [comment]
This should be resolved in 0.9.2, please re-open the issue if it's still happening after the latest updates.
