### ISSUE TITLE
surf_me incorrectly playing at sv_maxvelocity 3500

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#189]
`surf_me` maxvelocity should be `sv_maxvelocity 10000`; incorrectly playing at `sv_maxvelocity 3500`

Submitted by Beetle179

**Comment by Gocnak** [comment]
Solution is to remove the FCVAR_DEVELOPMENTONLY convar flag and make it manually listen for changes. The change has to be allowed via `-mapping` launch param.

Automatic changes need to probably come later through track properties (#233).
