### ISSUE TITLE
Add some sort of alternative to filtering by model name

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1896]
### Is your feature request related to a problem?

Currently if you filter by model name for something (e.g. weapon models or weapon projectiles) this can be bypassed by a client through a local override script. This is most noticeable if somebody wants to, say, filter something for "rockets" and enters the model name for the mmod rocket. This filter will work until somebody plays the map with the TF2 rocket launcher override which uses a different rocket. 

This could also be used maliciously to bypass certain map checks if a player knows that models are being filtered for, though the above is a much more concerning issue since it would harm normal players. Malicious usage can be swept up by run validation.

### Describe the solution you'd like

Perhaps add a `filter_momentum_projectile` or similar which will have options for common projectiles like Rocket, Stickybomb, Conc, [All the defrag weapons with projectiles]. That way code can determine what a rocket is and the mapper doesn't have to worry about the actual file name.

Repro map:
https://cdn.discordapp.com/attachments/671175695648423959/1021971570400436304/rj_model_filtertest.bsp
https://cdn.discordapp.com/attachments/671175695648423959/1021971570060693605/rj_model_filtertest.vmf

On loading this map you can shoot with the momentum rocket launcher and you will be teleported to a blue room. If you shoot while using the TF2 stock or original override script you will not be teleported as the rocket no longer matches the applied filter. 

### Additional context

We could also create some intelligent over-arching solution that would _also_ catch use cases that go beyond player projectiles (Like filtering to make sure a soccer ball hit a goal or something), but I have no clue how that would work. Plus, people would have to intentionally try to game those maps. Plus, run validation will catch it anyhow. Just something to keep in mind if anyone gets any smart ideas.

**Comment by SlidyBat** [comment]
This should be doable already using `filter_activator_class` to check for classname
Some classnames for the projectile entities:
- momentum_stickybomb
- momentum_rocket
- momentum_concgrenade
- mom_grenade_projectile
- momentum_df_rocket
- momentum_df_plasma
- momentum_df_grenade
- momentum_df_bfg_rocket

**Comment by SlidyBat** [comment]
Confirmed by Ninja Cookie that `filter_activator_class` works for this. If we find a case where it doesn't match our needs, can reopen this issue.
