### ISSUE TITLE
Infrequently, times are not uploading

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#190]
Still not exactly sure as to cause. API request log of when it failed once:
```
Recording Stopped! Ticks: 4306
CAPIRequests::EndRunSession {
  code int( 400 = 0x190 )
  method POST
  URL https://momentum-mod.org/api/maps/7/session/40395/end
  error {
    error {
      code int( 400 = 0x190 )
      message Timestamp length does not match!
    }
  }
}
```

guy151: https://pastebin.com/Rz5QK20p
guy151: https://pastebin.com/ZRUAGMgT

Spy Complex: https://pastebin.com/9rhYsg3n

Aux: https://pastebin.com/evmmJhea

Submitted by several users

**Comment by xen-000** [comment]
This seems to be due to missing the first checkpoint zone on surf_mesa, so any further reports of this error should include the map to verify that it's a zone issue.

**Comment by Gocnak** [comment]
Initial fix is in https://github.com/momentum-mod/website/pull/339/commits/eba82974c874fa12879db1a0946bedecde293b27 and we should urge players to use `mom_api_log_requests 1` during runs.

Closing for now unless this pops back up again.
