### ISSUE TITLE
Something is wrong with filter_momentum_player_state

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1900]
### Describe the bug

I don't quite understand what is going on, none of the values seem to differ, however if you initially spawn the "filter_momentum_player_state" entity, its filtering settings will not work until you have changed at least some kind of setting in "Player State"

### How To Reproduce

1. Create a trigger that does something obvious when you touch it
2. Create the "filter_momentum_player_state" entity, change its filter mode to "Disallow entities that match criteria" only, and give it a name.
3. Put the filter on the trigger.
4. Go in-game and you will notice it will always allow you to use the trigger regardless of the filters settings.

Alternatively:
1. Create a trigger that does something obvious when you touch it
2. Create the "filter_momentum_player_state" entity with NO changes and give it a name.
3. Put the filter on the trigger.
4. Go in-game and you should notice the trigger does nothing at all, even if you do what the filter says its filtering.

### Issue Map

N/A

### Expected Behavior

It should follow the filters settings from the beginning without needing any changes.

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by jason-e** [comment]
Assuming this is fixed since we remade this entity.
