### ISSUE TITLE
point_worldtext input "SetMessage" does not change passed 7 letters

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1905]
### Describe the bug

If you do "SetMessage" to a point_worldtext, for example `SetMessage "Momentum Mod"`, it will only set it to "Momentu", however, doing directly `AddOutput "message Momentum Mod"` will set it correctly.

### How To Reproduce

Download this map, step on white for correct result using AddOutput, step on red for bugged result using SetMessage.
[test_setmessage.zip](https://github.com/momentum-mod/game/files/9730564/test_setmessage.zip)

### Issue Map

N/A

### Expected Behavior

Display full text.

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Will be in next release.
