### ISSUE TITLE
Javascript exception when entering settings menu 

### ISSUE THREAD

**Issue by ChillWithMill** [momentum-mod/game#1906]
### Describe the bug

Javascript exception when opening settings menu for the first time while holding down "Escape" key.
Does not happen, if you already opened the menu once.

![image](https://user-images.githubusercontent.com/93768467/194542144-69b40f2c-e4f6-4615-abc8-217e529b0488.png)

### How To Reproduce

1. Start the game
2. On main menu screen, hold escape key down
3. Click settings icon
4. See javascript error

### Issue Map

Issue happens in the main menu of the game

### Expected Behavior

When I hold down Escape key and click to open settings menu, menu should immediately close.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by tsa96** [comment]
brae's gonna be reworking speedometer code in the near future so should be fixed then!
