### ISSUE TITLE
Field of view can be set to broken numbers

### ISSUE THREAD

**Issue by ChillWithMill** [momentum-mod/game#1908]
### Describe the bug

In the settings menu, maximum Field of view is 130 according to the slider. 
Typing in a number to the box allows you to set FOV up to 179.
Stays through restart.

![image](https://user-images.githubusercontent.com/93768467/194603598-1c3f24ea-e258-4be9-b5bb-5d932658a437.png)

### How To Reproduce

1. Open settings for video
2. Click on the text box next to "Field of view" slider
3. Set value to 999
4. Value defaults to 179, highest it will go

### Issue Map

Issue happens in settings menu

### Expected Behavior

When you enter a larger number than what the max FOV should be, it should default to the max value.
Slider allows you to set FOV of 130, entering a value above 130, should default to 130.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by tsa96** [comment]
179 is the maximum value the underlying cvar (I think `fov_desired`) can be set to. So the slider component is using the cvar's min/max values, not the `min` and `max` XML attributes. I agree it'd make more sense for it to be the latter. Clearly the slider component is a bit buggy (esp with percentage values), sounds like some bunch of easy fixes to all do at once - so this and https://github.com/momentum-mod/game/issues/1909

**Comment by tsa96** [comment]
We're going to keep allowing the out of bounds numbers, but I've added a little warning symbol to show that.
