### ISSUE TITLE
Brightness can be set to a value of 1000

### ISSUE THREAD

**Issue by ChillWithMill** [momentum-mod/game#1909]
### Describe the bug

In the settings menu, when you click into the text box that shows brightness as a percentage, and click out of the box, it defaults the value to 1000.

What ever value you type into this box, it will default to 1000.
Using the slider resets normal behaviour.

![image](https://user-images.githubusercontent.com/93768467/194605296-15a8799b-cfbc-402e-9866-7784e5d5fac0.png)

### How To Reproduce

1. Open video settings
2. Click into the textbox next to the "Brightness" slider
3. Click outside the box
4. Value sets to 1000

### Issue Map

Issue happens in settings menu

### Expected Behavior

Brightness is shown as a percentage in the menu ranging from 70% to 130%.

You should only be allowed to add values between 70-130 in the textbox.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by tsa96** [comment]
Yeah there's been weird behaviour with percentage-based ChaosSettingsSliders for a while now. Can't find an existing issue for it actually though. So we need to go into the ChaosSettingSlider component and clean stuff up, can do https://github.com/momentum-mod/game/issues/1908 and this together.

**Comment by ChillWithMill** [comment]
Seems like the crosshair setting text boxes also behave this way, where the value entered into the text box can be any value, and its accepted

**Comment by tsa96** [comment]
(Was closed by mistake)

**Comment by tsa96** [comment]
If it's a slider setting they'll all behave like this yes, as all sliders are instances of the ChaosSettingsSlider component

**Comment by tsa96** [comment]
Okay the `1000` is two things, 1. that the percentage sign was being cut off due to the max char limit; gonna up that. 2. percentage handling is just wrong, I've pushed a fix for that on our engine repo.
