### ISSUE TITLE
Plugins can be loaded and aren't checked when submitting a time

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#191]
fps_god run on surf_ace: https://momentum-mod.org/dashboard/runs/559

This run abuses nolem's Source TASing tool. fps_god basically just loaded the tool and used the plugin to set an impossible time.

Submitted by fps_god

**Comment by Gocnak** [comment]
A really unfortunate side to this is that it requires engine to completely disable plugin loading. We could spam `plugin_pause` every frame or something until we get engine...
