### ISSUE TITLE
trigger_look does not have the correct Outputs

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#1912]
### Describe the bug

trigger_look has two "OnTrigger"'s, and does not have "OnNotLooking" or "OnLooking", I don't know what other outputs it is supposed to have but it's very messy.

### How To Reproduce

N/A

### Issue Map

N/A

### Expected Behavior

Have the correct Outputs for the triggers

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by tmob03** [comment]
> trigger_look has two "OnTrigger"'s, and does not have "OnNotLooking" or "OnLooking", I don't know what other outputs it is 
> supposed to have but it's very messy.

The two OnTrigger's is an FGD issue I believe, I'll look into it. 

With `ent_info`, I get these outputs: 
`[client]   output: OnTimeout
[client]   output: OnTrigger
[client]   output: OnStartTouch
[client]   output: OnStartTouchAll
[client]   output: OnEndTouch
[client]   output: OnEndTouchAll
[client]   output: OnTouching
[client]   output: OnNotTouching
[client]   output: OnUser1
[client]   output: OnUser2
[client]   output: OnUser3
[client]   output: OnUser4
[client]   output: OutUser1
[client]   output: OutUser2
[client]   output: OutUser3
[client]   output: OutUser4`

and from `ent_info_datatable` I get these values specfic to trigger look, although I'm not exactly sure how they are to be intrepreted as they're internal names. Maybe someone from the coding side can give a little insight:
`[client]   =========| CTriggerLook |=========
[client]    EHANDLE (13): m_hLookTarget
[client]    FLOAT (1): m_flLookTimeTotal
[client]    TIME (16): m_flLookTimeLast
[client]    FLOAT (1): m_flTimeoutDuration
[client]    BOOLEAN (6): m_bTimeoutFired
[client]    EHANDLE (13): m_hActivator
[client]    CUSTOM (11): m_OnTimeout
[client]    VOID (0): CTriggerLookTimeoutThink
[client]    FLOAT (1): m_flFieldOfView
[client]    FLOAT (1): m_flLookTime`

(Formatting got messed up, each [client] is a new line)

**Comment by tmob03** [comment]
Alright yeah I think I see why it has two `OnTrigger` outputs, it's defined in `TriggerOnce` base, which `Trigger` inherits from, which then `trigger_look` inherits from that. Then for some reason `OnTrigger` is redefined in trigger_look (in fgd!)

**Comment by tmob03** [comment]
Upon further research it does have the correct outputs, `OnTrigger` is fired when the player is in the trigger and has been looking at the target for the specified amount of time. Definitely could be renamed to not be so obtuse though

**Comment by tmob03** [comment]
Upon even further research, it seems that `notlookingfrequency` got directly inherited from the Black Mesa fgd, as that is the only instance of it online, in black mesa's base.fgd. It was never in any other game

**Comment by Ninja-Cookie** [comment]
> Alright yeah I think I see why it has two `OnTrigger` outputs, it's defined in `TriggerOnce` base, which `Trigger` inherits from, which then `trigger_look` inherits from that. Then for some reason `OnTrigger` is redefined in trigger_look (in fgd!)

trigger_once also kills after triggering, so that's likely why trigger_look gets killed also regardless, which shouldn't be the case. (#1911)
