### ISSUE TITLE
Weapon Desirability set to "Required weapons only" causes game to close on map load

### ISSUE THREAD

**Issue by ChillWithMill** [momentum-mod/game#1914]
### Describe the bug

Setting the weapon desirability in settings to "Required weapons only" causes the game to crash or close without an error when loading certain maps.
Affects multiple maps.

### How To Reproduce

1. Start the game and go to settings
2. Set "Weapon desirability" to "Required weapons only"
3. Launch the map "df_modcompo13" or "df_precision"
4. See game crash or close without an error

### Issue Map

df_modcompo13
df_precision

### Expected Behavior

Loading into a map with "weapon desirability" set to "Required weapons only" should spawn you in the start zone with only the required weapons for the map.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
I'm unable to replicate this

**Comment by ChillWithMill** [comment]
I too am unable to reproduce this issue now. Even when I did do it multiple times, and changing the weapon desirability caused it to close or work consistantly, and it started to happen after I had changed that setting. 

Need to try to reproduce it again and come back to you, maybe get it on video as well.

**Comment by ChillWithMill** [comment]
Well, im back. The difference since last time was me adding the -mapping launch command. 
With -mapping removed I was able to reproduce the issue again.

Below a video of the bug
[https://www.youtube.com/watch?v=K-L0dmoKUk4](https://www.youtube.com/watch?v=K-L0dmoKUk4)

**Comment by Gocnak** [comment]
Hey, does this still happen on the latest update?

**Comment by ChillWithMill** [comment]
Hello,

i am unable to reproduce the crash on patch 0.9.11 using the same steps as i did in my video.
