### ISSUE TITLE
[DX11] Game is out of focus after tabbing back in while on a map

### ISSUE THREAD

**Issue by masogtm** [momentum-mod/game#1915]
### Describe the bug

Tabbing out by using the Windows key & tabbing back in causes the game to be out of focus (mouse movement only moves the cursor instead of the player's camera, the game appears to be about 15 fps when moving around with WASD), forcing user to tab back out & back in again to fix it. 
**The issue never occurs with the normal Alt+TAB method of tabbing out/back in. The issue also does not occur in DX9.**

### How To Reproduce

1. Boot Momentum Mod in DX11
2. Navigate to Settings>Video>Display Mode and set it to Fullscreen
3. Launch any map
4. Press the **Windows** key to tab out of the title
5. Focus on any other app (e.g.: left mouse click on a Discord/Chrome window)
6. On the Windows task bar, left mouse click on Momentum Mod to tab back into it
7. Observe the game not receiving mouse inputs and being very choppy when moving with WASD

### Issue Map

Any map.

### Expected Behavior

The game is in focus when brought back to foreground.

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by SlidyBat** [comment]
Thanks for the clear repro steps, heard about this bug a few times, but couldn't replicate it myself until now.
Should be fixed in next update.

**Comment by Gocnak** [comment]
Please let us know if this is not fixed.
