### ISSUE TITLE
You can trick the startzone, effectively avoiding the start-on-jump system

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#192]
You can trick the startzone by exiting the zone, strafing back to re-enter it, and then falling out of it, all in one jump; effectively avoiding the start-on-jump system.

Thanks to Garanimal for video: 
https://www.youtube.com/watch?v=AhRMkWdrz3E

Submitted by several users

**Comment by SlidyBat** [comment]
Should be fixed in da7d3510e0df2ceb6fc313dd57220ce97358d15b, needs more testing before being closed to make sure there aren't any regressions in that commit though.

**Comment by SlidyBat** [comment]
Tested it out and seems to work fine, so I'm closing this as solved. Would appreciate it if anyone else tests this however.

**Comment by Gocnak** [comment]
Re-opening due to #228. See that issue for more details.
