### ISSUE TITLE
Read Access Violation removing Defrag weapons

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#1920]
### Describe the bug

Setting defrag weapons to "Required Weapons Only" then reloading/loading another map can result in a read access violation and crash.

Sentry issue ID is 3560954624, probably quite an easy fix but I'm struggling to reach it in debugger without getting cockblocked by asserts.

### How To Reproduce

Open a Defrag (with weapons, I tested on df_precision) and set weapon desirability to "Required Weapons Only". Reload the map.

https://www.youtube.com/watch?v=G67324jLIGM

### Issue Map

df_precision

### Expected Behavior

...

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by chovelyoukai** [comment]
Can't reproduce this anymore.
