### ISSUE TITLE
Bodygroup/appearance changes aren't saving correctly

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#193]
Cannot save change to appearance, it still resets to “mom_ghost_bodygroup 11”.

Tried the following:
- Added +cl_cloud_settings 0 to launch params
- Added mom_ghost_bodygroup X to autoexec

Submitted by Cabbage McGravel

**Comment by Gocnak** [comment]
I believe this was also fixed in 0.8.1. Can re-open if this happens again.
