### ISSUE TITLE
Defrag: Add hitscan weapons

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#1933]
### Is your feature request related to a problem?

Defrag is still missing the following weapons:
- Gauntlet
- Machine gun
- Shotgun
- Lightning gun
- Railgun

### Describe the solution you'd like

Add the weapons.

### Describe alternatives you've considered, if any.

The existing knife, machine gun, and shotgun are not suitable for defrag because they don't implement the same mechanics.

**Comment by Gocnak** [comment]
Will be in the next release
