### ISSUE TITLE
Defrag: Consistent map reload/entity reset mechanism

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#1936]
### Is your feature request related to a problem?

Defrag maps often have lots of entities that need to be completely reset when the map is restarted. Also, some entities may not be present in all physics modes, so a reload/reset should be done when the player changes physics.

### Describe the solution you'd like

A way to reset the global state of the map, so that it's always fresh when a run starts.

**Comment by hexaflexahexagon** [comment]
Related to https://github.com/momentum-mod/game/issues/1832 since this isn't exclusive to defrag

**Comment by Gocnak** [comment]
Savestates will accomplish this, closing.
