### ISSUE TITLE
saveloc makes certain boosters trigger twice

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#1950]
### Describe the bug

I have a bhop booster in my map that triggers OnEndTouch within the map startzone and if i place a saveloc while standing inside the trigger then teleport to that saveloc it will trigger twice. 

More specifically with +mom_saveloc_current it will always trigger twice and shoot me out immediately without even jumping. With the normal mom_saveloc_current or when teleporting to the set start mark  it will only act like that if i am already standing inside the trigger as i teleport to the loc, when standing outside the trigger and teleport to the loc it acts as expected. 

This happens even if the trigger is filtered. 

![image](https://user-images.githubusercontent.com/52294733/205723834-eaca014e-1275-4967-a322-d531bf8c56cf.png)

### How To Reproduce

1. Find a map (or make one) that has a trigger_multiple that fires a basevelocity output OnEndTouch while inside the startzone, like this: 
![image](https://user-images.githubusercontent.com/52294733/205724052-74f56e77-9487-447d-8dc6-c31e1718b7af.png)
2. Place a saveloc inside the trigger. 
3. Teleport to that saveloc either using +mom_saveloc_current bind, or while standing inside the trigger teleport to it using a the normal mom_saveloc_current command. 
4. The boost should apply twice. 

### Issue Map

I can't think of a map in the map selector that uses bhop boosters like these in the startzone so I made this little test map to show it: 
[savelocinthebooster.zip](https://github.com/momentum-mod/game/files/10157356/savelocinthebooster.zip) (compiled for css)

### Expected Behavior

I expect the same behaviour you get when the startzone is not there where you dont get boosted twice

### Operating System

Windows

### Renderer

DX11 (default)

**Comment by jason-e** [comment]
This happens for the same reason as #1891. Thanks for the extra reproduction example!
