### ISSUE TITLE
vbsp does not compile

### ISSUE THREAD

**Issue by Unusuario2** [momentum-mod/game#1954]
### Describe the bug

vbsp gives this error
![image](https://user-images.githubusercontent.com/110506367/206922110-7e0a8da7-c242-495a-8157-4800c68ada87.png)

### How To Reproduce

1.download the .vmf
2.compile

### Issue Map

[vbsp_crash.zip](https://github.com/momentum-mod/game/files/10202962/vbsp_crash.zip)

### Expected Behavior

open hammer ,then compile and it is going to give this error
![image](https://user-images.githubusercontent.com/110506367/206922334-baeea57c-ca43-442d-b751-9ddb59a26118.png)

### Operating System

windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Hi, this was fixed as a hotfix for 0.9.4. Let us know if it's still happening, but I'll close this as fixed for now. Thanks for the report!
