### ISSUE TITLE
JS Exception in chat.js

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#1958]
### Describe the bug

![image](https://user-images.githubusercontent.com/49064563/209475859-9be3699a-0879-4baa-a4db-0e3fd430d38b.png)

### How To Reproduce

1. Use chat
2. Localized strings load
3. Exception

### Issue Map

any

### Expected Behavior

The game should localize strings and not throw js exceptions

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by tsa96** [comment]
Missing `$. ` before `Localize`, very easy fix
