### ISSUE TITLE
water bug

### ISSUE THREAD

**Issue by wowzie22** [momentum-mod/game#1962]
### Describe the bug

the water texture disappear when you see it through  the rocket particles 
![Screenshot_11](https://user-images.githubusercontent.com/121638875/210152872-87878b32-cafa-4f04-9b8b-a62d512812de.png)

### How To Reproduce

just fire a rocket into the water 

### Issue Map

rj_home

### Expected Behavior

what should happen is the water disappear through the rocket  particles 

### Operating System

windows

### Renderer

DX9 (Legacy)

**Comment by VortexParadox** [comment]
For graphical bug reports the game should be running in DX11. DX9 is not supported and will be removed eventually.

**Comment by wowzie22** [comment]
> For graphical bug reports the game should be running in DX11. DX9 is not supported and will be removed eventually.

But some PCs can't run on dx11 my pc closes the game without any errors when I try running it on dx11 like close it after opening in a slipt second is there any work arounds?

**Comment by hexaflexahexagon** [comment]
i can't replicate this in dx9 or dx11, I'm guessing it's some sort of bug with older hardware.

**Comment by lvaness** [comment]
> > For graphical bug reports the game should be running in DX11. DX9 is not supported and will be removed eventually.
> 
> But some PCs can't run on dx11 my pc closes the game without any errors when I try running it on dx11 like close it after opening in a slipt second is there any work arounds?

We hear you but DirectX 11 and graphics cards supporting it have been released well over a decade ago and legacy support for DirectX 9 puts a high maintenance burden on us and is sometimes nigh impossible due to its limitations.

**Comment by wowzie22** [comment]
> > > For graphical bug reports the game should be running in DX11. DX9 is not supported and will be removed eventually.
> > 
> > But some PCs can't run on dx11 my pc closes the game without any errors when I try running it on dx11 like close it after opening in a slipt second is there any work arounds?
> 
> We hear you but DirectX 11 and graphics cards supporting it have been released well over a decade ago and legacy support for DirectX 9 puts a high maintenance burden on us and is sometimes nigh impossible due to its limitations.

Well yeah I think you should remove dx9 support if it causes you all of this trouble

**Comment by Gocnak** [comment]
Since this seems to be a DX9 bug I will close. Feel free to re-open if this still occurs on DX11.
