### ISSUE TITLE
Opening Console Opens Main Menu

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1966]
### What feature is your improvement idea related to?

Opening console opens the main menu as well, and it feels clunky to have to close both every time you want to use the console

### Describe the solution you'd like

Opening console should only open the console, not the menu as well

**Comment by Gocnak** [comment]
Should this be a toggle? Could make the console more Quake-like as an option or something.

**Comment by Arkanoid0** [comment]
There are really 2 ways to implement this, either make console able to pop up on its own over gameplay, maybe with a more quake engine look, or what i think is preferable, just make escape not close console and instead close the entire main menu, leaving console up next time you open the menu.

**Comment by hexaflexahexagon** [comment]
Personally I like option number 2 to solve this issue as it's just better UX and would fix this problem, then in the future we can do a quake-style dropdown console when somebody gets bored enough to wanna implement that on their own.

**Comment by Arkanoid0** [comment]
I agree that its better UX generally, and IIRC is more similar to how other valve games handle console.
