### ISSUE TITLE
Demos have visible jump when boarding a surf ramp

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#1967]
### Describe the bug

Any demo recorded will see a visible large jump in the camera position on playback when boarding a surf ramp. 

For more context, see the discord bug report here: https://discord.com/channels/235111289435717633/1059971147724247122 as originally reported by masog#3737. Also includes a video + example demo file on surf_cyberwave. 

### How To Reproduce

1. Open any surf map
2. Start recording a demo `record asdfasdfasdf`
3. Surf
4. Stop the demo `stop`
5. Play the demo `playdemo asdfasdfasdf`

### Issue Map

Any surf map. 

### Expected Behavior

No visible jump

### Operating System

win10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Demos aren't our focus for a while. Replays will ideally be better in every way.
