### ISSUE TITLE
Sticky Launcher Charge Sound Playing On Normal Shots

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1969]
### Describe the bug

The Sticky Launcher keeps playing the charge sound on some normal clicks

### How To Reproduce

1. Load an SJ map or equip `weapon_momentum_stickylauncher`
2. Shoot
3. Hear the charge sound play 

### Issue Map

Any SJ map

### Expected Behavior

If you just fire normal shots the sticky launcher shouldn't continue to play the charge sound

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by braem** [comment]
Technically not possible to shoot a sticky without a little bit of charge so the charge sound will always play. Unless this means it plays fully without stopping?

**Comment by Shegetz** [comment]
The issue was actually that other players charge sounds will play for you in a lobby, fixed by brae and should be added next push

**Comment by braem** [comment]
For some context:
Slidybat added weapons to ghosts and so we are now able to hear other players weapon sounds. Though weapon sounds were being emitted assuming only the local player would hear, causing everyone in the lobby to hear them from their local player.

So should apply to any sound coming from the weapon, like charging, rocket shooting, etc.
