### ISSUE TITLE
Spectate target leaving causes crash

### ISSUE THREAD

**Issue by Shegetz** [momentum-mod/game#1973]
### Describe the bug

If you spectate somebody and they change maps or quit the game, then you will crash

### How To Reproduce

1. join lobby
2. spectate another player
3. have them leave in some way
4. crash

### Issue Map

Any

### Expected Behavior

When a spectate target leaves you should not crash

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by jason-e** [comment]
Not applicable to the new replay/lobby code
