### ISSUE TITLE
16:10 resolutions cause menu problems

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#199]
https://media.discordapp.net/attachments/235125108656701440/575399274288775187/Screen_Shot_2019-05-07_at_2.10.24_PM.png

Submitted by v

**Comment by itVictor** [comment]
will update this with more screenshots where menu stuff looks weird in a few days

**Comment by itVictor** [comment]
update: issue appears to be independent of resolution for the specific picture above, actual 16:10 issues should be in #224 

As for the screenshot in the OP, it appears I do not have the ability to display the timer in hud options when other people can:

mine: 
<img width="1890" alt="Screen Shot 2019-06-22 at 6 21 26 PM" src="https://user-images.githubusercontent.com/20176719/59969735-913ea180-951a-11e9-9315-097deddb2229.png">

other: 
![image](https://user-images.githubusercontent.com/20176719/59969739-a0bdea80-951a-11e9-8ded-4bc2647b316e.png)

**Comment by fuxx** [comment]
Actually the scaling for retina displays is not respected. I haven't found a way in the SDK yet to change the scaling so the pixel density is used of the current display. Maybe its closed source in one of the libs. I made also some research in other mods and haven't yet found a solution.

**Comment by Gocnak** [comment]
Closing as we are no longer supporting Mac for the forseeable future.
