### ISSUE TITLE
Only enable Vsync option in Fullscreen exclusive

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#1999]
### What feature is your improvement idea related to?

Right now VSYNC only works in fullscreen, but this is not communitaced to the player ingame. 

### Describe the solution you'd like

Being in anything other than fullscreen can gray out the vsync option in video settings and have it say in text when you hover the vsync option.  
  
Could also just make vsync apply in other modes as well if possible. 

### Additional context

Might be related to https://github.com/momentum-mod/game/issues/1918

**Comment by tsa96** [comment]
Updated the POEditor string, and have a branch for the video settings stuff I'll PR on red tomorrow.
