### ISSUE TITLE
LookupAttachment returning null (when it shouldn't?)

### ISSUE THREAD

**Issue by RabsRincon** [momentum-mod/game#20]
Hi!

I've been using Momentum's mod to learn more about the C++ side of the Source games (I spent the whole night (GMT +1 rules!) looking through the code and learning few nice things), and as a simple task I wanted to fix the fact that the beam of the momentum_gun was spawning from player's eyes.
My first idea was to actually use the right atttachment name of the muzzle for the ak47 (since it's not `Muzzle` as shown in tutorial used to implement the momentum_gun (*https://developer.valvesoftware.com/wiki/Laserweapon*) ,  but `muzzle_flash`). But as shown in the picture, it's not working, as it returns **NULL**.

I fixed the beam by hardcodding the attachment number, but it would be great to know what is causing the discrepancy

The attached image is the momentum_gun after using the command `ent_attachments`, which shows the attachments points and names for the entity you're aimming to. At the top right corner you can see that `LookupAttachment("muzzle_flash")` is returning (**NULL**), even thought it should be returning **1**

![LookupAttachment returning null](https://cloud.githubusercontent.com/assets/5364255/8051682/dc2f09da-0e7f-11e5-98e4-dc2b69b1c652.jpg)

**Comment by fatalis** [comment]
for whatever reason the attachments on the ak are named "1" and "2"

this works:

pBeam->SetEndAttachment(LookupAttachment("1"));

**Comment by RabsRincon** [comment]
>it's probably not loading some css content and defaulting the names?

If it was defaulting the names, then `ent_attachments` shouldn't be showing the `muzzle_flash (1)` name, but `1 (1)` , isn't it?

But the game shows `muzzle_flash` as the name (as shown in the *in-game* picture) for the attachment number 1, that concerns me :/ .

**Comment by fatalis** [comment]
that ak on the floor isn't a view model

**Comment by RabsRincon** [comment]
Ok, yeah, forgive me, you're **totally** right.

To clarify then,
>it's probably not loading some css content and defaulting the names?
is wrong. The attchments names are **1** and **2** even in CSS


![CS:S V_Model Attachments names](https://cloud.githubusercontent.com/assets/5364255/8072865/06af4a4c-0f1d-11e5-83d7-368fd260a805.png)


Sorry for missing the viewmodel fact and **thanks for helping** :smiley:
