### ISSUE TITLE
Model viewer viewport in various tools are displaying in the wrong size

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#2001]
### Describe the bug

After the latest update, I noticed the viewports for Hammer model browser and Half-Life Model Viewer are using the wrong display size.

<img src="https://user-images.githubusercontent.com/35622748/219532987-00d20018-b344-45fa-91e1-c67b9cb86ef2.png" width=400> <img src="https://user-images.githubusercontent.com/35622748/219533162-48125d19-d582-4996-971b-d9fb15a0feb6.png" width=400>
### How To Reproduce

1. Open Hammer's Model browser or HLMV
2. The issue should present itself immediately

### Issue Map

N/A

### Expected Behavior

The viewports should fill the display area

### Operating System

Windows 10

### Renderer

DX11 (default)

**Comment by Gocnak** [comment]
Is this still happening?

**Comment by VortexParadox** [comment]
Sorry, missed the update request.
Haven't noticed this issue anymore as I've been using HLMV for player model visualization.
Closing.
