### ISSUE TITLE
Packed .mrf files not being loaded by mom_replay_playback entity

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/game#2011]
### Describe the bug

Packing the replay files used by the mom_replay_playback entity does not allow the entity to play those demos.  The entity only works with files stored locally in the replays folder and not ones packed into the bsp.

### How To Reproduce

- Open a map with packed replay files
- Trigger mom_replay_playback entity
- Nothing happens

### Issue Map

[df_momentum_training](https://cdn.discordapp.com/attachments/409531321455607808/1077971078661541908/df_momentum_training.bsp)

### Expected Behavior

Pressing the replay hint buttons with +use should show the replay that has been packed into the bsp.

### Operating System

Windows 10

**Comment by VortexParadox** [comment]
the files look packed correctly, so the issue must lie in the engine not mounting those files. It might be a security feature, to avoid malicious arbitrary files. Someone with access might need to change that, as I can't get replay files to work with resource files either
