### ISSUE TITLE
"slipperyslime" surface type does not act the same as Half-Life 2

### ISSUE THREAD

**Issue by Ninja-Cookie** [momentum-mod/game#2017]
### Describe the bug

The "slipperyslime" surface type does not act the same as it does with Half-Life 2, mainly with it being slippery.

Texture Used: `nature/mudfloor004bs`

Momentum Mod:
https://user-images.githubusercontent.com/62808028/222552319-ac82e716-a630-4d02-b136-d02dd0e95bc7.mp4

Half-Life 2:
https://user-images.githubusercontent.com/62808028/222552334-d7493bab-7730-4d7b-a760-fdf6e7cd8146.mp4

### How To Reproduce

Map works in both Half-Life 2 and Momentum Mod for testing:
[ahop_test_slipperyslime.zip](https://github.com/momentum-mod/game/files/10875750/ahop_test_slipperyslime.zip)

### Issue Map

N/A

### Expected Behavior

Be slippery like Half-Life 2's surface type.

### Operating System

Windows

**Comment by jason-e** [comment]
Closing in favor of the similar #2173. See my comment there for more information.
