### ISSUE TITLE
$envmap not rendering on material where it should. 

### ISSUE THREAD

**Issue by granis48** [momentum-mod/game#2026]
### Describe the bug

If a vmt specifies an `$envmapmask` texture at the same time as `$normalmapalphaenvmapmask 1` it will stop rendering the cubemap reflections altogether. 

### How To Reproduce

Here is the material this bug was discovered on [glass.zip](https://github.com/momentum-mod/game/files/10945964/glass.zip). Seems to happen on every (only tested LightmappedGeneric) material that uses both an envmapmask and the other parameter with it. 

### Issue Map

Here is the map where this bug was discovered [surf_axiom](https://gamebanana.com/mods/137721). The glass texture can be found allover the map but here is a comparison: 
css 
![image](https://user-images.githubusercontent.com/52294733/224425908-9d062141-7595-4178-b130-baa80fa1c98d.png)
momentum 
![image](https://user-images.githubusercontent.com/52294733/224426017-4f23d092-1d08-43cd-83a7-cda68571ebee.png)

### Expected Behavior

I don't see why anyone would ever use `$normalmapalphaenvmapmask 1` when they have an actual envmapmask already specified but since it works in css i expect it to work in momentum mod as well :)

### Operating System

win10

**Comment by granis48** [comment]
Turns out this is a duplicate issue https://github.com/momentum-mod/game/issues/1268#issuecomment-812737968. 
I guess we gotta decide if this is worth "fixing" by doing what css does and prioritize one of the parameters, or if we'd rather just fix the material in the maps where it is used as we add those maps to the game.

**Comment by Gocnak** [comment]
Decided in the other issue, we can use Lumper to fix this in the future as well.
