### ISSUE TITLE
Top bar of Replay/Spec UI overlaps leaderboard panel > can't click tabs

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#203]

**Comment by McGravel** [comment]
I believe that i first saw this in Caff's Stream, and Garanimal spoke about it among the other UI bugs.

**Comment by Gocnak** [comment]
Solution here is to check the spectator UI to see if it already has mouse input enabled, and if so, automatically grant the leaderboards mouse enable as well.
