### ISSUE TITLE
Map play button reverts back to download button when clicked

### ISSUE THREAD

**Issue by JosSamLoh** [momentum-mod/game#2033]
### Describe the bug

Clicking the play button after downloading a map results in the button reverting back to the download button.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/72921778/226212961-71f9c720-a848-4211-b404-a74e49e62584.gif)

### How To Reproduce

1. Click play button
2. It reverts to download button
3. Unable to load map
4. Forever in a loop of re-downloading

### Issue Map

Seemingly all of them on the map selector

### Expected Behavior

1. Click play button
2. Load map
3. Play

### Operating System

Linux (Fedora 37)

**Comment by Gocnak** [comment]
Is this still happening after the latest version of Steam? Support got back to me about it being potentially fixed now.

**Comment by JosSamLoh** [comment]
Can confirm it has been fixed.
