### ISSUE TITLE
Defrag physics differences: downwards slope test 01

### ISSUE THREAD

**Issue by Tibuq** [momentum-mod/game#2034]
I did some slope physics tests between defrag (left) and momentum mod (right):

Test 1: https://streamable.com/xfe27e
Final speed difference: +3

Test 2: https://streamable.com/xlntrm
Final speed difference: +3

Test 3: https://streamable.com/q0pvzm
Final speed difference: +7

Test 4: https://streamable.com/d6kyrl
Final speed difference: +1

Test 5: https://streamable.com/8vezbv
Final speed difference: -111

Test 6: https://streamable.com/j6u3un
Final speed difference: 0

maps used for testing: (i used panzers bsp converter tool) 
https://cdn.discordapp.com/attachments/733230720079757332/1088108984550039624/sloopin3.zip

**Comment by Panzerhandschuh** [comment]
Teleport destinations and player spawn points are offset by a few units upwards compared to Quake 3. This is probably one of the main factors contributing to the downwards slope speed differences.

**Comment by chovelyoukai** [comment]
I made a new map to test this, and I don't think there are any major differences. I tested different sloped ramps from different heights with `df_ob_KillOBs 1` without NoOB, NoOB on everything, and in mmod, and these were the results:

```
ramp grade      height      killOBs     noob        mmdf
4:4
                1792        823         823         825
                1536        762         762         762
                1280        696         696         696
                1024        624         624         624
                768         543         543         543
                512         444         444         444
                256         318         318         318
4:3
                1792        792         792         792
                1536        735         735         735
                1280        671         671         671
                1024        602         602         602
                768         524         524         524
                512         429         429         429
                256         311         311         311
4:2
                1792        663         663         663
                1536        615         615         615
                1280        562         562         562
                1024        504         504         504
                768         439         439         439
                512         363         363         363
                256         262         262         264
4:1
                1792        391         391         391
                1536        363         363         363
                1280        332         332         332
                1024        298         298         298
                768         260         260         260
                512         215         215         215
                256         157         157         157
```
Only two ramps gave different speeds and only by +2 ups. Both of those ramps are overbounce heights, so probably the mmdf OB fix is just slightly different from the q3df OB height. I think this probably doesn't need to be looked into any more.
