### ISSUE TITLE
Multi-select in map selector only downloads one map, not all selected

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#204]
“dunno if this has been posted yet, but i went into map select, dled surf_ace. wanted to dl all the other maps at once so i ctrl+clicked them all and then right clicked>add to library. it only added 666 (first map i ctrl+clicked) and didnt add the rest”

https://cdn.discordapp.com/attachments/235125108656701440/575266968970592267/20190507202000_1.jpg

Submitted by rogaa

**Comment by Gocnak** [comment]
Users should be clicking the library icon for maps they want to add to library. I have disabled multiselect in the map list for now, it's too misleading.

**Comment by Gocnak** [comment]
I should also note that we will eventually have a little map settings panel so that it's a little easier to change these settings from the map selector itself, pending UI/UX updates to it first though.
