### ISSUE TITLE
Add cgaz toggleable for bhop, at least as a command

### ISSUE THREAD

**Issue by Linguistie1** [momentum-mod/game#2041]
### What feature is your improvement idea related to?

Cgaz. It is superior to explain and teach people bhop. 

### Describe the solution you'd like

Would be nice to see it toggleable through console or smth.

**Comment by Gocnak** [comment]
Just noting here, cgaz uses information that's very specific to defrag. Bhop doesn't have snap zones, for example.

The effort around synchronizer is probably what this issue could be about, but just to understand further, what would you like to see?

**Comment by Linguistie1** [comment]
bhop does have snap zones tho they are just extremely small, no?
like, when we bhop we don't bhop in a straight line, we look to the side like in defrag. it's just so small it's really hard to see.
And there is a dead zone, too. Just very very small.

**Comment by tsa96** [comment]
Don't know where you're getting this from, but bhop doesn't have snap zones. The movement mechanics of these modes are so different that it's not at all clear what "cgaz for bhop" even means; we certainly couldn't just reuse the existing CGAZ code.

If you want to suggest new bhop trainer UI you're welcome you, you could also have a go at doing stuff in Panorama yourself, this code is all open-source.
