### ISSUE TITLE
Timer does not automatically switch track to other zones

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#205]
“I'm on surf_ace and after I beat the map it brought me to what looks like a bonus, which does have the green box at the start, and the red box at the end, but shows up as stage 1/8 and doesn't have a timer”

Submitted by bonjorno7

**Comment by Beetle179** [comment]
some maps automatically place you into the bonuses after you finish the map. Seems like this currently causes weird behavior: since the player didn’t do mom_restart # to enter the bonus, it doesn’t properly register.
Might not even be a “bug”, but strange.

**Comment by SlidyBat** [comment]
This is sort of intentional, we only want players to be able to change track manually. Any better ideas?

**Comment by Gocnak** [comment]
> 
> 
> This is sort of intentional, we only want players to be able to change track manually. Any better ideas?

Maybe let's allow the timer to set its track to whatever start trigger you end up touching while your timer is not running? At least for this bonus it would be beneficial to just walk to the bonus and be able to start it. Not sure if that's the automatic track-switching functionality we should use, though...

**Comment by Gocnak** [comment]
Removing from projects until we pick up working on supporting Bonus/IL runs.

**Comment by Gocnak** [comment]
Superseded by #2155 and in for 0.10.0
