### ISSUE TITLE
Fix timer handling in cgaz to reflect new changes to engine code

### ISSUE THREAD

**Issue by TEKN1SHUN** [momentum-mod/game#2056]
### What feature is your improvement idea related to?

Changing timers to ints from floats. The timer will now be passed to pano as remaining milliseconds. This impacts limited powerups like haste (indefinite timers, -1, will still work)

### Describe the solution you'd like

update timer checking code to match engine changes.

**Comment by chovelyoukai** [comment]
Fixed with https://github.com/momentum-mod/panorama/pull/89
