### ISSUE TITLE
Option for run reset bind to remove end of run screen

### ISSUE THREAD

**Issue by archrhythm** [momentum-mod/game#2060]
### What feature is your improvement idea related to?

For game modes with short maps (such as defrag) it would be nice to be able to press one button to reset the map and remove the end-of-run screen, at the moment you would need to either click on the menu or press tab to remove it and also press the reset bind.

### Describe the solution you'd like

I would imagine having a setting to allow this in case people would rather not have this behavior, (e.g. not wanting to accidentally skip past their EOR stats etc.)

**Comment by Mac-tf2** [comment]
clone of https://github.com/momentum-mod/game/issues/2059, closing

**Comment by Mac-tf2** [comment]
not completed oopsie

**Comment by Mac-tf2** [comment]
wrong close option oops
