### ISSUE TITLE
Bad key mappings with Swiss keyboard layout

### ISSUE THREAD

**Issue by suburbski** [momentum-mod/game#2066]
### Describe the bug

Some keys such as `^`, `<` and `$` don't exist, whereas others have bad mappings, e.g. `'` maps to `ä`

### How To Reproduce

1. `bind $ "say hoi"`
2. `[engine] "$" isn't a valid key`

### Issue Map

All of them

### Expected Behavior

The same as in any quake 3 engine

### Operating System

Ubuntu 23.04

**Comment by lvaness** [comment]
The keys are referenced by their counterparts on a QWERTY layout. This is standard Source behavior and I doubt we'd want to change that, especially in console.
