### ISSUE TITLE
Defrag: Add jump sound

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#2070]
### What feature is your improvement idea related to?

The current "jump" sound is just the footstep sound.

### Describe the solution you'd like

There should be an actual dedicated jump sound.

**Comment by tsa96** [comment]
This isn't really defrag-specific, we want to have an optimal jump sound for every mode. Not sure how we're gonna handle defaults here though, do you think DF players will be okay with us having it off by default? On non-defrag with us having it on by default?
