### ISSUE TITLE
Change default engine cubemap from de_vertigo's to a black cubemap

### ISSUE THREAD

**Issue by EthanV-3D** [momentum-mod/game#2074]
### Describe the bug

Currently if a map does not have its own default cubemap, it will use the engine default cubemap which is de_vertigo. This cubemap is incredibly unfitting for pretty much every map, and causes very unsightly and obviously incorrect reflections in the viewmodel and on any reflective material in the map, commonly water and props.

This bug commonly appears on maps with broken cubemaps, which causes it to use the engine default. While not an ideal scenario, it is inevitable to happen, and will result in the map having terrible reflections and viewmodels because of it.

### How To Reproduce

1. Open any map that does not have its own default cubemap. A quick example is rj_forgotten
2. Have viewmodels on, with `r_drawviewmodel 1`
3. You will see all viewmodels having a particularly unsightly reflection. Water and other reflective materials will be particularly bright as well, and all look very off.

### Issue Map

Any map with no default cubemap, or potentially broken cubemaps due to filename changes, common when a map is simply being 'renamed' as a form of porting.

Here is the bug seen on rj_forgotten, where you can see the de_vertigo cubemap causes the viewmodel to look incredibly shiny despite being indoors, and the water reflecting an image of a crane.
![image](https://github.com/momentum-mod/game/assets/26844021/cdc846f6-fecd-4f33-8b8b-c980f03dd0f4)

### Expected Behavior

Models should appear normal, with no obviously incorrect reflections. This can be solved if the default engine cubemap is simply a black cubemap.

![image](https://github.com/momentum-mod/game/assets/26844021/3b9b697a-521c-449e-b08f-163d4e2bacb6)

### Operating System

Windows

**Comment by SlidyBat** [comment]
We already have a different defaultcubemap that is bit darker, but it isn't being used due to mounting issues, where files in `platform` folder are prioritised over our game files.

After fixing this, should use the intended cubemap, which will resolve this issue.

**Comment by Gocnak** [comment]
Will be in the next release
