### ISSUE TITLE
Boss

### ISSUE THREAD

**Issue by vpsdeep50** [momentum-mod/game#2099]
Traceback (most recent call last):
  File "/data/user/0/com.kvassyu.coding.py/files/default.py", line 2, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

[Process completed (code 1) - press Enter] Traceback import random

secret_number = random.randint(1, 10)
guesses_taken = 0
max_guesses = 3 # Số lượt đoán tối đa

print("Chào mừng đến với trò chơi đoán số!")
print("Tôi đang nghĩ về một số từ 1 đến 10. Bạn có thể đoán được không?")

while True:
    guess = int(input("Hãy đoán số tôi nghĩ là gì: "))
    
    guesses_taken += 1
    
    if guess == secret_number:
        print(f"Chúc mừng! Bạn đã đoán đúng số trong {guesses_taken} lượt.")
        break
    elif guess < secret_number:
        print("Số bạn đoán nhỏ hơn số tôi nghĩ. Hãy thử lại!")
    else:
        print("Số bạn đoán lớn hơn số tôi nghĩ. Hãy thử lại!")
    
    if guesses_taken == max_guesses:
        print(f"Rất tiếc, bạn đã hết số lượt đoán. Số tôi nghĩ là {secret_number}.")
        break

**Comment by GordiNoki** [comment]
@Gocnak can you delete this issue?
