### ISSUE TITLE
Map downloads sometimes fail, cause strange behavior

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#210]
Sometimes map downloads will fail and cause glitchy behavior with the Map Selector. I should have checked console to see if there were any errors, my mistake. Later I was able to download the map fine: https://clips.twitch.tv/CarelessUgliestCiderNomNom

Likely related to #207

Submitted by Beetle179

**Comment by braem** [comment]
Closing as it is dated and hasn't been reported since https://github.com/momentum-mod/game/commit/7402e66e0e2c573d1a3ba24db113c461f4502d5a
