### ISSUE TITLE
Consistent error when going from settings > main menu

### ISSUE THREAD

**Issue by AprilTheFool** [momentum-mod/game#2104]
### Describe the bug

![chaos_5wK7IY55m0](https://github.com/momentum-mod/game/assets/122740391/103b0e74-a505-4ad9-8b8d-1338d49b4480)

### How To Reproduce

1. Open settings from main menu
2. Left click the Momentum Mod logo (top left)

### Issue Map

N/A

### Expected Behavior

Switch to main menu UI

### Operating System

Windows 11

**Comment by miodl** [comment]
I'm experiencing this issue as well.
It happened to me after i switched the sensitivity.
