### ISSUE TITLE
Players can end up in a "ghost lobby" with fake other players

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#211]
Somehow, you can end up in a "ghost lobby". In this clip, I'm in a lobby with 2 other players; however, one of them had closed the game, and the other wasn't actually in my lobby. They had both left earlier, but somehow not disconnected from my lobby. I was able to spectate them (they just looked AFK), and they couldn't seem to join my lobby. https://clips.twitch.tv/EntertainingConsiderateMooseKippa

Submitted by Beetle179

**Comment by Gocnak** [comment]
Closing as we have not seen it happen recently, and it may have been a product of bad first implementation code.
