### ISSUE TITLE
rj_sketchy2 Improper Teleport speed cancelation usage on stage 19

### ISSUE THREAD

**Issue by Zapzerohero** [momentum-mod/game#2110]
### Describe the bug

teleports maintain speed on stage19 as you jump thought it making it impossible to do the second rocket on the jump
https://streamable.com/nayzxu

### How To Reproduce

1. Go to Jump 19
2. Jump Though Portal
3. Jumps speed is still carried going though the second tp with no time to jump though
https://streamable.com/nayzxu

### Issue Map

rj_sketchy2

### Expected Behavior

speed should be stopped as you jump though the tp

### Operating System

Windows

**Comment by tsa96** [comment]
This is just an issue with the map porting, now the game itself, so doesn't belong on this repo. Until 0.10.0, we don't track map bugs at all, since everything will be re-ported after 0.10.0, after which you'll be able to report map bugs on our website.
