### ISSUE TITLE
FOV converter in settings

### ISSUE THREAD

**Issue by chovelyoukai** [momentum-mod/game#2126]
### Is your feature request related to a problem?

Players coming from Quake 3 would like to be able to convert their horizontal FOV to Source's weird FOV. There are tools online that can do this like https://casualhacks.net/Source-FOV-calculator.html

### Describe the solution you'd like

Add an FOV converter in the settings that takes horizontal FOV and converts it to Source FOV.

**Comment by tsa96** [comment]
Link you posted isn't loading for me!

But this sounds good, something that could be done purely in Panorama JS if we have details of how Q3 FOV maps to Source.

**Comment by chovelyoukai** [comment]
The math isn't bad at all, not sure why that page isn't loading for you but it has a very compact JS implementation right there in the source.

**Comment by chovelyoukai** [comment]
Here's the source code for that page (txt file because github is stupid)
[Source FOV calculator.txt](https://github.com/momentum-mod/game/files/14551761/Source.FOV.calculator.txt)
