### ISSUE TITLE
Sometimes cannot join lobbies

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#213]
In certain (unknown) cases, the “join game” option is not even present on Steam, even though others don’t have that problem (with that lobby).

Other times, the “join lobby” button just does nothing; with developer 2, you get “error code 4”.

In both cases, invitations cause nothing to happen.

Rulldar was having an issue where he couldn't join a certain lobby, he was able to download maps and host lobbies. i joined his lobby, no issues (speccing and chatting worked fine). but then, after i joined his lobby, i couldn't re-join that original lobby :blobfrown:

rulldar has no option to "join game" thru steam on other people's lobbies, and so i was inviting him to my lobby to test (no dice). i'm still able to click "join game", but it's not working; no error codes or anything.

after typing this out i reopened momentum (i was just alt-tabbed out) and tried joining the lobby again and it worked. very weird, guessing it's a steam thing

Submitted by several users

**Comment by Gocnak** [comment]
Re-open if the new pop-up dialogs do not cover everything (fails to join and nothing pops up to say what went wrong).
