### ISSUE TITLE
Multiple main tracks for map difficulty

### ISSUE THREAD

**Issue by lodyb** [momentum-mod/game#2164]
### Is your feature request related to a problem?

There are a bunch of surf maps (and maybe other style maps) where the difficulty can be selected.

I don't think there is the ability in the current specification to have multiple main tracks.

### Describe the solution you'd like

Multiple main tracks? e.g. Easy, Pro track

![Screenshot 2024-05-25 231727](https://github.com/momentum-mod/game/assets/6186871/2de3296f-4b5c-47fe-b187-efd8b86439a2)

### Describe alternatives you've considered, if any.

We would have to make multiple BSPs for each difficulty if this is not implemented

I think it would need to be defined how the multiple tracks would be handled, probably multiple BSP or making the alternative routes bonuses or something

### Additional context

https://github.com/momentum-mod/game/assets/6186871/5cb70631-130a-4950-bb9e-b7004c9a8b48

**Comment by jason-e** [comment]
A lot of things (conceptually and tech-wise) are built around the idea that the main track *is* the map and that there is only one main track.

We considered the fact that some maps have multiple difficulty variants built into one BSP, but these are few and far between. It would add a lot of complication under the hood and also make UX more challenging -- having to ensure every UI element in game and on the website that shows the main track is able to handle multiple main tracks and do so in a way that is understandable to the user, versus being able to optimize the design for exactly one main track -- all just to support those rare cases, and when there is already the reasonable and accepted solution of treating them as separate maps as you pointed out.

In cases where a map has a variant that could rightfully be treated as a *bonus* track, that is definitely an option. A lot of Defrag maps do this where there are one or more bonuses which are the main track with some movement modifier applied.
