### ISSUE TITLE
Rocket Jumping doesn't feel right

### ISSUE THREAD

**Issue by gaygoblin** [momentum-mod/game#2172]
### What feature is your improvement idea related to?

I was playing around with the rocket jumping and realized there's something... off about it. I can't quite describe it, its just not quite the same. One thing I can definitely point to is that pogo is significantly more difficult as you gain more height than in TF2. That might mean that the speed/momentum gain might not be right.

### Describe the solution you'd like

Probably just look at some of the TF2 source code and compare it to the current code. I would have done this for you, if I could code or understand code in any useful way. Although, I'm pretty sure that rocket jumping in TF2 gives you something like ~620 HU of velocity off the ground, and I was seeing speeds like ~680-690 when testing the same thing in MM.

**Comment by Shegetz** [comment]
This isn't concrete enough to be an issue in the repo. We have and use the code from TF2 but if you can find more concrete info you can open a targeted issue. Feel free to discuss the vibes and generally off feeling of the mode in the general rocketjump channel to try and narrow down what you're feeling to something actionable

**Comment by gaygoblin** [comment]
> This isn't concrete enough to be an issue in the repo. We have and use the code from TF2 but if you can find more concrete info you can open a targeted issue. Feel free to discuss the vibes and generally off feeling of the mode in the general rocketjump channel to try and narrow down what you're feeling to something actionable

Oh, apologies for that! I wasn't aware.
