### ISSUE TITLE
Defrag: target_push entity behaviour

### ISSUE THREAD

**Issue by Mac-tf2** [momentum-mod/game#2175]
Source does not have an entity that can replicate target_push behaviour. We added a trigger_jumppad entity that replicates the behaviour for triggers but it turns out we need a similar thing for buttons. 

May be worth removing trigger_jumppad and just porting the target_push entity in its entirety to allow all ways of triggering the behaviour with entity i/o.

**Comment by Mac-tf2** [comment]
Actually looks like we need to keep trigger_jumppad as it has a few extra behaviours

**Comment by Panzerhandschuh** [comment]
@Mac-tf2 Do you think we could just set the player's `basevelocity` when they activate the button? The `basevelocity` would be calculated using the vector between the button and the target.

**Comment by Mac-tf2** [comment]
I don't fully remember what the issue was off the top of my head, but it was related to this pull request for bspconvert https://github.com/momentum-mod/BSPConvert/pull/73

**Comment by Mac-tf2** [comment]
Found a way around this in bspconvert, closing

https://github.com/momentum-mod/BSPConvert/pull/96
