### ISSUE TITLE
Game crashes when the resolution is changed to 1440x1080@Fullscreen

### ISSUE THREAD

**Issue by thecaaz** [momentum-mod/game#2186]
### Describe the bug

Changing the resolution to 1440x1080 (stretched) crashes the game.

The command i use to set my resolution:
`mat_setvideomode 1440 1080 0`

Don't know if it makes any difference, my screen is 1920x1080 - 240hz

If i set the settings manually its non stretched 4:3 fullscreen, where i can still see my desktop on the side.
Restarting does not help.
Nvidia is correctly configured.
Other games have no issues in stretched mode.

### How To Reproduce

1. Open the game
2. Open the console
3. Execute `mat_setvideomode 1440 1080 0`
4. Game crashes

### Issue Map

Main menu

### Expected Behavior

When i execute `mat_setvideomode 1440 1080 0` the game should run in a stretched resolution.

### Operating System

Windows 11, Windows 10

**Comment by VortexParadox** [comment]
Recently had an internal discussion about fullscreen resolutions below native making the window borderless instead.
@thecaaz can you try adding `-freq <monitorRefreshRate>` into the game's launch parameters and switch resolutions using the in-game settings instead?

**Comment by thecaaz** [comment]
Then it works perfectly 👍, thanks for the help
