### ISSUE TITLE
OSX: crash when trying to open an "official" map

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#220]
The game will quit to desktop (with no crash log) upon the loading bar reaching 100% for any of the maps that are being time globally as of the 0.8 update (kitsune, mesa, 666, etc.)

As of this writing I do not know the exact reason, however in my testing I noticed that if I tried to open those maps while steam was in offline mode (e.g. disabling my internet beforehand) the maps will open fine (but with no timers or leaderboards)

Happens when picking the map through the selector and opening it from the console (with the `map` command)

Note: I have not tested if the crash occurs with online lobbies as of this writing

**Comment by itVictor** [comment]
update: got a crash log once while trying to debug more, cause appears to be a seg. fault
(apparently it doesn't create a crash log every time for some reason)

**Comment by Gocnak** [comment]
Does it give any extra details? Like where it's faulting?

**Comment by itVictor** [comment]
hi sorry for very late reply, the crash log is here: https://pastebin.com/NaGkUkc5

however since that was the only time I got a crash log while trying to debug this, I'm inclined to believe that particular log isn't meaningful and the cause for the crashes is elsewhere

**Comment by Gocnak** [comment]
Interesting. I'm seeing a lot of CryptoPP stuff in there. If it's upon load of only official maps, it could very well be [this line](https://github.com/momentum-mod/game/blob/bugfix_and_qol/mp/src/game/client/momentum/mom_map_cache.cpp#L1115).

I don't have a mac to debug this. If you're able, try commenting out that line and replace the string that it's generating with some hardcoded value.

**Comment by itVictor** [comment]
crash logs appear to be consistently generated after 0.8.1 now, seems like it is that CryptoPP stuff
https://pastebin.com/sKJv19vV
