### ISSUE TITLE
Player entity endlessly spinning when looking around

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#2218]
### Describe the bug

The player entity, not to be confused with the player model, spins endlessly when still and looking side to side. It happens regardless of player model, wether it's the new one or the basic geometry shapes.

https://github.com/user-attachments/assets/1dc6376a-d00a-4b6b-b11b-63b75f5592cf

### How To Reproduce

1. Set `cl_showanimstate 1` (only needed for visualization purposes. May need `developer 1`).
2. Set `thirdperson`.
3. Look left/right far enough to cause the player entity to rotate, if it's far enough, the player should start spinning.

### Issue Map

N/A

### Expected Behavior

The player should only turn to face the model's forward vector.

### Operating System

Windows 11

**Comment by SlidyBat** [comment]
Can replicate this on Steam build, but not on local build
May already be fixed, will need to retest on next Steam update

**Comment by VortexParadox** [comment]
Still occurs as of the latest update

**Comment by Gocnak** [comment]
Was uninitialized values, should be fixed now

**Comment by VortexParadox** [comment]
Still occurs after latest 0.10.0-pre update
