### ISSUE TITLE
Spectator list doesn't show for other spectators

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#222]
When people are spectating you, there's a list of spectators that shows up on the right side of the screen. When you are spectating someone, that list doesn't show up; you're unable to see who ELSE is spectating that player.

Submitted by Beetle179

**Comment by Gocnak** [comment]
This is actually a feature request, not a bug. They normally aren't supposed to show because we didn't add support for that. We can pretty easily do it, though.
