### ISSUE TITLE
Reading certain textures fails after latest update

### ISSUE THREAD

**Issue by VortexParadox** [momentum-mod/game#2223]
##### I wanted to post this on StrataSource issue tracker, but I don't have the required data it asks for when creating an issue, plus I don't have a way to test if the issue is present for other games as well, so I'll be placing this here instead.

With the latest update, 0.9.37, the material system has issues loading some textures used in maps, as reported by @natanxp2 on Discord with ["Weird textures on ahop_stop"](https://discord.com/channels/235111289435717633/1314282458824572988), it looks like it's only affecting `$detail` textures.

![image](https://github.com/user-attachments/assets/d92ea745-52c5-4183-8ac0-3e76531d0535)
![image](https://github.com/user-attachments/assets/b65f7718-ee49-41fe-980f-b67a0068ee74)

https://github.com/user-attachments/assets/334b9879-ceec-4dfc-9ba8-14837007bd4d

### How To Reproduce

1. Run the map `ahop_stop` or technically any map that uses materials with detail textures.
2. The map should be covered in a missing texture overlay

### Issue Map

`ahop_stop`
`surf_happyhands`
any map with materials using detail textures

### Expected Behavior

The material should render the specified detail texture

### Operating System

Windows 10/11

**Comment by Gocnak** [comment]
Fixed in next update
