### ISSUE TITLE
OSX: certain things not scaling with resolution

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#224]
this issue should override #216 (so close that and leave this one open)

https://imgur.com/a/Fq4lF0w

As seen in the screenshots, the console, net_graph, cl_showfps, options menu, and the "0.8.0" in the upper right corner look weird at both resolutions, with font rendering issues for net_graph and cl_showfps in the "native" resolution and the console/options/showfps/0.8.0 being very small at the actual resolution (for this monitor anyways).

In short, these elements are varying in appearance depending on the resolution and do not scale as such.

If the objective is to be like other source games, then the resolution should be capped to the "native" resolution (in this case, 1280x800) and then adjust the elements as necessary. The reason why I say cap it to that one and not the actual resolution is because all the source games I've tried (except for portal 2) don't appear to support those larger resolutions in video options, alongside with the fact that changing the resolution to 2560x1600 and closing/relaunching the game will always set it back to 1280x800.

**Comment by itVictor** [comment]
this issue may also be an extension/related to of #199 but someone else will have to investigate that

**Comment by itVictor** [comment]
update: I tested this on a different machine (desktop, not laptop) and could not reproduce, everything looked fine in all aspect ratios (4:3, 16:10, 16:9), so I think it's just some weird issue where 16:10 isn't rendering things correctly in specific circumstances, but still an engine issue regardless

**Comment by Gocnak** [comment]
Closing as OSX support has been dropped for now.
