### ISSUE TITLE
Savelocs in startzone allow for unfair starts

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#228]
"creating a saveloc where you cross the start zone allows the timer to start like normal
https://youtu.be/EGvV3IaSO3w "

Submitted by Plarm

**Comment by Gocnak** [comment]
We need to make it so that the timer only starts if the player touches the ground inside the start zone.

**Comment by kitlith** [comment]
Might this be start be caused by this section?

https://github.com/momentum-mod/game/blob/7ae578d3fff22ef5cd8ae427da38fd5fa2817a5f/mp/src/game/server/momentum/mom_player.cpp#L939-L957

if it is, then checking the start on jump variable before calling TryStart would probably fix it.
