### ISSUE TITLE
Paint decals can overwrite most recent decal when at maximum decal count

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#243]
Likely related to max decals (r_decals, mp_decals). seems like after some point (probably reaching max decals), new decals will overwrite the most recent decal, instead of overwriting the oldest decal.

https://clips.twitch.tv/ShakingAffluentRingJonCarnage

Submitted by Beetle179

**Comment by Gocnak** [comment]
The thing about decals is, we use the FDECAL_PERMANENT flag on paint to make it so your paint persists, can exist in the same area as other decals, and has a higher limit than normal decals. 

The unfortunate side effects of this flag means that your paint cannot be removed unless you reload the map, and now this. The kicker is, it's all in engine. So unless we roll our own decal system, or get engine access, this will have to be backburner.

**Comment by Gocnak** [comment]
Does this still happen? We made paint no longer permanent on Chaos, so ideally it should start to remove the paint you placed a while ago.

**Comment by hexaflexahexagon** [comment]
the oldest paint decal is now properly removed rather than the most recent one.
