### ISSUE TITLE
Replays of linear maps only show CP1 on first play

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#248]
"linear replays will only show the CP1 the first time its played, not the second time (CP2 and onward will always work)"

(I believe this means that the CP1 splits only show up on the first run through of the replay)

Submitted by crashfort

**Comment by Gocnak** [comment]
Inherently closed with https://github.com/momentum-mod/game/commit/42cce2226a7b671f858dd21cab359624e321ecd5
