### ISSUE TITLE
Exiting Steam while ingame locks up the game/can't tab back in

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#253]
https://www.youtube.com/watch?v=LC6Xcm7gJhE
(Note in video that when I try to tab back into Momentum, the top left of the screen shows that I'm focused on Momentum, but I'm inactionable)

Also happens with CS:S; might be a Source or Steam bug, not our problem?

Submitted by Sneakyy

**Comment by braem** [comment]
Every source game crashes when steam is closed while playing. They crash as soon as they need to contact steam. This is true for Momentum when windowed as well.

When full screen we see this behavior; when focused it can lock the computer in focus which requires a ctrl+alt+del to get out of if it's in the main menu. When in game (not in main menu) the game does not open & releases focus, but doesn't crash. What's strange is that this does not happen for P2CE (it returns to fullscreen just fine).

**Comment by Gocnak** [comment]
When debugging, you can hit the "pause" button in the debugger to see where the game is currently executing code if it is stuck somewhere (in a loop for example). It would be good to do that here and see what's happening that it doesn't give back input.

**Comment by lvaness** [comment]
I can't reproduce it anymore, please reopen if this is still an issue for anyone.
