### ISSUE TITLE
Savelocs don't properly store certain trigger events

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#263]
"Savelocs don't appear to store delayed outputs correctly, this booster reset gravity on a delay, but if you make a saveloc while that delay is active and load it, then the output does not fire again"
https://streamable.com/0vt4p

Submitted by BorkChops

**Comment by SlidyBat** [comment]
I believe the solution to this would be to store the event queue for entities along with each saveloc.

Entity event queue is found here: https://github.com/momentum-mod/game/blob/5580774869a11c390393cc3812c3c24c02cb55f4/mp/src/game/server/cbase.cpp#L643

Some save/restore functionality already exists but might need to be changed slightly for our usecase: https://github.com/momentum-mod/game/blob/5580774869a11c390393cc3812c3c24c02cb55f4/mp/src/game/server/cbase.cpp#L1148-L1223

**Comment by Gocnak** [comment]
Yeah that sounds about right. We'll only want to store the ones where the player is the target though.

**Comment by SlidyBat** [comment]
Fixed in b2f64cc

Needs a bit more testing on more maps to ensure that everything works as expected, so leaving open for now.

**Comment by Gocnak** [comment]
Confirmed fixed by BorkChops, good work.
