### ISSUE TITLE
Option to hide other players' entity name panels on Momentum Settings panel

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#270]
Currently there is no way to hide other players' playermodels and trails. This can be pretty distracting. 

This would require an option in the Momentum settings panel, probably just a checkbox, to "hide other players". 

Suggested by several

**Comment by Gocnak** [comment]
Disabling other players trails:
![image](https://user-images.githubusercontent.com/5162166/65826119-a0399c00-e24d-11e9-9b00-41bbaa4faa13.png)
Disabling drawing other ghost bodies:
![image](https://user-images.githubusercontent.com/5162166/65826124-aaf43100-e24d-11e9-9ac2-f9830c44ad35.png)
Command to disable name panels:
`mom_entpanels_enable 0`

I will rename this issue to add an option for disabling name panels. If people aren't reading the options menu in the first place, a generic "disable drawing other players" won't help.
