### ISSUE TITLE
Better height control for zoning

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#276]
" Better Zone Height Control/Fill Z
At least some way of seeing how tall the zone you create is (so that a consistent height can be used) and a way to easily fill to the ceiling (typically using the center of the zone
https://puu.sh/DpnvC/ccc6989629.mp4 "

Suggested by BorkChops

**Comment by zachconnor** [comment]
https://youtu.be/4-B9L653HKc here is the video reuploaded, if you need context about how this could work ask me (borkchops) or rio

**Comment by Panzerhandschuh** [comment]
Outdated.
