### ISSUE TITLE
Unhide and cheat-protect certain commands

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#280]
The following commands are hidden:
sv_accelerate
sv_airaccelerate
sv_interval_per_tick
sv_maxvelocity

Unlock these commands, but require sv_cheats 1 to use them.

Suggested by several people

**Comment by SlidyBat** [comment]
Relevant commit: dc4f6b1

Players can only change the cvars when using the `-mapping` launch option, however they can view the values of those cvars by using the `mom_print_gamemode_vars` command.
