### ISSUE TITLE
A button to open the Momentum website in the Steam browser ingame

### ISSUE THREAD

**Issue by Beetle179** [momentum-mod/game#282]
(The Steam browser, in general, could be used in a number of places; for example, links to player profiles could utilize the Steam browser in this way. Kind of like that suggested in #271 )

^That said, this suggestion is purely for a button or bind to just open momentum-mod.org in the Steam browser; the rest could follow later

Suggested by Garanimal

**Comment by Gocnak** [comment]
Well the thing is, you'd have to log in to the site to be able to use it, so it'd be super easy if people are okay with logging in every time.

But if not, we could look into passing the game's API token to some sort of "loginFromGame" endpoint on the website to allow it easy authentication...

**Comment by Verttox** [comment]
from what i tried steambrowser will cache the login and not require the user to login again after every game start.
https://giant.gfycat.com/SingleCourteousGiantschnauzer.webm

**Comment by lvaness** [comment]
This exists now
