### ISSUE TITLE
Replace (Some) Default Sounds

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#30]
Much like how issue #21 describes, there needs to be replacing of the default _CRUNCH_ and other various sounds to make for a less dramatic-sounding mod.

**Comment by RabsRincon** [comment]
With the addition of the sounds_game_manifest, it is as easy as overriding the Cruch entry, so we have more control over how it sounds, (and adding the desired sound file, of course)
This doc is very helpful: https://developer.valvesoftware.com/wiki/Soundscripts

**Comment by Gocnak** [comment]
Crunch was removed by removing fall effects/damage.

Further sounds can be replaced as needed. Moved to trello: https://trello.com/b/N1oc0LxP/arte
