### ISSUE TITLE
[Map Finished] panel does not properly reset if using mom_restart

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#300]
Using the mom_restart/reset binds after completing the run does not properly reset the mapfinished panel so the next time you complete a run, the "Run Submitted!" and everything is still there.

As seen on truktruk's stream.

**Comment by braem** [comment]
I believe this was fixed at some point:

1. While the map finished panel is open, the `mom_restart` and `mom_reset` commands don't do anything. Not sure if it was different before.
2. Upon exiting the map finished panel, the map saved and map uploaded fields are reset correctly:
See the `SetRunSaved(false)` and `SetRunUploaded(false)` calls in the `CHudMapFinishedDialog::ClosePanel()` function in [hud_mapfinished.cpp](https://github.com/momentum-mod/game/blob/develop/mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp)

**Comment by Gocnak** [comment]
This bug has transformed into only needing to make sure the API call does not set the panel labels, since the API call can be delayed when uploading a particularly longer run.

That would be fixed by just checking if the panel `IsVisible` in [the callback for the API call event](https://github.com/momentum-mod/game/blob/develop/mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp#L107)
