### ISSUE TITLE
Refactor Replay Format

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#305]
Replays currently store a lot of redundant frames if the user pauses/spectates/practices/etc, and the replay frame format is pretty concrete and should be ripped apart to support multiple frame types.

Rough detail spec:
 * Replay header
    - [ ] Replay and map info
    - [ ] Player appearance data
    - [ ] Run stats
 * Replay body
    - [ ] Number of ticks in replay
    - [ ] Tick data
        - [ ] Number of frames (data) in the tick
             - [ ] Frame type
             - [ ] Frame pool index
 * Frame pools
    - [ ] Frame pool type
    - [ ] Num of frames
        - [ ] Frame data

The underlying code will also have to change to be able to "apply" their data to the run, maybe using a generic interface for this.

This allows storing things like:
 - [ ] Jump count
 - [ ] Yawspeed (and its changes)
 - [ ] Practice mode enter/exit events
 - [ ] Spectate mode enter/exit events
 - [ ] Strafe offsets

Overall we will be storing more data, but if a player stands still (pauses), or spectates for a while, the gain on the replay size is well worth it.

**Comment by SlidyBat** [comment]
I'd also like to do some investigating to see whether it's worth doing some compression on the frame data.

I was thinking either delta compression (similar to whats I'd also like to do some investigating to see whether it's worth doing some compression on the frame data. I was thinking either delta compression, similar to what's done with usercmds: https://github.com/momentum-mod/game/blob/f88b1577a0c7c1ceac10bfbcf2ceb57cc1c36ac8/mp/src/game/shared/usercmd.cpp#L19-L190

or just normal deflate compression (or possibly even some combination).

**Comment by hexaflexahexagon** [comment]
Replays should also be made to keep gamemode in mind on a given map to prevent runs of different gamemodes on a single map intermingling in the local replay folder.

**Comment by jason-e** [comment]
To make replays stateful enough to support something like creating a saveloc from a replay frame, make sure to track all properties that are stored in savelocs (e.g. targetname, classname, etc).

**Comment by Panzerhandschuh** [comment]
Requirements are outdated
