### ISSUE TITLE
Add Proportionality to All Applicable UI Elements

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#312]
Most panels weren't made with SetProportional(true) in mind, for example, Valve's GameUI code, and a lot of HUD elements.

Painstakingly go through each and every panel to make sure it scales properly to resolution by using SetProportional(true) and tweaking script/size values until it works.

# Modals
- [x] Momentum Settings Panel
- [x] Paintgun Panel
- [x] Replay UI
- [x] Spectator UI
- [x] Leaderboards UI
- [x] Changelog panel
- [x] BuildModeDialog panel

# HUD Elements
- [x] Map Finished UI
- [x] Chat UI

# GameUI
- [x] Console panel
- [x] Options panel
- [x] Loading screen

**Comment by braem** [comment]
Had someone report that the saveloc menu is taking up too much space on 4:3. Is it possible to have static hud menus like this be proportional as well?
