### ISSUE TITLE
"White Square" with HudAnimations.txt

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#32]
Apparently adding animations to the mod also brought upon a white spec in the bottom middle of the screen. Removing HudAnimations.txt fixes this, so look into what may cause this.

**Comment by RabsRincon** [comment]
Even if releated with .txt (and knowing that it disappears after its deletion), are you sure it is releated within the content of the file? I can't tell why the file would create a white spec right there. (Or/And I just suck at understanding it)

**Comment by Gocnak** [comment]
It could be because it's trying to load an element that's null? I think because the CPMenu has colors that aren't defined in HudLayout.res or something?
