### ISSUE TITLE
Change tricksurf maxvelocity setting from 10,000 back to 3500.

### ISSUE THREAD

**Issue by Fuhsahd** [momentum-mod/game#330]
A lot of, and I believe all tricksurf_ maps are meant to be set at 3500 maxvelocity. Skyworld and all others were afaik. On some maps with 10000 velocity it can make previous 3500 maxvel tricks a lot easier. Changing the maxvelocity back would bring the tricks back to the difficulty they are meant to be.

**Comment by Gocnak** [comment]
With track properties we can allow per-map settings for it. It has been reverted though in #355
