### ISSUE TITLE
Map Checkpoint Locations

### ISSUE THREAD

**Issue by zachconnor** [momentum-mod/game#341]
Option to display a ground indicator for map checkpoint locations (info_teleport_destination). Useful for bhop maps where it can often unclear if you have reached a checkpoint, and also has side benefit of making it more obvious where invisible reset boxes are (if they aren't fixed up for momentum). Could be an option in Momentum Settings or just a convar toggle.

[https://streamable.com/flzwd](https://streamable.com/flzwd)

**Comment by braem** [comment]
I suppose to do this you would need to somehow draw a model for teleport destinations, though it seems you can't draw models with `CPointEntity`. Perhaps use meshbuilder instead? Does that save edicts or something?

**Comment by Gocnak** [comment]
Models should be drawn on the client, so it would just need networked over to a stub class kinda like how our zone triggers are.
