### ISSUE TITLE
Native entities for Non-linear filtering system

### ISSUE THREAD

**Issue by zachconnor** [momentum-mod/game#343]
[This](https://gamebanana.com/prefabs/6845) is the prefab that some maps use but is rather unintuitive and does not always work perfectly, so a native implementation would be convenient for mappers, as well as offer potential integration with huds and stuff.

**Comment by xen-000** [comment]
Possibly filled in by filter_activator_context, especially when it can filter by multiple contexts with AND/OR support from mapbase.
