### ISSUE TITLE
Remove all ground weapons on tricksurf_ prefix maps

### ISSUE THREAD

**Issue by Fuhsahd** [momentum-mod/game#356]
Weapons are not needed in trick surf and most trick surf maps are flooded with ground weapons. These are often picked up during tricks and can get annoying. Also on maps such as greatriver_xdrea4m there is an Awp inside garage that changes how the map looks, by removing walls (which was how the map was presented on zee's servers (with the walls removed))

**Comment by Gocnak** [comment]
Wontfix, a map problem that can be fixed before the map is on the map selector is not the game's problem.
