### ISSUE TITLE
AirAccelerate 

### ISSUE THREAD

**Issue by tuxxi** [momentum-mod/game#37]
What's the current plan with AirAccelerate? Are we going to implement it as an unprotected svar, or do we have any other ideas? 

One idea is to have the airaccelerate value for the map stored in some file that is downloaded from the central server, similar to the zone file. It could be a text file with a bunch of flags for specific maps such as airaccelerate, tickrate, and/or any others we can think of. Obviously just like the zone file this would have to be checked via hash before the map is loaded.
Then we would have a cheat protected svar called sv_airaccellerate_override or something (in order to distinguish from freely changeable sv_airaccelerate in css). 

However, some bhop maps are made to be scrolled, so having one file with constant tickrate or airaccelerate values would not allow for variation (like 66 vs 100 tick surfing, or scroll/auto bhop). Does anyone have an idea of how to implement different gametypes on the same map? Perhaps different flag files corresponding to the gametype that the user selects?

One of the larger reasons (among many) that kzmod failed was that it split the community. I think we should make sure to have support for gametypes like kz and legit bhop (and maybe even trikz if someone feels like coding it) before release. 

If there is a better way to discuss ideas and implementations please let me know.

**Comment by RabsRincon** [comment]
Thanks for bringing AirAccelerate into the table. Currently, we (As far as I know) have no plans for AirAccelerate (besides some "*we really should take care with those vars guys*" warning), but you're right, we totally need to, and your idea seems as good as it can be.
Right now maps, when played properly, create 2 files: One for the local timers (*.tim*) and another for the zones (*.zon*) I don't know if having 1 more would be a great idea, but it's totally doable. (Maybe a cfg per map!)

As for different things for different gamemodes in the same map, we are not yet into gamemode developing, as we prefer to have a solid base before doing anything more "*advanced*" in terms of gameplay, but it's something we've considered and will mostly end up doing (Although Alpha will be focused on Bhop - Surf, we plan to expand the available gamemodes once the bases are set)

Last but not least, we use [Slack](www.slack.com) to communicate. PM me if you wish to be invited there!


Regards,
Rubén :)

**Comment by tuxxi** [comment]
Thanks for the invite! I think there are no private messages on github, though. :/ my email address is aidan@sojourner.me.
