### ISSUE TITLE
Surface-based trigger system

### ISSUE THREAD

**Issue by Auximous** [momentum-mod/game#376]
Custom entity that allows you to apply a placeholder trigger's properties to the player when they touch specific surfaces. 

Easiest example would be with a teleport trigger:
Player fails a level and touches a ground/fail displacement. This would normally be covered by a trigger_teleport. 
Placeholder trigger_teleport is applied to/activated on the player. 

The entity has... 
... a name. 
... a connected trigger that it applies properties from. 
... list of selected surfaces.

**Comment by Gocnak** [comment]
Reference of an already existing one to build off of: https://developer.valvesoftware.com/wiki/Env_player_surface_trigger
