### ISSUE TITLE
PBR Assets

### ISSUE THREAD

**Issue by bonjorno7** [momentum-mod/game#382]
For PBR textures we'll need:
- [x] Tiles
- [x] Bricks
- [x] Concrete
- [x] Planks

And we'll need those in LightmappedGeneric too:
- [x] Tiles
- [x] Bricks
- [x] Concrete
- [x] Planks

For PBR models we'll need:
- [x] Pipe thing
- [x] Metal stairs
- [x] Shaderballs
- [x] Light post
- [x] Fence
- [x] Crystal

And we'll need those in VertexLitGeneric too:
- [x] Pipe thing
- [x] Metal stairs
- [x] Shaderballs
- [x] Light post
- [x] Fence
- [x] Crystal

**Comment by bonjorno7** [comment]
I ticked Pipe thing (models/custom_props/pbr_asset.mdl) under the VertexLitGeneric list because I thought you made a VertexLitGeneric version, but I can't find it. I'll just untick the box for now. Feel free to retick if you the elusive VertexLitGeneric version does exist. Do tell me whether it does or doesn't so I'll know if I should make it myself or not.

**Comment by McGravel** [comment]
> @McGravel I ticked Pipe thing (models/custom_props/pbr_asset.mdl) under the VertexLitGeneric list because I thought you made a VertexLitGeneric version, but I can't find it. I'll just untick the box for now. Feel free to retick if you the elusive VertexLitGeneric version does exist. Do tell me whether it does or doesn't so I'll know if I should make it myself or not.

It should be called `vlg_asset.mdl` in the same folder - of course short of ***V***ertex***L***it***G***eneric
A bit stupid but consistent :V

**Comment by bonjorno7** [comment]
The map is done, including all its assets. Dunno what to PR into what but I guess it doesn't matter right now, I'll get back to fixing the shader now.
