### ISSUE TITLE
Timer is not reset when using mom_restart

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#388]
mom_restart is allowing times to persist past the command. On surf hob this allows players to start a run on the main map and then use mom_restart -1 to go to spawn which is also the endzone of the map. This lets people get a 3 second time on a long linear map.

**Comment by McGravel** [comment]
Confirmed on latest `develop` code.
Also the Start Zone doesn't seem to work the first time you enter the teleporter, but that's another Issue if anything.

**Comment by Gocnak** [comment]
While this will not properly accept the run on the site, we will definitely make it so that the timer stops if it is running and this command is done.

**Comment by patrickmoc** [comment]
If the run is reset to spawn after hitting the last checkpoint before the end you could still potentially cheat the run and have it upload unless there is another condition being checked.

**Comment by Gocnak** [comment]
There is, when you restart a run you're given a brand new run session. If you get a new session and don't do all the required checkpoints/stages, the run will not be accepted online.
