### ISSUE TITLE
start, end, and 'checkpoint' zones need to be added

### ISSUE THREAD

**Issue by sndrec** [momentum-mod/game#4]
an in-game system of placing and saving zones pertaining to the map needs to be implemented.
specifically, the zones that should be available to place:

start zone - exiting this zone will start your run timer immediately. speed inside of the start zone will be capped to the max prestrafe speed of 289ups (or whatever it actually is. we'll have to measure or calculate it)

end zone - immediately upon touching/entering this zone, the timer is stopped and your run is saved and submitted. 

checkpoint zone - purposefully placed points throughout a map, and on hit, showing your time gained/lost over your previous best run at the individual points.

**Comment by Juxtapo** [comment]
Also stage zones for staged surf maps - Should act basically as a checkpoint zone but tracks WR's between stages and is labelled S1, S2, etc.

**Comment by Flipybitz** [comment]
@Juxtapo that's what he meant with checkpoint zones.

**Comment by sndrec** [comment]
@Flipybitz it isn't, actually - checkpoints would be to measure progress throughout a stage, whereas stage zones would let you separate the map into definable pieces - like the stages in omnific, or arcane.

**Comment by Gocnak** [comment]
Relevant: http://pastebin.com/49vgyxsj

**Comment by Gocnak** [comment]
Moving over to issue #26
