### ISSUE TITLE
Rocket Jump - Shotgun range is too short for some maps

### ISSUE THREAD

**Issue by McGravel** [momentum-mod/game#416]
Weapon script says 3000 range - should we increase it, and does 3000 match TF2?
https://clips.twitch.tv/ColorfulSuaveAlmondPoooound Example in this clip

**Comment by itVictor** [comment]
>Bullet-based weapons (a list of which is given below) fire seemingly infinite lines (the actual maximum range is ~56,754 units). 

https://wiki.teamfortress.com/wiki/Hitscan
