### ISSUE TITLE
[Rocket Jump] weapon switch speed not consistent with TF2

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#426]
Currently, switching from rocket launcher to shotgun is too fast, and switching from shotgun to rocket launcher is too slow (compared to tf2).

I'm not 100% sure but I believe it should be 0.5 seconds both ways.

**Comment by Gocnak** [comment]
This is in the deploy time of the rocket, an animation I don't believe the rocket has in TF2. Our custom rocket should fix this. I'll leave this open for now.

**Comment by bonjorno7** [comment]
Changing the draw animation from 30fps to 68 fps makes it exactly 0.5 seconds. There should be code that makes you wait instead of relying on the length of the animation though. Also, it should interrupt the animation if you fire after 0.5 seconds.

**Comment by bonjorno7** [comment]
I should've probably named the branch fix/weapon-switch-speed instead of fix/rpg_switch_speed but oh well

**Comment by Gocnak** [comment]
The code may be in the base Deploy() method for guns. It may need overriding to not do the check for the animation maybe?

**Comment by bonjorno7** [comment]
I don't think we can close this issue before adding a shotgun deploy animation, so perhaps @McGravel wants to make one

**Comment by McGravel** [comment]
I'll look into it.

**Comment by bonjorno7** [comment]
I'll move the new DefaultDeploy function into the base weapon class, probably through rebase shenanigans so expect a force push :\

**Comment by bonjorno7** [comment]
Now it's better, still need the shotgun deploy though I guess

**Comment by bonjorno7** [comment]
Sorry for the last force push, uh have another
