### ISSUE TITLE
Paint does not work on water surfaces

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#429]
Found in Boshy's stream:

https://clips.twitch.tv/AdventurousObedientAniseBloodTrail

**Comment by bonjorno7** [comment]
Also doesn't work on the Refract shader

**Comment by laurirasanen** [comment]
Also doesn't work on illusionary? walls, not sure what these are called.  
For example the walls in `jump_sinister_final_ver2` room with water: `setpos -9200 -12200 -420`.  
The walls are made out of 2 layers, I think the first one is non-solid but has a clipbrush over it, the trace will go through the first one and paint the second wall behind it.
