### ISSUE TITLE
Add option to display unit speed in center of screen

### ISSUE THREAD

**Issue by Flipybitz** [momentum-mod/game#444]
This seems to have been a popular request, so I'm creating the issue for it. It seems easily doable, just need a setting in the options menu for it. Somewhere in this menu: http://prntscr.com/pjm1s5

**Comment by Gocnak** [comment]
The end user can accomplish this with .res file editing. Maybe in the distant future we will have in game hud editing that can do something like this, but it is otherwise already in the game.
