### ISSUE TITLE
bitbuff.cpp Overflow assert when entering/exiting water

### ISSUE THREAD

**Issue by Flipybitz** [momentum-mod/game#476]
Entering and exiting water on the latest develop branch causes this assert to be thrown 8-10 times:
![meT4ZGyqTyCNM1Ww7wrOZg](https://user-images.githubusercontent.com/3002858/68077512-20927600-fd93-11e9-9d51-5be2cb871bc0.png)
And here's the call stack:
![-aUWR3xhQ0aYEJFT05fTjA](https://user-images.githubusercontent.com/3002858/68077513-21c3a300-fd93-11e9-98ea-baad92a32ba1.png)

Tested on bhop_arcane and jump_summer

**Comment by Gocnak** [comment]
Unable to reproduce this. Deferring to figuring it out later.

**Comment by Gocnak** [comment]
Seems to be fixed or was a one time thing. Doesn't happen on latest code.
