### ISSUE TITLE
Unclamp mat_picmip

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#495]
Suggested by ficool2.

mat_picmip is clamped to be inside the range of -1 to 2 by the engine, so in order to remove the limit of the command, a new command needs to be used that temporarily enables this one, then mat_picmip needs to be disabled on the same frame. This code sample is how ficool2 went about doing it: 
```
// What is the reasoning for this mess? 
    // The engine clamps mat_picmip to -1 - 2 every rendering frame and we don't have access to change this
    // Therefore we set the desired picmip from another convar and then immediately nuke it on the same frame
    // So the engine doesn't have time to clamp, and it will stay at that level permanently
    if ( mom_picmip.GetInt() != 0 ) 
    {
        ConVar *mat_picmip = NULL;
        mat_picmip = g_pCVar->FindVar( "mat_picmip" );

        if ( mat_picmip )
        {
            int iPicmip = mom_picmip.GetInt();

            if ( iPicmip < -10 )
                iPicmip = -10;
            else if ( iPicmip > 10 )
                iPicmip = 10;

            ConColorMsg( Color( 170, 255, 170, 255 ), "[Engine] Hijacking mat_picmip with a value of %i...\n", iPicmip );

            // hijack the convar's clamp values to use our own range
            mat_picmip->SetMin( -10.0f );
            mat_picmip->SetMax( 10.0f );
            mat_picmip->SetValue( iPicmip );

            // delete the convar
            mat_picmip->Nuke();
        }
    }
```
This allows for much higher *or lower* resolution for the textures being rendered. The Nuke() function is a custom tier1 function:
```
    // Purpose: 
    //-----------------------------------------------------------------------------
    FORCEINLINE_CVAR void ConVar::Nuke( void )
    {
        m_pParent->Shutdown();
        Shutdown();
    }
```

**Comment by Gocnak** [comment]
It's yet to be determined if actually unclamping this will provide any visual benefit to the game. The only example of benefits are on world details that are normally mipped pretty low for performance gains in the first place. Most maps don't have things like this, and I don't think doing such a hacky workaround will be of any major benefit.

I put the `Needs more info` tag on as I'm open to discussion, as well as actually unclamping it when we get engine license, but I need to know of applicable gains to our game in particular, not default TF2 maps.

**Comment by patrickmoc** [comment]
Now that we have engine access and don't have to hack around it, this may be worth looking into again.

**Comment by Gocnak** [comment]
Strata has the range of -10 (ultra high quality) to 4 (very low quality). This is a reasonable enough range for our min spec of DX11-capable machines.
