### ISSUE TITLE
Spectator mode can be used to teleport in a run

### ISSUE THREAD

**Issue by benjl** [momentum-mod/game#497]
`mom_spectate_stop` teleports you to where you last entered spectator mode, regardless of being in spectator mode or not, and doesn't invalidate runs.

To reproduce: 
1. Go somewhere in the map and type `mom_spectate`, followed by `mom_spectate_stop`
2. Go to the start zone
3. Type `mom_spectate_stop`

**Comment by Gocnak** [comment]
This is intentional. The timer keeps going while you spectate.
