### ISSUE TITLE
Add HL2-style AH (Accelerated Hopping) Gamemode

### ISSUE THREAD

**Issue by tsa96** [momentum-mod/game#499]
There's been an increased interest in running custom HL2 maps lately, so myself and Waezone have been looking to get the game's splendidly wacky movement in Momentum. We've managed to get the essential movement working almost perfectly in under 200 lines of new code, and the only thing we've had to change in code related to other gamemodes is explicitly set their gravity to 800, as we set it to 650 in AH.

- [x] Add the new gamemode, auto set movement vars etc.
- [x] Implement the core HL2 movement
	- [x] ABH/ASH/AFH
	- [x] Sprint
	- [x] Crouch
	- [x] Toggleduck
- [x] Add togglable suit sprint noises - Done, can commit whenever
- [ ] Start zone speed limit to 700 ups - First thing tomorrow
- [x] Add sprint and walk to keypress UI
- [ ] Custom suit noise - Change from pointing to HL2Player.SuitSprint to a custom Momentum sound.

Our fork can be found here https://github.com/tsa96/game/tree/feature/hl2-movement

A zoned AH map, made by Mac, can be found here: http://trumpetdust.org/dl/ah_orange.bsp http://trumpetdust.org/dl/ah_orange.zon

**Comment by Gocnak** [comment]
We are not adding any health / fall damage mechanics. RJ / SJ are limiting explosives through entities, the fall damage of HL2 adds to the challenge of running the game but will otherwise be out of place in a game that does not have health in any other regard.

**Comment by tsa96** [comment]
Goddamnit I just accidently pressed Close Issue, sorry!!
