### ISSUE TITLE
Leaderboards - Client Code

### ISSUE THREAD

**Issue by TheAsuro** [momentum-mod/game#5]
For people to compare their times. Global leaderboards will need a sql database hosted somewhere, and also a way to make sure people used the correct map (md5 hash?). Also, how are we going to manage user accounts?

**Comment by sndrec** [comment]
this is probably something to worry about for much later in the mod's development.

user accounts are going to be tied to your steam ID, obvo

**Comment by gusnaughton** [comment]
Before discussion here gets more in-depth, please keep in mind that any server-related features of the leaderboard should be discussed here: https://github.com/momentum-mod/leaderboards/issues

**Comment by RabsRincon** [comment]
If the site is down (502), will be hard to test it

**Comment by gusnaughton** [comment]
Working on it.

**Comment by gusnaughton** [comment]
Fixed - uwsgi crashed.
