### ISSUE TITLE
Travis CI isn't setup

### ISSUE THREAD

**Issue by Margen67** [momentum-mod/game#510]
If you click on the green check mark next to a commit you won't find Travis listed.
I went to what I assume is momentum-mod's Travis account and only found the website: https://travis-ci.com/momentum-mod/

**Comment by Gocnak** [comment]
Right, we don't use Travis for this repository. Instead, we use [AppVeyor for Windows builds](https://ci.appveyor.com/project/Gocnak/game-ig8bh) and [CircleCI for Linux builds](https://circleci.com/gh/momentum-mod/workflows/game).

They build every PR, and AppVeyor is set up to build every push to develop/master on top of that.

**Comment by Margen67** [comment]
Maybe it should be deleted if it isn't used?

**Comment by Gocnak** [comment]
It's used for the website repository, though I can look into deleting it for the game.
