### ISSUE TITLE
Combine mom_rj_center_fire and cl_righthand into a single cvar

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#521]
Suggested: mom_rj_fireangle -1|0|1

Currently the cvar setup is fairly nonsensical, with mom_rj_center_fire over-riding cl_righthand when rocket jumping. Forcing all weapons to follow cl_righthand but not RL feels arbitrary, either all weapons should follow a single left/right/center, or each weapon gets its own cvar for maximum customizability.

**Comment by Gocnak** [comment]
No other guns have a center fire option though, and there's no plan to support it for them. Condensing the two into one doesn't make sense either, as it negates the need for cl_righthand which is indeed needed for the other weapons. `center_fire` being 1 makes it forced center, 0 respects what righthand setting you have.
