### ISSUE TITLE
Jumping disregards changes to sv_gravity

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#539]
**Describe the bug**
Due to `g_bMovementOptimizations` being true, some calculations are assuming that gravity is always 800, which isn't the case sometimes. Remove the checks where this bool is true and the gravity is assumed.

**To Reproduce**
1. Start a map in mapping mode
2. Change sv_gravity to some other value than 400
3. Note that jumping is the same height but is just slower

**Expected behavior**
The jumping height should be twice as high at half gravity.

**Comment by tsa96** [comment]
This appears essential for the ahop branch as HL2 has 650 grav, I can work on this in the next few days

**Comment by Gocnak** [comment]
From what I can determine, ahop won't use any of our gamemovement code but instead just the base class for every single thing. It may be tricky since we'll most likely want our rampbug and slope jump fixes though.
