### ISSUE TITLE
mat_texture_list 1 causes inconsistent crashes

### ISSUE THREAD

**Issue by patrickmoc** [momentum-mod/game#548]
**Bug Description**
mat_texture_list seems to be causing the game to crash shortly after rendering the menu. It was happening consistently for me but the behavior seemed to differ between my machine and Hat Kid's.

**To Reproduce**

- Load into a map (in my case: surf_artifex, in hat kid's case: de_dust)
- Activate mat_texture_list 1

**My Screenshots**
![screen](https://user-images.githubusercontent.com/49064563/73127015-9708d380-3f90-11ea-9587-a6f7e0ffcd9f.jpg)

![Capture](https://user-images.githubusercontent.com/49064563/73127020-a25bff00-3f90-11ea-9057-483eaf87e642.JPG)

**Hat Kid Screenshots**

![unknown](https://user-images.githubusercontent.com/49064563/73127033-c6b7db80-3f90-11ea-8740-7adb8daf3d03.png)
![unknown (1)](https://user-images.githubusercontent.com/49064563/73127038-e9e28b00-3f90-11ea-9537-aefd741be550.png)

 - OS: Windows

**Additional context**
The crashes seem to happen more quickly or frequently at higher resolutions from my testing.

**Comment by Gocnak** [comment]
Does this still happen after #916  ?

**Comment by patrickmoc** [comment]
I can no longer reproduce this on the new engine branch so I will close this issue and mark it as resolved.
