### ISSUE TITLE
Default viewing angle on resetting in the middle of a run

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#554]
**What feature is your improvement idea related to? Please describe.**
Going back to the start zone while mid run will keep the players view angle the same as where he was looking prior to the reset. Maps should have an established "forward" viewing angle for the start zone.

**Describe the solution you'd like** 
A "forward" viewing angle for maps so that the player always faces in a specific direction when resetting.

**Comment by xen-000** [comment]
It should be noted that zone triggers placed in hammer have this feature, meaning it's only a matter of adding the same functionality to .zon zones.

**Comment by Gocnak** [comment]
Will come by 0.9.0 in the form of a button that sets the start angle for the zone, just needs exposing through the UI.

**Comment by jason-e** [comment]
This goes along with #313. Start zones, stage zones, and sometimes map end zones generally have an `info_teleport_destination` that is both in a nice, safe restart location and has the "correct" restart angle. Restarting should put the player at this destination and angle (unless a custom start has been set of course), and also probably teleport the player directly to the ground below by tracing down. Using the `info_teleport_destination` also maximizes the chance of correctly resetting things like `targetname`, as the mapper may have positioned a resetting trigger just around the `info_teleport_destination`. Setting this reset point is almost always just a matter of detecting which `info_teleport_destination` is closest to the zone, which could be done automatically when a zone is created.

**Comment by Gocnak** [comment]
Zones now have a required restart destination which adds this functionality. Will be in 0.10.0
