### ISSUE TITLE
Implementing Trikz physics

### ISSUE THREAD

**Issue by shavitush** [momentum-mod/game#58]
I think that implementing the physics of Trikz (flashbang boosting, skyboosts, runboosts etc) is also a must for such a mod like Momentum.

I can't label it as "feature".. so, can you?

**Comment by tuxxi** [comment]
This will likely happen very far down the line, if at all. Momentum is a surfing/autobhop mod, with kz support only existing due to how easy it was to add in. Trikz support is much more difficult to add, so if it is ever added, we will work on it after beta or after we release officially.

**Comment by Gocnak** [comment]
Will be implemented in the future, after 1.0.0.

Moved to https://trello.com/c/eTJ9Zt7o/231-trikz-support
