### ISSUE TITLE
Brighter Modulate Shader Option

### ISSUE THREAD

**Issue by ghost** [momentum-mod/game#585]
**What feature is your improvement idea related to? Please describe.**
The current `Modulate` shader doesn't really have any options I could find that make it bright enough to act as a fake light you can place on walls via an overlay, so in the case of overlays you need to put several of them on top of each other, which isn't too big a deal but can add up fast in quantity and tedium.

**Describe the solution you'd like**
Either:
- Some modification to `Modulate` with something along the lines of `$mod4x` or `$mod8x`
- Alternate `Modulate` shader (ie. different line at start of the VMT) that is brighter or otherwise has the desired functionality.

**Describe alternatives you've considered, if any**
Stacking overlays does seem to work.
`Unlitgeneric` is fully opaque instead of brightening the surface behind it.

**Additional context**
Stacking overlays, 3/4 on the left, 2 centre and just a single on the right.
As you can see, it's quite lacking.
![](https://i.imgur.com/cXvVGG4.png)

**Comment by Gocnak** [comment]
I believe this was done by Slidy in the DX11 branch. Will add to 0.9.0 board for now.

**Comment by SlidyBat** [comment]
Added an $hdrscale parameter (only present in DX11 version of the shader).

It works as a multiplier for the final result, so an $hdrscale of 2 is equivalent to having $mod2x.

Here are some examples:
`$hdrscale 1`
![image](https://user-images.githubusercontent.com/25954912/117635298-08d75180-b1c3-11eb-8ffd-849bee616cb4.png)

`$hdrscale 2`
![image](https://user-images.githubusercontent.com/25954912/117635349-1260b980-b1c3-11eb-9fd1-79a17c66223c.png)

`$hdrscale 10`
![image](https://user-images.githubusercontent.com/25954912/117635392-1ab8f480-b1c3-11eb-8a93-c4e79fa91642.png)

**Comment by Gocnak** [comment]
Marking as resolved as it's in DX11 and we will be moving over to that by 1.0.0 anyways.
