### ISSUE TITLE
Menu GUI

### ISSUE THREAD

**Issue by Sewq90** [momentum-mod/game#59]
The texts in main menu are extremely hard to see, maybe change the color of the text?
[SCREENSHOT](http://imgur.com/O3RBIIV)

**Comment by tuxxi** [comment]
Hey Sewq90, thanks for the feedback! You're totally right, the main menu right now is pretty hard to read and frankly pretty ugly too, haha. We'll definitely be changing the menu quite a bit in the future, the one that exists right now is somewhat of a placeholder. 

If you have any other feedback, don't hesitate to let us know! You can [contact us](http://momentum-mod.org/contact) or just open another issue here on GitHub.

-tuxxi

**Comment by RabsRincon** [comment]
0.5.0 introduces a new, prettier GameUI.
