### ISSUE TITLE
UPS speedometer

### ISSUE THREAD

**Issue by sndrec** [momentum-mod/game#6]
should get in horizontal speedometer ASAP. maybe have it displayed as small, center justified text under the crosshair? a la quake live

**Comment by Juxtapo** [comment]
xyz as well as it's more useful than just horiz for surf

**Comment by Flipybitz** [comment]
@Juxtapo, maybe an option somewhere to track _both_ would be even more useful.

**Comment by Flipybitz** [comment]
What about a sound for running into a wall/being up against a wall while moving, to allert the player of possible speed loss. The sound that plays would be louder or quieter depending on how hard they hit the wall/how much speed they lose. Sound good?

**Comment by Gocnak** [comment]
Use mom_speedmeter and mom_speedmeter_hvel to use this.

Any other features can be suggested in new issues.
