### ISSUE TITLE
Skyboxes are culled when looking away with a high enough FOV

### ISSUE THREAD

**Issue by xen-000** [momentum-mod/game#609]
**Describe the bug**
If FOV is set high enough, the skybox gets culled on the sides revealing the void.

**To Reproduce**

- Set `fov_desired` to a higher value like 120
- Load a map and look at the skybox

**Expected behavior**
The side faces show the void if looking away

**Screenshots**
This is taken with `gl_clear 1` so the void is black
![hl2_2020-03-04_16-06-44](https://user-images.githubusercontent.com/24222257/75887558-a520fe00-5e32-11ea-9beb-e7fc1d577aaa.png)

Reported by ficool2

This can be patched in the engine similar to tickrate by modifying the value used here:
https://github.com/VSES/SourceEngine2007/blob/master/se2007/engine/gl_warp.cpp#L315

**Comment by Gocnak** [comment]
Added the engine tag as when we get it we will be going through and properly tackling everything with the tag.
