### ISSUE TITLE
Optimize the windows builder bot

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#634]
Currently the windows builder builds the "everything.sln" project for every PR, even if the only code changed was in the game projects SLN.

It could be worth it to do more optimizing on how it builds; only building game projects by default (might need another `slnfix.txt` file), and only building the "everything" project if it detects code changes in the tool folders, and for the PR to master.

It may also be worth it to look into using GitHub actions for PR builds with the other CI platforms only caring about PRs to master.

**Comment by Margen67** [comment]
This is possible with GitHub Actions, but would require separate ymls.

**Comment by Gocnak** [comment]
Closing, this is already done for our internal code repo.
