### ISSUE TITLE
env_projectedtexture Texture breaks on mat_reloadallmaterials

### ISSUE THREAD

**Issue by McGravel** [momentum-mod/game#672]
**Describe the bug**
When you do mat_reloadallmaterials, any env_projectedtexture entity's texture, specified or not, seems to switch to a random one in a pattern.
The pattern persists between map loads (map mapname was used)
This may relate to the texture being a raw VTF instead of a VMT being specified.

**To Reproduce**

[Youtube link of end-result I had recorded somewhere](https://youtu.be/Dnwam4VqRB0)

**Expected behavior**
The texture does not change when this command is run.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Added the `texturename` key to the Base.FGD for this setting and came across this when testing another texture in the same map.

**Comment by Gocnak** [comment]
It looks like the texture name is always fetched upon updating the light:
https://github.com/momentum-mod/game/blob/develop/mp/src/game/client/c_env_projectedtexture.cpp#L194

But the flashlight itself isn't updated until either forced to or the target entity is null. If there's some way for us to know when materials are reloaded, it would just be a matter of forcing the flashlight to be updated.

**Comment by Gocnak** [comment]
I'm thinking that we could compare with the current flashlight state and if the stored material isn't the same as the fetched one from materials, update the state.
