### ISSUE TITLE
game_text

### ISSUE THREAD

**Issue by Juxtapo** [momentum-mod/game#7]
game_text is a very useful entity and it may be disabled by default (It was only added in CS:S recently, and is missing in many source games) so if someone could make sure it's available that would be great!

**Comment by Flipybitz** [comment]
Can you explain what this is exactly? Sounds interesting.

**Comment by Juxtapo** [comment]
https://developer.valvesoftware.com/wiki/Game_text

**Comment by Gocnak** [comment]
This exists, no need to worry. Re-open if it's not, but it's in the game code and not commented out.
