### ISSUE TITLE
[Replay/Run Stats/Comparison] Fetch player's PB

### ISSUE THREAD

**Issue by luccapedrini** [momentum-mod/game#706]
**What feature is your improvement idea related to? Please describe.**
The way to fetch the player's pb can be done by the run stats and by getting the `CMomReplayBase` using `MomUtil::GetBestTime`, the problem with this is that run stats only store the stats by zone and if you want to get the overall you need to sum all the zone stats you want, and using GetBestTime when  you want to get stats is costly.

**Describe alternatives you've considered, if any**
Have all the run related attributes in run stats and load the player's best run when he loads the map.

**Additional context**
This can be reproduced by opening the leaderboards for the first time in a map, `LeaderboardsTimes.cpp` has a method simillar to `MomUtil::GetBestTime`.

**Comment by luccapedrini** [comment]
Instead of opening another issue I'm gonna expand on this one.
### The performance issue
We found out that the micro-stuttering is related to the amount of replays you have saved locally, don't know exactly how many it needs to start stuttering but when i checked i had 250.

This could be fixed in many ways. Gocnak suggested making the methods run in a working thread with a call back function, this seems like best way to tackle this now, since all the other ideas involved limiting players replay amount.

Some other ideas that popped in my head:
1. Index file
2. Save run time in replay name and check it before fetching the data.

### Centralize players PBs
Player PB is being fetched in at least three different ways code, ( `LeaderboardTimes.cpp`, `hud_comparisons.cpp`, `map_finished.cpp` ) centralizing it should improve a lot of the overhead when dealing with local replays.

**Comment by Gocnak** [comment]
The performance issue has been moved out to #930
