### ISSUE TITLE
Let GameUI dialogs auto apply changes rather than requiring OK/Apply

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#708]
**What feature is your improvement idea related to? Please describe.**
Do not need to press OK/Apply for GameUI option changes to take place. This is very similar to removing OK/Apply/Cancel buttons from the momentum settings panel ( #685 ).

**Describe the solution you'd like**
Change these dialogs to auto apply:

1. Keyboard settings - Complete: #707 
2. Mouse settings - Complete: #702 
3. Audio settings -Complete:  #703 
4. Video settings - Complete: #704 

As these settings write to a config file when OK/Apply is pressed, the functionality and text of the Apply button can Change; remove the OK/Cancel buttons and change the functionality of the Apply button to write the config file. Change the text on it to "Write settings to config file" or something similar.

**Describe alternatives you've considered, if any**
Settings can also write to the config files immediately after auto-applying, but this may be costly to do constantly. Could remove the buttons on the bottom if this route is chosen though.

**Additional context**
Future UX designs will most likely use a good amount of this code so this change will likely help in that transition.

**Comment by Gocnak** [comment]
Is this complete too?

**Comment by braem** [comment]
Almost, just have to change/remove the OK/Cancel/Apply buttons now.
