### ISSUE TITLE
Convert the rest of the UI to use cvar-tied vgui controls where appropriate

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#710]
**What feature is your improvement idea related to? Please describe.**
Now that the momentum settings pages are converted and the GameUI dialogs are being converted, the other UI that uses `CvarSlider`, `CvarComboBox`, `CvarTextEntry`, etc. needs to be converted.
These are: 

- Zone Menu - Complete #711 
- Paint gun panel - Complete #712
- Replay UI - Complete #713

**Describe the solution you'd like**
- Convert the instantiation of `CvarSlider` to use auto-apply where appropriate.
- Add `CvarTextEntry` number format overrides & numeric only flag. Convert cvar-tied `TextEntry`'s to `CvarTextEntry`.
- Convert cvar-tied `ComboBox`'s to `CvarComboBox`.

**Comment by Gocnak** [comment]
Completed
