### ISSUE TITLE
Use standalone ShaderCompile

### ISSUE THREAD

**Issue by bonjorno7** [momentum-mod/game#731]
Valve's ShaderCompile takes like 30 minutes to build PBR; the standalone ShaderCompile could do it in 3 minutes.

Should use Valve's ShaderCompile for .inc files so we don't have to change cshader.h and rebuild all shaders. For the main shader compilation it should use Sears's fork of SCell's ShaderCompile.

Instead of using Valve's ShaderCompile for inc files we could try to implement it into SCell's I guess but I already have this solution working so, meh.

To make it work I had to downgrade parallax mapping a little bit but it's not too noticable.

![Desktop Screenshot 2020 05 05 - 20 10 05 81](https://user-images.githubusercontent.com/43251584/81112538-18bcb580-8f1f-11ea-990d-618abc27d8c5.png)

![Desktop Screenshot 2020 05 05 - 20 11 28 48](https://user-images.githubusercontent.com/43251584/81112553-1ce8d300-8f1f-11ea-8567-5146d36d4d8f.png)

**Comment by SCell555** [comment]
For the incompatible inc files, you can run them through ShaderCompile with -dynamic switch and it will regenerate inc files only. All index calculations are the same as with ones generated with perl, so recompiling them is not necessary.
As for exit on first error, I think I'll add that feature, as it seems like useful feature.

**Comment by Gocnak** [comment]
Closed in https://github.com/momentum-mod/game/pull/739
