### ISSUE TITLE
Remove DX <= 80 / Shader Model <= 2.0 shaders

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#733]
**What feature is your improvement idea related to? Please describe.**
Shader files

**Describe the solution you'd like**
We have a ton of shaders in the `materialsystem/stdshaders/` folder that we don't support due to being on a lower shader model, or just due to using the higher version anyways.

We require DX9 by default now so we can remove all the gross shader model 2.0 and below versions (assuming that there's at least a 2.0b+ version, otherwise keep the 2.0 version but delete the ones below). 2.0b is required for Linux, so keep those in at the very minimum.

Example:
`BlurFilter_ps11`, `BlurFilter_vs11`, `BlurFilterX_dx80`, and `BlurFilterY_dx80` can be removed due to there being a `BlurFilterX.cpp [shader model 2.0+]`, `BlurFilter_ps2x`, etc.

**Comment by kleinapple** [comment]
I can do this either via grunt work or a script, but because I'm not familiar with shader naming conventions, would need a detailed ruleset of what qualifies as an unsupported or obviated shader. The example is nice but not comprehensive.
