### ISSUE TITLE
SVG rendering with librsvg + Cairo

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#740]
**Is your feature request related to a problem? Please describe.**
VGUI / UI

**Describe the solution you'd like**
Using [librsvg](https://gitlab.gnome.org/GNOME/librsvg) and [Cairo](https://www.cairographics.org/) we could look into rendering an SVG akin to how the current `FileImage` class handles PNG/JPG/etc. It would be a child class of `FileImage`.

Main idea of flow:

Load image via `g_pFullFileSystem->ReadFile` into a CUtlBuffer, pass the buffer of bytes down into `librsvg` via the [rvsg_handle_new_from_data](https://developer.gnome.org/rsvg/stable/RsvgHandle.html#rsvg-handle-new-from-data) method. Then it can be rendered via [rsvg_handle_render_cairo](https://developer.gnome.org/rsvg/stable/rsvg-Using-RSVG-with-cairo.html#rsvg-handle-render-cairo) into a Cairo context. Additional things can be applied to the cairo context, such as rotation, before being rendered via [cairo_surface_write_to_png_stream](https://www.cairographics.org/manual/cairo-PNG-Support.html#cairo-surface-write-to-png-stream) with an RBGA8888 output. This can then be copied over via surface and rendered via VGUI.

**Describe alternatives you've considered**
Another UI platform like Panorama could solve this for us already, but would be too much of a cost.

**Comment by SlidyBat** [comment]
Now that we have Panorama, we should explore whether this is still something we want. Panorama comes with it's own SVG loader, but it seems that it has trouble rendering some types of SVGs correctly. We should investigate what causes these SVGs to render incorrectly to decide what to do about this.

See attached example file:
[playIcon.zip](https://github.com/momentum-mod/game/files/6433670/playIcon.zip)

**Comment by Gocnak** [comment]
Two month update: should we still do this? I think it was agreed upon that just updating the SVG parser to support the things we need, and carefully editing the SVGs to properly work with our parser was the way we were gonna go.

It's always an option to use librsvg though even they don't implement the full SVG spec... Closing for now, can always re-open if it's the path we actually want to take.

**Comment by SlidyBat** [comment]
Yeah, the panorama SVG loader was fixed/updated to support more types of SVGs, and I don't think there are any that we're having trouble loading anymore (the file I originally attached now renders correctly in-game).

If/when we feel restricted by the kind of SVGs we can load, we can revisit this.
