### ISSUE TITLE
Paintgun decal previewing

### ISSUE THREAD

**Issue by Flipybitz** [momentum-mod/game#759]
**What feature is your improvement idea related to? Please describe.**
I think it would be handy to be able to see a preview of your paint dot on the surface you're aiming at before placing it. Considering there's no way to currently remove single decals, it makes it sorta "permanent" where the only way to undo paint is to clear ALL of it. This can be a 1.0+ feature, but I figured I would still put it here.

**Describe the solution you'd like**
Render the paint decal at 10% opacity wherever you're aiming, or have a circular outline that would represent the size of the brush, with a dot in the middle for precision. Something along these lines would be super handy: 
![image](https://user-images.githubusercontent.com/3002858/81994482-96fb1500-960d-11ea-981c-4de19d5b54aa.png)

**Describe alternatives you've considered, if any**
We could also look into the ability to manipulate individual decals, we could add an "eraser" feature for paint decals, or we could add the ability to clear the last decal placed into the actual paintgun modal

**Additional context**
This should be low priority, but I think it would help improve the usefulness of the paintgun significantly. It could even open up more creative/artistic possibilities for those who want a break from going fast all the time :)

**Comment by braem** [comment]
Closing as the paintgun was removed https://github.com/momentum-mod/game/pull/890
