### ISSUE TITLE
Implement trigger_momentum_timer_cancel

### ISSUE THREAD

**Issue by Arkanoid0** [momentum-mod/game#763]
### Reason for Inclusion
Some maps are designed in such a way that you can walk or otherwise transport yourself between the start of the map and the end of the map without doing the map properly. This is not usually a problem with the timer invalidating the run, but such maps often have non-gameplay sections where you don't want the timer to be running.

This also nicely fixes #205 by only allowing the timer to switch tracks when the timer is the "no timer" state.
### Proposed keyvalues
track_number (-1,0,1)

**Comment by sleepCOW** [comment]
Am I correct that you would like to have a new trigger zone which will cancel the player's timer on touch?
With keyvalue <track_number> (-1,0,1) representing when this zone should affect the player?

**Comment by braem** [comment]
> 
> 
> Am I correct that you would like to have a new trigger zone which will cancel the player's timer on touch?
> With keyvalue <track_number> (-1,0,1) representing when this zone should affect the player?

I believe they mean to cancel the timer on touch if the player's current run is on the same track, with the numbers meaning what the other timer triggers mean, like [`trigger_momentum_timer_stop`](https://docs.momentum-mod.org/entity/trigger_momentum_timer_stop/). IE
`track_number` = `-1`: Always cancel timer regardless of track
`track_number` = `0`: Cancel timer if player is on a map run (track 0)
`track_number` = `1` or greater: Cancel timer if player is on the same track (bonus).

Not sure what utility there is in specifying track number here though.

**Comment by sleepCOW** [comment]
> > Am I correct that you would like to have a new trigger zone which will cancel the player's timer on touch?
> > With keyvalue <track_number> (-1,0,1) representing when this zone should affect the player?
> 
> I believe they mean to cancel the timer on touch if the player's current run is on the same track, with the numbers meaning what the other timer triggers mean, like [`trigger_momentum_timer_stop`](https://docs.momentum-mod.org/entity/trigger_momentum_timer_stop/). IE
> `track_number` = `-1`: Always cancel timer regardless of track
> `track_number` = `0`: Cancel timer if player is on a map run (track 0)
> `track_number` = `1` or greater: Cancel timer if player is on the same track (bonus).
> 
> Not sure what utility there is in specifying track number here though.

Thank you for the clarification, I will do this
