### ISSUE TITLE
Make the paintgun automatically equipped in every gamemode

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#764]
**What feature is your improvement idea related to? Please describe.**
Currently, the only way to get the paintgun is to do the `give_weapon` command in console, which is not very intuitive compared to other weapons. It would be easier have the paintgun assigned to its own slot so it can be bound to a key and not have to do the console command/create a bind every time. This would also require a "blank" weapon for gamemodes that don't require weapons (all the time) so the paintgun isn't always visible (eg surf).

**Describe the solution you'd like**
Give the paintgun by default for every gamemode, and have it in its own slot. Also add a "blank" weapon for gamemodes that don't require weapons, so the paintgun is not the active weapon all the time.

**Comment by braem** [comment]
Closing as will be resolved by implementing https://github.com/momentum-mod/game/issues/886
