### ISSUE TITLE
Sorting by favorite/in library on the map selector sorts by name

### ISSUE THREAD

**Issue by Flipybitz** [momentum-mod/game#774]
**Describe the bug**
It appears that clicking both the favorites icon and the in library icons to sort them **actually** sorts them by name. Sorting by name functions as intended, so it appears that it was accidentally applied to these buttons as well.

**Expected behavior**
Since there's already tabs for favorites and library, the sorting functionality for both buttons is redundant and should just be disabled.

**Screenshots**
Clicked once
![image](https://user-images.githubusercontent.com/3002858/82621925-0f2f8080-9ba2-11ea-97ee-77b981511cfb.png)
Clicked again
![image](https://user-images.githubusercontent.com/3002858/82621956-25d5d780-9ba2-11ea-8b4a-80357bbcc4b7.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Flipybitz** [comment]
Updated issue since it appears that the "in library" icon has the same issue

**Comment by Gocnak** [comment]
This would be more of a UX question, should sorting by this be disabled? Because there are the favorites and library tabs...
