### ISSUE TITLE
Map finished time comparison sometimes shows a very high value or doesn't show at all

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#780]
**Describe the bug**
Sometimes the time comparison on the map finished panel shows a ridiculously high value. Sometimes it doesn't show at all (when it should).

**To Reproduce**
Cannot reproduce this consistently. Basically just finish several maps hoping it pops up.

**Screenshots**
![image](https://user-images.githubusercontent.com/9014762/82749292-fddea380-9d5c-11ea-8caf-109e64e9f821.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
The bad line of code is [here](https://github.com/momentum-mod/game/blob/564dd9455658c7bc7c4a556a7408061bf5994b6d/mp/src/game/client/momentum/ui/HUD/hud_mapfinished.cpp#L519).
Debugged this and it doesn't make much sense. `diff` sometimes gets a really high value:
![image](https://user-images.githubusercontent.com/9014762/82749060-80666380-9d5b-11ea-92ca-8d008bc0da36.png)
This is despite the components in the calculation being sensible: 
![image](https://user-images.githubusercontent.com/9014762/82749130-f7036100-9d5b-11ea-8acc-c6ea97174c2a.png)
![image](https://user-images.githubusercontent.com/9014762/82749145-100c1200-9d5c-11ea-8623-7a852ce7d248.png)
![image](https://user-images.githubusercontent.com/9014762/82749192-519cbd00-9d5c-11ea-9f35-add493eaccd1.png)
`diff` here should be `-308.85`. 

Tried using `static_cast<float>` instead of `float` to no avail.

**Comment by Gocnak** [comment]
Oh boy, signage issues. Pretty sure one of these is values are stored as unsigned ints, so going negative wraps to the upper bound of the 32 bit int, aka 6 billion. Solution may be to cast to signed int

**Comment by Gocnak** [comment]
Also, doesn't show at all = you had no run comparison (PB)

**Comment by braem** [comment]
> Also, doesn't show at all = you had no run comparison (PB)

I remember it not showing even though there was a run comparison, though I was probably been looking at a PR I got on 0.8.4 since they're shared.

> Oh boy, signage issues. Pretty sure one of these is values are stored as unsigned ints, so going negative wraps to the upper bound of the unsigned 32 bit int, aka 6 billion. Solution may be to cast `GetZoneTicks` result to signed int

Ah! I was thinking it was related to a negative value, though I was able to still get a diff under 0 & it showed fine. Weird.
