### ISSUE TITLE
Menu buttons don't show subtext properly on my system

### ISSUE THREAD

**Issue by ianbean2001** [momentum-mod/game#83]
I am on a 1920x1080 monitor and running the game at that as well. The mod is in full screen. Here's the screenshot of the bug: https://imgur.com/a/Ff9WT.

Oh and I don't know if it's supposed to work but triggertest doesn't load up.

**Comment by Gocnak** [comment]
Thank you for the bug report! This is going to be fixed in the next major push; the offset for the text was a tad too small.

**Comment by RabsRincon** [comment]
Also, triggertest is porbably not loading because `mom_allow_custom_maps` is set to `0`. We will make it more obvious on the next major push too

**Comment by ianbean2001** [comment]
Yeah changing that value to 1 loads it.

**Comment by RabsRincon** [comment]
Thank you for reporting the bug. If you find any more bugs/errors etc... , please contact us again 😄
