### ISSUE TITLE
Shader override fails when another game's bin folder is in PATH

### ISSUE THREAD

**Issue by SlidyBat** [momentum-mod/game#832]
**Describe the bug**
To override shaders we rely on the `stdshader*.dll` files not existing. However, some users, mostly mappers, have other game's bin folder in their PATH which makes the engine try to load `stdshader*.dll` from there.

**To Reproduce**
Add a bin folder that contains `stdshader*.dll` to your PATH envvar. For example you could add `C:\Program Files (x86)\Steam\steamapps\common\Team Fortress 2\bin`. Try running Momentum and you'll get a launch error about overriding shaders.

**Expected behavior**
People have the bin folder in their PATH in order to use the mapping tools in the command line from anywhere. Ideally we shouldn't interfere with this and allow running Momentum regardless of what the user has in their PATH.

**Potential fix**
We could add logic in the game to remove other source engine games bin folders from the PATH at runtime. Would have to make sure that this happens before the engine loads the stdshader DLLs.

**Comment by Gocnak** [comment]
Engine access fixed this. Closing.
