### ISSUE TITLE
A few little questions

### ISSUE THREAD

**Issue by ianbean2001** [momentum-mod/game#84]
I've been experimenting with the mod a little bit more (trying to compile maps for it, zoning, reading commands) and have a few little things I was thinking about.

The Trello roadmap doesn't show much more done to zoning, except for adding different types of zones, and I was just wondering if you were going to add a visual component like cksurf's zoning. Additionally, I am interpreting that the documentation on zoning (command descriptions) expects you to know when to place different types of zones, and I am having issues getting stage starts and the finish trigger to work.

I have a very picky and minuscule question about the prefix for commands, as in why it's mom instead of something like mm ('**M**omentum **M**od' vs 'mother'). I know that's a very small issue and I get it if you don't want to change every console command reference for one little thing.

Lastly, I am having trouble compiling for this mod in hammer, but maybe I'm setting the game config up wrong. On that topic, I read in one of the blog posts that you guys are mapping using plugins for 3DS Max, and I'm wondering if you are supporting hammer at all.

Sorry for the big post, but I didn't want to fill the issue box with small posts. If there is information you can direct me to to know more about these certain issues I'll be sure to read up.

**Comment by JasonZ10** [comment]
Hey Ian,

In regards to zoning, we will be zoning all of the maps when we begin recording times, and will likely have a toggle-able laser drawing the zone boundaries. If you're having trouble getting your own personal zones working, [check out this guide](http://www.moddb.com/mods/momentum2/tutorials/using-mom-zone-commands).

If you already have CS:S hammer setup, maps compiled there can be run in Momentum Mod natively. If you want to utilize the custom triggers, you'll have to setup the game config in SDK 2013 Hammer. Also, the blog post regarding 3DS Max was just showing some level mock ups made by a 3D artist involved in the project. All mapping will be done in Hammer aside from model/material creation. 

Lastly, we will be changing the command prefix to [p_](https://en.wikipedia.org/wiki/Momentum) right before alpha is released.

**Comment by ianbean2001** [comment]
Thanks for the reply and the dense information, I didn't know this had a moddb page. I also **love** the command prefix.
