### ISSUE TITLE
Trails stacking if you change color while spectating someone

### ISSUE THREAD

**Issue by tricksurf** [momentum-mod/game#844]
**Describe the bug**
If you change your trail color while spectating someone, your trail will show up on top of theirs. 

**To Reproduce**
1. Spectate someone.
2. Change trail color.
3. Profit

https://www.youtube.com/watch?v=ZOSvft0HKFI

**Expected behavior**
I would assume you should only see the player you're spectating's trail.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by braem** [comment]
The handle for the trail is not valid when it's changed like this, causing it to not be removed. Not sure why.
![image](https://user-images.githubusercontent.com/9014762/88227239-28948d80-cc22-11ea-9c43-71fc9863784f.png)

**Comment by Gocnak** [comment]
I figured this was just a problem of player appearance data force updating even though the player `IsObeserver()`

**Comment by braem** [comment]
Ah didn't realize it gets updated on player spawn so can just do an `IsObserver()` early return yeah.
