### ISSUE TITLE
Resetting in RJ/SJ while crouched causes glitched camera state

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#852]
**Describe the bug**
"if I reset my map run while crouched I remain crouched without pressing the crouch key" - vov&sons
Creating a start mark may also affect this...

**To Reproduce**

- Go to a map with zones
- Start a run
- Use `mom_restart` while fully crouched
- Notice the view stays crouched (?)

**Expected behavior**
The view should reset to fully unducked. This may be related to the start mark code with resetting, as savelocs save crouched state, and I believe upon resetting to a start mark it may be trying to reset crouch state without resetting view height...

**Comment by tricksurf** [comment]
This also applies to savelocs btw
