### ISSUE TITLE
sv_maxvelocity

### ISSUE THREAD

**Issue by lodyb** [momentum-mod/game#87]
sv_maxvelocity seems to be a protected svar, and a lot of the newer maps rely on unlocking this for faster gameplay.

Seems like a regression to have this set so low when we do not have to worry about going fast over the network.

Any thoughts?

**Comment by Gocnak** [comment]
Eventually the plan is to have each map be able to override it, but until we approach that point, sv_maxvelocity will be editable through console on 0.6.0.
