### ISSUE TITLE
Shooting a player or prop with paint changes paint color

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#870]
**Describe the bug**
Shooting a player model with the paintgun changes the color of already drawn paint decals. Your paint decal color then stays the same despite you changing it.

**To Reproduce**
- join a lobby
- join a map someone else is on
- have people shoot a paint decal
- shoot a player model with paint
- everyone's paint changes color
- notice how whatever you change your paintgun color to it stays the same

**Expected behavior**
Everyone's paint decal color should be what they set and not change when you or someone else shoots another player's model.

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
May happen when shooting any non-solid model.

Does not have to do with decal limit as in https://github.com/momentum-mod/game/issues/243

Might be the same issue as https://github.com/momentum-mod/game/issues/229

**Comment by Gocnak** [comment]
Does this still happen on Chaos? Painting was updated to properly store colors for models and brushes alike.

**Comment by hexaflexahexagon** [comment]
issue fixed
