### ISSUE TITLE
r_drawdecals 0 still displays decals on Displacements

### ISSUE THREAD

**Issue by NinjaTheCookie** [momentum-mod/game#879]
r_drawdecals 0 does stop drawing decals on normal surfaces, such as rocket explosion decals, but seems to still draw them on Displacements.

**Comment by lvaness** [comment]
This is definitely still happening, they still draw on displacements and props.

**Comment by Gocnak** [comment]
Yep this should be fixed for the next (0.8.8 release) push. The only thing that respected it was brushes, it's now been updated to disable decals on props, displacements, and other models.

**Comment by lvaness** [comment]
Now, it only still draws on dynamic props when it's set to 0.

**Comment by Gocnak** [comment]
Good catch, that is also fixed in the next push.

**Comment by lvaness** [comment]
Looks fixed

**Comment by Arkanoid0** [comment]
fix is good
