### ISSUE TITLE
bhop_exodus crash (and possibly more maps)

### ISSUE THREAD

**Issue by lodyb** [momentum-mod/game#88]
This crash came along back in 2010 when the cs:s engine got updated to orange box - perhaps we could fix it.

Here's how to replicate it

map bhop_exodus    (do not get bhop_exodus_fixed, it is an unofficial fixed version)

`sv_cheats 1;noclip;setpos 2715.311279 8839.288086 6182.142090;setang 79.339775 168.301331 0.000000;noclip`

You'll fall down and crash when you hit the teleport.

**Comment by Gocnak** [comment]
http://gamebanana.com/maps/181850

Using this version does not cause the crash.
