### ISSUE TITLE
showconsole only works ingame

### ISSUE THREAD

**Issue by itVictor** [momentum-mod/game#885]
**Describe the bug**
The `showconsole` command only works if you are in a map, not on the main menu. Using ` to open the console still works fine everywhere.

**To Reproduce**
Bind a key to `showconsole` then load a map. Observe that the command works as intended. Disconnect to main menu and observe that the bind does nothing.

**Expected behavior**
showconsole should work regardless of where you are

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
possibly hardcoded as part of the command to not work on main menu

**Comment by braem** [comment]
Is this on 0.8.5 on steam or the latest develop branch?

**Comment by braem** [comment]
This happens on every source game actually. ooph

**Comment by braem** [comment]
A LOT of stuff relating to this is in the engine. I pushed a wip commit if anyone wants to try to tackle further: `bug/console-toggle-keybind`.
