### ISSUE TITLE
Hull & origin of player

### ISSUE THREAD

**Issue by lodyb** [momentum-mod/game#89]
I think the hull of the player is correct (if you are going for pre-2010 CS:S).

A problem that persists is that the origin of the player is still too high - this can be tested on bhop_exodus stage 2 where the player teleports under a brush that works fine in the old CS:S but in Momentum we get stuck in the ceiling.

I've uploaded a video:
https://www.youtube.com/watch?v=KsjtdsJutG8

Here's how to test it yourself:
```
map bhop_exodus;
(wait for it to load)
sv_cheats 1;noclip;setpos -6426.276855 -4954.470703 4050.968750;setang 18.317482 148.869186 0.000000;noclip;
```

For some reason setpos only works for me when noclipped

**Comment by Gocnak** [comment]
Using an updated map provides the solution needed: make that ceiling larger. The one on gamebanana is outdated for some reason. I have an updated version, which I put on MEGA and you can download it [here.](https://mega.nz/#!pp9W3QhJ!lM33nXHWqIEI6ZjajxnIxSxwXce2qr9ZERG281apEI4) 

Using the gamebanana version on CS:S causes the exact same issue to happen. So somewhere, there's an updated Exodus that I got from a bhop server, and it's not on gamebanana.
