### ISSUE TITLE
Precise time calculations

### ISSUE THREAD

**Issue by Flipybitz** [momentum-mod/game#9]
**Before I continue... YES, precise timing is a _VERY_ important deal considering our entire mod is based around that idea. This is not an optional step, this _ABSOLUTELY MUST_ be added eventually.**
This goes along side issue #4, but as a tweak to keep in mind. If you have any questions about this or how it works, I'll re-explain it here the best I can;
`Rather than ending the timer on the tick it registers the player inside of the end zone, instead we can take the tick just _before_ the player comes inside the end zone, pair it with the tick that they are in the end zone, and use some math to calculate the end zone position between the two points and use that as the final time.`

**Comment by Juxtapo** [comment]
I'm not sure how you would pair the tick in the start zone to the one inside the end zone to get any useful information so I'll explain what I had in mind.

Say the first tick the player is in the trigger is Tick 10. You take the velocity and position (and angles to get slightly more precise) of the player on  tick 9 as well as the trigger position, and grab the time on tick 9 then add on the quotient of (distance from the trigger) / (speed) to get a more precise time.

Reverse for start zones (if they leave the start zone on tick 2, take the start trigger position and velocity/position/angles from tick 1)
