### ISSUE TITLE
Save start marks to file

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#906]
**Is your feature request related to a problem? Please describe.**
Would like the ability to keep start marks as is done with savelocs. 

**Describe the solution you'd like**
Write start mark information to file when created, and delete it when cleared. Can be in `savedlocs.txt` or a new file.

**Comment by Gocnak** [comment]
They should save to savedlocs.txt yeah

**Comment by braem** [comment]
> 
> 
> They should save to savedlocs.txt yeah

Probably best to move the code for it into the saveloc system as well then I presume.
