### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by Sewq90** [momentum-mod/game#91]
Will categories like w and sw only be a thing along with like normal (no autojump but still so that you gain as much speed as with autojump), easy (higher airaccelerate + autojump), lowgrav (same as easy but with low gravity), hard (no autojump) and insane (no nothing)

**Comment by Gocnak** [comment]
Yes.

Not all of those categories, but we will have "run tags" which will modify the game and/or specify a certain behavior of the run you submit.
