### ISSUE TITLE
The new main menu blur is on when playing maps

### ISSUE THREAD

**Issue by TheRealHona** [momentum-mod/game#911]
From my stream:
https://clips.twitch.tv/InexpensiveHonestDillAMPEnergy

**Comment by braem** [comment]
Old loading screen in this clip. Might be that the gameui DLL is old & needs to be overriden or symlinked.

**Comment by braem** [comment]
Fixed for another user by updating their gameui.dll. Doesnt seem to symlink correctly, despite https://github.com/momentum-mod/game/pull/791

**Comment by Gocnak** [comment]
Fixed by updating the GameUI dll inside MomentumDev/bin. Our script does symlink it, but only if `mp/game/bin` does *not* exist beforehand. Users with clean clones should not have issues, but existing devs will need to be reminded of this.
