### ISSUE TITLE
Stickybomb sometimes does not fire

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#912]
**Describe the bug**
Occassionally, pressing `+attack` does not fire a stickybomb. This still occurs when setting the stickybomb buffer window to a number higher than the firing rate, so it is likely not to do with the buffer.

**To Reproduce**
Difficult to reproduce. Seems to happen when pressing it close to the time you are able to shoot (around ~0.6s after firing one) and also releasing very quickly. 

**Expected behavior**
M1 should always shoot a sticky.

**Video**
Will provide a video with handcam soonTM.

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by TheRealHona** [comment]
I may have experienced this sometimes, either that or I click too early, or both. I would have no way of knowing though.

**Comment by braem** [comment]
> I may have experienced this sometimes, either that or I click too early, or both. I would have no way of knowing though.

Id say this is the culprit for the times when we swear we clicked at the correct time but nothing came out. Other people have experienced this, exile for instance.

**Comment by braem** [comment]
Looks like the problem is with this code in `weapon_mom_stickybomblauncher`:
![image](https://user-images.githubusercontent.com/9014762/91644773-33e29200-e9f4-11ea-8756-16c359e4f245.png)

Normally, the `if (bPressingM1)` branch is called and the `else if (m_bEarlyPrimaryFire.Get())` is hit next call. When the bug occurs however, the `else if` branch is never called, but the `if` is.

Removing the `else` from the `else if` here seems to fix the problem:
![image](https://user-images.githubusercontent.com/9014762/91644829-b4a18e00-e9f4-11ea-8c58-5289c789f79b.png)

Though this causes charging during the buffer to not play the charge sound.

**Comment by braem** [comment]
Video:
https://www.youtube.com/watch?v=sujo-CzoSrA
