### ISSUE TITLE
Props/textures don't load on certain workflows (reproducible)

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#915]
**Describe the bug**
Props and textures have trouble loading correctly on certain workflows. Despite props not being visible, they still have collision. 

Happens on tf2 as well, maybe all source games. Most likely will require engine access to remedy, but putting up for reference.

**To Reproduce**
Some maps not effected.

Bug 1, reported by ninja cookie:
- Open game in windowed
- Load a map
- Go into fullscreen
- Disconnect
- Go back into windowed
- Load same map

Bug 1 (alternate workflow):
- Load map
- Disconnect
- Change resolution
- Load same map

Bug 2:
- Stop loading of map prematurely (escape key while loading map)
- Start another map

**Screenshots**
Bug 1:
![image](https://user-images.githubusercontent.com/9014762/92311118-115af680-ef69-11ea-9e5b-81001ded07cc.png)
![image](https://user-images.githubusercontent.com/9014762/92311453-fb026a00-ef6b-11ea-9db7-39ac2f3f1933.png)

Bug 2:
![image](https://user-images.githubusercontent.com/9014762/92311151-7a426e80-ef69-11ea-8561-dd15c3ac772b.png)
![image](https://user-images.githubusercontent.com/9014762/92311162-8e866b80-ef69-11ea-9936-27379e8f5b0e.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional Context**
@xen-000 's debugging:
Bug 1 - Seems that when assets are reloaded on resolution/window mode, cached assets are included; the specific maps' packed assets are reloaded in the menu and fail, hence the MDLCache spam (see screenshots).

**Comment by Gocnak** [comment]
Does this still happen on Chaos?

**Comment by braem** [comment]
> 
> 
> Does this still happen on Chaos?

Nope! :)
