### ISSUE TITLE
Load replay files asynchronously

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#930]
**What feature is your improvement idea related to? Please describe.**
When a player has a large amount of replay files on a specific map, opening the leaderboards panel for the first time freezes the game until all replay files are loaded.

**Describe the solution you'd like**
Asynchronously load replay files, populating the "Local" tab of the leaderboards as they are loaded.

**Comment by bltech** [comment]
I'm trying to implement this atm, would be nice if you could tag it as assigned, thanks!
