### ISSUE TITLE
Use Alien Swarm's Viewmodel Code

### ISSUE THREAD

**Issue by Gocnak** [momentum-mod/game#939]
**What feature is your improvement idea related to? Please describe.**
Viewmodels

**Describe the solution you'd like**
ASW branch seems to have a bit more inside of its [predicted_viewmodel](https://github.com/NicolasDe/AlienSwarm/blob/c5a2d3fa853c726d040032ff2c7b90c8ed8d5d84/src/game/shared/predicted_viewmodel.cpp#L52) and [baseviewmodel_shared](https://github.com/NicolasDe/AlienSwarm/blob/c5a2d3fa853c726d040032ff2c7b90c8ed8d5d84/src/game/shared/baseviewmodel_shared.cpp#L371). It could be good to yoink this and make weapons sway a bit more like L4D.

**Describe alternatives you've considered, if any**
CS:GO weapon sway requires engine.

**Comment by xen-000** [comment]
It seems the L4D viewmodel sway is only in L4D-specific code so it's not in the public ASW SDK, but there's at least the small snippet for viewmodel offset that we can grab.
