### ISSUE TITLE
Speed threshold filter

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#942]
**Is your feature request related to a problem? Please describe.**
Give mappers the ability to filter on speed. 

**Describe the solution you'd like**
Add a speed threshold filter. Also include an `UseAbsoluteValue` field. Ability to check speed on each axis as well.
https://discordapp.com/channels/235111289435717633/602643431453360148/753346188434210906

**Comment by Gocnak** [comment]
See https://github.com/momentum-mod/game/blob/7b0c74933f5b54bf49c770bbe2352a70a381e849/mp/src/game/server/momentum/mom_triggers.cpp#L1245 for more info
