### ISSUE TITLE
Console output not formatted consistently

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#949]
Reported by osplo ( @benjl )

**Describe the bug**
At least the `find`, `echo` and `getpos` commands do not format their output consistently.

**To Reproduce**
Run `find`/`echo`/`getpos` more than once, see different results.

**Expected behavior**
The formatting should not be random.

**Screenshots**
![image](https://user-images.githubusercontent.com/9014762/93176913-d3876c00-f6e6-11ea-8308-bd4ac373ab02.png)

![image](https://user-images.githubusercontent.com/9014762/93249247-dbc2c400-f745-11ea-98f6-510361cfb70c.png)

![image](https://user-images.githubusercontent.com/9014762/93176946-deda9780-f6e6-11ea-9b02-35d09a4a7298.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version, Latest develop branch & supposedly other source games (csgo/css/tf2)

**Additional context**
Most likely will require engine access, though needs investigation first.
Perhaps a race condition?

**Comment by Gocnak** [comment]
Does this still happen on Chaos? The console uses a new and improved backend for logging.

**Comment by hexaflexahexagon** [comment]
appears to be fixed with Chaos
