### ISSUE TITLE
Different paint color on changing geometry

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#951]
Suggested by Inkurious

**Is your feature request related to a problem? Please describe.**
Surfers sometimes use paint to make the spine of ramps more visible. However, paint application applies on the ramp as well as the spine in the same color, which doesn't provide the desired visibility.

**Describe the solution you'd like**
Provide an option to have the X Y Z of plane hit normal determine paint color. This will paint the ramp spine in a different color allowing visibility.

**Describe alternatives you've considered**
If possible, only paint the spines of ramps.

**Additional context**
[Discord discussion](https://discordapp.com/channels/235111289435717633/390338161982570517/755638561637793912)

**Comment by tsa96** [comment]
Is this something we'd like on by default? Do we want to add a setting for it in Pano? I worry about how much adding obscure cvars actually benefits anyone. I'm happy to add this to the paint settings!

**Comment by SlidyBat** [comment]
Yeah should definitely add to pano settings, maybe worth separate issue on pano repo though once feature actually gets in.

**Comment by tsa96** [comment]
We don't use that repo for issues, easier to include here and try to keep cvars and settings in sync - I'll do the settings now
