### ISSUE TITLE
Noticeable delay on first sticky shot

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#952]
Reported by hex

**Describe the bug**
There is sometimes a noticeable delay on firing the first sticky on game boot/map load(?). Perhaps for rockets as well. Nothing outputted to console.

**To Reproduce**
1. Open the game
2. Load an sticky jump map
3. Shoot a sticky

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Steam version

**Additional context**
Unable to reproduce on my computer. May have to do with precaching done incorrectly.
Requester tested using a hybrid hard drive and an ssd, both noticeable but less so on the ssd. Maybe related to their computer as this hasn't been reported often.

[Discord discussion](https://discordapp.com/channels/235111289435717633/235125108656701440/755549080855249027)

**Comment by Gocnak** [comment]
Does this still happen on Chaos? I figured it was something related to precaching, which chaos does differently.

**Comment by hexaflexahexagon** [comment]
issue still happens but is quite a bit less noticeable on Chaos. the same thing also happens on other games (e.g. an enemy spawning for the first time in Terraria) so it's most likely just my hard drive dying as nobody else has reported this afaik.
