### ISSUE TITLE
"Fizzle immediately" property to func_nogrenades 

### ISSUE THREAD

**Issue by braem** [momentum-mod/game#957]
**What feature is your improvement idea related to? Please describe.**
In a large majority of situations a stickybomb hitting a `func_nogrenades` will never be able to detonate. The ability to have a `func_nogrenades` immediately fizzle a stickybomb when it enters the trigger or when it hits the ground inside of the trigger is then a useful optimization.

**Describe the solution you'd like**
Add a "fizzle immediately" property to `func_nogrenades` that fizzles a stickybomb immediately on enter, or on impact with the ground.

KeyValues:
0 - Off; `func_nogrenades` operates as it normally does.
1 - On, on ground hit; Sticky immediately fizzles when hitting the ground inside of the `func_nogrenades` iff "airborne only" property is `false`. If "airborne_only" is `true`, act normally (as if it was KeyValue 0).
2 - On, on touch; Sticky immediately fizzles when entering the `func_nogrenades` regardless of the the value of "airborne_only".

**Additional context**
See [the PR for adding the "airborne_only"](https://github.com/momentum-mod/game/pull/725).

**Comment by ijre** [comment]
If the KeyValue is set to 1, and airborne_only is set to true, should it act like KeyValue 2?

**Comment by braem** [comment]
> 
> 
> If the KeyValue is set to 1, and airborne_only is set to true, should it act like KeyValue 2?

In that case no, it should act like KeyValue 0; like normal.
