### ISSUE TITLE
[Linux] Game shader 'game_shader_dx9.so' trying to override a base shader 'Aftershock'

### ISSUE THREAD

**Issue by metronidazole** [momentum-mod/game#972]
**Describe the bug**
After compiling momentum mod with netbeans and setting up my environment correctly, after attempting to load the mod, i get the following engine error 

> Game shader 'game_shader_dx9.so' trying to override a base shader 'Aftershock'

**To Reproduce**
1. Use linux
2. Checkout the latest git build of MM
3. Compile + setup MM
4. run hl2.sh -game momentum

**Expected behavior**
Game menu should load 

**Additional context**
Using arch linux (updated)

I have read various posts on the discord regarding a similar issue but they seem to reference Windows and having other shader dlls in your path or the bin folder. Have also seen issue #832 . Neither of these apply

> $ echo $PATH
> /home/foo/.gem/ruby/2.2.0/bin:/home/foo/.gem/ruby/2.3.0/bin:/home/foo/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/opt/cxoffice/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
> 

> $ ls ./bin
> client.so  client.so.dbg  game_shader_dx9.so  game_shader_dx9.so.dbg  server.so  server.so.dbg

Workaround:
If I rename/delete game_shader_dx9.so, the game starts up fine (although this breaks the shaders/textures).

**Comment by bltech** [comment]
What about the bin folder where hl2.sh is inside? Do you have any stdshader* files there?

**Comment by metronidazole** [comment]
Oh! Looks like there was one in that folder - have renamed it thanks. Will close this and leave the other issue.
