### ISSUE TITLE
"Feeling Lucky" Button doesn't move with rescaled Map Selector window

### ISSUE THREAD

**Issue by ghost** [momentum-mod/game#973]
**Describe the bug**
If the width of the Map Selector is increased, the Feeling Lucky button
Reported by False_

**To Reproduce**
Increase the Map Selector width beyond its default.

**Expected behavior**
The Button should be pinned to the right side of the window.

**Screenshots**

![image](https://user-images.githubusercontent.com/5135158/94350240-4cba8380-0044-11eb-9d69-b3e8e141cfd6.png)

**Desktop/Branch (please complete the following information):**
 - OS: Windows / Linux
 - Branch: Latest develop branch

**Additional context**
N/A

**Comment by McGravel** [comment]
This Issue may be superseded by #978

**Comment by lvaness** [comment]
VGUI begone
