### ISSUE TITLE
Show Map Info crash if opened too quickly

### ISSUE THREAD

**Issue by McGravel** [momentum-mod/game#987]
**Describe the bug**
If you open/close the Map Info dialog too quickly in the Map Selector, the game may crash.

**To Reproduce**

Open Map Selector
Right Click Map -> Show Map Info
Close Immediately, Repeat with any other map
Eventual Crash

If you have a video with the steps to recreate the bug, please post it here.
[Video](https://youtu.be/60Y9D1iNDXI)

**Expected behavior**
The game should not crash!

**Screenshots**
N/A

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch

**Additional context**
N/A

**Comment by ijre** [comment]
I'm completely unable to replicate this; I think it might be some sort of race condition? Do you have any info that could help?

**Comment by McGravel** [comment]
> I'm completely unable to replicate this; I think it might be some sort of race condition? Do you have any info that could help?

I'm honestly not sure, it may be a race condition type of thing going on. The video is pretty much all I know about this odd crash at the moment.

**Comment by ijre** [comment]
Yeah, I gotcha
Are you able to consistently replicate it?

**Comment by Gocnak** [comment]
I think an important details forgotten here is that this may happen on clearing the map_cache.dat file

**Comment by McGravel** [comment]
I've tried this a few more times and did nothing to the `map_cache.dat` file and was able to crash the game several times in a row.
That said, I'm not sure of the *exact* steps to get this crash to occur; sometimes it can happen first try and other times it takes a few attempts.

**Comment by braem** [comment]
From what I understand, opening the tab starts an API call. The crash happens when you open, close, then reopen before the first API call is done, causing 2 API calls to be parsed and thus causing an access violation.

Should be solved by adding a mutex or preventing the map info tab from closing until the API call is complete.

**Comment by braem** [comment]
This actually happens when opening then closing before times are loaded. The panel is set to auto delete on close and the API calls execute code that references the panel's fields after the panel is closed, causing an access violation.
