### ISSUE TITLE
Cursor not hidden while spinning main menu model

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#989]
**Describe the bug**
Pressing mouse2 while controlling the spinning model on the main menu will un-hide the mouse cursor when it shouldn't.

**To Reproduce**
1. Launch game
2. Hold mouse1 over the 3d Momentum logo to drag and spin
3. Press mouse2 (without ever releasing mouse1) 
4. The cursor is now visible and is jittery while moving the mouse around

**Expected behavior**
The cursor should remain invisible

**Desktop/Branch (please complete the following information):**
 - OS: Windows
 - Branch: Latest develop branch

**Comment by Gocnak** [comment]
Initial investigation is showing really weird stuff. Even with all modes enabled, the same bug happens. Having the cursor set to null all the time also doesn't work. I don't know why it sets itself to visible. It may require engine, but I don't know if it's like a windows bug or something.

**Comment by Gocnak** [comment]
Fixed in Chaos build. Closing.
