### ISSUE TITLE
Settings panel doesn't reset focused input box

### ISSUE THREAD

**Issue by hexaflexahexagon** [momentum-mod/game#990]
**Describe the bug**
When the settings panel is closed and opened again it is reset to the first "Input" tab. Any box in focus that the user was typing in is still in focus, however, even if it is on another tab entirely.
Sorta related to #937

**To Reproduce**
1. Launch game, open settings
2. go to a tab besides input (gameplay) 
3. start typing in an input box (yaw speed = 10)
4. close and reopen settings
5. type anything (backspace & 2000)
6. go back to the tab (gameplay) and the box's value has changed

**Video Example**
video of me doing exactly the above steps: https://streamable.com/rirtfw 

**Expected behavior**
The focus should be reset on closing and reopening the settings menu (unless #937 is implemented and enabled by the user)

**Desktop/Branch (please complete the following information):**
 - OS: windows
 - Branch: Latest develop branch

**Comment by Gocnak** [comment]
Should just be a matter of requesting focus to the activated page upon reopening the panel.
